Question 1 Find all players who represent India. Display their full name, playing role, batting style, and bowling style.

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
from datetime import datetime
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/2/players"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)

print(response.json())
indian_players_data=response.json()
indian_players_data

{'player': [{'name': 'BATSMEN', 'imageId': 174146}, {'id': '11808', 'name': 'Shubman Gill', 'imageId': 616515, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '13940', 'name': 'Yashasvi Jaiswal', 'imageId': 591942, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '13866', 'name': 'Sai Sudharsan', 'imageId': 717782, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '576', 'name': 'Rohit Sharma', 'imageId': 616514, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '1413', 'name': 'Virat Kohli', 'imageId': 616517, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm medium'}, {'id': '7915', 'name': 'Suryakumar Yadav', 'imageId': 846028, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '9428', 'name': 'Shreyas Iyer', 'imageId': 616518, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '10896', 'name': 'Rinku Singh', 'imageId': 846030, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '14504', 'name': 'Tilak Varma', 'imageId': 846029, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '11813', 'name': 'Ruturaj Gaikwad', 'imageId': 781069, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '10636', 'name': 'Rajat Patidar', 'imageId': 760758, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '9429', 'name': 'Sarfaraz Khan', 'imageId': 591955, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '9716', 'name': 'Abhimanyu Easwaran', 'imageId': 591956, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '8257', 'name': 'Karun Nair', 'imageId': 717781, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'name': 'ALL ROUNDER', 'imageId': 174146}, {'id': '14701', 'name': 'Nitish Kumar Reddy', 'imageId': 591947, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '9647', 'name': 'Hardik Pandya', 'imageId': 846032, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '11195', 'name': 'Shivam Dube', 'imageId': 846034, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm medium'}, {'id': '12086', 'name': 'Abhishek Sharma', 'imageId': 846031, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '587', 'name': 'Ravindra Jadeja', 'imageId': 616520, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '8683', 'name': 'Shardul Thakur', 'imageId': 352487, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '10945', 'name': 'Washington Sundar', 'imageId': 616522, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '8808', 'name': 'Axar Patel', 'imageId': 846033, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'name': 'WICKET KEEPER', 'imageId': 174146}, {'id': '10744', 'name': 'Rishabh Pant', 'imageId': 616524, 'battingStyle': 'Left-hand bat'}, {'id': '8733', 'name': 'KL Rahul', 'imageId': 616523, 'battingStyle': 'Right-hand bat'}, {'id': '14691', 'name': 'Dhruv Jurel', 'imageId': 591954, 'battingStyle': 'Right-hand bat'}, {'id': '8271', 'name': 'Sanju Samson', 'imageId': 846035, 'battingStyle': 'Right-hand bat'}, {'id': '10276', 'name': 'Ishan Kishan', 'imageId': 846036, 'battingStyle': 'Left-hand bat'}, {'name': 'BOWLER', 'imageId': 174146}, {'id': '10808', 'name': 'Mohammed Siraj', 'imageId': 591952, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast'}, {'id': '9311', 'name': 'Jasprit Bumrah', 'imageId': 846037, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast'}, {'id': '10551', 'name': 'Prasidh Krishna', 'imageId': 591958, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast'}, {'id': '14726', 'name': 'Akash Deep', 'imageId': 591951, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '8292', 'name': 'Kuldeep Yadav', 'imageId': 846039, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm wrist-spin'}, {'id': '13217', 'name': 'Arshdeep Singh', 'imageId': 846038, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm fast-medium'}, {'id': '24729', 'name': 'Harshit Rana', 'imageId': 616529, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '14659', 'name': 'Ravi Bishnoi', 'imageId': 226280, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '10754', 'name': 'Mukesh Kumar', 'imageId': 333872, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '12926', 'name': 'Varun Chakaravarthy', 'imageId': 846040, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}]}

{'player': [{'name': 'BATSMEN', 'imageId': 174146},
  {'id': '11808',
   'name': 'Shubman Gill',
   'imageId': 616515,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '13940',
   'name': 'Yashasvi Jaiswal',
   'imageId': 591942,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '13866',
   'name': 'Sai Sudharsan',
   'imageId': 717782,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '576',
   'name': 'Rohit Sharma',
   'imageId': 616514,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '1413',
   'name': 'Virat Kohli',
   'imageId': 616517,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm medium'},
  {'id': '7915',
   'name': 'Suryakumar Yadav',
   'imageId': 846028,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '9428',
   'name': 'Shreyas Iyer',
   'imageId': 616518,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '10896',
   'name': 'Rinku Singh',
   'imageId': 846030,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '14504',
   'name': 'Tilak Varma',
   'imageId': 846029,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '11813',
   'name': 'Ruturaj Gaikwad',
   'imageId': 781069,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '10636',
   'name': 'Rajat Patidar',
   'imageId': 760758,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '9429',
   'name': 'Sarfaraz Khan',
   'imageId': 591955,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '9716',
   'name': 'Abhimanyu Easwaran',
   'imageId': 591956,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '8257',
   'name': 'Karun Nair',
   'imageId': 717781,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'name': 'ALL ROUNDER', 'imageId': 174146},
  {'id': '14701',
   'name': 'Nitish Kumar Reddy',
   'imageId': 591947,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '9647',
   'name': 'Hardik Pandya',
   'imageId': 846032,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '11195',
   'name': 'Shivam Dube',
   'imageId': 846034,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm medium'},
  {'id': '12086',
   'name': 'Abhishek Sharma',
   'imageId': 846031,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm orthodox'},
  {'id': '587',
   'name': 'Ravindra Jadeja',
   'imageId': 616520,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm orthodox'},
  {'id': '8683',
   'name': 'Shardul Thakur',
   'imageId': 352487,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '10945',
   'name': 'Washington Sundar',
   'imageId': 616522,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '8808',
   'name': 'Axar Patel',
   'imageId': 846033,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm orthodox'},
  {'name': 'WICKET KEEPER', 'imageId': 174146},
  {'id': '10744',
   'name': 'Rishabh Pant',
   'imageId': 616524,
   'battingStyle': 'Left-hand bat'},
  {'id': '8733',
   'name': 'KL Rahul',
   'imageId': 616523,
   'battingStyle': 'Right-hand bat'},
  {'id': '14691',
   'name': 'Dhruv Jurel',
   'imageId': 591954,
   'battingStyle': 'Right-hand bat'},
  {'id': '8271',
   'name': 'Sanju Samson',
   'imageId': 846035,
   'battingStyle': 'Right-hand bat'},
  {'id': '10276',
   'name': 'Ishan Kishan',
   'imageId': 846036,
   'battingStyle': 'Left-hand bat'},
  {'name': 'BOWLER', 'imageId': 174146},
  {'id': '10808',
   'name': 'Mohammed Siraj',
   'imageId': 591952,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast'},
  {'id': '9311',
   'name': 'Jasprit Bumrah',
   'imageId': 846037,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast'},
  {'id': '10551',
   'name': 'Prasidh Krishna',
   'imageId': 591958,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast'},
  {'id': '14726',
   'name': 'Akash Deep',
   'imageId': 591951,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '8292',
   'name': 'Kuldeep Yadav',
   'imageId': 846039,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm wrist-spin'},
  {'id': '13217',
   'name': 'Arshdeep Singh',
   'imageId': 846038,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm fast-medium'},
  {'id': '24729',
   'name': 'Harshit Rana',
   'imageId': 616529,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '14659',
   'name': 'Ravi Bishnoi',
   'imageId': 226280,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '10754',
   'name': 'Mukesh Kumar',
   'imageId': 333872,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '12926',
   'name': 'Varun Chakaravarthy',
   'imageId': 846040,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'}]}

In [2]:
import pandas as pd

indian_players_list = []
current_role = None 

for item in indian_players_data['player']:

    
    if 'id' not in item:
        current_role = item.get('name')
        continue

    
    indian_players_list.append({
        "playerId": item.get('id'),
        "playerName": item.get('name'),
        "playingrole": current_role,
        "battingStyle": item.get('battingStyle'),
        "bowlingStyle": item.get('bowlingStyle')
    })


indian_players_table = pd.DataFrame(indian_players_list)

print(indian_players_table)

   playerId           playerName    playingrole    battingStyle  \
0     11808         Shubman Gill        BATSMEN  Right-hand bat
1     13940     Yashasvi Jaiswal        BATSMEN   Left-hand bat
2     13866        Sai Sudharsan        BATSMEN   Left-hand bat
3       576         Rohit Sharma        BATSMEN  Right-hand bat
4      1413          Virat Kohli        BATSMEN  Right-hand bat
5      7915     Suryakumar Yadav        BATSMEN  Right-hand bat
6      9428         Shreyas Iyer        BATSMEN  Right-hand bat
7     10896          Rinku Singh        BATSMEN   Left-hand bat
8     14504          Tilak Varma        BATSMEN   Left-hand bat
9     11813      Ruturaj Gaikwad        BATSMEN  Right-hand bat
10    10636        Rajat Patidar        BATSMEN  Right-hand bat
11     9429        Sarfaraz Khan        BATSMEN  Right-hand bat
12     9716   Abhimanyu Easwaran        BATSMEN  Right-hand bat
13     8257           Karun Nair        BATSMEN  Right-hand bat
14    14701   Nitish Kumar Reddy    ALL ROUNDER  Right-hand bat
15     9647        Hardik Pandya    ALL ROUNDER  Right-hand bat
16    11195          Shivam Dube    ALL ROUNDER   Left-hand bat
17    12086      Abhishek Sharma    ALL ROUNDER   Left-hand bat
18      587      Ravindra Jadeja    ALL ROUNDER   Left-hand bat
19     8683       Shardul Thakur    ALL ROUNDER  Right-hand bat
20    10945    Washington Sundar    ALL ROUNDER   Left-hand bat
21     8808           Axar Patel    ALL ROUNDER   Left-hand bat
22    10744         Rishabh Pant  WICKET KEEPER   Left-hand bat
23     8733             KL Rahul  WICKET KEEPER  Right-hand bat
24    14691          Dhruv Jurel  WICKET KEEPER  Right-hand bat
25     8271         Sanju Samson  WICKET KEEPER  Right-hand bat
26    10276         Ishan Kishan  WICKET KEEPER   Left-hand bat
27    10808       Mohammed Siraj         BOWLER  Right-hand bat
28     9311       Jasprit Bumrah         BOWLER  Right-hand bat
29    10551      Prasidh Krishna         BOWLER  Right-hand bat
30    14726           Akash Deep         BOWLER  Right-hand bat
31     8292        Kuldeep Yadav         BOWLER   Left-hand bat
32    13217       Arshdeep Singh         BOWLER   Left-hand bat
33    24729         Harshit Rana         BOWLER  Right-hand bat
34    14659         Ravi Bishnoi         BOWLER  Right-hand bat
35    10754         Mukesh Kumar         BOWLER  Right-hand bat
36    12926  Varun Chakaravarthy         BOWLER  Right-hand bat

             bowlingStyle
0      Right-arm offbreak
1      Right-arm legbreak
2      Right-arm legbreak
3      Right-arm offbreak
4        Right-arm medium
5      Right-arm offbreak
6      Right-arm legbreak
7      Right-arm offbreak
8      Right-arm offbreak
9      Right-arm offbreak
10     Right-arm offbreak
11     Right-arm legbreak
12     Right-arm legbreak
13     Right-arm offbreak
14  Right-arm fast-medium
15  Right-arm fast-medium
16       Right-arm medium
17      Left-arm orthodox
18      Left-arm orthodox
19  Right-arm fast-medium
20     Right-arm offbreak
21      Left-arm orthodox
22                   None
23                   None
24                   None
25                   None
26                   None
27         Right-arm fast
28         Right-arm fast
29         Right-arm fast
30  Right-arm fast-medium
31    Left-arm wrist-spin
32   Left-arm fast-medium
33  Right-arm fast-medium
34     Right-arm legbreak
35  Right-arm fast-medium
36     Right-arm legbreak

In [4]:
import os
from dotenv import load_dotenv
from pathlib import Path
import pandas as pd
from sqlalchemy import create_engine


    # Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")


engine = create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")

# Upload DataFrame to MySQL
indian_players_table.to_sql(name="indian_player", con=engine, if_exists="replace", index=False)

print(f"Data uploaded to MySQL successfully, Database: {database}, Table: indian_player")

Data uploaded to MySQL successfully, Database: CricBuzz, Table: indian_player

Question 2 Show all cricket matches that were played in the last Few days. Include the match description, both team names, venue name with city, and the match date. Sort by most recent matches first.

In [5]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/matches/v1/recent"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)
RM_rawData=(response.json())

RM_rawData['typeMatches'][0]['seriesMatches'][0]['seriesAdWrapper']['matches'][0]['matchInfo']

RM_matchInfo=[]
for type_match in RM_rawData['typeMatches']:
    for series_match in type_match['seriesMatches']:
        wrapper = series_match.get('seriesAdWrapper')
        if not wrapper:
            continue
        for match in wrapper.get('matches', []):
            RM_matchInfo.append(match['matchInfo'])
            print(match['matchInfo'])

{'matchId': 122731, 'seriesId': 10234, 'seriesName': 'South Africa tour of New Zealand, 2026', 'matchDesc': '5th T20I', 'matchFormat': 'T20', 'startDate': '1774419300000', 'endDate': '1774431900000', 'state': 'Complete', 'status': 'South Africa won by 33 runs', 'team1': {'teamId': 11, 'teamName': 'South Africa', 'teamSName': 'RSA', 'imageId': 776287}, 'team2': {'teamId': 13, 'teamName': 'New Zealand', 'teamSName': 'NZ', 'imageId': 776333}, 'venueInfo': {'id': 371, 'ground': 'Hagley Oval', 'city': 'Christchurch', 'timezone': '+13:00', 'latitude': '-43.535831', 'longitude': '172.624863'}, 'currBatTeamId': 11, 'seriesStartDt': '1773532800000', 'seriesEndDt': '1774569600000', 'isTimeAnnounced': True, 'stateTitle': 'RSA Won', 'isFantasyEnabled': True}
{'matchId': 148298, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '14th Match', 'matchFormat': 'T20', 'startDate': '1774792200000', 'endDate': '1774804800000', 'state': 'Complete', 'status': 'Match abandoned due to wet outfield (No toss)', 'team1': {'teamId': 531, 'teamName': 'Ghana', 'teamSName': 'GH', 'imageId': 172581}, 'team2': {'teamId': 535, 'teamName': 'Tanzania', 'teamSName': 'TAN', 'imageId': 172586}, 'venueInfo': {'id': 1864, 'ground': 'Achimota Senior Secondary School A Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon'}
{'matchId': 148305, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '15th Match', 'matchFormat': 'T20', 'startDate': '1774792200000', 'endDate': '1774804800000', 'state': 'Complete', 'status': 'Match abandoned due to wet outfield (No toss)', 'team1': {'teamId': 562, 'teamName': 'Saint Helena', 'teamSName': 'SHN', 'imageId': 172614}, 'team2': {'teamId': 553, 'teamName': 'Malawi', 'teamSName': 'MWI', 'imageId': 172605}, 'venueInfo': {'id': 1871, 'ground': 'Achimota Senior Secondary School B Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon'}
{'matchId': 148287, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '13th Match', 'matchFormat': 'T20', 'startDate': '1774776600000', 'endDate': '1774789200000', 'state': 'Complete', 'status': 'Match abandoned due to rain (no toss)', 'team1': {'teamId': 1277, 'teamName': 'Seychelles', 'teamSName': 'SEY', 'imageId': 248523}, 'team2': {'teamId': 1284, 'teamName': 'Eswatini', 'teamSName': 'SWT', 'imageId': 248525}, 'venueInfo': {'id': 1864, 'ground': 'Achimota Senior Secondary School A Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon'}
{'matchId': 148265, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '11th Match', 'matchFormat': 'T20', 'startDate': '1774705800000', 'endDate': '1774718400000', 'state': 'Complete', 'status': 'Malawi won by 6 wkts', 'team1': {'teamId': 1277, 'teamName': 'Seychelles', 'teamSName': 'SEY', 'imageId': 248523}, 'team2': {'teamId': 553, 'teamName': 'Malawi', 'teamSName': 'MWI', 'imageId': 172605}, 'venueInfo': {'id': 1864, 'ground': 'Achimota Senior Secondary School A Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 553, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'MWI Won'}
{'matchId': 148276, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '12th Match', 'matchFormat': 'T20', 'startDate': '1774705800000', 'endDate': '1774718400000', 'state': 'Complete', 'status': 'Ghana won by 83 runs', 'team1': {'teamId': 531, 'teamName': 'Ghana', 'teamSName': 'GH', 'imageId': 172581}, 'team2': {'teamId': 1284, 'teamName': 'Eswatini', 'teamSName': 'SWT', 'imageId': 248525}, 'venueInfo': {'id': 1871, 'ground': 'Achimota Senior Secondary School B Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 531, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'GH Won'}
{'matchId': 148254, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '10th Match', 'matchFormat': 'T20', 'startDate': '1774690200000', 'endDate': '1774702800000', 'state': 'Complete', 'status': 'Tanzania won by 161 runs', 'team1': {'teamId': 535, 'teamName': 'Tanzania', 'teamSName': 'TAN', 'imageId': 172586}, 'team2': {'teamId': 562, 'teamName': 'Saint Helena', 'teamSName': 'SHN', 'imageId': 172614}, 'venueInfo': {'id': 1871, 'ground': 'Achimota Senior Secondary School B Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 535, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'TAN Won'}
{'matchId': 148243, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '9th Match', 'matchFormat': 'T20', 'startDate': '1774619400000', 'endDate': '1774632000000', 'state': 'Complete', 'status': 'Tanzania won by 153 runs', 'team1': {'teamId': 535, 'teamName': 'Tanzania', 'teamSName': 'TAN', 'imageId': 172586}, 'team2': {'teamId': 1277, 'teamName': 'Seychelles', 'teamSName': 'SEY', 'imageId': 248523}, 'venueInfo': {'id': 1871, 'ground': 'Achimota Senior Secondary School B Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 535, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'TAN Won'}
{'matchId': 148236, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '8th Match', 'matchFormat': 'T20', 'startDate': '1774603800000', 'endDate': '1774616400000', 'state': 'Complete', 'status': 'Malawi won by 8 wkts', 'team1': {'teamId': 1284, 'teamName': 'Eswatini', 'teamSName': 'SWT', 'imageId': 248525}, 'team2': {'teamId': 553, 'teamName': 'Malawi', 'teamSName': 'MWI', 'imageId': 172605}, 'venueInfo': {'id': 1871, 'ground': 'Achimota Senior Secondary School B Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 553, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'MWI Won'}
{'matchId': 148225, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '7th Match', 'matchFormat': 'T20', 'startDate': '1774603800000', 'endDate': '1774616400000', 'state': 'Complete', 'status': 'Ghana won by 9 wkts', 'team1': {'teamId': 562, 'teamName': 'Saint Helena', 'teamSName': 'SHN', 'imageId': 172614}, 'team2': {'teamId': 531, 'teamName': 'Ghana', 'teamSName': 'GH', 'imageId': 172581}, 'venueInfo': {'id': 1864, 'ground': 'Achimota Senior Secondary School A Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 531, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'GH Won'}
{'matchId': 148221, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '6th Match', 'matchFormat': 'T20', 'startDate': '1774446600000', 'endDate': '1774459200000', 'state': 'Complete', 'status': 'Ghana won by 2 wkts', 'team1': {'teamId': 553, 'teamName': 'Malawi', 'teamSName': 'MWI', 'imageId': 172605}, 'team2': {'teamId': 531, 'teamName': 'Ghana', 'teamSName': 'GH', 'imageId': 172581}, 'venueInfo': {'id': 1864, 'ground': 'Achimota Senior Secondary School A Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 531, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'GH Won'}
{'matchId': 148210, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '5th Match', 'matchFormat': 'T20', 'startDate': '1774431000000', 'endDate': '1774443600000', 'state': 'Complete', 'status': 'Tanzania won by 158 runs', 'team1': {'teamId': 535, 'teamName': 'Tanzania', 'teamSName': 'TAN', 'imageId': 172586}, 'team2': {'teamId': 1284, 'teamName': 'Eswatini', 'teamSName': 'SWT', 'imageId': 248525}, 'venueInfo': {'id': 1871, 'ground': 'Achimota Senior Secondary School B Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 535, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'TAN Won'}
{'matchId': 148199, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '4th Match', 'matchFormat': 'T20', 'startDate': '1774431000000', 'endDate': '1774443600000', 'state': 'Complete', 'status': 'Seychelles won by 7 wkts', 'team1': {'teamId': 562, 'teamName': 'Saint Helena', 'teamSName': 'SHN', 'imageId': 172614}, 'team2': {'teamId': 1277, 'teamName': 'Seychelles', 'teamSName': 'SEY', 'imageId': 248523}, 'venueInfo': {'id': 1864, 'ground': 'Achimota Senior Secondary School A Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 1277, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'SEY Won'}
{'matchId': 148177, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '2nd Match', 'matchFormat': 'T20', 'startDate': '1774360200000', 'endDate': '1774372800000', 'state': 'Complete', 'status': 'Eswatini won by 27 runs', 'team1': {'teamId': 1284, 'teamName': 'Eswatini', 'teamSName': 'SWT', 'imageId': 248525}, 'team2': {'teamId': 562, 'teamName': 'Saint Helena', 'teamSName': 'SHN', 'imageId': 172614}, 'venueInfo': {'id': 1864, 'ground': 'Achimota Senior Secondary School A Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 1284, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'SWT Won'}
{'matchId': 148188, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '3rd Match', 'matchFormat': 'T20', 'startDate': '1774360200000', 'endDate': '1774372800000', 'state': 'Complete', 'status': 'Ghana won by 6 wkts', 'team1': {'teamId': 1277, 'teamName': 'Seychelles', 'teamSName': 'SEY', 'imageId': 248523}, 'team2': {'teamId': 531, 'teamName': 'Ghana', 'teamSName': 'GH', 'imageId': 172581}, 'venueInfo': {'id': 1871, 'ground': 'Achimota Senior Secondary School B Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 531, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'GH Won'}
{'matchId': 148166, 'seriesId': 11627, 'seriesName': "ICC Men's T20 World Cup Africa Sub Regional Qualifier B, 2026", 'matchDesc': '1st Match', 'matchFormat': 'T20', 'startDate': '1774344600000', 'endDate': '1774357200000', 'state': 'Complete', 'status': 'Tanzania won by 8 wkts', 'team1': {'teamId': 553, 'teamName': 'Malawi', 'teamSName': 'MWI', 'imageId': 172605}, 'team2': {'teamId': 535, 'teamName': 'Tanzania', 'teamSName': 'TAN', 'imageId': 172586}, 'venueInfo': {'id': 1864, 'ground': 'Achimota Senior Secondary School A Field', 'city': 'Accra', 'timezone': '+00:00', 'latitude': '5.6130975', 'longitude': '-0.3142454'}, 'currBatTeamId': 535, 'seriesStartDt': '1774310400000', 'seriesEndDt': '1774915200000', 'isTimeAnnounced': True, 'stateTitle': 'TAN Won'}
{'matchId': 149629, 'seriesId': 9241, 'seriesName': 'Indian Premier League 2026', 'matchDesc': '2nd Match', 'matchFormat': 'T20', 'startDate': '1774792800000', 'endDate': '1774805400000', 'state': 'Complete', 'status': 'Mumbai Indians won by 6 wkts', 'team1': {'teamId': 63, 'teamName': 'Kolkata Knight Riders', 'teamSName': 'KKR', 'imageId': 860046}, 'team2': {'teamId': 62, 'teamName': 'Mumbai Indians', 'teamSName': 'MI', 'imageId': 860053}, 'venueInfo': {'id': 81, 'ground': 'Wankhede Stadium', 'city': 'Mumbai', 'timezone': '+05:30', 'latitude': '18.938956', 'longitude': '72.825719'}, 'currBatTeamId': 62, 'seriesStartDt': '1774656000000', 'seriesEndDt': '1780358400000', 'isTimeAnnounced': True, 'stateTitle': 'Complete', 'isFantasyEnabled': True}
{'matchId': 149618, 'seriesId': 9241, 'seriesName': 'Indian Premier League 2026', 'matchDesc': '1st Match', 'matchFormat': 'T20', 'startDate': '1774706400000', 'endDate': '1774719000000', 'state': 'Complete', 'status': 'Royal Challengers Bengaluru won by 6 wkts', 'team1': {'teamId': 255, 'teamName': 'Sunrisers Hyderabad', 'teamSName': 'SRH', 'imageId': 860066}, 'team2': {'teamId': 59, 'teamName': 'Royal Challengers Bengaluru', 'teamSName': 'RCB', 'imageId': 860056}, 'venueInfo': {'id': 27, 'ground': 'M.Chinnaswamy Stadium', 'city': 'Bengaluru', 'timezone': '+05:30', 'latitude': '12.978853', 'longitude': '77.599533'}, 'currBatTeamId': 59, 'seriesStartDt': '1774656000000', 'seriesEndDt': '1780358400000', 'isTimeAnnounced': True, 'stateTitle': 'RCB Won', 'isFantasyEnabled': True}
{'matchId': 148998, 'seriesId': 11537, 'seriesName': 'Pakistan Super League 2026', 'matchDesc': '6th Match', 'matchFormat': 'T20', 'startDate': '1774792800000', 'endDate': '1774805400000', 'state': 'Complete', 'status': 'Karachi Kings won by 4 wkts', 'team1': {'teamId': 333, 'teamName': 'Lahore Qalandars', 'teamSName': 'LHQ', 'imageId': 883181}, 'team2': {'teamId': 332, 'teamName': 'Karachi Kings', 'teamSName': 'KRK', 'imageId': 883188}, 'venueInfo': {'id': 26, 'ground': 'Gaddafi Stadium', 'city': 'Lahore', 'timezone': '+05:00', 'latitude': '31.513467', 'longitude': '74.333375'}, 'currBatTeamId': 332, 'seriesStartDt': '1774483200000', 'seriesEndDt': '1777939200000', 'isTimeAnnounced': True, 'stateTitle': 'Complete', 'isFantasyEnabled': True}
{'matchId': 148987, 'seriesId': 11537, 'seriesName': 'Pakistan Super League 2026', 'matchDesc': '5th Match', 'matchFormat': 'T20', 'startDate': '1774776600000', 'endDate': '1774789200000', 'state': 'Complete', 'status': 'Quetta Gladiators won by 40 runs', 'team1': {'teamId': 331, 'teamName': 'Quetta Gladiators', 'teamSName': 'QTG', 'imageId': 883182}, 'team2': {'teamId': 3114, 'teamName': 'Hyderabad Kingsmen', 'teamSName': 'HYDK', 'imageId': 883179}, 'venueInfo': {'id': 26, 'ground': 'Gaddafi Stadium', 'city': 'Lahore', 'timezone': '+05:00', 'latitude': '31.513467', 'longitude': '74.333375'}, 'currBatTeamId': 331, 'seriesStartDt': '1774483200000', 'seriesEndDt': '1777939200000', 'isTimeAnnounced': True, 'stateTitle': 'Complete'}
{'matchId': 148984, 'seriesId': 11537, 'seriesName': 'Pakistan Super League 2026', 'matchDesc': '4th Match', 'matchFormat': 'T20', 'startDate': '1774706400000', 'endDate': '1774719000000', 'state': 'Complete', 'status': 'Multan Sultans won by 5 wkts', 'team1': {'teamId': 330, 'teamName': 'Islamabad United', 'teamSName': 'ISU', 'imageId': 883184}, 'team2': {'teamId': 437, 'teamName': 'Multan Sultans', 'teamSName': 'MS', 'imageId': 883178}, 'venueInfo': {'id': 26, 'ground': 'Gaddafi Stadium', 'city': 'Lahore', 'timezone': '+05:00', 'latitude': '31.513467', 'longitude': '74.333375'}, 'currBatTeamId': 437, 'seriesStartDt': '1774483200000', 'seriesEndDt': '1777939200000', 'isTimeAnnounced': True, 'stateTitle': 'MS Won', 'isFantasyEnabled': True}
{'matchId': 148973, 'seriesId': 11537, 'seriesName': 'Pakistan Super League 2026', 'matchDesc': '3rd Match', 'matchFormat': 'T20', 'startDate': '1774690200000', 'endDate': '1774702800000', 'state': 'Complete', 'status': 'Peshawar Zalmi won by 5 wkts', 'team1': {'teamId': 3116, 'teamName': 'Rawalpindiz', 'teamSName': 'RWP', 'imageId': 883174}, 'team2': {'teamId': 334, 'teamName': 'Peshawar Zalmi', 'teamSName': 'PSZ', 'imageId': 883180}, 'venueInfo': {'id': 26, 'ground': 'Gaddafi Stadium', 'city': 'Lahore', 'timezone': '+05:00', 'latitude': '31.513467', 'longitude': '74.333375'}, 'currBatTeamId': 334, 'seriesStartDt': '1774483200000', 'seriesEndDt': '1777939200000', 'isTimeAnnounced': True, 'stateTitle': 'PSZ Won', 'isFantasyEnabled': True}
{'matchId': 148963, 'seriesId': 11537, 'seriesName': 'Pakistan Super League 2026', 'matchDesc': '2nd Match', 'matchFormat': 'T20', 'startDate': '1774620000000', 'endDate': '1774632600000', 'state': 'Complete', 'status': 'Karachi Kings won by 14 runs', 'team1': {'teamId': 332, 'teamName': 'Karachi Kings', 'teamSName': 'KRK', 'imageId': 883188}, 'team2': {'teamId': 331, 'teamName': 'Quetta Gladiators', 'teamSName': 'QTG', 'imageId': 883182}, 'venueInfo': {'id': 26, 'ground': 'Gaddafi Stadium', 'city': 'Lahore', 'timezone': '+05:00', 'latitude': '31.513467', 'longitude': '74.333375'}, 'currBatTeamId': 332, 'seriesStartDt': '1774483200000', 'seriesEndDt': '1777939200000', 'isTimeAnnounced': True, 'stateTitle': 'KRK Won', 'isFantasyEnabled': True}
{'matchId': 148962, 'seriesId': 11537, 'seriesName': 'Pakistan Super League 2026', 'matchDesc': '1st Match', 'matchFormat': 'T20', 'startDate': '1774533600000', 'endDate': '1774546200000', 'state': 'Complete', 'status': 'Lahore Qalandars won by 69 runs', 'team1': {'teamId': 333, 'teamName': 'Lahore Qalandars', 'teamSName': 'LHQ', 'imageId': 883181}, 'team2': {'teamId': 3114, 'teamName': 'Hyderabad Kingsmen', 'teamSName': 'HYDK', 'imageId': 883179}, 'venueInfo': {'id': 26, 'ground': 'Gaddafi Stadium', 'city': 'Lahore', 'timezone': '+05:00', 'latitude': '31.513467', 'longitude': '74.333375'}, 'currBatTeamId': 333, 'seriesStartDt': '1774483200000', 'seriesEndDt': '1777939200000', 'isTimeAnnounced': True, 'stateTitle': 'LHQ Won', 'isFantasyEnabled': True}
{'matchId': 151459, 'seriesId': 11671, 'seriesName': 'Legends League Cricket 2026', 'matchDesc': 'Final', 'matchFormat': 'T20', 'startDate': '1774620000000', 'endDate': '1774632600000', 'state': 'Complete', 'status': 'Royal Riders Punjab won by 41 runs', 'team1': {'teamId': 3171, 'teamName': 'Royal Riders Punjab', 'teamSName': 'RRP', 'imageId': 880414}, 'team2': {'teamId': 2156, 'teamName': 'Konark Suryas Odisha', 'teamSName': 'KNSO', 'imageId': 880449}, 'venueInfo': {'id': 1438295, 'ground': 'Indira Gandhi International Cricket Stadium', 'city': 'Haldwani', 'timezone': '+05:30', 'latitude': '29.2183', 'longitude': '79.5120'}, 'currBatTeamId': 3171, 'seriesStartDt': '1773187200000', 'seriesEndDt': '1774742400000', 'isTimeAnnounced': True, 'stateTitle': 'RRP Won'}
{'matchId': 152285, 'seriesId': 11671, 'seriesName': 'Legends League Cricket 2026', 'matchDesc': 'Semi Final 2 (Rescheduled match)', 'matchFormat': 'T20', 'startDate': '1774606500000', 'endDate': '1774619100000', 'state': 'Complete', 'status': 'Match cancelled, Royal Riders Punjab were declared the winners via walkover', 'team1': {'teamId': 3171, 'teamName': 'Royal Riders Punjab', 'teamSName': 'RRP', 'imageId': 880414}, 'team2': {'teamId': 3160, 'teamName': 'Mumbai Spartans', 'teamSName': 'MS', 'imageId': 880422}, 'venueInfo': {'id': 1438295, 'ground': 'Indira Gandhi International Cricket Stadium', 'city': 'Haldwani', 'timezone': '+05:30', 'latitude': '29.2183', 'longitude': '79.5120'}, 'seriesStartDt': '1773187200000', 'seriesEndDt': '1774742400000', 'isTimeAnnounced': True, 'stateTitle': 'Abandon'}

In [7]:
#recentMatches_info_table

RM_rows = []

for info in RM_matchInfo:

    start_ts = info.get('startDate')
    end_ts = info.get('endDate')

   #start_date = datetime.fromtimestamp(int(start_ts) / 1000).strftime('%d/%m/%Y') if start_ts else None
    #end_date = datetime.fromtimestamp(int(end_ts) / 1000).strftime('%d/%m/%Y') if end_ts else None

    start_date = datetime.fromtimestamp(int(start_ts) / 1000) if start_ts else None
    end_date = datetime.fromtimestamp(int(end_ts) / 1000) if end_ts else None

    row = {
        "matchId": info.get('matchId'),
        "seriesId": info.get('seriesId'),
        "seriesName": info.get('seriesName'),
        "matchDesc": info.get('matchDesc'),
        "startDate": start_date,
        "endDate": end_date,
        "team1": info['team1']['teamSName'],
        "team2": info['team2']['teamSName'],
        "venue" : info['venueInfo']['ground'],
        "city": info['venueInfo']['city'],
        "status": info.get('status')
    }

    RM_rows.append(row)

RM = pd.DataFrame(RM_rows)
print(RM)

    matchId  seriesId                                         seriesName  \
0    122731     10234             South Africa tour of New Zealand, 2026
1    148298     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
2    148305     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
3    148287     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
4    148265     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
5    148276     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
6    148254     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
7    148243     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
8    148236     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
9    148225     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
10   148221     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
11   148210     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
12   148199     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
13   148177     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
14   148188     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
15   148166     11627  ICC Men's T20 World Cup Africa Sub Regional Qu...
16   149629      9241                         Indian Premier League 2026
17   149618      9241                         Indian Premier League 2026
18   148998     11537                         Pakistan Super League 2026
19   148987     11537                         Pakistan Super League 2026
20   148984     11537                         Pakistan Super League 2026
21   148973     11537                         Pakistan Super League 2026
22   148963     11537                         Pakistan Super League 2026
23   148962     11537                         Pakistan Super League 2026
24   151459     11671                        Legends League Cricket 2026
25   152285     11671                        Legends League Cricket 2026
26   152274     11671                        Legends League Cricket 2026
27   148716     11671                        Legends League Cricket 2026
28   148705     11671                        Legends League Cricket 2026
29   151526     11671                        Legends League Cricket 2026
30   151448     11671                        Legends League Cricket 2026
31   148666     11671                        Legends League Cricket 2026
32   148677     11671                        Legends League Cricket 2026
33   148657     11671                        Legends League Cricket 2026
34   148646     11671                        Legends League Cricket 2026
35   147477     11553  CSA Provincial One-Day Challenge Division One ...
36   147466     11553  CSA Provincial One-Day Challenge Division One ...
37   122836     10251       South Africa Women tour of New Zealand, 2026
38   122825     10251       South Africa Women tour of New Zealand, 2026
39   148360     11634          Australia Women tour of West Indies, 2026
40   148353     11634          Australia Women tour of West Indies, 2026
41   150175     11693  Nigeria Invitational Women's T20I Tournament, ...
42   150164     11693  Nigeria Invitational Women's T20I Tournament, ...
43   148863     11693  Nigeria Invitational Women's T20I Tournament, ...
44   148852     11693  Nigeria Invitational Women's T20I Tournament, ...
45   148842     11693  Nigeria Invitational Women's T20I Tournament, ...
46   148831     11693  Nigeria Invitational Women's T20I Tournament, ...
47   148830     11693  Nigeria Invitational Women's T20I Tournament, ...
48   148819     11693  Nigeria Invitational Women's T20I Tournament, ...

                           matchDesc           startDate             endDate  \
0                           5th T20I 2026-03-25 11:45:00 2026-03-25 15:15:00
1                         14th Match 2026-03-29 19:20:00 2026-03-29 22:50:00
2                         15th Match 2026-03-29 19:20:00 2026-03-29 22:50:00
3                         13th Match 2026-03-29 15:00:00 2026-03-29 18:30:00
4                         11th Match 2026-03-28 19:20:00 2026-03-28 22:50:00
5                         12th Match 2026-03-28 19:20:00 2026-03-28 22:50:00
6                         10th Match 2026-03-28 15:00:00 2026-03-28 18:30:00
7                          9th Match 2026-03-27 19:20:00 2026-03-27 22:50:00
8                          8th Match 2026-03-27 15:00:00 2026-03-27 18:30:00
9                          7th Match 2026-03-27 15:00:00 2026-03-27 18:30:00
10                         6th Match 2026-03-25 19:20:00 2026-03-25 22:50:00
11                         5th Match 2026-03-25 15:00:00 2026-03-25 18:30:00
12                         4th Match 2026-03-25 15:00:00 2026-03-25 18:30:00
13                         2nd Match 2026-03-24 19:20:00 2026-03-24 22:50:00
14                         3rd Match 2026-03-24 19:20:00 2026-03-24 22:50:00
15                         1st Match 2026-03-24 15:00:00 2026-03-24 18:30:00
16                         2nd Match 2026-03-29 19:30:00 2026-03-29 23:00:00
17                         1st Match 2026-03-28 19:30:00 2026-03-28 23:00:00
18                         6th Match 2026-03-29 19:30:00 2026-03-29 23:00:00
19                         5th Match 2026-03-29 15:00:00 2026-03-29 18:30:00
20                         4th Match 2026-03-28 19:30:00 2026-03-28 23:00:00
21                         3rd Match 2026-03-28 15:00:00 2026-03-28 18:30:00
22                         2nd Match 2026-03-27 19:30:00 2026-03-27 23:00:00
23                         1st Match 2026-03-26 19:30:00 2026-03-26 23:00:00
24                             Final 2026-03-27 19:30:00 2026-03-27 23:00:00
25  Semi Final 2 (Rescheduled match) 2026-03-27 15:45:00 2026-03-27 19:15:00
26  Semi Final 1 (Rescheduled match) 2026-03-27 12:30:00 2026-03-27 16:00:00
27                      Semi Final 2 2026-03-26 19:30:00 2026-03-26 23:00:00
28                      Semi Final 1 2026-03-26 14:30:00 2026-03-26 18:00:00
29                        15th Match 2026-03-25 19:30:00 2026-03-25 23:00:00
30            14th Match (Cancelled) 2026-03-25 14:30:00 2026-03-25 18:00:00
31                        12th Match 2026-03-24 20:30:00 2026-03-25 00:00:00
32            13th Match (Cancelled) 2026-03-24 14:30:00 2026-03-24 18:00:00
33    11th Match (rescheduled match) 2026-03-23 20:30:00 2026-03-24 00:00:00
34                        10th Match 2026-03-23 14:30:00 2026-03-23 18:00:00
35                             Final 2026-03-29 13:30:00 2026-03-29 21:30:00
36                         Qualifier 2026-03-25 16:30:00 2026-03-26 00:30:00
37                           1st ODI 2026-03-29 06:30:00 2026-03-29 14:30:00
38                          5th T20I 2026-03-25 07:15:00 2026-03-25 10:45:00
39                           1st ODI 2026-03-27 23:30:00 2026-03-28 07:30:00
40                          3rd T20I 2026-03-24 04:00:00 2026-03-24 07:30:00
41                             Final 2026-03-28 18:30:00 2026-03-28 22:00:00
42                3rd Place Play-off 2026-03-28 14:30:00 2026-03-28 18:00:00
43                    2nd Semi-Final 2026-03-27 18:30:00 2026-03-27 22:00:00
44                    1st Semi-Final 2026-03-27 14:30:00 2026-03-27 18:00:00
45                        10th Match 2026-03-25 18:30:00 2026-03-25 22:00:00
46                         9th Match 2026-03-25 14:30:00 2026-03-25 18:00:00
47                         8th Match 2026-03-24 18:30:00 2026-03-24 22:00:00
48                         7th Match 2026-03-24 14:30:00 2026-03-24 18:00:00

      team1    team2                                        venue  \
0       RSA       NZ                                  Hagley Oval
1        GH      TAN     Achimota Senior Secondary School A Field
2       SHN      MWI     Achimota Senior Secondary School B Field
3       SEY      SWT     Achimota Senior Secondary School A Field
4       SEY      MWI     Achimota Senior Secondary School A Field
5        GH      SWT     Achimota Senior Secondary School B Field
6       TAN      SHN     Achimota Senior Secondary School B Field
7       TAN      SEY     Achimota Senior Secondary School B Field
8       SWT      MWI     Achimota Senior Secondary School B Field
9       SHN       GH     Achimota Senior Secondary School A Field
10      MWI       GH     Achimota Senior Secondary School A Field
11      TAN      SWT     Achimota Senior Secondary School B Field
12      SHN      SEY     Achimota Senior Secondary School A Field
13      SWT      SHN     Achimota Senior Secondary School A Field
14      SEY       GH     Achimota Senior Secondary School B Field
15      MWI      TAN     Achimota Senior Secondary School A Field
16      KKR       MI                             Wankhede Stadium
17      SRH      RCB                        M.Chinnaswamy Stadium
18      LHQ      KRK                              Gaddafi Stadium
19      QTG     HYDK                              Gaddafi Stadium
20      ISU       MS                              Gaddafi Stadium
21      RWP      PSZ                              Gaddafi Stadium
22      KRK      QTG                              Gaddafi Stadium
23      LHQ     HYDK                              Gaddafi Stadium
24      RRP     KNSO  Indira Gandhi International Cricket Stadium
25      RRP       MS  Indira Gandhi International Cricket Stadium
26     INDT     KNSO  Indira Gandhi International Cricket Stadium
27      RRP       MS  Indira Gandhi International Cricket Stadium
28     INDT     KNSO  Indira Gandhi International Cricket Stadium
29     KNSO     INDT  Indira Gandhi International Cricket Stadium
30       MS     SNSS  Indira Gandhi International Cricket Stadium
31       MS     KNSO  Indira Gandhi International Cricket Stadium
32     SNSS     INDT  Indira Gandhi International Cricket Stadium
33      RRP   INDCAP  Indira Gandhi International Cricket Stadium
34     KNSO     SNSS  Indira Gandhi International Cricket Stadium
35    LIONS      TIT                        The Wanderers Stadium
36      WAR      TIT                             St George's Park
37      NZW     RSAW                                  Hagley Oval
38      NZW     RSAW                                  Hagley Oval
39     AUSW      WIW                                  Warner Park
40     AUSW      WIW                            Arnos Vale Ground
41     NGAW     RWAW            Tafawa Balewa Square Cricket Oval
42  RSAWU19  ZIMWU19            Tafawa Balewa Square Cricket Oval
43  RSAWU19     NGAW            Tafawa Balewa Square Cricket Oval
44  ZIMWU19     RWAW            Tafawa Balewa Square Cricket Oval
45  ZIMWU19      GHW            Tafawa Balewa Square Cricket Oval
46  RSAWU19     NGAW            Tafawa Balewa Square Cricket Oval
47     NGAW     RWAW            Tafawa Balewa Square Cricket Oval
48  RSAWU19  ZIMWU19            Tafawa Balewa Square Cricket Oval

                     city                                             status
0            Christchurch                        South Africa won by 33 runs
1                   Accra      Match abandoned due to wet outfield (No toss)
2                   Accra      Match abandoned due to wet outfield (No toss)
3                   Accra              Match abandoned due to rain (no toss)
4                   Accra                               Malawi won by 6 wkts
5                   Accra                               Ghana won by 83 runs
6                   Accra                           Tanzania won by 161 runs
7                   Accra                           Tanzania won by 153 runs
8                   Accra                               Malawi won by 8 wkts
9                   Accra                                Ghana won by 9 wkts
10                  Accra                                Ghana won by 2 wkts
11                  Accra                           Tanzania won by 158 runs
12                  Accra                           Seychelles won by 7 wkts
13                  Accra                            Eswatini won by 27 runs
14                  Accra                                Ghana won by 6 wkts
15                  Accra                             Tanzania won by 8 wkts
16                 Mumbai                       Mumbai Indians won by 6 wkts
17              Bengaluru          Royal Challengers Bengaluru won by 6 wkts
18                 Lahore                        Karachi Kings won by 4 wkts
19                 Lahore                   Quetta Gladiators won by 40 runs
20                 Lahore                       Multan Sultans won by 5 wkts
21                 Lahore                       Peshawar Zalmi won by 5 wkts
22                 Lahore                       Karachi Kings won by 14 runs
23                 Lahore                    Lahore Qalandars won by 69 runs
24               Haldwani                 Royal Riders Punjab won by 41 runs
25               Haldwani  Match cancelled, Royal Riders Punjab were decl...
26               Haldwani  Konark Suryas Odisha won by 8 wkts (2nd inning...
27               Haldwani  Match rescheduled to 27/03/2026 due to wet out...
28               Haldwani  Match rescheduled to 27/03/2026 due to wet out...
29               Haldwani  Match Cancelled - No contest on the field - In...
30               Haldwani  Southern Super Stars have been disqualified  -...
31               Haldwani                 Konark Suryas Odisha won by 3 wkts
32               Haldwani  Southern Super Stars have been disqualified - ...
33               Haldwani  Royal Riders Punjab won by 49 runs - 14 Overs ...
34               Haldwani  Southern Super Stars have been disqualified  -...
35           Johannesburg                               Titans won by 3 wkts
36               Gqeberha                               Titans won by 4 wkts
37           Christchurch                   South Africa Women won by 2 wkts
38           Christchurch                   New Zealand Women won by 92 runs
39   Basseterre, St Kitts                    Australia Women won by 103 runs
40  Kingstown, St Vincent  Australia Women won by 40 runs (DLS method) du...
41                  Lagos                        Nigeria Women won by 9 runs
42                  Lagos              South Africa Women U19 won by 70 runs
43                  Lagos                        Nigeria Women won by 7 wkts
44                  Lagos                         Rwanda Women won by 5 wkts
45                  Lagos                 Zimbabwe Women U19 won by 180 runs
46                  Lagos      Match Tied (Nigeria Women won the Super Over)
47                  Lagos                         Rwanda Women won by 6 wkts
48                  Lagos              South Africa Women U19 won by 28 runs

In [8]:
import os
from dotenv import load_dotenv
import pandas as pd 
from pathlib import Path
from sqlalchemy import create_engine


    # Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")


engine = create_engine(f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")
RM.to_sql(name="recent_matches",con=engine,if_exists="replace",index=False)
print(f"Data uploaded to MySQL successfully, Database: {database}, recent_matches")

Data uploaded to MySQL successfully, Database: CricBuzz, recent_matches

Question 3 List the top 10 highest run scorers in ODI cricket. Show player name, total runs scored, batting average, and number of centuries. Display the highest run scorer first.

In [9]:
import requests
import pandas as pd

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats/0"

headers = {
    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

# --- Fetch Most Runs (ODI) ---
response1 = requests.get(url, headers=headers, params={"statsType": "mostRuns", "matchTypeId": "2"})
runs_data = response1.json().get("values", [])

# --- Fetch Most Hundreds (ODI) ---
response2 = requests.get(url, headers=headers, params={"statsType": "mostHundreds", "matchTypeId": "2"})
hundreds_data = response2.json().get("values", [])

# --- Build Lookup: Player ID -> Hundreds ---
hundreds_by_id = {p["values"][0]: p["values"][5] for p in hundreds_data}

# --- Sort by Runs Descending ---
runs_sorted = sorted(runs_data, key=lambda x: int(x["values"][4]), reverse=True)

# --- Build DataFrame ---
records = []
for player in runs_sorted[:10]:
    player_id = player["values"][0]
    records.append({
        "Player ID" : player_id,
        "Player"    : player["values"][1],
        "Runs"      : int(player["values"][4]),
        "Average"   : float(player["values"][5]),
        "100s"      : int(hundreds_by_id.get(player_id, 0))
    })

most_run_scores = pd.DataFrame(records)
most_run_scores.index = range(1, len(most_run_scores) + 1)  # Rank starting from 1
most_run_scores.index.name = "Rank"

print(most_run_scores.to_string())

     Player ID         Player   Runs  Average  100s
Rank
1           25      Tendulkar  15921    53.79    51
2         8019           Root  13943    51.07    41
3           38  Ricky Ponting  13378    51.85    41
4          213         Kallis  13289    55.37    45
5           27         Dravid  13288    52.31    36
6          488           Cook  12472    45.35    33
7          104     Sangakkara  12400    57.14    38
8          240         B Lara  11953    52.89    34
9          244    Chanderpaul  11867    51.37    30
10         101         Mahela  11814    49.85    34

In [10]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path 
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")


engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")
most_run_scores.to_sql(name="mostruns_odi", con=engine, if_exists="replace", index=False)

print(
    f"Data uploaded to MySQL successfully, Database: {database}, Table: mostruns_odi")

Data uploaded to MySQL successfully, Database: CricBuzz, Table: mostruns_odi

Question 4 Display all cricket venues that have a seating capacity of more than 25,000 spectators. Show venue name, city, country, and capacity. Order by largest capacity first (10 Venues enough).

In [11]:
import time
import requests
import pandas as pd

headers = {
    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
    "Content-Type": "application/json"
}

valid_data = []
error_data = []

for venue_id in range(1, 500):
    url = f"https://cricbuzz-cricket.p.rapidapi.com/venues/v1/{venue_id}"

    try:
        response = requests.get(url, headers=headers, timeout=10)

        if response.status_code != 200:
            error_data.append({
                "id": venue_id,
                "ground": "N/A",
                "capacity": 0,
                "city": "N/A",
                "country": "N/A",
                "error": f"HTTP {response.status_code}"
            })
            continue

        data = response.json()

        if not data:
            error_data.append({
                "id": venue_id,
                "ground": "N/A",
                "capacity": 0,
                "city": "N/A",
                "country": "N/A",
                "error": "Empty JSON"
            })
            continue

        ground = data.get("ground", "N/A")
        capacity = data.get("capacity", "0")
        city = data.get("city", "N/A")
        country = data.get("country", "N/A")

        try:
            capacity = int(str(capacity).replace(",", ""))
        except:
            capacity = 0

        valid_data.append({
            "id": venue_id,
            "ground": ground,
            "capacity": capacity,
            "city": city,
            "country": country
        })

    except Exception as e:
        error_data.append({
            "id": venue_id,
            "ground": "N/A",
            "capacity": 0,
            "city": "N/A",
            "country": "N/A",
            "error": str(e)
        })

    time.sleep(3)

# --- CONVERT TO DATAFRAMES ---
df_valid = pd.DataFrame(valid_data)

# --- TOP 10 STADIUMS BY CAPACITY ---
venue_top10 = df_valid.sort_values(by="capacity", ascending=False).head(10).reset_index(drop=True)
venue_top10.index += 1
venue_top10.index.name = "Rank"

# --- OUTPUT ---
print("\n🔥 TOP 10 STADIUMS (BY CAPACITY):")
print(venue_top10.to_string())

venue_list25k = df_valid[df_valid["capacity"] >= 25000].sort_values(by="capacity", ascending=False)
print(venue_list25k.to_string(index=False))

🔥 TOP 10 STADIUMS (BY CAPACITY):
       id                                            ground  capacity                  city       country
Rank
1      50                             Narendra Modi Stadium    132000             Ahmedabad         India
2     205                                        Ellis Park    100000          Johannesburg  South Africa
3     286                                 Stadium Australia     78000  Homebush Bay, Sydney     Australia
4     273                             Moses Mabhida Stadium     69000                Durban  South Africa
5     335  Shaheed Veer Narayan Singh International Stadium     65000                Raipur         India
6      31                                      Eden Gardens     63000               Kolkata         India
7     236                          Jawaharlal Nehru Stadium     60000                 Delhi         India
8     132                        Dr DY Patil Sports Academy     60000          Navi Mumbai          India
9      47                                     Nehru Stadium     60000                 Kochi         India
10     11                            MA Chidambaram Stadium     50000               Chennai         India
 id                                                       ground  capacity                    city              country
 50                                        Narendra Modi Stadium    132000               Ahmedabad                India
205                                                   Ellis Park    100000            Johannesburg         South Africa
286                                            Stadium Australia     78000    Homebush Bay, Sydney            Australia
273                                        Moses Mabhida Stadium     69000                  Durban         South Africa
335             Shaheed Veer Narayan Singh International Stadium     65000                  Raipur                India
 31                                                 Eden Gardens     63000                 Kolkata                India
 47                                                Nehru Stadium     60000                   Kochi                India
132                                   Dr DY Patil Sports Academy     60000            Navi Mumbai                 India
236                                     Jawaharlal Nehru Stadium     60000                   Delhi                India
227                                                 Bramall Lane     50000               Sheffield              England
151                               Narendra Modi Stadium A Ground     50000               Ahmedabad                India
 11                                       MA Chidambaram Stadium     50000                 Chennai                India
485 Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium     50000                 Lucknow                India
 51                                         Arun Jaitley Stadium     48000                   Delhi                India
 34                                        Sydney Cricket Ground     48000                  Sydney            Australia
 29                          Vidarbha Cricket Association Ground     45000                  Nagpur                India
 32                                                   Green Park     45000                  Kanpur                India
115                                   Captain Roop Singh Stadium     45000                 Gwalior                India
228                         Vidarbha Cricket Association Stadium     45000                  Nagpur                India
103                                             Barabati Stadium     45000                 Cuttack                India
 41                                                    Eden Park     41000                Auckland          New Zealand
 27                                        M.Chinnaswamy Stadium     40000               Bengaluru                India
380                                    Barsapara Cricket Stadium     40000                Guwahati                India
 80                           Rajiv Gandhi International Stadium     38000               Hyderabad                India
 43                                                  AMI Stadium     36500            Christchurch          New Zealand
 36                                 Bangabandhu National Stadium     36000                   Dhaka           Bangladesh
 15                                          R.Premadasa Stadium     35000                 Colombo            Sri Lanka
254                      Pallekele International Cricket Stadium     35000               Pallekele            Sri Lanka
113                                  Galle International Stadium     35000                   Galle            Sri Lanka
255                      Mahinda Rajapaksa International Stadium     34300              Hambantota            Sri Lanka
 24                                             National Stadium     34228                 Karachi             Pakistan
 88                                        The Wanderers Stadium     34000            Johannesburg         South Africa
 81                                             Wankhede Stadium     33000                  Mumbai                India
130                                  Lal Bahadur Shastri Stadium     30000               Hyderabad                India
294                                        New Wanderers Stadium     30000            Johannesburg         South Africa
241                                     Barkatullah Khan Stadium     30000                 Jodhpur                India
316                          Maharaja Bir Bikram College Stadium     30000                Agartala                India
 22                                       Multan Cricket Stadium     30000                  Multan             Pakistan
 19                                                       Lord's     30000                  London              England
 46                 Punjab Cricket Association IS Bindra Stadium     30000                  Mohali                India
 76                                       Sawai Mansingh Stadium     30000                  Jaipur                India
210                                                   Carisbrook     29000                 Dunedin          New Zealand
 55                                              Kensington Oval     28000    Bridgetown, Barbados          West Indies
290                             Niranjan Shah Stadium, Khandheri     28000                  Rajkot                India
154                                     ACA-VDCA Cricket Stadium     28000           Visakhapatnam                India
 84                                                Nehru Stadium     27300                  Margao                India
 26                                              Gaddafi Stadium     27000                  Lahore             Pakistan
215                                            Exhibition Ground     26000                Brisbane            Australia
 54                                            Queen's Park Oval     25000 Port of Spain, Trinidad          West Indies
 52                                                     Newlands     25000               Cape Town         South Africa
 53                                                       Bourda     25000      Georgetown, Guyana          West Indies
 30                                                Iqbal Stadium     25000              Faisalabad             Pakistan
 74                                                    Kingsmead     25000                  Durban         South Africa
 83                                          Nahar Singh Stadium     25000               Faridabad                India
 77                                                Nehru Stadium     25000                    Pune                India
 86                                                Nehru Stadium     25000                  Indore                India
128                                Shere Bangla National Stadium     25000                   Dhaka           Bangladesh
153                          Dubai International Cricket Stadium     25000                   Dubai United Arab Emirates
237                                 Indira Priyadarshini Stadium     25000           Visakhapatnam                India
235                                     K.D.Singh 'Babu' Stadium     25000                 Lucknow                India
344                     Vishvesharayya Iron and Steel Ltd Ground     25000              Bhadravati                India

In [12]:
import os
from dotenv import load_dotenv
import pandas as pd
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")


engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")
venue_list25k.to_sql(name="bigger_venues", con=engine, if_exists="replace", index=False)

print(f"Data uploaded to MySQL successfully, Database: {database}, Table: bigger_venues")

Data uploaded to MySQL successfully, Database: CricBuzz, Table: bigger_venues

Question 5 Calculate how many matches each team has won. Show team name and total number of wins. Display teams with the most wins first.

In [13]:
import requests
import pandas as pd

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/series/9237/points-table"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers)
data = response.json()

teams = data["pointsTable"][0]["pointsTableInfo"]

df = pd.DataFrame([
    {
        "team_name": t["teamFullName"],
        "total_wins": t["matchesWon"]
    }
    for t in teams
]).sort_values("total_wins", ascending=False).reset_index(drop=True)

df.index += 1
df.index.name="Sl.no"
print(df.to_string())

                         team_name  total_wins
Sl.no
1                     Punjab Kings           9
2      Royal Challengers Bengaluru           9
3                   Gujarat Titans           9
4                   Mumbai Indians           8
5                   Delhi Capitals           7
6              Sunrisers Hyderabad           6
7             Lucknow Super Giants           6
8            Kolkata Knight Riders           5
9                 Rajasthan Royals           4
10             Chennai Super Kings           4

In [14]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")


engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")
df.to_sql(name="matches_won", con=engine, if_exists="replace", index=False)

print(
    f"Data uploaded to MySQL successfully, Database: {database}, Table: matches_won ")

Data uploaded to MySQL successfully, Database: CricBuzz, Table: matches_won

Question 6 Count how many players belong to each playing role (like Batsman, Bowler, All-rounder, Wicket-keeper). Show the role and count of players for each role.

In [15]:
import requests 
players_data = []
test_team_ids = [2, 3, 4, 5]

for team_id in test_team_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/teams/v1/{team_id}/players"
    headers = {
        "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
        "Content-Type": "application/json"
    }
    response = requests.get(url, headers=headers)
    players_data.append(response.json())

print(players_data)

[{'player': [{'name': 'BATSMEN', 'imageId': 174146}, {'id': '11808', 'name': 'Shubman Gill', 'imageId': 616515, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '13940', 'name': 'Yashasvi Jaiswal', 'imageId': 591942, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '13866', 'name': 'Sai Sudharsan', 'imageId': 717782, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '576', 'name': 'Rohit Sharma', 'imageId': 616514, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '1413', 'name': 'Virat Kohli', 'imageId': 616517, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm medium'}, {'id': '7915', 'name': 'Suryakumar Yadav', 'imageId': 846028, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '9428', 'name': 'Shreyas Iyer', 'imageId': 616518, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '10896', 'name': 'Rinku Singh', 'imageId': 846030, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '14504', 'name': 'Tilak Varma', 'imageId': 846029, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '11813', 'name': 'Ruturaj Gaikwad', 'imageId': 781069, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '10636', 'name': 'Rajat Patidar', 'imageId': 760758, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '9429', 'name': 'Sarfaraz Khan', 'imageId': 591955, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '9716', 'name': 'Abhimanyu Easwaran', 'imageId': 591956, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '8257', 'name': 'Karun Nair', 'imageId': 717781, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'name': 'ALL ROUNDER', 'imageId': 174146}, {'id': '14701', 'name': 'Nitish Kumar Reddy', 'imageId': 591947, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '9647', 'name': 'Hardik Pandya', 'imageId': 846032, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '11195', 'name': 'Shivam Dube', 'imageId': 846034, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm medium'}, {'id': '12086', 'name': 'Abhishek Sharma', 'imageId': 846031, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '587', 'name': 'Ravindra Jadeja', 'imageId': 616520, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '8683', 'name': 'Shardul Thakur', 'imageId': 352487, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '10945', 'name': 'Washington Sundar', 'imageId': 616522, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '8808', 'name': 'Axar Patel', 'imageId': 846033, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'name': 'WICKET KEEPER', 'imageId': 174146}, {'id': '10744', 'name': 'Rishabh Pant', 'imageId': 616524, 'battingStyle': 'Left-hand bat'}, {'id': '8733', 'name': 'KL Rahul', 'imageId': 616523, 'battingStyle': 'Right-hand bat'}, {'id': '14691', 'name': 'Dhruv Jurel', 'imageId': 591954, 'battingStyle': 'Right-hand bat'}, {'id': '8271', 'name': 'Sanju Samson', 'imageId': 846035, 'battingStyle': 'Right-hand bat'}, {'id': '10276', 'name': 'Ishan Kishan', 'imageId': 846036, 'battingStyle': 'Left-hand bat'}, {'name': 'BOWLER', 'imageId': 174146}, {'id': '10808', 'name': 'Mohammed Siraj', 'imageId': 591952, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast'}, {'id': '9311', 'name': 'Jasprit Bumrah', 'imageId': 846037, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast'}, {'id': '10551', 'name': 'Prasidh Krishna', 'imageId': 591958, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast'}, {'id': '14726', 'name': 'Akash Deep', 'imageId': 591951, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '8292', 'name': 'Kuldeep Yadav', 'imageId': 846039, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm wrist-spin'}, {'id': '13217', 'name': 'Arshdeep Singh', 'imageId': 846038, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm fast-medium'}, {'id': '24729', 'name': 'Harshit Rana', 'imageId': 616529, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '14659', 'name': 'Ravi Bishnoi', 'imageId': 226280, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '10754', 'name': 'Mukesh Kumar', 'imageId': 333872, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '12926', 'name': 'Varun Chakaravarthy', 'imageId': 846040, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}]}, {'player': [{'name': 'BATSMEN', 'imageId': 174146}, {'id': '8364', 'name': 'Imam-ul-Haq', 'imageId': 617489, 'battingStyle': 'Left-hand bat'}, {'id': '15847', 'name': 'Muhammad Hurraira', 'imageId': 174146, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '8359', 'name': 'Babar Azam', 'imageId': 846059, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '9545', 'name': 'Shan Masood', 'imageId': 244962, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm medium'}, {'id': '10863', 'name': 'Fakhar Zaman', 'imageId': 846057, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '41113', 'name': 'Hasan Nawaz', 'imageId': 174146, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '13625', 'name': 'Sahibzada Farhan', 'imageId': 846069, 'battingStyle': 'Right-hand bat'}, {'id': '12139', 'name': 'Abdullah Shafique', 'imageId': 352418, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '37572', 'name': 'Tayyab Tahir', 'imageId': 616438, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '13239', 'name': 'Omair Yousuf', 'imageId': 174146, 'battingStyle': 'Right-hand bat'}, {'id': '1433121', 'name': 'Abdul Samad', 'imageId': 174146, 'battingStyle': 'Right-hand bat'}, {'name': 'ALL ROUNDER', 'imageId': 174146}, {'id': '9812', 'name': 'Saud Shakeel', 'imageId': 616442, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '9807', 'name': 'Kamran Ghulam', 'imageId': 616444, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '10101', 'name': 'Salman Agha', 'imageId': 846055, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '14241', 'name': 'Saim Ayub', 'imageId': 846058, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '12565', 'name': 'Khushdil Shah', 'imageId': 616448, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '15460', 'name': 'Irfan Khan', 'imageId': 582346, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '9804', 'name': 'Hussain Talat', 'imageId': 174146, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm medium'}, {'id': '14545', 'name': 'Noman Ali', 'imageId': 174146, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '11265', 'name': 'Faheem Ashraf', 'imageId': 846064, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm medium'}, {'id': '11186', 'name': 'Shadab Khan', 'imageId': 846060, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '55256', 'name': 'Jahandad Khan', 'imageId': 174146, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm fast-medium'}, {'name': 'WICKET KEEPER', 'imageId': 174146}, {'id': '13192', 'name': 'Rohail Nazir', 'imageId': 155978, 'battingStyle': 'Right-hand bat'}, {'id': '9468', 'name': 'Mohammad Rizwan', 'imageId': 616445, 'battingStyle': 'Right-hand bat'}, {'id': '15038', 'name': 'Mohammad Haris', 'imageId': 244950, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '19013', 'name': 'Usman Khan', 'imageId': 846070, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'name': 'BOWLER', 'imageId': 174146}, {'id': '12555', 'name': 'Abrar Ahmed', 'imageId': 846068, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '19066', 'name': 'Sajid Khan', 'imageId': 174146, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '35250', 'name': 'Mohammad Ali', 'imageId': 174146, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '19627', 'name': 'Khurram Shahzad', 'imageId': 174146, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm medium'}, {'id': '1450089', 'name': 'Kashif Ali', 'imageId': 174146, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm medium'}, {'id': '14561', 'name': 'Haris Rauf', 'imageId': 616449, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast'}, {'id': '14247', 'name': 'Naseem Shah', 'imageId': 846067, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast'}, {'id': '11320', 'name': 'Hasan Ali', 'imageId': 352428, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '15034', 'name': 'Abbas Afridi', 'imageId': 582350, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '15751', 'name': 'Akif Javed', 'imageId': 174146, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Left-arm fast-medium'}, {'id': '15040', 'name': 'Mohammad Wasim Jr', 'imageId': 352429, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '41169', 'name': 'Sufiyan Muqeem', 'imageId': 174146, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm wrist-spin'}, {'id': '12160', 'name': 'Shaheen Afridi', 'imageId': 846065, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm fast-medium'}, {'id': '14248', 'name': 'Mohammad Hasnain', 'imageId': 616436, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}]}, {'player': [{'name': 'BATSMEN', 'imageId': 174146}, {'id': '2250', 'name': 'Steven Smith', 'imageId': 619873, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '10182', 'name': 'Marnus Labuschagne', 'imageId': 619875, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '8497', 'name': 'Travis Head', 'imageId': 845768, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '11375', 'name': 'Jake Weatherald', 'imageId': 226265, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'name': 'ALL ROUNDER', 'imageId': 174146}, {'id': '12225', 'name': 'Cameron Green', 'imageId': 845943, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '8646', 'name': 'Beau Webster', 'imageId': 178326, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm medium'}, {'id': '6250', 'name': 'Mitchell Marsh', 'imageId': 845760, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '8130', 'name': 'Michael Neser', 'imageId': 332917, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'name': 'WICKET KEEPER', 'imageId': 174146}, {'id': '9200', 'name': 'Alex Carey', 'imageId': 619880, 'battingStyle': 'Left-hand bat'}, {'id': '10637', 'name': 'Josh Inglis', 'imageId': 845950, 'battingStyle': 'Right-hand bat'}, {'name': 'BOWLER', 'imageId': 174146}, {'id': '8095', 'name': 'Pat Cummins', 'imageId': 352460, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast'}, {'id': '7710', 'name': 'Mitchell Starc', 'imageId': 352462, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm fast'}, {'id': '8642', 'name': 'Adam Zampa', 'imageId': 845772, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '6258', 'name': 'Josh Hazlewood', 'imageId': 845819, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '11689', 'name': 'Xavier Bartlett', 'imageId': 845954, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '8631', 'name': 'Scott Boland', 'imageId': 332914, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '15480', 'name': 'Nathan Ellis', 'imageId': 845764, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '13141', 'name': 'Matthew Kuhnemann', 'imageId': 845767, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '15146', 'name': 'Todd Murphy', 'imageId': 332916, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '11772', 'name': 'Brendan Doggett', 'imageId': 180286, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '7850', 'name': 'Nathan Lyon', 'imageId': 332913, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}]}, {'player': [{'name': 'BATSMEN', 'imageId': 174146}, {'id': '13682', 'name': 'Pathum Nissanka', 'imageId': 847160, 'battingStyle': 'Right-hand bat'}, {'id': '15081', 'name': 'Pavan Rathnayake', 'imageId': 847149, 'battingStyle': 'Right-hand bat'}, {'id': '11545', 'name': 'Oshada Fernando', 'imageId': 582354, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '13884', 'name': 'Pasindu Sooriyabandara', 'imageId': 174146, 'battingStyle': 'Right-hand bat'}, {'id': '10939', 'name': 'Avishka Fernando', 'imageId': 170702, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '13187', 'name': 'Nuwanidu Fernando', 'imageId': 155852, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'name': 'ALL ROUNDER', 'imageId': 174146}, {'id': '1629', 'name': 'Angelo Mathews', 'imageId': 170706, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '10940', 'name': 'Kamindu Mendis', 'imageId': 847173, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '7872', 'name': 'Dhananjaya de Silva', 'imageId': 351878, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '10934', 'name': 'Charith Asalanka', 'imageId': 847180, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '13694', 'name': 'Janith Liyanage', 'imageId': 847190, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '13930', 'name': 'Sonal Dinusha', 'imageId': 174146, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '18515', 'name': 'Tharindu Rathnayake', 'imageId': 174146, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '39678', 'name': 'Milan Priyanath Rathnayake', 'imageId': 717700, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '14251', 'name': 'Dunith Wellalage', 'imageId': 847184, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '10926', 'name': 'Wanindu Hasaranga', 'imageId': 847146, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'name': 'WICKET KEEPER', 'imageId': 174146}, {'id': '6245', 'name': 'Dinesh Chandimal', 'imageId': 582334, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '9494', 'name': 'Kusal Mendis', 'imageId': 847148, 'battingStyle': 'Right-hand bat'}, {'id': '15586', 'name': 'Lahiru Udara', 'imageId': 717709, 'battingStyle': 'Right-hand bat'}, {'id': '13236', 'name': 'Nishan Madushka', 'imageId': 155859, 'battingStyle': 'Right-hand bat'}, {'id': '9495', 'name': 'Sadeera Samarawickrama', 'imageId': 351890, 'battingStyle': 'Right-hand bat'}, {'name': 'BOWLER', 'imageId': 174146}, {'id': '10938', 'name': 'Asitha Fernando', 'imageId': 582352, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '11498', 'name': 'Prabath Jayasuriya', 'imageId': 582353, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Left-arm orthodox'}, {'id': '10472', 'name': 'Kasun Rajitha', 'imageId': 351884, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '8483', 'name': 'Akila Dananjaya', 'imageId': 717699, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '41309', 'name': 'Isitha Wijesundera', 'imageId': 174146, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '10928', 'name': 'Lahiru Kumara', 'imageId': 351887, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '13675', 'name': 'Nishan Peiris', 'imageId': 174146, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm offbreak'}, {'id': '8413', 'name': 'Vishwa Fernando', 'imageId': 165706, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Left-arm fast-medium'}, {'id': '10469', 'name': 'Jeffrey Vandersay', 'imageId': 244667, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm legbreak'}, {'id': '14574', 'name': 'Mohamed Shiraz', 'imageId': 174146, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '46926', 'name': 'Eshan Malinga', 'imageId': 174146, 'battingStyle': 'Left-hand bat', 'bowlingStyle': 'Right-arm fast-medium'}, {'id': '18504', 'name': 'Maheesh Theekshana', 'imageId': 847197, 'battingStyle': 'Right-hand bat', 'bowlingStyle': 'Right-arm offbreak'}]}]

In [17]:
import pandas as pd

players_list = []
team_names = {2: 'India', 3: 'Pakistan', 4: 'Australia', 5: 'Sri Lanka'}

for team_id, team_data in zip(test_team_ids, players_data):
    current_role = 'Unknown'
    for player in team_data['player']:
        if 'id' not in player:
            current_role = player['name']
        else:
            players_list.append({
                'Team ID': team_id,
                'Team Name': team_names[team_id],
                'Player ID': player['id'],
                'Player Name': player['name'],
                'Role': current_role,
                'Batting Style': player.get('battingStyle', 'Unknown'),
                'Bowling Style': player.get('bowlingStyle', 'Unknown'),
            })

all_players_data = pd.DataFrame(players_list)
all_players_data.index = all_players_data.index + 1
all_players_data.index.name = 'Sl No'
print(all_players_data)

       Team ID  Team Name Player ID         Player Name     Role  \
Sl No
1            2      India     11808        Shubman Gill  BATSMEN
2            2      India     13940    Yashasvi Jaiswal  BATSMEN
3            2      India     13866       Sai Sudharsan  BATSMEN
4            2      India       576        Rohit Sharma  BATSMEN
5            2      India      1413         Virat Kohli  BATSMEN
...        ...        ...       ...                 ...      ...
127          5  Sri Lanka      8413     Vishwa Fernando   BOWLER
128          5  Sri Lanka     10469   Jeffrey Vandersay   BOWLER
129          5  Sri Lanka     14574      Mohamed Shiraz   BOWLER
130          5  Sri Lanka     46926       Eshan Malinga   BOWLER
131          5  Sri Lanka     18504  Maheesh Theekshana   BOWLER

        Batting Style          Bowling Style
Sl No
1      Right-hand bat     Right-arm offbreak
2       Left-hand bat     Right-arm legbreak
3       Left-hand bat     Right-arm legbreak
4      Right-hand bat     Right-arm offbreak
5      Right-hand bat       Right-arm medium
...               ...                    ...
127    Right-hand bat   Left-arm fast-medium
128    Right-hand bat     Right-arm legbreak
129    Right-hand bat  Right-arm fast-medium
130     Left-hand bat  Right-arm fast-medium
131    Right-hand bat     Right-arm offbreak

[131 rows x 7 columns]

In [18]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")


engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")
all_players_data.to_sql(name="all_players", con=engine, if_exists="replace", index=False)

print(
    f"Data uploaded to MySQL successfully, Database: {database}, Table: all_players ")

Data uploaded to MySQL successfully, Database: CricBuzz, Table: all_players

Question 7 Find the highest individual batting score achieved in each cricket format (Test, ODI, T20I). Display the format and the highest score for that format.

In [21]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats"
querystring = {"statsType": "highestScore", "formatType": "test"}

headers = {
    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)
highest_score_test=response.json()
print(highest_score_test)
top = highest_score_test['values'][0]['values']
print("Format        :", highest_score_test['filter']['selectedMatchType'].upper())
print("Player        :", top[1])
print("Highest Score :", top[2])

{'filter': {'matchtype': [{'matchTypeId': '1', 'matchTypeDesc': 'test'}, {'matchTypeId': '2', 'matchTypeDesc': 'odi'}, {'matchTypeId': '3', 'matchTypeDesc': 't20i'}], 'team': [{'id': '2', 'teamShortName': 'IND'}, {'id': '27', 'teamShortName': 'IRE'}, {'id': '3', 'teamShortName': 'PAK'}, {'id': '4', 'teamShortName': 'AUS'}, {'id': '5', 'teamShortName': 'SL'}, {'id': '6', 'teamShortName': 'BAN'}, {'id': '9', 'teamShortName': 'ENG'}, {'id': '10', 'teamShortName': 'WI'}, {'id': '11', 'teamShortName': 'RSA'}, {'id': '12', 'teamShortName': 'ZIM'}, {'id': '13', 'teamShortName': 'NZ'}, {'id': '96', 'teamShortName': 'AFG'}], 'selectedMatchType': 'test'}, 'headers': ['Batter', 'HS', 'Balls', 'SR', 'Vs'], 'values': [{'values': ['240', 'B Lara', '400', '582', '68.73', 'ENG']}, {'values': ['157', 'Matthew Hayden', '380', '437', '86.96', 'ZIM']}, {'values': ['240', 'B Lara', '375', '538', '69.70', 'ENG']}, {'values': ['101', 'Mahela', '374', '572', '65.38', 'RSA']}, {'values': ['11200', 'Mulder', '367', '334', '109.88', 'ZIM']}, {'values': ['4160', 'G Sobers', '365', '', '', 'PAK']}, {'values': ['5141', 'S Hutton', '364', '847', '42.98', 'AUS']}, {'values': ['102', 'S Jayasuriya', '340', '578', '58.82', 'IND']}, {'values': ['5759', 'H Mohammad', '337', '', '', 'WI']}, {'values': ['5074', 'W Hammond', '336', '', '', 'NZ']}, {'values': ['1739', 'David Warner', '335', '418', '80.14', 'PAK']}, {'values': ['5945', 'DG Bradman', '334', '448', '74.55', 'ENG']}, {'values': ['4729', 'M Taylor', '334', '564', '59.22', 'PAK']}, {'values': ['247', 'Gayle', '333', '437', '76.20', 'SL']}, {'values': ['5308', 'G Gooch', '333', '485', '68.66', 'IND']}, {'values': ['35', 'Inzamam-ul-Haq', '329', '436', '75.46', 'NZ']}, {'values': ['138', 'Clarke', '329', '468', '70.30', 'IND']}, {'values': ['5052', 'A Sandham', '325', '640', '50.78', 'WI']}, {'values': ['26', 'Sehwag', '319', '304', '104.93', 'RSA']}, {'values': ['104', 'Sangakkara', '319', '482', '66.18', 'BAN']}, {'values': ['12201', 'Harry Brook', '317', '322', '98.45', 'PAK']}, {'values': ['247', 'Gayle', '317', '483', '65.63', 'RSA']}, {'values': ['130', 'Younis Khan', '313', '568', '55.11', 'SL']}, {'values': ['314', 'Amla', '311', '529', '58.79', 'ENG']}, {'values': ['4667', 'Bob Simpson', '311', '740', '42.03', 'ENG']}, {'values': ['5262', 'J Edrich', '310', '450', '68.89', 'NZ']}, {'values': ['26', 'Sehwag', '309', '375', '82.40', 'PAK']}, {'values': ['6045', 'B Cowper', '307', '589', '52.12', 'ENG']}, {'values': ['5945', 'DG Bradman', '304', '473', '64.27', 'ENG']}, {'values': ['8257', 'Karun Nair', '303', '381', '79.53', 'ENG']}], 'appIndex': {'seoTitle': 'Live cricket scores, schedule, news, archive, series | Cricbuzz.com', 'webURL': 'www.cricbuzz.com'}}
Format        : TEST
Player        : B Lara
Highest Score : 400

In [22]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats"
querystring = {"statsType": "highestScore", "matchType": "2"}

headers = {
    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)
highest_score_odi = response.json()

top = highest_score_odi['values'][0]['values']
print("Format        :", highest_score_odi['filter']['selectedMatchType'].upper())
print("Player        :", top[1])
print("Highest Score :", top[2])

Format        : ODI
Player        : Rohit Sharma
Highest Score : 264

In [23]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/stats/v1/topstats"
querystring = {"statsType": "highestScore", "matchType": "3"}

headers = {
    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers, params=querystring)
highest_score_t20i = response.json()

top = highest_score_t20i['values'][0]['values']
print("Format        :", highest_score_t20i['filter']['selectedMatchType'].upper())
print("Player        :", top[1])
print("Highest Score :", top[2])

Format        : T20I
Player        : Aaron Finch
Highest Score : 172

In [26]:


import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

highest_scores = [
    {"Format": "TEST", "Player": highest_score_test['values'][0]['values'][1], "Highest Score": highest_score_test['values'][0]['values'][2]},
    {"Format": "ODI",  "Player": highest_score_odi['values'][0]['values'][1],  "Highest Score": highest_score_odi['values'][0]['values'][2]},
    {"Format": "T20I", "Player": highest_score_t20i['values'][0]['values'][1],  "Highest Score": highest_score_t20i['values'][0]['values'][2]}
]

highest_scores_data=pd.DataFrame(highest_scores)


engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")
highest_scores_data.to_sql(name="highest_scores", con=engine, if_exists="replace", index=False)

print(
    f"Data uploaded to MySQL successfully, Database: {database}, Table: highest_scores")

Data uploaded to MySQL successfully, Database: CricBuzz, Table: highest_scores

Question 8 Show all cricket series that started in the year 2024. Include series name, host country, match type, start date, and total number of matches planned.

In [30]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/archives/international"
querystring = {"year":"2024"}

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
	"Content-Type": "application/json"
}

response = requests.get(url, headers=headers ,params=querystring)

series_list2024=response.json()
print(series_list2024)

{'seriesMapProto': [{'date': '2024', 'series': [{'id': 8553, 'name': 'Sri Lanka tour of New Zealand, 2024-25', 'startDt': '1734912000000', 'endDt': '1736553600000', 'thumborImageId': 379130}, {'id': 9297, 'name': 'Gulf Cricket T20I Championship, 2024', 'startDt': '1734048000000', 'endDt': '1734739200000', 'thumborImageId': 379130}, {'id': 8044, 'name': 'Pakistan tour of South Africa, 2024 -25', 'startDt': '1733788800000', 'endDt': '1736208000000', 'thumborImageId': 379130}, {'id': 9171, 'name': 'Afghanistan tour of Zimbabwe, 2024-25', 'startDt': '1733702400000', 'endDt': '1736121600000', 'thumborImageId': 379130}, {'id': 9265, 'name': 'ICC Mens T20 World Cup Americas Sub Regional Qualifier, 2024', 'startDt': '1733443200000', 'endDt': '1734307200000', 'thumborImageId': 379130}, {'id': 9289, 'name': 'Africa Continental Cup 2024', 'startDt': '1733270400000', 'endDt': '1734134400000', 'thumborImageId': 379130}, {'id': 8058, 'name': 'Sri Lanka tour of South Africa, 2024', 'startDt': '1732665600000', 'endDt': '1733702400000', 'thumborImageId': 379130}, {'id': 8494, 'name': 'Pakistan tour of Zimbabwe, 2024', 'startDt': '1732406400000', 'endDt': '1733356800000', 'thumborImageId': 379130}, {'id': 7853, 'name': 'England tour of New Zealand, 2024', 'startDt': '1732320000000', 'endDt': '1734480000000', 'thumborImageId': 379130}, {'id': 9132, 'name': 'ICC Mens T20 World Cup Africa Sub Regional Qualifier C 2024', 'startDt': '1732320000000', 'endDt': '1732752000000', 'thumborImageId': 379130}, {'id': 7745, 'name': 'India tour of Australia, 2024-25', 'startDt': '1732233600000', 'endDt': '1736208000000', 'thumborImageId': 379130}, {'id': 9129, 'name': 'ICC Mens T20 World Cup Asia Qualifier B 2024', 'startDt': '1731974400000', 'endDt': '1732752000000', 'thumborImageId': 379130}, {'id': 8116, 'name': 'Bangladesh tour of West Indies, 2024', 'startDt': '1731801600000', 'endDt': '1734566400000', 'thumborImageId': 379130}, {'id': 9125, 'name': 'Netherlands tour of Oman, 2024', 'startDt': '1731456000000', 'endDt': '1731715200000', 'thumborImageId': 379130}, {'id': 9146, 'name': 'Myanmar tour of Indonesia, 2024', 'startDt': '1731369600000', 'endDt': '1731974400000', 'thumborImageId': 379130}, {'id': 9083, 'name': 'New Zealand tour of Sri Lanka, 2024', 'startDt': '1731110400000', 'endDt': '1731974400000', 'thumborImageId': 379130}, {'id': 8404, 'name': 'India tour of South Africa, 2024', 'startDt': '1731024000000', 'endDt': '1731628800000', 'thumborImageId': 379130}, {'id': 9091, 'name': 'Afghanistan v Bangladesh in UAE, 2024', 'startDt': '1730851200000', 'endDt': '1731283200000', 'thumborImageId': 379130}, {'id': 7781, 'name': 'Pakistan tour of Australia, 2024', 'startDt': '1730592000000', 'endDt': '1731801600000', 'thumborImageId': 379130}, {'id': 8107, 'name': 'England tour of West Indies, 2024', 'startDt': '1730332800000', 'endDt': '1731801600000', 'thumborImageId': 379130}, {'id': 9157, 'name': 'Bahrain in Uganda 2024', 'startDt': '1730073600000', 'endDt': '1730160000000', 'thumborImageId': 379130}, {'id': 9033, 'name': 'South Africa tour of Bangladesh, 2024', 'startDt': '1729468800000', 'endDt': '1730505600000', 'thumborImageId': 379130}, {'id': 9041, 'name': 'ICC Mens T20 World Cup Sub Regional Africa Qualifier Group B, 2024', 'startDt': '1729296000000', 'endDt': '1729728000000', 'thumborImageId': 379130}, {'id': 9025, 'name': 'Quadrangular T20I Series in Bhutan, 2024', 'startDt': '1729296000000', 'endDt': '1729814400000', 'thumborImageId': 379130}, {'id': 9115, 'name': 'Seychelles tour of Kenya, Only T20I', 'startDt': '1729209600000', 'endDt': '1729209600000', 'thumborImageId': 379130}, {'id': 9043, 'name': 'Nepal tour of United States of America 2024', 'startDt': '1729123200000', 'endDt': '1729382400000', 'thumborImageId': 379130}, {'id': 8395, 'name': 'New Zealand tour of India, 2024', 'startDt': '1729036800000', 'endDt': '1730764800000', 'thumborImageId': 379130}, {'id': 9009, 'name': 'West Indies tour of Sri Lanka, 2024', 'startDt': '1728777600000', 'endDt': '1729900800000', 'thumborImageId': 379130}, {'id': 9057, 'name': 'Rwanda tour of Malawi 2024', 'startDt': '1728432000000', 'endDt': '1728864000000', 'thumborImageId': 379130}, {'id': 8497, 'name': 'England tour of Pakistan, 2024', 'startDt': '1728259200000', 'endDt': '1730073600000', 'thumborImageId': 379130}, {'id': 9017, 'name': 'Serbia tour of Gibraltar, 2024', 'startDt': '1727654400000', 'endDt': '1727654400000', 'thumborImageId': 379130}, {'id': 8947, 'name': 'Namibia T20I Tri-Series 2024', 'startDt': '1727568000000', 'endDt': '1728086400000', 'thumborImageId': 379130}, {'id': 8598, 'name': 'ICC Mens T20 World Cup Sub Regional East Asia-Pacific Qualifier B, 2024', 'startDt': '1727481600000', 'endDt': '1728086400000', 'thumborImageId': 379130}, {'id': 8955, 'name': 'Canada T20I Tri-Series 2024', 'startDt': '1727481600000', 'endDt': '1727913600000', 'thumborImageId': 379130}, {'id': 7981, 'name': 'Ireland v South Africa in UAE, 2024', 'startDt': '1727308800000', 'endDt': '1728172800000', 'thumborImageId': 379130}, {'id': 8969, 'name': 'T20I Tri-Series in South Korea, 2024', 'startDt': '1727222400000', 'endDt': '1727308800000', 'thumborImageId': 379130}, {'id': 8835, 'name': 'ICC Mens T20 World Cup Africa Sub Regional Qualifier A 2024', 'startDt': '1726876800000', 'endDt': '1727308800000', 'thumborImageId': 379130}, {'id': 8393, 'name': 'Bangladesh tour of India, 2024', 'startDt': '1726704000000', 'endDt': '1728691200000', 'thumborImageId': 379130}, {'id': 8818, 'name': 'New Zealand tour of Sri Lanka, 2024', 'startDt': '1726617600000', 'endDt': '1727654400000', 'thumborImageId': 379130}, {'id': 8661, 'name': 'Afghanistan v South Africa in UAE, 2024', 'startDt': '1726617600000', 'endDt': '1726963200000', 'thumborImageId': 379130}, {'id': 6794, 'name': 'Australia tour of England, 2024', 'startDt': '1726012800000', 'endDt': '1727568000000', 'thumborImageId': 379130}, {'id': 8625, 'name': 'Afghanistan v New Zealand in India, 2024', 'startDt': '1725840000000', 'endDt': '1726185600000', 'thumborImageId': 379130}, {'id': 8552, 'name': 'Australia tour of Scotland, 2024', 'startDt': '1725408000000', 'endDt': '1725667200000', 'thumborImageId': 379130}, {'id': 8764, 'name': 'ICC Mens T20 World Cup Asia Qualifier A 2024', 'startDt': '1724976000000', 'endDt': '1725840000000', 'thumborImageId': 379130}, {'id': 8632, 'name': 'Netherlands T20I Tri-Series, 2024', 'startDt': '1724371200000', 'endDt': '1724803200000', 'thumborImageId': 379130}, {'id': 8596, 'name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier C, 2024', 'startDt': '1724198400000', 'endDt': '1724803200000', 'thumborImageId': 379130}, {'id': 8495, 'name': 'Bangladesh tour of Pakistan, 2024', 'startDt': '1724198400000', 'endDt': '1725321600000', 'thumborImageId': 379130}, {'id': 8686, 'name': 'Malaysia T20I Tri Nations Cup, 2024', 'startDt': '1724198400000', 'endDt': '1724716800000', 'thumborImageId': 379130}, {'id': 8587, 'name': 'ICC Mens T20 World Cup Sub Regional East Asia-Pacific Qualifier A, 2024', 'startDt': '1723852800000', 'endDt': '1724457600000', 'thumborImageId': 379130}, {'id': 6787, 'name': 'Sri Lanka tour of England, 2024', 'startDt': '1723593600000', 'endDt': '1725926400000', 'thumborImageId': 379130}, {'id': 8578, 'name': 'Spain tour of Croatia, 2024', 'startDt': '1722556800000', 'endDt': '1722902400000', 'thumborImageId': 379130}, {'id': 8238, 'name': 'South Africa tour of West Indies, 2024', 'startDt': '1722384000000', 'endDt': '1724716800000', 'thumborImageId': 379130}, {'id': 8528, 'name': 'India tour of Sri Lanka, 2024', 'startDt': '1722038400000', 'endDt': '1722988800000', 'thumborImageId': 379130}, {'id': 7979, 'name': 'Zimbabwe tour of Ireland, 2024', 'startDt': '1721865600000', 'endDt': '1722211200000', 'thumborImageId': 379130}, {'id': 8476, 'name': 'Nigeria tour of Kenya 2024', 'startDt': '1720742400000', 'endDt': '1721174400000', 'thumborImageId': 379130}, {'id': 8337, 'name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier B, 2024', 'startDt': '1720310400000', 'endDt': '1720915200000', 'thumborImageId': 379130}, {'id': 7546, 'name': 'India tour of Zimbabwe, 2024', 'startDt': '1720224000000', 'endDt': '1720915200000', 'thumborImageId': 379130}, {'id': 6780, 'name': 'West Indies tour of England, 2024', 'startDt': '1719964800000', 'endDt': '1722297600000', 'thumborImageId': 379130}, {'id': 8422, 'name': 'Serbia tour of Slovenia, 2024', 'startDt': '1719619200000', 'endDt': '1719705600000', 'thumborImageId': 379130}, {'id': 8382, 'name': 'Kenya Quadrangular Cup 2024', 'startDt': '1719532800000', 'endDt': '1720569600000', 'thumborImageId': 379130}, {'id': 8413, 'name': 'Jersey tour of Guernsey, 2024', 'startDt': '1719014400000', 'endDt': '1719100800000', 'thumborImageId': 379130}, {'id': 8310, 'name': 'Estonia tour of Cyprus 2024', 'startDt': '1718582400000', 'endDt': '1718755200000', 'thumborImageId': 379130}, {'id': 8260, 'name': 'Jersey tour of Denmark, 2024', 'startDt': '1718409600000', 'endDt': '1718496000000', 'thumborImageId': 379130}, {'id': 8332, 'name': 'Nordic T20I Cup 2024', 'startDt': '1718323200000', 'endDt': '1718496000000', 'thumborImageId': 379130}, {'id': 8256, 'name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier A, 2024', 'startDt': '1717891200000', 'endDt': '1718496000000', 'thumborImageId': 379130}, {'id': 8294, 'name': 'Guernsey tour of Belgium, 2024', 'startDt': '1717804800000', 'endDt': '1717891200000', 'thumborImageId': 379130}, {'id': 7476, 'name': 'ICC Mens T20 World Cup 2024', 'startDt': '1717200000000', 'endDt': '1719619200000', 'thumborImageId': 379130}, {'id': 8247, 'name': 'Belgium tour of Austria, 2024', 'startDt': '1716595200000', 'endDt': '1716681600000', 'thumborImageId': 379130}, {'id': 8166, 'name': 'Continental Cup 2024', 'startDt': '1716508800000', 'endDt': '1716681600000', 'thumborImageId': 379130}, {'id': 8103, 'name': 'South Africa tour of West Indies, 2024', 'startDt': '1716422400000', 'endDt': '1716681600000', 'thumborImageId': 379130}, {'id': 6773, 'name': 'Pakistan tour of England, 2024', 'startDt': '1716336000000', 'endDt': '1717027200000', 'thumborImageId': 379130}, {'id': 7700, 'name': 'Bangladesh tour of USA, 2024', 'startDt': '1716249600000', 'endDt': '1716595200000', 'thumborImageId': 379130}, {'id': 7819, 'name': 'Netherlands T20I Tri-Series, 2024', 'startDt': '1715990400000', 'endDt': '1716508800000', 'thumborImageId': 379130}, {'id': 7808, 'name': 'Pakistan tour of Ireland, 2024', 'startDt': '1715299200000', 'endDt': '1715644800000', 'thumborImageId': 379130}, {'id': 8080, 'name': 'Mdina Cup 2024', 'startDt': '1715212800000', 'endDt': '1715472000000', 'thumborImageId': 379130}, {'id': 7896, 'name': 'Mongolia tour of Japan, 2024', 'startDt': '1715040000000', 'endDt': '1715472000000', 'thumborImageId': 379130}, {'id': 7706, 'name': 'Zimbabwe tour of Bangladesh, 2024', 'startDt': '1714694400000', 'endDt': '1715472000000', 'thumborImageId': 379130}, {'id': 8042, 'name': 'Thailand tour of Indonesia 2024', 'startDt': '1714521600000', 'endDt': '1714953600000', 'thumborImageId': 379130}, {'id': 7679, 'name': 'New Zealand tour of Pakistan, 2024', 'startDt': '1713398400000', 'endDt': '1714176000000', 'thumborImageId': 379130}, {'id': 7817, 'name': 'Jersey tour of Spain, 2024', 'startDt': '1713052800000', 'endDt': '1713052800000', 'thumborImageId': 379130}, {'id': 7667, 'name': 'ACC Mens T20I Premier Cup, 2024', 'startDt': '1712880000000', 'endDt': '1713657600000', 'thumborImageId': 379130}, {'id': 7900, 'name': 'Central American Cricket Championships 2024', 'startDt': '1712793600000', 'endDt': '1713052800000', 'thumborImageId': 379130}, {'id': 7693, 'name': 'Canada tour of USA, 2024', 'startDt': '1712448000000', 'endDt': '1712966400000', 'thumborImageId': 379130}, {'id': 7727, 'name': 'Namibia tour of Oman, 2024', 'startDt': '1711929600000', 'endDt': '1712448000000', 'thumborImageId': 379130}, {'id': 7790, 'name': 'Lesotho tour of Eswatini, 2024', 'startDt': '1711670400000', 'endDt': '1711843200000', 'thumborImageId': 379130}, {'id': 7672, 'name': 'Mens African Games, 2024', 'startDt': '1710633600000', 'endDt': '1711152000000', 'thumborImageId': 379130}, {'id': 7686, 'name': 'Papua New Guinea tour of Malaysia, 2024', 'startDt': '1710547200000', 'endDt': '1710633600000', 'thumborImageId': 379130}, {'id': 7590, 'name': 'Scotland tour of United Arab Emirates 2024', 'startDt': '1710115200000', 'endDt': '1710374400000', 'thumborImageId': 379130}, {'id': 7644, 'name': 'Hong Kong T20I Tri-Series, 2024', 'startDt': '1710028800000', 'endDt': '1710288000000', 'thumborImageId': 379130}, {'id': 7637, 'name': 'Hong Kong Friendship Cup, 2024', 'startDt': '1709942400000', 'endDt': '1709942400000', 'thumborImageId': 379130}, {'id': 7586, 'name': 'Malaysia Open T20I Championship, 2024', 'startDt': '1709596800000', 'endDt': '1710115200000', 'thumborImageId': 379130}, {'id': 7534, 'name': 'Sri Lanka tour of Bangladesh, 2024', 'startDt': '1709510400000', 'endDt': '1712102400000', 'thumborImageId': 379130}, {'id': 7623, 'name': 'Papua New Guinea tour of Oman 2024', 'startDt': '1709424000000', 'endDt': '1709856000000', 'thumborImageId': 379130}, {'id': 7485, 'name': 'Afghanistan v Ireland in UAE, 2024', 'startDt': '1709078400000', 'endDt': '1710720000000', 'thumborImageId': 379130}, {'id': 7618, 'name': 'Hong Kong tour of Qatar 2024', 'startDt': '1708992000000', 'endDt': '1709251200000', 'thumborImageId': 379130}, {'id': 7583, 'name': 'Nepal T20I Tri-Series 2024', 'startDt': '1708992000000', 'endDt': '1709596800000', 'thumborImageId': 379130}, {'id': 6899, 'name': 'Australia tour of New Zealand, 2024', 'startDt': '1708473600000', 'endDt': '1710201600000', 'thumborImageId': 379130}, {'id': 7572, 'name': 'ICC Cricket World Cup League Two 2023-27', 'startDt': '1707955200000', 'endDt': '1830038400000', 'thumborImageId': 892393}, {'id': 7558, 'name': 'East Asia Cup 2024', 'startDt': '1707868800000', 'endDt': '1708128000000', 'thumborImageId': 379130}, {'id': 7579, 'name': 'Quadrangular Twenty20 Series in Thailand 2024', 'startDt': '1707696000000', 'endDt': '1708041600000', 'thumborImageId': 379130}, {'id': 7553, 'name': 'Canada tour of Nepal, 2024', 'startDt': '1707350400000', 'endDt': '1707696000000', 'thumborImageId': 379130}, {'id': 7481, 'name': 'Afghanistan tour of Sri Lanka, 2024', 'startDt': '1706832000000', 'endDt': '1708473600000', 'thumborImageId': 379130}, {'id': 6892, 'name': 'South Africa tour of New Zealand, 2024', 'startDt': '1706486400000', 'endDt': '1708128000000', 'thumborImageId': 379130}, {'id': 7511, 'name': 'ACC Mens T20I Challenger Cup 2024', 'startDt': '1706313600000', 'endDt': '1707609600000', 'thumborImageId': 379130}, {'id': 6927, 'name': 'England tour of India, 2024', 'startDt': '1706140800000', 'endDt': '1710115200000', 'thumborImageId': 379130}, {'id': 6885, 'name': 'Pakistan tour of New Zealand, 2024', 'startDt': '1705017600000', 'endDt': '1705795200000', 'thumborImageId': 379130}, {'id': 6920, 'name': 'Afghanistan tour of India, 2024', 'startDt': '1704931200000', 'endDt': '1705449600000', 'thumborImageId': 379130}, {'id': 6297, 'name': 'West Indies tour of Australia, 2024', 'startDt': '1704844800000', 'endDt': '1707782400000', 'thumborImageId': 379130}, {'id': 7411, 'name': 'Zimbabwe tour of Sri Lanka 2024', 'startDt': '1704499200000', 'endDt': '1705536000000', 'thumborImageId': 379130}]}], 'appIndex': {'seoTitle': 'Current Running Cricket Series - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}, 'contentFilters': [{'filterId': 'fantasy', 'filterName': 'Fantasy Handbook'}]}

In [31]:
series2024_data = series_list2024['seriesMapProto'][0]['series']

series_name_list = []
series_ids_list = []

for series in series2024_data:
    series_name_list.append(series["name"])
    series_ids_list.append(series["id"])

print(series_name_list)
print(series_ids_list)

['Sri Lanka tour of New Zealand, 2024-25', 'Gulf Cricket T20I Championship, 2024', 'Pakistan tour of South Africa, 2024 -25', 'Afghanistan tour of Zimbabwe, 2024-25', 'ICC Mens T20 World Cup Americas Sub Regional Qualifier, 2024', 'Africa Continental Cup 2024', 'Sri Lanka tour of South Africa, 2024', 'Pakistan tour of Zimbabwe, 2024', 'England tour of New Zealand, 2024', 'ICC Mens T20 World Cup Africa Sub Regional Qualifier C 2024', 'India tour of Australia, 2024-25', 'ICC Mens T20 World Cup Asia Qualifier B 2024', 'Bangladesh tour of West Indies, 2024', 'Netherlands tour of Oman, 2024', 'Myanmar tour of Indonesia, 2024', 'New Zealand tour of Sri Lanka, 2024', 'India tour of South Africa, 2024', 'Afghanistan v Bangladesh in UAE, 2024', 'Pakistan tour of Australia, 2024', 'England tour of West Indies, 2024', 'Bahrain in Uganda 2024', 'South Africa tour of Bangladesh, 2024', 'ICC Mens T20 World Cup Sub Regional Africa Qualifier Group B, 2024', 'Quadrangular T20I Series in Bhutan, 2024', 'Seychelles tour of Kenya, Only T20I', 'Nepal tour of United States of America 2024', 'New Zealand tour of India, 2024', 'West Indies tour of Sri Lanka, 2024', 'Rwanda tour of Malawi 2024', 'England tour of Pakistan, 2024', 'Serbia tour of Gibraltar, 2024', 'Namibia T20I Tri-Series 2024', 'ICC Mens T20 World Cup Sub Regional East Asia-Pacific Qualifier B, 2024', 'Canada T20I Tri-Series 2024', 'Ireland v South Africa in UAE, 2024', 'T20I Tri-Series in South Korea, 2024', 'ICC Mens T20 World Cup Africa Sub Regional Qualifier A 2024', 'Bangladesh tour of India, 2024', 'New Zealand tour of Sri Lanka, 2024', 'Afghanistan v South Africa in UAE, 2024', 'Australia tour of England, 2024', 'Afghanistan v New Zealand in India, 2024', 'Australia tour of Scotland, 2024', 'ICC Mens T20 World Cup Asia Qualifier A 2024', 'Netherlands T20I Tri-Series, 2024', 'ICC Mens T20 World Cup Sub Regional Europe Qualifier C, 2024', 'Bangladesh tour of Pakistan, 2024', 'Malaysia T20I Tri Nations Cup, 2024', 'ICC Mens T20 World Cup Sub Regional East Asia-Pacific Qualifier A, 2024', 'Sri Lanka tour of England, 2024', 'Spain tour of Croatia, 2024', 'South Africa tour of West Indies, 2024', 'India tour of Sri Lanka, 2024', 'Zimbabwe tour of Ireland, 2024', 'Nigeria tour of Kenya 2024', 'ICC Mens T20 World Cup Sub Regional Europe Qualifier B, 2024', 'India tour of Zimbabwe, 2024', 'West Indies tour of England, 2024', 'Serbia tour of Slovenia, 2024', 'Kenya Quadrangular Cup 2024', 'Jersey tour of Guernsey, 2024', 'Estonia tour of Cyprus 2024', 'Jersey tour of Denmark, 2024', 'Nordic T20I Cup 2024', 'ICC Mens T20 World Cup Sub Regional Europe Qualifier A, 2024', 'Guernsey tour of Belgium, 2024', 'ICC Mens T20 World Cup 2024', 'Belgium tour of Austria, 2024', 'Continental Cup 2024', 'South Africa tour of West Indies, 2024', 'Pakistan tour of England, 2024', 'Bangladesh tour of USA, 2024', 'Netherlands T20I Tri-Series, 2024', 'Pakistan tour of Ireland, 2024', 'Mdina Cup 2024', 'Mongolia tour of Japan, 2024', 'Zimbabwe tour of Bangladesh, 2024', 'Thailand tour of Indonesia 2024', 'New Zealand tour of Pakistan, 2024', 'Jersey tour of Spain, 2024', 'ACC Mens T20I Premier Cup, 2024', 'Central American Cricket Championships 2024', 'Canada tour of USA, 2024', 'Namibia tour of Oman, 2024', 'Lesotho tour of Eswatini, 2024', 'Mens African Games, 2024', 'Papua New Guinea tour of Malaysia, 2024', 'Scotland tour of United Arab Emirates 2024', 'Hong Kong T20I Tri-Series, 2024', 'Hong Kong Friendship Cup, 2024', 'Malaysia Open T20I Championship, 2024', 'Sri Lanka tour of Bangladesh, 2024', 'Papua New Guinea tour of Oman 2024', 'Afghanistan v Ireland in UAE, 2024', 'Hong Kong tour of Qatar 2024', 'Nepal T20I Tri-Series 2024', 'Australia tour of New Zealand, 2024', 'ICC Cricket World Cup League Two 2023-27', 'East Asia Cup 2024', 'Quadrangular Twenty20 Series in Thailand 2024', 'Canada tour of Nepal, 2024', 'Afghanistan tour of Sri Lanka, 2024', 'South Africa tour of New Zealand, 2024', 'ACC Mens T20I Challenger Cup 2024', 'England tour of India, 2024', 'Pakistan tour of New Zealand, 2024', 'Afghanistan tour of India, 2024', 'West Indies tour of Australia, 2024', 'Zimbabwe tour of Sri Lanka 2024']
[8553, 9297, 8044, 9171, 9265, 9289, 8058, 8494, 7853, 9132, 7745, 9129, 8116, 9125, 9146, 9083, 8404, 9091, 7781, 8107, 9157, 9033, 9041, 9025, 9115, 9043, 8395, 9009, 9057, 8497, 9017, 8947, 8598, 8955, 7981, 8969, 8835, 8393, 8818, 8661, 6794, 8625, 8552, 8764, 8632, 8596, 8495, 8686, 8587, 6787, 8578, 8238, 8528, 7979, 8476, 8337, 7546, 6780, 8422, 8382, 8413, 8310, 8260, 8332, 8256, 8294, 7476, 8247, 8166, 8103, 6773, 7700, 7819, 7808, 8080, 7896, 7706, 8042, 7679, 7817, 7667, 7900, 7693, 7727, 7790, 7672, 7686, 7590, 7644, 7637, 7586, 7534, 7623, 7485, 7618, 7583, 6899, 7572, 7558, 7579, 7553, 7481, 6892, 7511, 6927, 6885, 6920, 6297, 7411]

In [3]:
import requests
series_data=[]
series_ids_list1=[8553, 9297, 8044, 9171, 9265, 9289, 8058, 8494, 7853, 9132, 7745, 9129, 8116, 9125, 9146, 9083, 8404, 9091, 7781, 8107, 9157, 9033, 9041, 9025, 9115, 9043, 8395, 9009, 9057, 8497, 9017, 8947, 8598, 8955, 7981, 8969, 8835, 8393, 8818, 8661, 6794, 8625, 8552, 8764, 8632, 8596, 8495, 8686, 8587, 6787, 8578, 8238, 8528, 7979, 8476, 8337, 7546, 6780, 8422, 8382, 8413, 8310, 8260, 8332, 8256, 8294, 7476, 8247, 8166, 8103, 6773, 7700, 7819, 7808, 8080, 7896, 7706, 8042, 7679, 7817, 7667, 7900, 7693, 7727, 7790, 7672, 7686, 7590, 7644, 7637, 7586, 7534, 7623, 7485, 7618, 7583, 6899, 7572, 7558, 7579, 7553, 7481, 6892, 7511, 6927, 6885, 6920, 6297, 7411]

for series_id in series_ids_list1:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/series/v1/{series_id}"
    headers = {
    "x-rapidapi-key": "fc7f30fb9cmsh8725b330cc40e86p18a9aejsnb2a96a85740a",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
     }
    response = requests.get(url, headers=headers)
    series_data.append(response.json())

print(series_data)

[{'matchDetails': [{'matchDetailsMap': {'key': 'Mon, 23 Dec 2024', 'match': [{'matchInfo': {'matchId': 112385, 'seriesId': 8553, 'seriesName': 'Sri Lanka tour of New Zealand, 2024-25', 'matchDesc': 'Practice Match 1', 'matchFormat': 'T20', 'startDate': '1734904800000', 'endDate': '1734904800000', 'state': 'complete', 'status': 'Sri Lanka won by 7 wkts', 'team1': {'teamId': 286, 'teamName': 'NEW ZEALAND XI', 'teamSName': 'NZXI', 'imageId': 776339}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Bert Sutcliffe Oval', 'city': 'Lincoln', 'timezone': '+13:00'}, 'currBatTeamId': 5, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 94, 'wickets': 10, 'overs': 13.4}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 97, 'wickets': 3, 'overs': 10.5}}}}, {'matchInfo': {'matchId': 112389, 'seriesId': 8553, 'seriesName': 'Sri Lanka tour of New Zealand, 2024-25', 'matchDesc': 'Practice Match 2', 'matchFormat': 'T20', 'startDate': '1734915600000', 'endDate': '1734915600000', 'state': 'complete', 'status': 'Sri Lanka won by 32 runs', 'team1': {'teamId': 286, 'teamName': 'NEW ZEALAND XI', 'teamSName': 'NZXI', 'imageId': 776339}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Bert Sutcliffe Oval', 'city': 'Lincoln', 'timezone': '+13:00'}, 'currBatTeamId': 5, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 96, 'wickets': 2, 'overs': 10.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 128, 'wickets': 2, 'overs': 10.0}}}}], 'seriesId': 8553}}, {'adDetail': {'name': 'native_news_index_random_1', 'layout': 'native_large', 'position': 1}}, {'matchDetailsMap': {'key': 'Sat, 28 Dec 2024', 'match': [{'matchInfo': {'matchId': 102036, 'seriesId': 8553, 'seriesName': 'Sri Lanka tour of New Zealand, 2024-25', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1735366500000', 'endDate': '1735366500000', 'state': 'complete', 'status': 'New Zealand won by 8 runs', 'team1': {'teamId': 13, 'teamName': 'NEW ZEALAND', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Bay Oval', 'city': 'Mount Maunganui', 'timezone': '+13:00'}, 'currBatTeamId': 13, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 172, 'wickets': 8, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 164, 'wickets': 8, 'overs': 20.0}}}}], 'seriesId': 8553}}, {'matchDetailsMap': {'key': 'Mon, 30 Dec 2024', 'match': [{'matchInfo': {'matchId': 102040, 'seriesId': 8553, 'seriesName': 'Sri Lanka tour of New Zealand, 2024-25', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1735539300000', 'endDate': '1735539300000', 'state': 'complete', 'status': 'New Zealand won by 45 runs', 'team1': {'teamId': 13, 'teamName': 'NEW ZEALAND', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Bay Oval', 'city': 'Mount Maunganui', 'timezone': '+13:00'}, 'currBatTeamId': 13, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 186, 'wickets': 5, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 141, 'wickets': 10, 'overs': 19.1}}}}], 'seriesId': 8553}}, {'matchDetailsMap': {'key': 'Thu, 02 Jan 2025', 'match': [{'matchInfo': {'matchId': 102045, 'seriesId': 8553, 'seriesName': 'Sri Lanka tour of New Zealand, 2024-25', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1735776900000', 'endDate': '1735776900000', 'state': 'complete', 'status': 'Sri Lanka won by 7 runs', 'team1': {'teamId': 13, 'teamName': 'NEW ZEALAND', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Saxton Oval', 'city': 'Nelson', 'timezone': '+13:00'}, 'currBatTeamId': 5, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 211, 'wickets': 7, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 218, 'wickets': 5, 'overs': 20.0}}}}], 'seriesId': 8553}}, {'matchDetailsMap': {'key': 'Sun, 05 Jan 2025', 'match': [{'matchInfo': {'matchId': 102049, 'seriesId': 8553, 'seriesName': 'Sri Lanka tour of New Zealand, 2024-25', 'matchDesc': '1st ODI', 'matchFormat': 'ODI', 'startDate': '1736028000000', 'endDate': '1736028000000', 'state': 'complete', 'status': 'New Zealand won by 9 wkts', 'team1': {'teamId': 13, 'teamName': 'NEW ZEALAND', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Basin Reserve', 'city': 'Wellington', 'timezone': '+13:00'}, 'currBatTeamId': 13, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 180, 'wickets': 1, 'overs': 26.2}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 178, 'wickets': 10, 'overs': 43.4}}}}], 'seriesId': 8553}}, {'matchDetailsMap': {'key': 'Wed, 08 Jan 2025', 'match': [{'matchInfo': {'matchId': 102058, 'seriesId': 8553, 'seriesName': 'Sri Lanka tour of New Zealand, 2024-25', 'matchDesc': '2nd ODI', 'matchFormat': 'ODI', 'startDate': '1736298000000', 'endDate': '1736298000000', 'state': 'complete', 'status': 'New Zealand won by 113 runs (Match reduced to 37 ovs due to rain)', 'team1': {'teamId': 13, 'teamName': 'NEW ZEALAND', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Seddon Park', 'city': 'Hamilton', 'timezone': '+13:00'}, 'currBatTeamId': 13, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 255, 'wickets': 9, 'overs': 37.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 142, 'wickets': 10, 'overs': 30.2}}}}], 'seriesId': 8553}}, {'matchDetailsMap': {'key': 'Sat, 11 Jan 2025', 'match': [{'matchInfo': {'matchId': 102067, 'seriesId': 8553, 'seriesName': 'Sri Lanka tour of New Zealand, 2024-25', 'matchDesc': '3rd ODI', 'matchFormat': 'ODI', 'startDate': '1736557200000', 'endDate': '1736557200000', 'state': 'complete', 'status': 'Sri Lanka won by 140 runs', 'team1': {'teamId': 13, 'teamName': 'NEW ZEALAND', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Eden Park', 'city': 'Auckland', 'timezone': '+13:00'}, 'currBatTeamId': 5, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 150, 'wickets': 10, 'overs': 29.4}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 290, 'wickets': 8, 'overs': 50.0}}}}], 'seriesId': 8553}}], 'appIndex': {'seoTitle': 'Sri Lanka tour of New Zealand, 2024-25 live scores, schedule and results - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}}, {'matchDetails': [{'matchDetailsMap': {'key': 'Fri, 13 Dec 2024', 'match': [{'matchInfo': {'matchId': 112233, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '1st Match', 'matchFormat': 'T20', 'startDate': '1734066000000', 'endDate': '1734066000000', 'state': 'complete', 'status': 'United Arab Emirates won by 8 wkts', 'team1': {'teamId': 543, 'teamName': 'BAHRAIN', 'teamSName': 'BHR', 'imageId': 172594}, 'team2': {'teamId': 7, 'teamName': 'UNITED ARAB EMIRATES', 'teamSName': 'UAE', 'imageId': 776242}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 7, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 113, 'wickets': 8, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 117, 'wickets': 2, 'overs': 16.5}}}}, {'matchInfo': {'matchId': 112237, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '2nd Match', 'matchFormat': 'T20', 'startDate': '1734082200000', 'endDate': '1734082200000', 'state': 'complete', 'status': 'Kuwait won by 6 wkts', 'team1': {'teamId': 298, 'teamName': 'KUWAIT', 'teamSName': 'KUW', 'imageId': 776312}, 'team2': {'teamId': 571, 'teamName': 'SAUDI ARABIA', 'teamSName': 'SAU', 'imageId': 172623}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 298, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 140, 'wickets': 4, 'overs': 16.5}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 136, 'wickets': 10, 'overs': 19.0}}}}], 'seriesId': 9297}}, {'adDetail': {'name': 'native_news_index_random_1', 'layout': 'native_large', 'position': 1}}, {'matchDetailsMap': {'key': 'Sat, 14 Dec 2024', 'match': [{'matchInfo': {'matchId': 112241, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '3rd Match', 'matchFormat': 'T20', 'startDate': '1734152400000', 'endDate': '1734152400000', 'state': 'complete', 'status': 'Bahrain won by 4 runs', 'team1': {'teamId': 298, 'teamName': 'KUWAIT', 'teamSName': 'KUW', 'imageId': 776312}, 'team2': {'teamId': 543, 'teamName': 'BAHRAIN', 'teamSName': 'BHR', 'imageId': 172594}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 543, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 121, 'wickets': 10, 'overs': 19.3}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 125, 'wickets': 8, 'overs': 20.0}}}}, {'matchInfo': {'matchId': 112249, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '4th Match', 'matchFormat': 'T20', 'startDate': '1734168600000', 'endDate': '1734168600000', 'state': 'complete', 'status': 'Oman won by 35 runs', 'team1': {'teamId': 525, 'teamName': 'QATAR', 'teamSName': 'QAT', 'imageId': 172575}, 'team2': {'teamId': 304, 'teamName': 'OMAN', 'teamSName': 'OMAN', 'imageId': 776328}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 304, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 169, 'wickets': 8, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 204, 'wickets': 5, 'overs': 20.0}}}}], 'seriesId': 9297}}, {'matchDetailsMap': {'key': 'Sun, 15 Dec 2024', 'match': [{'matchInfo': {'matchId': 112257, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '5th Match', 'matchFormat': 'T20', 'startDate': '1734238800000', 'endDate': '1734238800000', 'state': 'complete', 'status': 'United Arab Emirates won by 24 runs', 'team1': {'teamId': 7, 'teamName': 'UNITED ARAB EMIRATES', 'teamSName': 'UAE', 'imageId': 776242}, 'team2': {'teamId': 304, 'teamName': 'OMAN', 'teamSName': 'OMAN', 'imageId': 776328}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 7, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 157, 'wickets': 7, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 133, 'wickets': 8, 'overs': 20.0}}}}, {'matchInfo': {'matchId': 112261, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '6th Match', 'matchFormat': 'T20', 'startDate': '1734255000000', 'endDate': '1734255000000', 'state': 'complete', 'status': 'Saudi Arabia won by 9 wkts', 'team1': {'teamId': 571, 'teamName': 'SAUDI ARABIA', 'teamSName': 'SAU', 'imageId': 172623}, 'team2': {'teamId': 525, 'teamName': 'QATAR', 'teamSName': 'QAT', 'imageId': 172575}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 571, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 126, 'wickets': 1, 'overs': 16.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 123, 'wickets': 9, 'overs': 20.0}}}}], 'seriesId': 9297}}, {'matchDetailsMap': {'key': 'Mon, 16 Dec 2024', 'match': [{'matchInfo': {'matchId': 112269, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '7th Match', 'matchFormat': 'T20', 'startDate': '1734325200000', 'endDate': '1734325200000', 'state': 'complete', 'status': 'Bahrain won by 8 wkts', 'team1': {'teamId': 571, 'teamName': 'SAUDI ARABIA', 'teamSName': 'SAU', 'imageId': 172623}, 'team2': {'teamId': 543, 'teamName': 'BAHRAIN', 'teamSName': 'BHR', 'imageId': 172594}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 543, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 113, 'wickets': 9, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 119, 'wickets': 2, 'overs': 15.2}}}}, {'matchInfo': {'matchId': 112273, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '8th Match', 'matchFormat': 'T20', 'startDate': '1734341400000', 'endDate': '1734341400000', 'state': 'complete', 'status': 'United Arab Emirates won by 11 runs', 'team1': {'teamId': 7, 'teamName': 'UNITED ARAB EMIRATES', 'teamSName': 'UAE', 'imageId': 776242}, 'team2': {'teamId': 298, 'teamName': 'KUWAIT', 'teamSName': 'KUW', 'imageId': 776312}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 7, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 168, 'wickets': 8, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 157, 'wickets': 8, 'overs': 20.0}}}}], 'seriesId': 9297}}, {'matchDetailsMap': {'key': 'Tue, 17 Dec 2024', 'match': [{'matchInfo': {'matchId': 112281, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '9th Match', 'matchFormat': 'T20', 'startDate': '1734411600000', 'endDate': '1734411600000', 'state': 'complete', 'status': 'Kuwait won by 6 wkts', 'team1': {'teamId': 525, 'teamName': 'QATAR', 'teamSName': 'QAT', 'imageId': 172575}, 'team2': {'teamId': 298, 'teamName': 'KUWAIT', 'teamSName': 'KUW', 'imageId': 776312}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 298, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 138, 'wickets': 7, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 142, 'wickets': 4, 'overs': 16.0}}}}, {'matchInfo': {'matchId': 112285, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '10th Match', 'matchFormat': 'T20', 'startDate': '1734427800000', 'endDate': '1734427800000', 'state': 'complete', 'status': 'Oman won by 2 runs', 'team1': {'teamId': 304, 'teamName': 'OMAN', 'teamSName': 'OMAN', 'imageId': 776328}, 'team2': {'teamId': 543, 'teamName': 'BAHRAIN', 'teamSName': 'BHR', 'imageId': 172594}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 304, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 130, 'wickets': 8, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 128, 'wickets': 8, 'overs': 20.0}}}}], 'seriesId': 9297}}, {'matchDetailsMap': {'key': 'Wed, 18 Dec 2024', 'match': [{'matchInfo': {'matchId': 112293, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '11th Match', 'matchFormat': 'T20', 'startDate': '1734498000000', 'endDate': '1734498000000', 'state': 'complete', 'status': 'Saudi Arabia won by 8 wkts', 'team1': {'teamId': 304, 'teamName': 'OMAN', 'teamSName': 'OMAN', 'imageId': 776328}, 'team2': {'teamId': 571, 'teamName': 'SAUDI ARABIA', 'teamSName': 'SAU', 'imageId': 172623}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 571, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 165, 'wickets': 6, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 166, 'wickets': 2, 'overs': 18.5}}}}, {'matchInfo': {'matchId': 112297, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '12th Match', 'matchFormat': 'T20', 'startDate': '1734514200000', 'endDate': '1734514200000', 'state': 'complete', 'status': 'United Arab Emirates won by 23 runs', 'team1': {'teamId': 525, 'teamName': 'QATAR', 'teamSName': 'QAT', 'imageId': 172575}, 'team2': {'teamId': 7, 'teamName': 'UNITED ARAB EMIRATES', 'teamSName': 'UAE', 'imageId': 776242}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 7, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 139, 'wickets': 7, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 162, 'wickets': 6, 'overs': 20.0}}}}], 'seriesId': 9297}}, {'matchDetailsMap': {'key': 'Thu, 19 Dec 2024', 'match': [{'matchInfo': {'matchId': 112301, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '13th Match', 'matchFormat': 'T20', 'startDate': '1734600600000', 'endDate': '1734600600000', 'state': 'complete', 'status': 'Saudi Arabia won by 11 runs', 'team1': {'teamId': 7, 'teamName': 'UNITED ARAB EMIRATES', 'teamSName': 'UAE', 'imageId': 776242}, 'team2': {'teamId': 571, 'teamName': 'SAUDI ARABIA', 'teamSName': 'SAU', 'imageId': 172623}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 571, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 171, 'wickets': 5, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 182, 'wickets': 8, 'overs': 20.0}}}}], 'seriesId': 9297}}, {'matchDetailsMap': {'key': 'Fri, 20 Dec 2024', 'match': [{'matchInfo': {'matchId': 112305, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '14th Match', 'matchFormat': 'T20', 'startDate': '1734670800000', 'endDate': '1734670800000', 'state': 'complete', 'status': 'Qatar won by 6 wkts', 'team1': {'teamId': 525, 'teamName': 'QATAR', 'teamSName': 'QAT', 'imageId': 172575}, 'team2': {'teamId': 543, 'teamName': 'BAHRAIN', 'teamSName': 'BHR', 'imageId': 172594}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 525, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 102, 'wickets': 4, 'overs': 17.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 98, 'wickets': 10, 'overs': 16.3}}}}, {'matchInfo': {'matchId': 112309, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': '15th Match', 'matchFormat': 'T20', 'startDate': '1734687000000', 'endDate': '1734687000000', 'state': 'complete', 'status': 'Kuwait won by 3 wkts', 'team1': {'teamId': 304, 'teamName': 'OMAN', 'teamSName': 'OMAN', 'imageId': 776328}, 'team2': {'teamId': 298, 'teamName': 'KUWAIT', 'teamSName': 'KUW', 'imageId': 776312}, 'venueInfo': {'ground': 'ICC Academy Ground', 'city': 'Dubai', 'timezone': '+04:00'}, 'currBatTeamId': 298, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 143, 'wickets': 8, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 144, 'wickets': 7, 'overs': 19.3}}}}], 'seriesId': 9297}}, {'matchDetailsMap': {'key': 'Sat, 21 Dec 2024', 'match': [{'matchInfo': {'matchId': 112317, 'seriesId': 9297, 'seriesName': 'Gulf Cricket T20I Championship, 2024', 'matchDesc': 'Final', 'matchFormat': 'T20', 'startDate': '1734791400000', 'endDate': '1734791400000', 'state': 'complete', 'team1': {'teamId': 7, 'teamName': 'UNITED ARAB EMIRATES', 'teamSName': 'UAE', 'imageId': 776242}, 'team2': {'teamId': 298, 'teamName': 'KUWAIT', 'teamSName': 'KUW', 'imageId': 776312}, 'venueInfo': {'ground': 'Dubai International Cricket Stadium', 'city': 'Dubai', 'timezone': '

In [7]:
from datetime import datetime

# First pass: count total matches per series
match_counts = {}
for i in series_data:
    for j in i['matchDetails']:
        matchDetailsMap = j.get('matchDetailsMap')
        if not matchDetailsMap:
            continue
        for k in j['matchDetailsMap']['match']:
            sname = k['matchInfo']['seriesName']
            match_counts[sname] = match_counts.get(sname, 0) + 1

# Second pass: extract series info
series_info = []
seen_series = set()

for i in series_data:
    for j in i['matchDetails']:
        matchDetailsMap = j.get('matchDetailsMap')
        if not matchDetailsMap:
            continue
        first_match = j['matchDetailsMap']['match'][0]['matchInfo']
        sname = first_match['seriesName']

        if sname not in seen_series:
            start_ts = first_match['startDate']
            start_date = datetime.fromtimestamp(int(start_ts) / 1000).strftime("%d-%m-%Y") if start_ts else None

            series_info.append({
                'series_name': sname,
                'city': first_match['venueInfo']['city'],
                'matchFormat': first_match['matchFormat'],
                'startDate': start_date,
                'total_matches': match_counts[sname]
            })
            seen_series.add(sname)

series_info

[{'series_name': 'Sri Lanka tour of New Zealand, 2024-25',
  'city': 'Lincoln',
  'matchFormat': 'T20',
  'startDate': '23-12-2024',
  'total_matches': 8},
 {'series_name': 'Gulf Cricket T20I Championship, 2024',
  'city': 'Dubai',
  'matchFormat': 'T20',
  'startDate': '13-12-2024',
  'total_matches': 16},
 {'series_name': 'Pakistan tour of South Africa, 2024 -25',
  'city': 'Durban',
  'matchFormat': 'T20',
  'startDate': '10-12-2024',
  'total_matches': 8},
 {'series_name': 'Afghanistan tour of Zimbabwe, 2024-25',
  'city': 'Harare',
  'matchFormat': 'T20',
  'startDate': '11-12-2024',
  'total_matches': 8},
 {'series_name': 'ICC Mens T20 World Cup Americas Sub Regional Qualifier, 2024',
  'city': 'Quilmes, Buenos Aires',
  'matchFormat': 'T20',
  'startDate': '06-12-2024',
  'total_matches': 36},
 {'series_name': 'Africa Continental Cup 2024',
  'city': 'Kigali City',
  'matchFormat': 'T20',
  'startDate': '04-12-2024',
  'total_matches': 19},
 {'series_name': 'Sri Lanka tour of South Africa, 2024',
  'city': 'Durban',
  'matchFormat': 'TEST',
  'startDate': '27-11-2024',
  'total_matches': 2},
 {'series_name': 'Pakistan tour of Zimbabwe, 2024',
  'city': 'Bulawayo',
  'matchFormat': 'ODI',
  'startDate': '24-11-2024',
  'total_matches': 6},
 {'series_name': 'England tour of New Zealand, 2024',
  'city': 'Queenstown',
  'matchFormat': 'TEST',
  'startDate': '23-11-2024',
  'total_matches': 4},
 {'series_name': 'ICC Mens T20 World Cup Africa Sub Regional Qualifier C 2024',
  'city': 'Lagos',
  'matchFormat': 'T20',
  'startDate': '23-11-2024',
  'total_matches': 15},
 {'series_name': 'India tour of Australia, 2024-25',
  'city': 'Perth',
  'matchFormat': 'TEST',
  'startDate': '22-11-2024',
  'total_matches': 6},
 {'series_name': 'ICC Mens T20 World Cup Asia Qualifier B 2024',
  'city': 'Doha',
  'matchFormat': 'T20',
  'startDate': '19-11-2024',
  'total_matches': 21},
 {'series_name': 'Bangladesh tour of West Indies, 2024',
  'city': 'Antigua',
  'matchFormat': 'TEST',
  'startDate': '17-11-2024',
  'total_matches': 9},
 {'series_name': 'Netherlands tour of Oman, 2024',
  'city': 'Al Amerat',
  'matchFormat': 'T20',
  'startDate': '13-11-2024',
  'total_matches': 3},
 {'series_name': 'Myanmar tour of Indonesia, 2024',
  'city': 'Bali',
  'matchFormat': 'T20',
  'startDate': '12-11-2024',
  'total_matches': 6},
 {'series_name': 'New Zealand tour of Sri Lanka, 2024',
  'city': 'Dambulla',
  'matchFormat': 'T20',
  'startDate': '09-11-2024',
  'total_matches': 7},
 {'series_name': 'India tour of South Africa, 2024',
  'city': 'Durban',
  'matchFormat': 'T20',
  'startDate': '08-11-2024',
  'total_matches': 4},
 {'series_name': 'Afghanistan v Bangladesh in UAE, 2024',
  'city': 'Sharjah',
  'matchFormat': 'ODI',
  'startDate': '06-11-2024',
  'total_matches': 3},
 {'series_name': 'Pakistan tour of Australia, 2024',
  'city': 'Melbourne',
  'matchFormat': 'ODI',
  'startDate': '04-11-2024',
  'total_matches': 6},
 {'series_name': 'England tour of West Indies, 2024',
  'city': 'North Sound, Antigua',
  'matchFormat': 'ODI',
  'startDate': '31-10-2024',
  'total_matches': 8},
 {'series_name': 'Bahrain in Uganda 2024',
  'city': 'Jinja',
  'matchFormat': 'T20',
  'startDate': '28-10-2024',
  'total_matches': 2},
 {'series_name': 'South Africa tour of Bangladesh, 2024',
  'city': 'Dhaka',
  'matchFormat': 'TEST',
  'startDate': '21-10-2024',
  'total_matches': 2},
 {'series_name': 'ICC Mens T20 World Cup Sub Regional Africa Qualifier Group B, 2024',
  'city': 'Nairobi',
  'matchFormat': 'T20',
  'startDate': '19-10-2024',
  'total_matches': 15},
 {'series_name': 'Quadrangular T20I Series in Bhutan, 2024',
  'city': 'Gelephu',
  'matchFormat': 'T20',
  'startDate': '19-10-2024',
  'total_matches': 10},
 {'series_name': 'Seychelles tour of Kenya, Only T20I',
  'city': 'Nairobi',
  'matchFormat': 'T20',
  'startDate': '18-10-2024',
  'total_matches': 1},
 {'series_name': 'Nepal tour of United States of America 2024',
  'city': 'Dallas',
  'matchFormat': 'T20',
  'startDate': '18-10-2024',
  'total_matches': 3},
 {'series_name': 'New Zealand tour of India, 2024',
  'city': 'Bengaluru',
  'matchFormat': 'TEST',
  'startDate': '16-10-2024',
  'total_matches': 3},
 {'series_name': 'West Indies tour of Sri Lanka, 2024',
  'city': 'Dambulla',
  'matchFormat': 'T20',
  'startDate': '13-10-2024',
  'total_matches': 6},
 {'series_name': 'Rwanda tour of Malawi 2024',
  'city': 'Blantyre',
  'matchFormat': 'T20',
  'startDate': '09-10-2024',
  'total_matches': 5},
 {'series_name': 'England tour of Pakistan, 2024',
  'city': 'Multan',
  'matchFormat': 'TEST',
  'startDate': '07-10-2024',
  'total_matches': 3},
 {'series_name': 'Serbia tour of Gibraltar, 2024',
  'city': 'Gibraltar',
  'matchFormat': 'T20',
  'startDate': '30-09-2024',
  'total_matches': 2},
 {'series_name': 'Namibia T20I Tri-Series 2024',
  'city': 'Windhoek',
  'matchFormat': 'T20',
  'startDate': '29-09-2024',
  'total_matches': 6},
 {'series_name': 'ICC Mens T20 World Cup Sub Regional East Asia-Pacific Qualifier B, 2024',
  'city': 'Incheon',
  'matchFormat': 'T20',
  'startDate': '28-09-2024',
  'total_matches': 12},
 {'series_name': 'Canada T20I Tri-Series 2024',
  'city': 'King City',
  'matchFormat': 'T20',
  'startDate': '28-09-2024',
  'total_matches': 6},
 {'series_name': 'Ireland v South Africa in UAE, 2024',
  'city': 'Abu Dhabi',
  'matchFormat': 'T20',
  'startDate': '27-09-2024',
  'total_matches': 5},
 {'series_name': 'T20I Tri-Series in South Korea, 2024',
  'city': 'Incheon',
  'matchFormat': 'T20',
  'startDate': '25-09-2024',
  'total_matches': 2},
 {'series_name': 'ICC Mens T20 World Cup Africa Sub Regional Qualifier A 2024',
  'city': 'Dar-es-Salaam',
  'matchFormat': 'T20',
  'startDate': '21-09-2024',
  'total_matches': 15},
 {'series_name': 'Bangladesh tour of India, 2024',
  'city': 'Chennai',
  'matchFormat': 'TEST',
  'startDate': '19-09-2024',
  'total_matches': 5},
 {'series_name': 'Afghanistan v South Africa in UAE, 2024',
  'city': 'Sharjah',
  'matchFormat': 'ODI',
  'startDate': '18-09-2024',
  'total_matches': 3},
 {'series_name': 'Australia tour of England, 2024',
  'city': 'Southampton',
  'matchFormat': 'T20',
  'startDate': '11-09-2024',
  'total_matches': 8},
 {'series_name': 'Afghanistan v New Zealand in India, 2024',
  'city': 'Greater Noida',
  'matchFormat': 'TEST',
  'startDate': '09-09-2024',
  'total_matches': 1},
 {'series_name': 'Australia tour of Scotland, 2024',
  'city': 'Edinburgh',
  'matchFormat': 'T20',
  'startDate': '04-09-2024',
  'total_matches': 3},
 {'series_name': 'ICC Mens T20 World Cup Asia Qualifier A 2024',
  'city': 'Kuala Lumpur',
  'matchFormat': 'T20',
  'startDate': '30-08-2024',
  'total_matches': 21},
 {'series_name': 'Netherlands T20I Tri-Series, 2024',
  'city': 'Utrecht',
  'matchFormat': 'T20',
  'startDate': '23-08-2024',
  'total_matches': 12},
 {'series_name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier C, 2024',
  'city': 'Castel',
  'matchFormat': 'T20',
  'startDate': '21-08-2024',
  'total_matches': 24},
 {'series_name': 'Bangladesh tour of Pakistan, 2024',
  'city': 'Rawalpindi',
  'matchFormat': 'TEST',
  'startDate': '21-08-2024',
  'total_matches': 2},
 {'series_name': 'Malaysia T20I Tri Nations Cup, 2024',
  'city': 'Kuala Lumpur',
  'matchFormat': 'T20',
  'startDate': '21-08-2024',
  'total_matches': 7},
 {'series_name': 'ICC Mens T20 World Cup Sub Regional East Asia-Pacific Qualifier A, 2024',
  'city': 'Apia',
  'matchFormat': 'T20',
  'startDate': '17-08-2024',
  'total_matches': 12},
 {'series_name': 'Sri Lanka tour of England, 2024',
  'city': 'Worcester',
  'matchFormat': 'TEST',
  'startDate': '14-08-2024',
  'total_matches': 4},
 {'series_name': 'Spain tour of Croatia, 2024',
  'city': 'Zagreb',
  'matchFormat': 'T20',
  'startDate': '02-08-2024',
  'total_matches': 5},
 {'series_name': 'South Africa tour of West Indies, 2024',
  'city': 'Tarouba, Trinidad',
  'matchFormat': 'TEST',
  'startDate': '31-07-2024',
  'total_matches': 9},
 {'series_name': 'India tour of Sri Lanka, 2024',
  'city': 'Pallekele',
  'matchFormat': 'T20',
  'startDate': '27-07-2024',
  'total_matches': 6},
 {'series_name': 'Zimbabwe tour of Ireland, 2024',
  'city': 'Belfast',
  'matchFormat': 'TEST',
  'startDate': '25-07-2024',
  'total_matches': 1},
 {'series_name': 'Nigeria tour of Kenya 2024',
  'city': 'Nairobi',
  'matchFormat': 'T20',
  'startDate': '12-07-2024',
  'total_matches': 5},
 {'series_name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier B, 2024',
  'city': 'Krefeld',
  'matchFormat': 'T20',
  'startDate': '07-07-2024',
  'total_matches': 22},
 {'series_name': 'India tour of Zimbabwe, 2024',
  'city': 'Harare',
  'matchFormat': 'T20',
  'startDate': '06-07-2024',
  'total_matches': 5},
 {'series_name': 'West Indies tour of England, 2024',
  'city': 'Beckenham',
  'matchFormat': 'TEST',
  'startDate': '03-07-2024',
  'total_matches': 4},
 {'series_name': 'Serbia tour of Slovenia, 2024',
  'city': 'Ljubljana',
  'matchFormat': 'T20',
  'startDate': '29-06-2024',
  'total_matches': 3},
 {'series_name': 'Kenya Quadrangular Cup 2024',
  'city': 'Nairobi',
  'matchFormat': 'T20',
  'startDate': '28-06-2024',
  'total_matches': 20},
 {'series_name': 'Jersey tour of Guernsey, 2024',
  'city': 'Castel',
  'matchFormat': 'T20',
  'startDate': '22-06-2024',
  'total_matches': 3},
 {'series_name': 'Estonia tour of Cyprus 2024',
  'city': 'Episkopi',
  'matchFormat': 'T20',
  'startDate': '17-06-2024',
  'total_matches': 6},
 {'series_name': 'Jersey tour of Denmark, 2024',
  'city': 'Brondby',
  'matchFormat': 'T20',
  'startDate': '15-06-2024',
  'total_matches': 3},
 {'series_name': 'Nordic T20I Cup 2024',
  'city': 'Kerava',
  'matchFormat': 'T20',
  'startDate': '14-06-2024',
  'total_matches': 3},
 {'series_name': 'ICC Mens T20 World Cup Sub Regional Europe Qualifier A, 2024',
  'city': 'Rome',
  'matchFormat': 'T20',
  'startDate': '09-06-2024',
  'total_matches': 24},
 {'series_name': 'Guernsey tour of Belgium, 2024',
  'city': 'Brussels',
  'matchFormat': 'T20',
  'startDate': '08-06-2024',
  'total_matches': 4},
 {'series_name': 'ICC Mens T20 World Cup 2024',
  'city': 'Dallas',
  'matchFormat': 'T20',
  'startDate': '02-06-2024',
  'total_matches': 55},
 {'series_name': 'Belgium tour of Austria, 2024',
  'city': 'Seebarn',
  'matchFormat': 'T20',
  'startDate': '25-05-2024',
  'total_matches': 4},
 {'series_name': 'Continental Cup 2024',
  'city': 'Ilfov County',
  'matchFormat': 'T20',
  'startDate': '24-05-2024',
  'total_matches': 8},
 {'series_name': 'Pakistan tour of England, 2024',
  'city': 'Leeds',
  'matchFormat': 'T20',
  'startDate': '22-05-2024',
  'total_matches': 4},
 {'series_name': 'Bangladesh tour of USA, 2024',
  'city': 'Houston',
  'matchFormat': 'T20',
  'startDate': '21-05-2024',
  'total_matches': 3},
 {'series_name': 'Pakistan tour of Ireland, 2024',
  'city': 'Dublin',
  'matchFormat': 'T20',
  'startDate': '10-05-2024',
  'total_matches': 3},
 {'series_name': 'Mdina Cup 2024',
  'city': 'Dreux',
  'matchFormat': 'T20',
  'startDate': '09-05-2024',
  'total_matches': 7},
 {'series_name': 'Mongolia tour of Japan, 2024',
  'city': 'Sano, Kanto',
  'matchFormat': 'T20',
  'startDate': '07-05-2024',
  'total_matches': 7},
 {'series_name': 'Zimbabwe tour of Bangladesh, 2024',
  'city': 'Chattogram',
  'matchFormat': 'T20',
  'startDate': '03-05-2024',
  'total_matches': 5},
 {'series_name': 'Thailand tour of Indonesia 2024',
  'city': 'Bali',
  'matchFormat': 'T20',
  'startDate': '01-05-2024',
  'total_matches': 5},
 {'series_name': 'New Zealand tour of Pakistan, 2024',
  'city': 'Rawalpindi',
  'matchFormat': 'T20',
  'startDate': '18-04-2024',
  'total_matches': 5},
 {'series_name': 'Jersey tour of Spain, 2024',
  'city': 'Cartagena, Murcia',
  'matchFormat': 'T20',
  'startDate': '14-04-2024',
  'total_matches': 2},
 {'series_name': 'ACC Mens T20I Premier Cup, 2024',
  'city': 'Al Amerat',
  'matchFormat': 'T20',
  'startDate': '12-04-2024',
  'total_matches': 24},
 {'series_name': 'Central American Cricket Championships 2024',
  'city': 'Guacima',
  'matchFormat': 'T20',
  'startDate': '11-04-2024',
  'total_matches': 5},
 {'series_name': 'Canada tour of USA, 2024',
  'city': 'Houston',
  'matchFormat': 'T20',
  'startDate': '07-04-2024',
  'total_matches': 5},
 {'series_name': 'Namibia tour of Oman, 2024',
  'city': 'Al Amerat',
  'matchFormat': 'T20',
  'startDate': '01-04-2024',
  'total_matches': 5},
 {'series_name': 'Lesotho tour of Eswatini, 2024',
  'city': 'Malkerns',
  'matchFormat': 'T20',
  'startDate': '29-03-2024',
  'total_matches': 5},
 {'series_name': 'Mens African Games, 2024',
  'city': 'Accra',
  'matchFormat': 'T20',
  'startDate': '17-03-2024',
  'total_matches': 16},
 {'series_name': 'Papua New Guinea tour of Malaysia, 2024',
  'city': 'Bangi, Malaysia',
  'matchFormat': 'T20',
  'startDate': '16-03-2024',
  'total_matches': 2},
 {'series_name': 'Scotland tour of United Arab Emirates 2024',
  'city': 'Dubai',
  'matchFormat': 'T20',
  'startDate': '11-03-2024',
  'total_matches': 3},
 {'series_name': 'Hong Kong T20I Tri-Series, 2024',
  'city': 'Mong Kok',
  'matchFormat': 'T20',
  'startDate': '10-03-2024',
  'total_matches': 5},
 {'series_name': 'Hong Kong Friendship Cup, 2024',
  'city': 'Mong Kok',
  'matchFormat': 'T20',
  'startDate': '09-03-2024',
  'total_matches': 1},
 {'series_name': 'Malaysia Open T20I Championship, 2024',
  'city': 'Kuala Lumpur',
  'matchFormat': 'T20',
  'startDate': '05-03-2024',
  'total_matches': 12},
 {'series_name': 'Sri Lanka tour of Bangladesh, 2024',
  'city': 'Sylhet',
  'matchFormat': 'T20',
  'startDate': '04-03-2024',
  'total_matches': 8},
 {'series_name': 'Papua New Guinea tour of Oman 2024',
  'city': 'Al Amerat',
  'matchFormat': 'ODI',
  'startDate': '03-03-2024',
  'total_matches': 5},
 {'series_name': 'Afghanistan v Ireland in UAE, 2024',
  'city': 'Abu Dhabi',
  'matchFormat': 'TEST',
  'startDate': '28-02-2024',
  'total_matches': 7},
 {'series_name': 'Hong Kong tour of Qatar 2024',
  'city': 'Doha',
  'matchFormat': 'T20',
  'startDate': '27-02-2024',
  'total_matches': 3},
 {'series_name': 'Nepal T20I Tri-Series 2024',
  'city': 'Kirtipur',
  'matchFormat': 'T20',
  'startDate': '27-02-2024',
  'total_matches': 7},
 {'series_name': 'Australia tour of New Zealand, 2024',
  'city': 'Wellington',
  'matchFormat': 'T20',
  'startDate': '21-02-2024',
  'total_matches': 5},
 {'series_name': 'ICC Cricket World Cup League Two 2023-27',
  'city': 'Kirtipur',
  'matchFormat': 'ODI',
  'startDate': '15-02-2024',
  'total_matches': 109},
 {'series_name': 'East Asia Cup 2024',
  'city': 'Mong Kok',
  'matchFormat': 'T20',
  'startDate': '14-02-2024',
  'total_matches': 7},
 {'series_name': 'Quadrangular Twenty20 Series in Thailand 2024',
  'city': 'Bangkok',
  'matchFormat': 'T20',
  'startDate': '12-02-2024',
  'total_matches': 8},
 {'series_name': 'Canada tour of Nepal, 2024',
  'city': 'Kirtipur',
  'matchFormat': 'ODI',
  'startDate': '08-02-2024',
  'total_matches': 3},
 {'series_name': 'Afghanistan tour of Sri Lanka, 2024',
  'city': 'Colombo',
  'matchFormat': 'TEST',
  'startDate': '02-02-2024',
  'total_matches': 7},
 {'series_name': 'South Africa tour of New Zealand, 2024',
  'city': 'Lincoln',
  'matchFormat': 'TEST',
  'startDate': '30-01-2024',
  'total_matches': 3},
 {'series_name': 'ACC Mens T20I Challenger Cup 2024',
  'city': 'Bangkok',
  'matchFormat': 'T20',
  'startDate': '27-01-2024',
  'total_matches': 22},
 {'series_name': 'England tour of India, 2024',
  'city': 'Hyderabad',
  'matchFormat': 'TEST',
  'startDate': '25-01-2024',
  'total_matches': 5},
 {'series_name': 'Pakistan tour of New Zealand, 2024',
  'city': 'Auckland',
  'matchFormat': 'T20',
  'startDate': '12-01-2024',
  'total_matches': 5},
 {'series_name': 'Afghanistan tour of India, 2024',
  'city': 'Mohali',
  'matchFormat': 'T20',
  'startDate': '11-01-2024',
  'total_matches': 3},
 {'series_name': 'West Indies tour of Australia, 2024',
  'city': 'Adelaide, South Australia',
  'matchFormat': 'TEST',
  'startDate': '10-01-2024',
  'total_matches': 9},
 {'series_name': 'Zimbabwe tour of Sri Lanka 2024',
  'city': 'Colombo',
  'matchFormat': 'ODI',
  'startDate': '06-01-2024',
  'total_matches': 6}]

In [8]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

series_details_2024 = pd.DataFrame(series_info)


engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")
series_details_2024.to_sql(name="series_list_2024", con=engine, if_exists="replace", index=False)

print(
    f"Data uploaded to MySQL successfully, Database: {database}, Table: series_list_2024 ")

Data uploaded to MySQL successfully, Database: CricBuzz, Table: series_list_2024

Question 9 Find all-rounder players who have scored more than 1000 runs AND taken more than 50 wickets in their career. Display player name, total runs, total wickets, and the cricket format.

In [1]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/teams/v1/international"

headers = {
    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com",
    "Content-Type": "application/json"
}

response = requests.get(url, headers=headers)
data = response.json()

response = requests.get(url, headers=headers)
data = response.json()
team_ids = [item['teamId'] for item in data['list'] if 'teamId' in item]
print(team_ids)

[2, 96, 27, 3, 4, 5, 6, 9, 10, 11, 12, 13, 71, 72, 77, 161, 185, 190, 287, 298, 300, 303, 304, 343, 527, 529, 541, 44, 26, 7, 8, 14, 15, 23, 24, 25, 675]

In [10]:
import requests

team_ids = [2, 96, 27, 3, 4, 5, 6, 9, 10, 11, 12, 13, 71, 72, 77, 161, 185, 190, 287, 298, 300, 303, 304, 343, 527, 529, 541, 44, 26, 7, 8, 14, 15, 23, 24, 25, 675]

headers = {
    "x-rapidapi-key": "19598f3bb8msh40acf21e76b4d40p10e659jsn5acad54a832d",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

all_rounders = []

for team_id in team_ids:
    response = requests.get(f"https://cricbuzz-cricket.p.rapidapi.com/teams/v1/{team_id}/players", headers=headers)
    if response.status_code == 200:
        players = response.json().get("player", [])
        capture = False
        for p in players:
            if p.get("name", "").upper() == "ALL ROUNDER":
                capture = True
                continue
            if capture:
                if "id" in p:
                    all_rounders.append({"id": p["id"], "name": p["name"]})
                else:
                    break

all_rounders

all_rounder_ids = list(set([p["id"] for p in all_rounders]))
print(all_rounders)
all_rounder_ids

[{'id': '14701', 'name': 'Nitish Kumar Reddy'}, {'id': '9647', 'name': 'Hardik Pandya'}, {'id': '11195', 'name': 'Shivam Dube'}, {'id': '12086', 'name': 'Abhishek Sharma'}, {'id': '587', 'name': 'Ravindra Jadeja'}, {'id': '8683', 'name': 'Shardul Thakur'}, {'id': '10945', 'name': 'Washington Sundar'}, {'id': '8808', 'name': 'Axar Patel'}, {'id': '15752', 'name': 'Abdul Malik'}, {'id': '1449069', 'name': 'Ismat Alam'}, {'id': '8030', 'name': 'Gulbadin Naib'}, {'id': '13214', 'name': 'Azmatullah Omarzai'}, {'id': '14281', 'name': 'Zahir Shehzad'}, {'id': '10738', 'name': 'Rashid Khan'}, {'id': '53160', 'name': 'Bashir Ahmad'}, {'id': '3007', 'name': 'Mohammad Nabi'}, {'id': '22956', 'name': 'Nangeyalia Kharoti'}, {'id': '11077', 'name': 'Karim Janat'}, {'id': '47000', 'name': 'Zubaid Akbari'}, {'id': '1114', 'name': 'Paul Stirling'}, {'id': '13983', 'name': 'Gareth Delany'}, {'id': '6329', 'name': 'George Dockrell'}, {'id': '9667', 'name': 'Andy McBrine'}, {'id': '54252', 'name': 'Jordan Neill'}, {'id': '29018', 'name': 'Fionn Hand'}, {'id': '9812', 'name': 'Saud Shakeel'}, {'id': '9807', 'name': 'Kamran Ghulam'}, {'id': '10101', 'name': 'Salman Agha'}, {'id': '14241', 'name': 'Saim Ayub'}, {'id': '12565', 'name': 'Khushdil Shah'}, {'id': '15460', 'name': 'Irfan Khan'}, {'id': '9804', 'name': 'Hussain Talat'}, {'id': '14545', 'name': 'Noman Ali'}, {'id': '11265', 'name': 'Faheem Ashraf'}, {'id': '11186', 'name': 'Shadab Khan'}, {'id': '55256', 'name': 'Jahandad Khan'}, {'id': '12225', 'name': 'Cameron Green'}, {'id': '8646', 'name': 'Beau Webster'}, {'id': '6250', 'name': 'Mitchell Marsh'}, {'id': '8130', 'name': 'Michael Neser'}, {'id': '1629', 'name': 'Angelo Mathews'}, {'id': '10940', 'name': 'Kamindu Mendis'}, {'id': '7872', 'name': 'Dhananjaya de Silva'}, {'id': '10934', 'name': 'Charith Asalanka'}, {'id': '13694', 'name': 'Janith Liyanage'}, {'id': '13930', 'name': 'Sonal Dinusha'}, {'id': '18515', 'name': 'Tharindu Ratnayake'}, {'id': '39678', 'name': 'Milan Priyanath Rathnayake'}, {'id': '14251', 'name': 'Dunith Wellalage'}, {'id': '10926', 'name': 'Wanindu Hasaranga'}]

['10926',
 '22956',
 '587',
 '11195',
 '8030',
 '15460',
 '10945',
 '8646',
 '10101',
 '15752',
 '6329',
 '54252',
 '12086',
 '9807',
 '12565',
 '12225',
 '18515',
 '7872',
 '9812',
 '13214',
 '1114',
 '14251',
 '11265',
 '13930',
 '14241',
 '9667',
 '10934',
 '3007',
 '13694',
 '13983',
 '8683',
 '8808',
 '11186',
 '10940',
 '6250',
 '55256',
 '1449069',
 '47000',
 '1629',
 '29018',
 '39678',
 '14701',
 '9804',
 '8130',
 '10738',
 '53160',
 '9647',
 '11077',
 '14281',
 '14545']

In [15]:
import requests
import time

batting_stats_data = []

headers = {
    "x-rapidapi-key": "68b998acc8mshdf376a5f413c7ffp1eed7bjsnda23974c15d8",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

for player_id in all_rounder_ids:
    try:
        url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{player_id}/batting"

        response = requests.get(url, headers=headers, timeout=30)

        if response.status_code == 200:
            batting_stats_data.append({
                "player_id": player_id,
                "batting_stats": response.json()
            })
            print(f"✓ Success: {player_id}")

        elif response.status_code == 204:
            print(f"⚠ No batting data: {player_id}")

        else:
            print(f"✗ Error {response.status_code}: {player_id}")

        time.sleep(2)  # helps avoid rate limits

    except Exception as e:
        print(f"✗ Exception for {player_id}: {e}")

print(f"\nTotal successful records: {len(batting_stats_data)}")

✓ Success: 10926
✓ Success: 22956
✓ Success: 587
✓ Success: 11195
✓ Success: 8030
✓ Success: 15460
✓ Success: 10945
✓ Success: 8646
✓ Success: 10101
✓ Success: 15752
✓ Success: 6329
✓ Success: 54252
✓ Success: 12086
✓ Success: 9807
✓ Success: 12565
✓ Success: 12225
✓ Success: 18515
✓ Success: 7872
✓ Success: 9812
✓ Success: 13214
✓ Success: 1114
✓ Success: 14251
✓ Success: 11265
✓ Success: 13930
✓ Success: 14241
✓ Success: 9667
✓ Success: 10934
✓ Success: 3007
✓ Success: 13694
✓ Success: 13983
✓ Success: 8683
✓ Success: 8808
✓ Success: 11186
✓ Success: 10940
✓ Success: 6250
✓ Success: 55256
✓ Success: 1449069
✓ Success: 47000
✓ Success: 1629
✓ Success: 29018
✓ Success: 39678
✓ Success: 14701
✓ Success: 9804
✓ Success: 8130
✓ Success: 10738
✓ Success: 53160
✓ Success: 9647
✓ Success: 11077
⚠ No batting data: 14281
✓ Success: 14545

Total successful records: 49

In [18]:
batting_stats_data[0]

{'player_id': '10926',
 'batting_stats': {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '4', '70', '96', '37']},
   {'values': ['Innings', '7', '58', '78', '19']},
   {'values': ['Runs', '196', '1142', '810', '81']},
   {'values': ['Balls', '227', '1039', '645', '88']},
   {'values': ['Highest', '59', '80', '71', '18']},
   {'values': ['Average', '28', '23.31', '13.28', '5.4']},
   {'values': ['SR', '86.35', '109.92', '125.59', '92.05']},
   {'values': ['Not Out', '0', '9', '17', '4']},
   {'values': ['Fours', '29', '103', '81', '7']},
   {'values': ['Sixes', '1', '36', '17', '1']},
   {'values': ['Ducks', '0', '3', '8', '5']},
   {'values': ['50s', '1', '5', '2', '0']},
   {'values': ['100s', '0', '0', '0', '0']},
   {'values': ['200s', '0', '0', '0', '0']},
   {'values': ['300s', '0', '0', '0', '0']},
   {'values': ['400s', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Wanindu Hasaranga Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/10926/wanindu-hasaranga'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11946, 'seriesName': 'Sri Lanka tour of West Indies 2026'}]}}

In [16]:
import requests
import time

bowling_stats_data = []

headers = {
    "x-rapidapi-key": "68b998acc8mshdf376a5f413c7ffp1eed7bjsnda23974c15d8",
    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

for player_id in all_rounder_ids:
    try:
        url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{player_id}/bowling"

        response = requests.get(url, headers=headers, timeout=30)

        if response.status_code == 200:
            bowling_stats_data.append({
                "player_id": player_id,
                "bowling_stats": response.json()
            })
            print(f"✓ Success: {player_id}")

        elif response.status_code == 204:
            print(f"⚠ No bowling data: {player_id}")

        else:
            print(f"✗ Error {response.status_code}: {player_id}")

        time.sleep(2)

    except Exception as e:
        print(f"✗ Exception for {player_id}: {e}")

print(f"\nTotal successful records: {len(bowling_stats_data)}")

✓ Success: 10926
✓ Success: 22956
✓ Success: 587
✓ Success: 11195
✓ Success: 8030
✓ Success: 15460
✓ Success: 10945
✓ Success: 8646
✓ Success: 10101
✓ Success: 15752
✓ Success: 6329
✓ Success: 54252
✓ Success: 12086
✓ Success: 9807
✓ Success: 12565
✓ Success: 12225
✓ Success: 18515
✓ Success: 7872
✓ Success: 9812
✓ Success: 13214
✓ Success: 1114
✓ Success: 14251
✓ Success: 11265
✓ Success: 13930
✓ Success: 14241
✓ Success: 9667
✓ Success: 10934
✓ Success: 3007
✓ Success: 13694
✓ Success: 13983
✓ Success: 8683
✓ Success: 8808
✓ Success: 11186
✓ Success: 10940
✓ Success: 6250
✓ Success: 55256
✓ Success: 1449069
✓ Success: 47000
✓ Success: 1629
✓ Success: 29018
✓ Success: 39678
✓ Success: 14701
✓ Success: 9804
✓ Success: 8130
✓ Success: 10738
✓ Success: 53160
✓ Success: 9647
✓ Success: 11077
⚠ No bowling data: 14281
✓ Success: 14545

Total successful records: 49

In [17]:
bowling_stats_data[0]

{'player_id': '10926',
 'bowling_stats': {'headers': ['ROWHEADER', 'Test', 'ODI', 'T20', 'IPL'],
  'values': [{'values': ['Matches', '4', '70', '96', '37']},
   {'values': ['Innings', '7', '69', '94', '37']},
   {'values': ['Balls', '674', '3305', '2136', '798']},
   {'values': ['Runs', '403', '2807', '2505', '1119']},
   {'values': ['Maidens', '8', '26', '2', '1']},
   {'values': ['Wickets', '4', '113', '156', '46']},
   {'values': ['Avg', '100.75', '24.84', '16.06', '24.33']},
   {'values': ['Eco', '3.59', '5.1', '7.04', '8.41']},
   {'values': ['SR', '168.5', '29.25', '13.69', '17.35']},
   {'values': ['BBI', '4/171', '7/19', '4/9', '5/18']},
   {'values': ['BBM', '4/171', '7/19', '4/9', '5/18']},
   {'values': ['4w', '1', '5', '5', '2']},
   {'values': ['5w', '0', '4', '0', '1']},
   {'values': ['10w', '0', '0', '0', '0']}],
  'appIndex': {'seoTitle': 'Wanindu Hasaranga Profile - Cricbuzz | Cricbuzz.com',
   'webURL': 'http://www.cricbuzz.com/profiles/10926/wanindu-hasaranga'},
  'seriesSpinner': [{'seriesName': 'Career'},
   {'seriesId': 11946, 'seriesName': 'Sri Lanka tour of West Indies 2026'}]}}

In [19]:
allrounders_list_1000runs = []
allrounders_id_1000runs = []
allrounder_stats = []
allrounders_list_1000runs_50wkts = []


for index, bat in enumerate(batting_stats_data):
    try:
        odi_runs = int(bat['values'][2]['values'][2]) 
        test_runs= int(bat['values'][2]['values'][1])
    except:
        continue

    if odi_runs > 1000 or test_runs>1000: 
        allrounders_list_1000runs.append({
            "PlayerID": all_rounder_ids[index]["PlayerID"],
            "PlayerName": all_rounder_ids[index]["PlayerName"],
            "ODI Runs": odi_runs,
            "Test Runs" : test_runs
        })
        allrounders_id_1000runs.append(index)  



for index in allrounders_id_1000runs:
    bowl = bowling_stats_data[index]

    try:
        odi_wickets = int(bowl['values'][5]['values'][2]) 
        test_wickets = int(bowl['values'][5]['values'][1])
    except:
        continue

    if odi_wickets > 50 or test_wickets > 50:  
        player_name = all_rounder_ids[index]["PlayerName"]
        odi_runs = batting_stats_data[index]['values'][2]['values'][2]
        test_runs = batting_stats_data[index]['values'][2]['values'][1]
        player_stat = {
            "PlayerName": player_name,
            "ODI Runs": odi_runs,
            "Test Runs" : test_runs,
            "ODI Wickets": odi_wickets,
            "Test Wickets":test_wickets,
            "Game Format": "Test & ODI"
        }
        allrounder_stats.append(player_stat)
        allrounders_list_1000runs_50wkts.append(all_rounder_ids[index])
allrounder_stats

[]

In [20]:
allrounder_stats = []

for bat, bowl in zip(batting_stats_data, bowling_stats_data):

    try:
        # Ensure same player
        if bat["player_id"] != bowl["player_id"]:
            continue

        player_id = bat["player_id"]

        # Player name
        player_name = (
            bat["batting_stats"]["appIndex"]["seoTitle"]
            .split(" Profile")[0]
        )

        # Batting stats
        batting_values = bat["batting_stats"]["values"]

        odi_runs = int(batting_values[2]["values"][2])
        test_runs = int(batting_values[2]["values"][1])

        # Bowling stats
        bowling_values = bowl["bowling_stats"]["values"]

        odi_wickets = int(bowling_values[5]["values"][2])
        test_wickets = int(bowling_values[5]["values"][1])

        # Filter criteria
        if (odi_runs > 1000 or test_runs > 1000) and \
           (odi_wickets > 50 or test_wickets > 50):

            allrounder_stats.append({
                "PlayerID": player_id,
                "PlayerName": player_name,
                "ODI Runs": odi_runs,
                "Test Runs": test_runs,
                "ODI Wickets": odi_wickets,
                "Test Wickets": test_wickets
            })

    except Exception as e:
        print(f"Error for player {bat.get('player_id')}: {e}")

print(f"Total qualifying all-rounders: {len(allrounder_stats)}")

# View first few results
print(allrounder_stats[:5])

Total qualifying all-rounders: 9
[{'PlayerID': '10926', 'PlayerName': 'Wanindu Hasaranga', 'ODI Runs': 1142, 'Test Runs': 196, 'ODI Wickets': 113, 'Test Wickets': 4}, {'PlayerID': '587', 'PlayerName': 'Ravindra Jadeja', 'ODI Runs': 2905, 'Test Runs': 4095, 'ODI Wickets': 232, 'Test Wickets': 348}, {'PlayerID': '8030', 'PlayerName': 'Gulbadin Naib', 'ODI Runs': 1332, 'Test Runs': 0, 'ODI Wickets': 74, 'Test Wickets': 0}, {'PlayerID': '6329', 'PlayerName': 'George Dockrell', 'ODI Runs': 1459, 'Test Runs': 98, 'ODI Wickets': 111, 'Test Wickets': 3}, {'PlayerID': '3007', 'PlayerName': 'Mohammad Nabi', 'ODI Runs': 3759, 'Test Runs': 33, 'ODI Wickets': 176, 'Test Wickets': 8}]

In [21]:
import pandas as pd
allrounder_stats_table = pd.DataFrame(allrounder_stats)
allrounder_stats_table

  PlayerID         PlayerName  ODI Runs  Test Runs  ODI Wickets  Test Wickets
0    10926  Wanindu Hasaranga      1142        196          113             4
1      587    Ravindra Jadeja      2905       4095          232           348
2     8030      Gulbadin Naib      1332          0           74             0
3     6329    George Dockrell      1459         98          111             3
4     3007      Mohammad Nabi      3759         33          176             8
5     6250     Mitchell Marsh      3098       2083           57            51
6     1629     Angelo Mathews      5916       8214          126            33
7    10738        Rashid Khan      1402        154          211            45
8     9647      Hardik Pandya      1904        532           91            17

In [22]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

allrounder_stats_table = pd.DataFrame(allrounder_stats)


engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")
allrounder_stats_table.to_sql(name="allrounder_stats_table", con=engine, if_exists="replace", index=False)

print(
    f"Data uploaded to MySQL successfully, Database: {database}, Table: allrounder_stats_table ")

Data uploaded to MySQL successfully, Database: CricBuzz, Table: allrounder_stats_table

Question 10 Get details of the last 20 completed matches. Show match description, both team names, winning team, victory margin, victory type (runs/wickets), and venue name. Display the most recent matches first.

In [23]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/7607"

headers = {
	"x-rapidapi-key": "68b998acc8mshdf376a5f413c7ffp1eed7bjsnda23974c15d8",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
results_data=response.json()

{'matchDetails': [{'matchDetailsMap': {'key': 'Fri, 22 Mar 2024', 'match': [{'matchInfo': {'matchId': 89654, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '1st Match', 'matchFormat': 'T20', 'startDate': '1711117800000', 'endDate': '1711117800000', 'state': 'complete', 'status': 'Chennai Super Kings won by 6 wkts', 'team1': {'teamId': 58, 'teamName': 'CHENNAI SUPER KINGS', 'teamSName': 'CSK', 'imageId': 860038}, 'team2': {'teamId': 59, 'teamName': 'ROYAL CHALLENGERS BENGALURU', 'teamSName': 'RCB', 'imageId': 860056}, 'venueInfo': {'ground': 'MA Chidambaram Stadium', 'city': 'Chennai', 'timezone': '+05:30'}, 'currBatTeamId': 58, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 176, 'wickets': 4, 'overs': 18.4}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 173, 'wickets': 6, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'adDetail': {'name': 'native_news_index_random_1', 'layout': 'native_large', 'position': 1}}, {'matchDetailsMap': {'key': 'Sat, 23 Mar 2024', 'match': [{'matchInfo': {'matchId': 89661, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '2nd Match', 'matchFormat': 'T20', 'startDate': '1711188000000', 'endDate': '1711188000000', 'state': 'complete', 'status': 'Punjab Kings won by 4 wkts', 'team1': {'teamId': 65, 'teamName': 'PUNJAB KINGS', 'teamSName': 'PBKS', 'imageId': 860084}, 'team2': {'teamId': 61, 'teamName': 'DELHI CAPITALS', 'teamSName': 'DC', 'imageId': 860040}, 'venueInfo': {'ground': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'city': 'New Chandigarh', 'timezone': '+05:30'}, 'currBatTeamId': 65, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 177, 'wickets': 6, 'overs': 19.2}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 174, 'wickets': 9, 'overs': 20.0}}}}, {'matchInfo': {'matchId': 89665, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '3rd Match', 'matchFormat': 'T20', 'startDate': '1711202400000', 'endDate': '1711202400000', 'state': 'complete', 'status': 'Kolkata Knight Riders won by 4 runs', 'team1': {'teamId': 63, 'teamName': 'KOLKATA KNIGHT RIDERS', 'teamSName': 'KKR', 'imageId': 860046}, 'team2': {'teamId': 255, 'teamName': 'SUNRISERS HYDERABAD', 'teamSName': 'SRH', 'imageId': 860066}, 'venueInfo': {'ground': 'Eden Gardens', 'city': 'Kolkata', 'timezone': '+05:30'}, 'currBatTeamId': 63, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 208, 'wickets': 7, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 204, 'wickets': 7, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Sun, 24 Mar 2024', 'match': [{'matchInfo': {'matchId': 89668, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '4th Match', 'matchFormat': 'T20', 'startDate': '1711274400000', 'endDate': '1711274400000', 'state': 'complete', 'status': 'Rajasthan Royals won by 20 runs', 'team1': {'teamId': 64, 'teamName': 'RAJASTHAN ROYALS', 'teamSName': 'RR', 'imageId': 860055}, 'team2': {'teamId': 966, 'teamName': 'LUCKNOW SUPER GIANTS', 'teamSName': 'LSG', 'imageId': 882545}, 'venueInfo': {'ground': 'Sawai Mansingh Stadium', 'city': 'Jaipur', 'timezone': '+05:30'}, 'currBatTeamId': 64, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 193, 'wickets': 4, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 173, 'wickets': 6, 'overs': 20.0}}}}, {'matchInfo': {'matchId': 89675, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '5th Match', 'matchFormat': 'T20', 'startDate': '1711288800000', 'endDate': '1711288800000', 'state': 'complete', 'status': 'Gujarat Titans won by 6 runs', 'team1': {'teamId': 971, 'teamName': 'GUJARAT TITANS', 'teamSName': 'GT', 'imageId': 860068}, 'team2': {'teamId': 62, 'teamName': 'MUMBAI INDIANS', 'teamSName': 'MI', 'imageId': 860053}, 'venueInfo': {'ground': 'Narendra Modi Stadium', 'city': 'Ahmedabad', 'timezone': '+05:30'}, 'currBatTeamId': 971, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 168, 'wickets': 6, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 162, 'wickets': 9, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Mon, 25 Mar 2024', 'match': [{'matchInfo': {'matchId': 89682, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '6th Match', 'matchFormat': 'T20', 'startDate': '1711375200000', 'endDate': '1711375200000', 'state': 'complete', 'status': 'Royal Challengers Bengaluru won by 4 wkts', 'team1': {'teamId': 59, 'teamName': 'ROYAL CHALLENGERS BENGALURU', 'teamSName': 'RCB', 'imageId': 860056}, 'team2': {'teamId': 65, 'teamName': 'PUNJAB KINGS', 'teamSName': 'PBKS', 'imageId': 860084}, 'venueInfo': {'ground': 'M.Chinnaswamy Stadium', 'city': 'Bengaluru', 'timezone': '+05:30'}, 'currBatTeamId': 59, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 178, 'wickets': 6, 'overs': 19.2}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 176, 'wickets': 6, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Tue, 26 Mar 2024', 'match': [{'matchInfo': {'matchId': 89689, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '7th Match', 'matchFormat': 'T20', 'startDate': '1711461600000', 'endDate': '1711461600000', 'state': 'complete', 'status': 'Chennai Super Kings won by 63 runs', 'team1': {'teamId': 58, 'teamName': 'CHENNAI SUPER KINGS', 'teamSName': 'CSK', 'imageId': 860038}, 'team2': {'teamId': 971, 'teamName': 'GUJARAT TITANS', 'teamSName': 'GT', 'imageId': 860068}, 'venueInfo': {'ground': 'MA Chidambaram Stadium', 'city': 'Chennai', 'timezone': '+05:30'}, 'currBatTeamId': 58, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 206, 'wickets': 6, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 143, 'wickets': 8, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Wed, 27 Mar 2024', 'match': [{'matchInfo': {'matchId': 89693, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '8th Match', 'matchFormat': 'T20', 'startDate': '1711548000000', 'endDate': '1711548000000', 'state': 'complete', 'status': 'Sunrisers Hyderabad won by 31 runs', 'team1': {'teamId': 255, 'teamName': 'SUNRISERS HYDERABAD', 'teamSName': 'SRH', 'imageId': 860066}, 'team2': {'teamId': 62, 'teamName': 'MUMBAI INDIANS', 'teamSName': 'MI', 'imageId': 860053}, 'venueInfo': {'ground': 'Rajiv Gandhi International Stadium', 'city': 'Hyderabad', 'timezone': '+05:30'}, 'currBatTeamId': 255, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 277, 'wickets': 3, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 246, 'wickets': 5, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Thu, 28 Mar 2024', 'match': [{'matchInfo': {'matchId': 89700, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '9th Match', 'matchFormat': 'T20', 'startDate': '1711634400000', 'endDate': '1711634400000', 'state': 'complete', 'status': 'Rajasthan Royals won by 12 runs', 'team1': {'teamId': 64, 'teamName': 'RAJASTHAN ROYALS', 'teamSName': 'RR', 'imageId': 860055}, 'team2': {'teamId': 61, 'teamName': 'DELHI CAPITALS', 'teamSName': 'DC', 'imageId': 860040}, 'venueInfo': {'ground': 'Sawai Mansingh Stadium', 'city': 'Jaipur', 'timezone': '+05:30'}, 'currBatTeamId': 64, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 185, 'wickets': 5, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 173, 'wickets': 5, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Fri, 29 Mar 2024', 'match': [{'matchInfo': {'matchId': 89703, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '10th Match', 'matchFormat': 'T20', 'startDate': '1711720800000', 'endDate': '1711720800000', 'state': 'complete', 'status': 'Kolkata Knight Riders won by 7 wkts', 'team1': {'teamId': 59, 'teamName': 'ROYAL CHALLENGERS BENGALURU', 'teamSName': 'RCB', 'imageId': 860056}, 'team2': {'teamId': 63, 'teamName': 'KOLKATA KNIGHT RIDERS', 'teamSName': 'KKR', 'imageId': 860046}, 'venueInfo': {'ground': 'M.Chinnaswamy Stadium', 'city': 'Bengaluru', 'timezone': '+05:30'}, 'currBatTeamId': 63, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 182, 'wickets': 6, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 186, 'wickets': 3, 'overs': 16.5}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Sat, 30 Mar 2024', 'match': [{'matchInfo': {'matchId': 89710, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '11th Match', 'matchFormat': 'T20', 'startDate': '1711807200000', 'endDate': '1711807200000', 'state': 'complete', 'status': 'Lucknow Super Giants won by 21 runs', 'team1': {'teamId': 966, 'teamName': 'LUCKNOW SUPER GIANTS', 'teamSName': 'LSG', 'imageId': 882545}, 'team2': {'teamId': 65, 'teamName': 'PUNJAB KINGS', 'teamSName': 'PBKS', 'imageId': 860084}, 'venueInfo': {'ground': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'city': 'Lucknow', 'timezone': '+05:30'}, 'currBatTeamId': 966, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 199, 'wickets': 8, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 178, 'wickets': 5, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Sun, 31 Mar 2024', 'match': [{'matchInfo': {'matchId': 89717, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '12th Match', 'matchFormat': 'T20', 'startDate': '1711879200000', 'endDate': '1711879200000', 'state': 'complete', 'status': 'Gujarat Titans won by 7 wkts', 'team1': {'teamId': 971, 'teamName': 'GUJARAT TITANS', 'teamSName': 'GT', 'imageId': 860068}, 'team2': {'teamId': 255, 'teamName': 'SUNRISERS HYDERABAD', 'teamSName': 'SRH', 'imageId': 860066}, 'venueInfo': {'ground': 'Narendra Modi Stadium', 'city': 'Ahmedabad', 'timezone': '+05:30'}, 'currBatTeamId': 971, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 168, 'wickets': 3, 'overs': 19.1}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 162, 'wickets': 8, 'overs': 20.0}}}}, {'matchInfo': {'matchId': 89724, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '13th Match', 'matchFormat': 'T20', 'startDate': '1711893600000', 'endDate': '1711893600000', 'state': 'complete', 'status': 'Delhi Capitals won by 20 runs', 'team1': {'teamId': 61, 'teamName': 'DELHI CAPITALS', 'teamSName': 'DC', 'imageId': 860040}, 'team2': {'teamId': 58, 'teamName': 'CHENNAI SUPER KINGS', 'teamSName': 'CSK', 'imageId': 860038}, 'venueInfo': {'ground': 'ACA-VDCA Cricket Stadium', 'city': 'Visakhapatnam', 'timezone': '+05:30'}, 'currBatTeamId': 61, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 191, 'wickets': 5, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 171, 'wickets': 6, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Mon, 01 Apr 2024', 'match': [{'matchInfo': {'matchId': 89731, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '14th Match', 'matchFormat': 'T20', 'startDate': '1711980000000', 'endDate': '1711980000000', 'state': 'complete', 'status': 'Rajasthan Royals won by 6 wkts', 'team1': {'teamId': 62, 'teamName': 'MUMBAI INDIANS', 'teamSName': 'MI', 'imageId': 860053}, 'team2': {'teamId': 64, 'teamName': 'RAJASTHAN ROYALS', 'teamSName': 'RR', 'imageId': 860055}, 'venueInfo': {'ground': 'Wankhede Stadium', 'city': 'Mumbai', 'timezone': '+05:30'}, 'currBatTeamId': 64, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 125, 'wickets': 9, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 127, 'wickets': 4, 'overs': 15.3}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Tue, 02 Apr 2024', 'match': [{'matchInfo': {'matchId': 89738, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '15th Match', 'matchFormat': 'T20', 'startDate': '1712066400000', 'endDate': '1712066400000', 'state': 'complete', 'status': 'Lucknow Super Giants won by 28 runs', 'team1': {'teamId': 59, 'teamName': 'ROYAL CHALLENGERS BENGALURU', 'teamSName': 'RCB', 'imageId': 860056}, 'team2': {'teamId': 966, 'teamName': 'LUCKNOW SUPER GIANTS', 'teamSName': 'LSG', 'imageId': 882545}, 'venueInfo': {'ground': 'M.Chinnaswamy Stadium', 'city': 'Bengaluru', 'timezone': '+05:30'}, 'currBatTeamId': 966, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 153, 'wickets': 10, 'overs': 19.4}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 181, 'wickets': 5, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Wed, 03 Apr 2024', 'match': [{'matchInfo': {'matchId': 89745, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '16th Match', 'matchFormat': 'T20', 'startDate': '1712152800000', 'endDate': '1712152800000', 'state': 'complete', 'status': 'Kolkata Knight Riders won by 106 runs', 'team1': {'teamId': 61, 'teamName': 'DELHI CAPITALS', 'teamSName': 'DC', 'imageId': 860040}, 'team2': {'teamId': 63, 'teamName': 'KOLKATA KNIGHT RIDERS', 'teamSName': 'KKR', 'imageId': 860046}, 'venueInfo': {'ground': 'ACA-VDCA Cricket Stadium', 'city': 'Visakhapatnam', 'timezone': '+05:30'}, 'currBatTeamId': 63, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 166, 'wickets': 10, 'overs': 17.2}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 272, 'wickets': 7, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Thu, 04 Apr 2024', 'match': [{'matchInfo': {'matchId': 89749, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '17th Match', 'matchFormat': 'T20', 'startDate': '1712239200000', 'endDate': '1712239200000', 'state': 'complete', 'status': 'Punjab Kings won by 3 wkts', 'team1': {'teamId': 971, 'teamName': 'GUJARAT TITANS', 'teamSName': 'GT', 'imageId': 860068}, 'team2': {'teamId': 65, 'teamName': 'PUNJAB KINGS', 'teamSName': 'PBKS', 'imageId': 860084}, 'venueInfo': {'ground': 'Narendra Modi Stadium', 'city': 'Ahmedabad', 'timezone': '+05:30'}, 'currBatTeamId': 65, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 199, 'wickets': 4, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 200, 'wickets': 7, 'overs': 19.5}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Fri, 05 Apr 2024', 'match': [{'matchInfo': {'matchId': 89752, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '18th Match', 'matchFormat': 'T20', 'startDate': '1712325600000', 'endDate': '1712325600000', 'state': 'complete', 'status': 'Sunrisers Hyderabad won by 6 wkts', 'team1': {'teamId': 255, 'teamName': 'SUNRISERS HYDERABAD', 'teamSName': 'SRH', 'imageId': 860066}, 'team2': {'teamId': 58, 'teamName': 'CHENNAI SUPER KINGS', 'teamSName': 'CSK', 'imageId': 860038}, 'venueInfo': {'ground': 'Rajiv Gandhi International Stadium', 'city': 'Hyderabad', 'timezone': '+05:30'}, 'currBatTeamId': 255, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 166, 'wickets': 4, 'overs': 18.1}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 165, 'wickets': 5, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Sat, 06 Apr 2024', 'match': [{'matchInfo': {'matchId': 89756, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '19th Match', 'matchFormat': 'T20', 'startDate': '1712412000000', 'endDate': '1712412000000', 'state': 'complete', 'status': 'Rajasthan Royals won by 6 wkts', 'team1': {'teamId': 64, 'teamName': 'RAJASTHAN ROYALS', 'teamSName': 'RR', 'imageId': 860055}, 'team2': {'teamId': 59, 'teamName': 'ROYAL CHALLENGERS BENGALURU', 'teamSName': 'RCB', 'imageId': 860056}, 'venueInfo': {'ground': 'Sawai Mansingh Stadium', 'city': 'Jaipur', 'timezone': '+05:30'}, 'currBatTeamId': 64, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 189, 'wickets': 4, 'overs': 19.1}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 183, 'wickets': 3, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Sun, 07 Apr 2024', 'match': [{'matchInfo': {'matchId': 89763, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '20th Match', 'matchFormat': 'T20', 'startDate': '1712484000000', 'endDate': '1712484000000', 'state': 'complete', 'status': 'Mumbai Indians won by 29 runs', 'team1': {'teamId': 62, 'teamName': 'MUMBAI INDIANS', 'teamSName': 'MI', 'imageId': 860053}, 'team2': {'teamId': 61, 'teamName': 'DELHI CAPITALS', 'teamSName': 'DC', 'imageId': 860040}, 'venueInfo': {'ground': 'Wankhede Stadium', 'city': 'Mumbai', 'timezone': '+05:30'}, 'currBatTeamId': 62, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 234, 'wickets': 5, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 205, 'wickets': 8, 'overs': 20.0}}}}, {'matchInfo': {'matchId': 89770, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '21st Match', 'matchFormat': 'T20', 'startDate': '1712498400000', 'endDate': '1712498400000', 'state': 'complete', 'status': 'Lucknow Super Giants won by 33 runs', 'team1': {'teamId': 966, 'teamName': 'LUCKNOW SUPER GIANTS', 'teamSName': 'LSG', 'imageId': 882545}, 'team2': {'teamId': 971, 'teamName': 'GUJARAT TITANS', 'teamSName': 'GT', 'imageId': 860068}, 'venueInfo': {'ground': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'city': 'Lucknow', 'timezone': '+05:30'}, 'currBatTeamId': 966, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 163, 'wickets': 5, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 130, 'wickets': 10, 'overs': 18.5}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Mon, 08 Apr 2024', 'match': [{'matchInfo': {'matchId': 91380, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '22nd Match', 'matchFormat': 'T20', 'startDate': '1712584800000', 'endDate': '1712584800000', 'state': 'complete', 'status': 'Chennai Super Kings won by 7 wkts', 'team1': {'teamId': 58, 'teamName': 'CHENNAI SUPER KINGS', 'teamSName': 'CSK', 'imageId': 860038}, 'team2': {'teamId': 63, 'teamName': 'KOLKATA KNIGHT RIDERS', 'teamSName': 'KKR', 'imageId': 860046}, 'venueInfo': {'ground': 'MA Chidambaram Stadium', 'city': 'Chennai', 'timezone': '+05:30'}, 'currBatTeamId': 58, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 141, 'wickets': 3, 'overs': 17.4}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 137, 'wickets': 9, 'overs': 20.0}}}}], 'seriesId': 7607}}, {'matchDetailsMap': {'key': 'Tue, 09 Apr 2024', 'match': [{'matchInfo': {'matchId': 91389, 'seriesId': 7607, 'seriesName': 'Indian Premier League 2024', 'matchDesc': '23rd Match', 'matchFormat': 'T20', 'startDate': '1712671200000', 'endDate': '1712671200000', 'state': 'complete', 'status': 'Sunrisers Hyderabad won by 2 runs', 'team1': {'teamId': 65, 'teamName': 'PUNJAB KINGS', 'teamSName': 'PBKS', 'imageId': 860084}, 'team2': {'teamId': 255, 'teamName': 'SUNRISERS HYDERABAD', 'teamSName': 'SRH', 'imageId': 860066}, 'venueInfo': {'ground': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'city': 'New Chandigarh', 'timezone': '+05:30'}, 'currBatTeamId': 255, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 180, 'wickets': 6, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 182, 'wickets': 

In [24]:
results_data

{'matchDetails': [{'matchDetailsMap': {'key': 'Fri, 22 Mar 2024',
    'match': [{'matchInfo': {'matchId': 89654,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '1st Match',
       'matchFormat': 'T20',
       'startDate': '1711117800000',
       'endDate': '1711117800000',
       'state': 'complete',
       'status': 'Chennai Super Kings won by 6 wkts',
       'team1': {'teamId': 58,
        'teamName': 'CHENNAI SUPER KINGS',
        'teamSName': 'CSK',
        'imageId': 860038},
       'team2': {'teamId': 59,
        'teamName': 'ROYAL CHALLENGERS BENGALURU',
        'teamSName': 'RCB',
        'imageId': 860056},
       'venueInfo': {'ground': 'MA Chidambaram Stadium',
        'city': 'Chennai',
        'timezone': '+05:30'},
       'currBatTeamId': 58,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 176,
         'wickets': 4,
         'overs': 18.4}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 173,
         'wickets': 6,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'adDetail': {'name': 'native_news_index_random_1',
    'layout': 'native_large',
    'position': 1}},
  {'matchDetailsMap': {'key': 'Sat, 23 Mar 2024',
    'match': [{'matchInfo': {'matchId': 89661,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '2nd Match',
       'matchFormat': 'T20',
       'startDate': '1711188000000',
       'endDate': '1711188000000',
       'state': 'complete',
       'status': 'Punjab Kings won by 4 wkts',
       'team1': {'teamId': 65,
        'teamName': 'PUNJAB KINGS',
        'teamSName': 'PBKS',
        'imageId': 860084},
       'team2': {'teamId': 61,
        'teamName': 'DELHI CAPITALS',
        'teamSName': 'DC',
        'imageId': 860040},
       'venueInfo': {'ground': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
        'city': 'New Chandigarh',
        'timezone': '+05:30'},
       'currBatTeamId': 65,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 177,
         'wickets': 6,
         'overs': 19.2}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 174,
         'wickets': 9,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 89665,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '3rd Match',
       'matchFormat': 'T20',
       'startDate': '1711202400000',
       'endDate': '1711202400000',
       'state': 'complete',
       'status': 'Kolkata Knight Riders won by 4 runs',
       'team1': {'teamId': 63,
        'teamName': 'KOLKATA KNIGHT RIDERS',
        'teamSName': 'KKR',
        'imageId': 860046},
       'team2': {'teamId': 255,
        'teamName': 'SUNRISERS HYDERABAD',
        'teamSName': 'SRH',
        'imageId': 860066},
       'venueInfo': {'ground': 'Eden Gardens',
        'city': 'Kolkata',
        'timezone': '+05:30'},
       'currBatTeamId': 63,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 208,
         'wickets': 7,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 204,
         'wickets': 7,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Sun, 24 Mar 2024',
    'match': [{'matchInfo': {'matchId': 89668,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '4th Match',
       'matchFormat': 'T20',
       'startDate': '1711274400000',
       'endDate': '1711274400000',
       'state': 'complete',
       'status': 'Rajasthan Royals won by 20 runs',
       'team1': {'teamId': 64,
        'teamName': 'RAJASTHAN ROYALS',
        'teamSName': 'RR',
        'imageId': 860055},
       'team2': {'teamId': 966,
        'teamName': 'LUCKNOW SUPER GIANTS',
        'teamSName': 'LSG',
        'imageId': 882545},
       'venueInfo': {'ground': 'Sawai Mansingh Stadium',
        'city': 'Jaipur',
        'timezone': '+05:30'},
       'currBatTeamId': 64,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 193,
         'wickets': 4,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 173,
         'wickets': 6,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 89675,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '5th Match',
       'matchFormat': 'T20',
       'startDate': '1711288800000',
       'endDate': '1711288800000',
       'state': 'complete',
       'status': 'Gujarat Titans won by 6 runs',
       'team1': {'teamId': 971,
        'teamName': 'GUJARAT TITANS',
        'teamSName': 'GT',
        'imageId': 860068},
       'team2': {'teamId': 62,
        'teamName': 'MUMBAI INDIANS',
        'teamSName': 'MI',
        'imageId': 860053},
       'venueInfo': {'ground': 'Narendra Modi Stadium',
        'city': 'Ahmedabad',
        'timezone': '+05:30'},
       'currBatTeamId': 971,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 168,
         'wickets': 6,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 162,
         'wickets': 9,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Mon, 25 Mar 2024',
    'match': [{'matchInfo': {'matchId': 89682,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '6th Match',
       'matchFormat': 'T20',
       'startDate': '1711375200000',
       'endDate': '1711375200000',
       'state': 'complete',
       'status': 'Royal Challengers Bengaluru won by 4 wkts',
       'team1': {'teamId': 59,
        'teamName': 'ROYAL CHALLENGERS BENGALURU',
        'teamSName': 'RCB',
        'imageId': 860056},
       'team2': {'teamId': 65,
        'teamName': 'PUNJAB KINGS',
        'teamSName': 'PBKS',
        'imageId': 860084},
       'venueInfo': {'ground': 'M.Chinnaswamy Stadium',
        'city': 'Bengaluru',
        'timezone': '+05:30'},
       'currBatTeamId': 59,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 178,
         'wickets': 6,
         'overs': 19.2}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 176,
         'wickets': 6,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Tue, 26 Mar 2024',
    'match': [{'matchInfo': {'matchId': 89689,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '7th Match',
       'matchFormat': 'T20',
       'startDate': '1711461600000',
       'endDate': '1711461600000',
       'state': 'complete',
       'status': 'Chennai Super Kings won by 63 runs',
       'team1': {'teamId': 58,
        'teamName': 'CHENNAI SUPER KINGS',
        'teamSName': 'CSK',
        'imageId': 860038},
       'team2': {'teamId': 971,
        'teamName': 'GUJARAT TITANS',
        'teamSName': 'GT',
        'imageId': 860068},
       'venueInfo': {'ground': 'MA Chidambaram Stadium',
        'city': 'Chennai',
        'timezone': '+05:30'},
       'currBatTeamId': 58,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 206,
         'wickets': 6,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 143,
         'wickets': 8,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Wed, 27 Mar 2024',
    'match': [{'matchInfo': {'matchId': 89693,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '8th Match',
       'matchFormat': 'T20',
       'startDate': '1711548000000',
       'endDate': '1711548000000',
       'state': 'complete',
       'status': 'Sunrisers Hyderabad won by 31 runs',
       'team1': {'teamId': 255,
        'teamName': 'SUNRISERS HYDERABAD',
        'teamSName': 'SRH',
        'imageId': 860066},
       'team2': {'teamId': 62,
        'teamName': 'MUMBAI INDIANS',
        'teamSName': 'MI',
        'imageId': 860053},
       'venueInfo': {'ground': 'Rajiv Gandhi International Stadium',
        'city': 'Hyderabad',
        'timezone': '+05:30'},
       'currBatTeamId': 255,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 277,
         'wickets': 3,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 246,
         'wickets': 5,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Thu, 28 Mar 2024',
    'match': [{'matchInfo': {'matchId': 89700,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '9th Match',
       'matchFormat': 'T20',
       'startDate': '1711634400000',
       'endDate': '1711634400000',
       'state': 'complete',
       'status': 'Rajasthan Royals won by 12 runs',
       'team1': {'teamId': 64,
        'teamName': 'RAJASTHAN ROYALS',
        'teamSName': 'RR',
        'imageId': 860055},
       'team2': {'teamId': 61,
        'teamName': 'DELHI CAPITALS',
        'teamSName': 'DC',
        'imageId': 860040},
       'venueInfo': {'ground': 'Sawai Mansingh Stadium',
        'city': 'Jaipur',
        'timezone': '+05:30'},
       'currBatTeamId': 64,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 185,
         'wickets': 5,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 173,
         'wickets': 5,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Fri, 29 Mar 2024',
    'match': [{'matchInfo': {'matchId': 89703,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '10th Match',
       'matchFormat': 'T20',
       'startDate': '1711720800000',
       'endDate': '1711720800000',
       'state': 'complete',
       'status': 'Kolkata Knight Riders won by 7 wkts',
       'team1': {'teamId': 59,
        'teamName': 'ROYAL CHALLENGERS BENGALURU',
        'teamSName': 'RCB',
        'imageId': 860056},
       'team2': {'teamId': 63,
        'teamName': 'KOLKATA KNIGHT RIDERS',
        'teamSName': 'KKR',
        'imageId': 860046},
       'venueInfo': {'ground': 'M.Chinnaswamy Stadium',
        'city': 'Bengaluru',
        'timezone': '+05:30'},
       'currBatTeamId': 63,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 182,
         'wickets': 6,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 186,
         'wickets': 3,
         'overs': 16.5}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Sat, 30 Mar 2024',
    'match': [{'matchInfo': {'matchId': 89710,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '11th Match',
       'matchFormat': 'T20',
       'startDate': '1711807200000',
       'endDate': '1711807200000',
       'state': 'complete',
       'status': 'Lucknow Super Giants won by 21 runs',
       'team1': {'teamId': 966,
        'teamName': 'LUCKNOW SUPER GIANTS',
        'teamSName': 'LSG',
        'imageId': 882545},
       'team2': {'teamId': 65,
        'teamName': 'PUNJAB KINGS',
        'teamSName': 'PBKS',
        'imageId': 860084},
       'venueInfo': {'ground': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
        'city': 'Lucknow',
        'timezone': '+05:30'},
       'currBatTeamId': 966,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 199,
         'wickets': 8,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 178,
         'wickets': 5,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Sun, 31 Mar 2024',
    'match': [{'matchInfo': {'matchId': 89717,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '12th Match',
       'matchFormat': 'T20',
       'startDate': '1711879200000',
       'endDate': '1711879200000',
       'state': 'complete',
       'status': 'Gujarat Titans won by 7 wkts',
       'team1': {'teamId': 971,
        'teamName': 'GUJARAT TITANS',
        'teamSName': 'GT',
        'imageId': 860068},
       'team2': {'teamId': 255,
        'teamName': 'SUNRISERS HYDERABAD',
        'teamSName': 'SRH',
        'imageId': 860066},
       'venueInfo': {'ground': 'Narendra Modi Stadium',
        'city': 'Ahmedabad',
        'timezone': '+05:30'},
       'currBatTeamId': 971,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 168,
         'wickets': 3,
         'overs': 19.1}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 162,
         'wickets': 8,
         'overs': 20.0}}}},
     {'matchInfo': {'matchId': 89724,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '13th Match',
       'matchFormat': 'T20',
       'startDate': '1711893600000',
       'endDate': '1711893600000',
       'state': 'complete',
       'status': 'Delhi Capitals won by 20 runs',
       'team1': {'teamId': 61,
        'teamName': 'DELHI CAPITALS',
        'teamSName': 'DC',
        'imageId': 860040},
       'team2': {'teamId': 58,
        'teamName': 'CHENNAI SUPER KINGS',
        'teamSName': 'CSK',
        'imageId': 860038},
       'venueInfo': {'ground': 'ACA-VDCA Cricket Stadium',
        'city': 'Visakhapatnam',
        'timezone': '+05:30'},
       'currBatTeamId': 61,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 191,
         'wickets': 5,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 171,
         'wickets': 6,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Mon, 01 Apr 2024',
    'match': [{'matchInfo': {'matchId': 89731,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '14th Match',
       'matchFormat': 'T20',
       'startDate': '1711980000000',
       'endDate': '1711980000000',
       'state': 'complete',
       'status': 'Rajasthan Royals won by 6 wkts',
       'team1': {'teamId': 62,
        'teamName': 'MUMBAI INDIANS',
        'teamSName': 'MI',
        'imageId': 860053},
       'team2': {'teamId': 64,
        'teamName': 'RAJASTHAN ROYALS',
        'teamSName': 'RR',
        'imageId': 860055},
       'venueInfo': {'ground': 'Wankhede Stadium',
        'city': 'Mumbai',
        'timezone': '+05:30'},
       'currBatTeamId': 64,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 125,
         'wickets': 9,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 127,
         'wickets': 4,
         'overs': 15.3}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Tue, 02 Apr 2024',
    'match': [{'matchInfo': {'matchId': 89738,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '15th Match',
       'matchFormat': 'T20',
       'startDate': '1712066400000',
       'endDate': '1712066400000',
       'state': 'complete',
       'status': 'Lucknow Super Giants won by 28 runs',
       'team1': {'teamId': 59,
        'teamName': 'ROYAL CHALLENGERS BENGALURU',
        'teamSName': 'RCB',
        'imageId': 860056},
       'team2': {'teamId': 966,
        'teamName': 'LUCKNOW SUPER GIANTS',
        'teamSName': 'LSG',
        'imageId': 882545},
       'venueInfo': {'ground': 'M.Chinnaswamy Stadium',
        'city': 'Bengaluru',
        'timezone': '+05:30'},
       'currBatTeamId': 966,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 153,
         'wickets': 10,
         'overs': 19.4}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 181,
         'wickets': 5,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Wed, 03 Apr 2024',
    'match': [{'matchInfo': {'matchId': 89745,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '16th Match',
       'matchFormat': 'T20',
       'startDate': '1712152800000',
       'endDate': '1712152800000',
       'state': 'complete',
       'status': 'Kolkata Knight Riders won by 106 runs',
       'team1': {'teamId': 61,
        'teamName': 'DELHI CAPITALS',
        'teamSName': 'DC',
        'imageId': 860040},
       'team2': {'teamId': 63,
        'teamName': 'KOLKATA KNIGHT RIDERS',
        'teamSName': 'KKR',
        'imageId': 860046},
       'venueInfo': {'ground': 'ACA-VDCA Cricket Stadium',
        'city': 'Visakhapatnam',
        'timezone': '+05:30'},
       'currBatTeamId': 63,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 166,
         'wickets': 10,
         'overs': 17.2}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 272,
         'wickets': 7,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Thu, 04 Apr 2024',
    'match': [{'matchInfo': {'matchId': 89749,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '17th Match',
       'matchFormat': 'T20',
       'startDate': '1712239200000',
       'endDate': '1712239200000',
       'state': 'complete',
       'status': 'Punjab Kings won by 3 wkts',
       'team1': {'teamId': 971,
        'teamName': 'GUJARAT TITANS',
        'teamSName': 'GT',
        'imageId': 860068},
       'team2': {'teamId': 65,
        'teamName': 'PUNJAB KINGS',
        'teamSName': 'PBKS',
        'imageId': 860084},
       'venueInfo': {'ground': 'Narendra Modi Stadium',
        'city': 'Ahmedabad',
        'timezone': '+05:30'},
       'currBatTeamId': 65,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 1,
         'runs': 199,
         'wickets': 4,
         'overs': 20.0}},
       'team2Score': {'inngs1': {'inningsId': 2,
         'runs': 200,
         'wickets': 7,
         'overs': 19.5}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Fri, 05 Apr 2024',
    'match': [{'matchInfo': {'matchId': 89752,
       'seriesId': 7607,
       'seriesName': 'Indian Premier League 2024',
       'matchDesc': '18th Match',
       'matchFormat': 'T20',
       'startDate': '1712325600000',
       'endDate': '1712325600000',
       'state': 'complete',
       'status': 'Sunrisers Hyderabad won by 6 wkts',
       'team1': {'teamId': 255,
        'teamName': 'SUNRISERS HYDERABAD',
        'teamSName': 'SRH',
        'imageId': 860066},
       'team2': {'teamId': 58,
        'teamName': 'CHENNAI SUPER KINGS',
        'teamSName': 'CSK',
        'imageId': 860038},
       'venueInfo': {'ground': 'Rajiv Gandhi International Stadium',
        'city': 'Hyderabad',
        'timezone': '+05:30'},
       'currBatTeamId': 255,
       'isTimeAnnounced': True},
      'matchScore': {'team1Score': {'inngs1': {'inningsId': 2,
         'runs': 166,
         'wickets': 4,
         'overs': 18.1}},
       'team2Score': {'inngs1': {'inningsId': 1,
         'runs': 165,
         'wickets': 5,
         'overs': 20.0}}}}],
    'seriesId': 7607}},
  {'matchDetailsMap': {'key': 'Sat, 06 Apr 2024',
    'match': [{'matchInfo': {'matchId': 89756,
       'seriesId': 7607,

In [25]:
from datetime import datetime

Match_Results = []
for matches in results_data['matchDetails']:
    if not matches.get('matchDetailsMap'):
        continue
    #match_date=(i['matchDetailsMap']['key'])
    for match1 in matches['matchDetailsMap']['match']:
        raw_ts = match1['matchInfo']['startDate']
        #print("Raw Timestamp:", raw_ts)

        start_date = datetime.fromtimestamp(int(match1['matchInfo']['startDate']) / 1000).strftime('%Y-%m-%d')

        
        MatchDetails = { 
            "MatchDesc" : match1['matchInfo']['matchDesc'],
            "Team1" : match1['matchInfo']['team1']['teamName'],
            "Team2" : match1['matchInfo']['team2']['teamName'],
            "Winning Team" : match1['matchInfo']['status'],
            "Venue" : match1['matchInfo']['venueInfo']['ground'],
            "StartDate" : start_date
        }
        Match_Results.append(MatchDetails)
Match_Results

[{'MatchDesc': '1st Match',
  'Team1': 'CHENNAI SUPER KINGS',
  'Team2': 'ROYAL CHALLENGERS BENGALURU',
  'Winning Team': 'Chennai Super Kings won by 6 wkts',
  'Venue': 'MA Chidambaram Stadium',
  'StartDate': '2024-03-22'},
 {'MatchDesc': '2nd Match',
  'Team1': 'PUNJAB KINGS',
  'Team2': 'DELHI CAPITALS',
  'Winning Team': 'Punjab Kings won by 4 wkts',
  'Venue': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
  'StartDate': '2024-03-23'},
 {'MatchDesc': '3rd Match',
  'Team1': 'KOLKATA KNIGHT RIDERS',
  'Team2': 'SUNRISERS HYDERABAD',
  'Winning Team': 'Kolkata Knight Riders won by 4 runs',
  'Venue': 'Eden Gardens',
  'StartDate': '2024-03-23'},
 {'MatchDesc': '4th Match',
  'Team1': 'RAJASTHAN ROYALS',
  'Team2': 'LUCKNOW SUPER GIANTS',
  'Winning Team': 'Rajasthan Royals won by 20 runs',
  'Venue': 'Sawai Mansingh Stadium',
  'StartDate': '2024-03-24'},
 {'MatchDesc': '5th Match',
  'Team1': 'GUJARAT TITANS',
  'Team2': 'MUMBAI INDIANS',
  'Winning Team': 'Gujarat Titans won by 6 runs',
  'Venue': 'Narendra Modi Stadium',
  'StartDate': '2024-03-24'},
 {'MatchDesc': '6th Match',
  'Team1': 'ROYAL CHALLENGERS BENGALURU',
  'Team2': 'PUNJAB KINGS',
  'Winning Team': 'Royal Challengers Bengaluru won by 4 wkts',
  'Venue': 'M.Chinnaswamy Stadium',
  'StartDate': '2024-03-25'},
 {'MatchDesc': '7th Match',
  'Team1': 'CHENNAI SUPER KINGS',
  'Team2': 'GUJARAT TITANS',
  'Winning Team': 'Chennai Super Kings won by 63 runs',
  'Venue': 'MA Chidambaram Stadium',
  'StartDate': '2024-03-26'},
 {'MatchDesc': '8th Match',
  'Team1': 'SUNRISERS HYDERABAD',
  'Team2': 'MUMBAI INDIANS',
  'Winning Team': 'Sunrisers Hyderabad won by 31 runs',
  'Venue': 'Rajiv Gandhi International Stadium',
  'StartDate': '2024-03-27'},
 {'MatchDesc': '9th Match',
  'Team1': 'RAJASTHAN ROYALS',
  'Team2': 'DELHI CAPITALS',
  'Winning Team': 'Rajasthan Royals won by 12 runs',
  'Venue': 'Sawai Mansingh Stadium',
  'StartDate': '2024-03-28'},
 {'MatchDesc': '10th Match',
  'Team1': 'ROYAL CHALLENGERS BENGALURU',
  'Team2': 'KOLKATA KNIGHT RIDERS',
  'Winning Team': 'Kolkata Knight Riders won by 7 wkts',
  'Venue': 'M.Chinnaswamy Stadium',
  'StartDate': '2024-03-29'},
 {'MatchDesc': '11th Match',
  'Team1': 'LUCKNOW SUPER GIANTS',
  'Team2': 'PUNJAB KINGS',
  'Winning Team': 'Lucknow Super Giants won by 21 runs',
  'Venue': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
  'StartDate': '2024-03-30'},
 {'MatchDesc': '12th Match',
  'Team1': 'GUJARAT TITANS',
  'Team2': 'SUNRISERS HYDERABAD',
  'Winning Team': 'Gujarat Titans won by 7 wkts',
  'Venue': 'Narendra Modi Stadium',
  'StartDate': '2024-03-31'},
 {'MatchDesc': '13th Match',
  'Team1': 'DELHI CAPITALS',
  'Team2': 'CHENNAI SUPER KINGS',
  'Winning Team': 'Delhi Capitals won by 20 runs',
  'Venue': 'ACA-VDCA Cricket Stadium',
  'StartDate': '2024-03-31'},
 {'MatchDesc': '14th Match',
  'Team1': 'MUMBAI INDIANS',
  'Team2': 'RAJASTHAN ROYALS',
  'Winning Team': 'Rajasthan Royals won by 6 wkts',
  'Venue': 'Wankhede Stadium',
  'StartDate': '2024-04-01'},
 {'MatchDesc': '15th Match',
  'Team1': 'ROYAL CHALLENGERS BENGALURU',
  'Team2': 'LUCKNOW SUPER GIANTS',
  'Winning Team': 'Lucknow Super Giants won by 28 runs',
  'Venue': 'M.Chinnaswamy Stadium',
  'StartDate': '2024-04-02'},
 {'MatchDesc': '16th Match',
  'Team1': 'DELHI CAPITALS',
  'Team2': 'KOLKATA KNIGHT RIDERS',
  'Winning Team': 'Kolkata Knight Riders won by 106 runs',
  'Venue': 'ACA-VDCA Cricket Stadium',
  'StartDate': '2024-04-03'},
 {'MatchDesc': '17th Match',
  'Team1': 'GUJARAT TITANS',
  'Team2': 'PUNJAB KINGS',
  'Winning Team': 'Punjab Kings won by 3 wkts',
  'Venue': 'Narendra Modi Stadium',
  'StartDate': '2024-04-04'},
 {'MatchDesc': '18th Match',
  'Team1': 'SUNRISERS HYDERABAD',
  'Team2': 'CHENNAI SUPER KINGS',
  'Winning Team': 'Sunrisers Hyderabad won by 6 wkts',
  'Venue': 'Rajiv Gandhi International Stadium',
  'StartDate': '2024-04-05'},
 {'MatchDesc': '19th Match',
  'Team1': 'RAJASTHAN ROYALS',
  'Team2': 'ROYAL CHALLENGERS BENGALURU',
  'Winning Team': 'Rajasthan Royals won by 6 wkts',
  'Venue': 'Sawai Mansingh Stadium',
  'StartDate': '2024-04-06'},
 {'MatchDesc': '20th Match',
  'Team1': 'MUMBAI INDIANS',
  'Team2': 'DELHI CAPITALS',
  'Winning Team': 'Mumbai Indians won by 29 runs',
  'Venue': 'Wankhede Stadium',
  'StartDate': '2024-04-07'},
 {'MatchDesc': '21st Match',
  'Team1': 'LUCKNOW SUPER GIANTS',
  'Team2': 'GUJARAT TITANS',
  'Winning Team': 'Lucknow Super Giants won by 33 runs',
  'Venue': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
  'StartDate': '2024-04-07'},
 {'MatchDesc': '22nd Match',
  'Team1': 'CHENNAI SUPER KINGS',
  'Team2': 'KOLKATA KNIGHT RIDERS',
  'Winning Team': 'Chennai Super Kings won by 7 wkts',
  'Venue': 'MA Chidambaram Stadium',
  'StartDate': '2024-04-08'},
 {'MatchDesc': '23rd Match',
  'Team1': 'PUNJAB KINGS',
  'Team2': 'SUNRISERS HYDERABAD',
  'Winning Team': 'Sunrisers Hyderabad won by 2 runs',
  'Venue': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
  'StartDate': '2024-04-09'},
 {'MatchDesc': '24th Match',
  'Team1': 'RAJASTHAN ROYALS',
  'Team2': 'GUJARAT TITANS',
  'Winning Team': 'Gujarat Titans won by 3 wkts',
  'Venue': 'Sawai Mansingh Stadium',
  'StartDate': '2024-04-10'},
 {'MatchDesc': '25th Match',
  'Team1': 'MUMBAI INDIANS',
  'Team2': 'ROYAL CHALLENGERS BENGALURU',
  'Winning Team': 'Mumbai Indians won by 7 wkts',
  'Venue': 'Wankhede Stadium',
  'StartDate': '2024-04-11'},
 {'MatchDesc': '26th Match',
  'Team1': 'LUCKNOW SUPER GIANTS',
  'Team2': 'DELHI CAPITALS',
  'Winning Team': 'Delhi Capitals won by 6 wkts',
  'Venue': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
  'StartDate': '2024-04-12'},
 {'MatchDesc': '27th Match',
  'Team1': 'PUNJAB KINGS',
  'Team2': 'RAJASTHAN ROYALS',
  'Winning Team': 'Rajasthan Royals won by 3 wkts',
  'Venue': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
  'StartDate': '2024-04-13'},
 {'MatchDesc': '28th Match',
  'Team1': 'KOLKATA KNIGHT RIDERS',
  'Team2': 'LUCKNOW SUPER GIANTS',
  'Winning Team': 'Kolkata Knight Riders won by 8 wkts',
  'Venue': 'Eden Gardens',
  'StartDate': '2024-04-14'},
 {'MatchDesc': '29th Match',
  'Team1': 'MUMBAI INDIANS',
  'Team2': 'CHENNAI SUPER KINGS',
  'Winning Team': 'Chennai Super Kings won by 20 runs',
  'Venue': 'Wankhede Stadium',
  'StartDate': '2024-04-14'},
 {'MatchDesc': '30th Match',
  'Team1': 'ROYAL CHALLENGERS BENGALURU',
  'Team2': 'SUNRISERS HYDERABAD',
  'Winning Team': 'Sunrisers Hyderabad won by 25 runs',
  'Venue': 'M.Chinnaswamy Stadium',
  'StartDate': '2024-04-15'},
 {'MatchDesc': '31st Match',
  'Team1': 'KOLKATA KNIGHT RIDERS',
  'Team2': 'RAJASTHAN ROYALS',
  'Winning Team': 'Rajasthan Royals won by 2 wkts',
  'Venue': 'Eden Gardens',
  'StartDate': '2024-04-16'},
 {'MatchDesc': '32nd Match',
  'Team1': 'GUJARAT TITANS',
  'Team2': 'DELHI CAPITALS',
  'Winning Team': 'Delhi Capitals won by 6 wkts',
  'Venue': 'Narendra Modi Stadium',
  'StartDate': '2024-04-17'},
 {'MatchDesc': '33rd Match',
  'Team1': 'PUNJAB KINGS',
  'Team2': 'MUMBAI INDIANS',
  'Winning Team': 'Mumbai Indians won by 9 runs',
  'Venue': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
  'StartDate': '2024-04-18'},
 {'MatchDesc': '34th Match',
  'Team1': 'LUCKNOW SUPER GIANTS',
  'Team2': 'CHENNAI SUPER KINGS',
  'Winning Team': 'Lucknow Super Giants won by 8 wkts',
  'Venue': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
  'StartDate': '2024-04-19'},
 {'MatchDesc': '35th Match',
  'Team1': 'DELHI CAPITALS',
  'Team2': 'SUNRISERS HYDERABAD',
  'Winning Team': 'Sunrisers Hyderabad won by 67 runs',
  'Venue': 'Arun Jaitley Stadium',
  'StartDate': '2024-04-20'},
 {'MatchDesc': '36th Match',
  'Team1': 'KOLKATA KNIGHT RIDERS',
  'Team2': 'ROYAL CHALLENGERS BENGALURU',
  'Winning Team': 'Kolkata Knight Riders won by 1 run',
  'Venue': 'Eden Gardens',
  'StartDate': '2024-04-21'},
 {'MatchDesc': '37th Match',
  'Team1': 'PUNJAB KINGS',
  'Team2': 'GUJARAT TITANS',
  'Winning Team': 'Gujarat Titans won by 3 wkts',
  'Venue': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur',
  'StartDate': '2024-04-21'},
 {'MatchDesc': '38th Match',
  'Team1': 'RAJASTHAN ROYALS',
  'Team2': 'MUMBAI INDIANS',
  'Winning Team': 'Rajasthan Royals won by 9 wkts',
  'Venue': 'Sawai Mansingh Stadium',
  'StartDate': '2024-04-22'},
 {'MatchDesc': '39th Match',
  'Team1': 'CHENNAI SUPER KINGS',
  'Team2': 'LUCKNOW SUPER GIANTS',
  'Winning Team': 'Lucknow Super Giants won by 6 wkts',
  'Venue': 'MA Chidambaram Stadium',
  'StartDate': '2024-04-23'},
 {'MatchDesc': '40th Match',
  'Team1': 'DELHI CAPITALS',
  'Team2': 'GUJARAT TITANS',
  'Winning Team': 'Delhi Capitals won by 4 runs',
  'Venue': 'Arun Jaitley Stadium',
  'StartDate': '2024-04-24'},
 {'MatchDesc': '41st Match',
  'Team1': 'SUNRISERS HYDERABAD',
  'Team2': 'ROYAL CHALLENGERS BENGALURU',
  'Winning Team': 'Royal Challengers Bengaluru won by 35 runs',
  'Venue': 'Rajiv Gandhi International Stadium',
  'StartDate': '2024-04-25'},
 {'MatchDesc': '42nd Match',
  'Team1': 'KOLKATA KNIGHT RIDERS',
  'Team2': 'PUNJAB KINGS',
  'Winning Team': 'Punjab Kings won by 8 wkts',
  'Venue': 'Eden Gardens',
  'StartDate': '2024-04-26'},
 {'MatchDesc': '43rd Match',
  'Team1': 'DELHI CAPITALS',
  'Team2': 'MUMBAI INDIANS',
  'Winning Team': 'Delhi Capitals won by 10 runs',
  'Venue': 'Arun Jaitley Stadium',
  'StartDate': '2024-04-27'},
 {'MatchDesc': '44th Match',
  'Team1': 'LUCKNOW SUPER GIANTS',
  'Team2': 'RAJASTHAN ROYALS',
  'Winning Team': 'Rajasthan Royals won by 7 wkts',
  'Venue': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
  'StartDate': '2024-04-27'},
 {'MatchDesc': '45th Match',
  'Team1': 'GUJARAT TITANS',
  'Team2': 'ROYAL CHALLENGERS BENGALURU',
  'Winning Team': 'Royal Challengers Bengaluru won by 9 wkts',
  'Venue': 'Narendra Modi Stadium',
  'StartDate': '2024-04-28'},
 {'MatchDesc': '46th Match',
  'Team1': 'CHENNAI SUPER KINGS',
  'Team2': 'SUNRISERS HYDERABAD',
  'Winning Team': 'Chennai Super Kings won by 78 runs',
  'Venue': 'MA Chidambaram Stadium',
  'StartDate': '2024-04-28'},
 {'MatchDesc': '47th Match',
  'Team1': 'KOLKATA KNIGHT RIDERS',
  'Team2': 'DELHI CAPITALS',
  'Winning Team': 'Kolkata Knight Riders won by 7 wkts',
  'Venue': 'Eden Gardens',
  'StartDate': '2024-04-29'},
 {'MatchDesc': '48th Match',
  'Team1': 'LUCKNOW SUPER GIANTS',
  'Team2': 'MUMBAI INDIANS',
  'Winning Team': 'Lucknow Super Giants won by 4 wkts',
  'Venue': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
  'StartDate': '2024-04-30'},
 {'MatchDesc': '49th Match',
  'Team1': 'CHENNAI SUPER KINGS',
  'Team2': 'PUNJAB KINGS',
  'Winning Team': 'Punjab Kings won by 7 wkts',
  'Venue': 'MA Chidambaram Stadium',
  'StartDate': '2024-05-01'},
 {'MatchDesc': '50th Match',
  'Team1': 'SUNRISERS HYDERABAD',
  'Team2': 'RAJASTHAN ROYALS',
  'Winning Team': 'Sunrisers Hyderabad won by 1 run',
  'Venue': 'Rajiv Gandhi International Stadium',
  'StartDate': '2024-05-02'},
 {'MatchDesc': '51st Match',
  'Team1': 'MUMBAI INDIANS',
  'Team2': 'KOLKATA KNIGHT RIDERS',
  'Winning Team': 'Kolkata Knight Riders won by 24 runs',
  'Venue': 'Wankhede Stadium',
  'StartDate': '2024-05-03'},
 {'MatchDesc': '52nd Match',
  'Team1': 'ROYAL CHALLENGERS BENGALURU',
  'Team2': 'GUJARAT TITANS',
  'Winning Team': 'Royal Challengers Bengaluru won by 4 wkts',
  'Venue': 'M.Chinnaswamy Stadium',
  'StartDate': '2024-05-04'},
 {'MatchDesc': '53rd Match',
  'Team1': 'PUNJAB KINGS',
  'Team2': 'CHENNAI SUPER KINGS',
  'Winning Team': 'Chennai Super Kings won by 28 runs',
  'Venue': 'Himachal Pradesh Cricket Association Stadium',
  'StartDate': '2024-05-05'},
 {'MatchDesc': '54th Match',
  'Team1': 'LUCKNOW SUPER GIANTS',
  'Team2': 'KOLKATA KNIGHT RIDERS',
  'Winning Team': 'Kolkata Knight Riders won by 98 runs',
  'Venue': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
  'StartDate': '2024-05-05'},
 {'MatchDesc': '55th Match',
  'Team1': 'MUMBAI INDIANS',
  'Team2': 'SUNRISERS HYDERABAD',
  'Winning Team': 'Mumbai Indians won by 7 wkts',
  'Venue': 'Wankhede Stadium',
  'StartDate': '2024-05-06'},
 {'MatchDesc': '56th Match',
  'Team1': 'DELHI CAPITALS',
  'Team2': 'RAJASTHAN ROYALS',
  'Winning Team': 'Delhi Capitals won by 20 runs',
  'Venue': 'Arun Jaitley Stadium',
  'StartDate': '2024-05-07'},
 {'MatchDesc': '57th Match',
  'Team1': 'SUNRISERS HYDERABAD',
  'Team2': 'LUCKNOW SUPER GIANTS',
  'Winning Team': 'Sunrisers Hyderabad won by 10 wkts',
  'Venue': 'Rajiv Gandhi International Stadium',
  'StartDate': '2024-05-08'},
 {'MatchDesc': '58th Match',
  'Team1': 'PUNJAB KINGS',
  'Team2': 'ROYAL CHALLENGERS BENGALURU',
  'Winning Team': 'Royal Challengers Bengaluru won by 60 runs',
  'Venue': 'Himachal Pradesh Cricket Association Stadium',
  'StartDate': '2024-05-09'},
 {'MatchDesc': '59th Match',
  'Team1': 'GUJARAT TITANS',
  'Team2': 'CHENNAI SUPER KINGS',
  'Winning Team': 'Gujarat Titans won by 35 runs',
  'Venue': 'Narendra Modi Stadium',
  'StartDate': '2024-05-10'},
 {'MatchDesc': '60th Match',
  'Team1': 'KOLKATA KNIGHT RIDERS',
  'Team2': 'MUMBAI INDIANS',
  'Winning Team': 'Kolkata Knight Riders won by 18 runs - 16 overs game - due to rain',
  'Venue': 'Eden Gardens',
  'StartDate': '2024-05-11'},
 {'MatchDesc': '61st Match',
  'Team1': 'CHENNAI SUPER KINGS',
  'Team2': 'RAJASTHAN ROYALS',
  'Winning Team': 'Chennai Super Kings won by 5 wkts',
  'Venue': 'MA Chidambaram Stadium',
  'StartDate': '2024-05-12'},
 {'MatchDesc': '62nd Match',
  'Team1': 'ROYAL CHALLENGERS BENGALURU',
  'Team2': 'DELHI CAPITALS',
  'Winning Team': 'Royal Challengers Bengaluru won by 47 runs',
  'Venue': 'M.Chinnaswamy Stadium',
  'StartDate': '2024-05-12'},
 {'MatchDesc': '63rd Match',
  'Team1': 'GUJARAT TITANS',
  'Team2': 'KOLKATA KNIGHT RIDERS',
  'Winning Team': 'Match abandoned without toss',
  'Venue': 'Narendra Modi Stadium',
  'StartDate': '2024-05-13'},
 {'MatchDesc': '64th Match',
  'Team1': 'DELHI CAPITALS',
  'Team2': 'LUCKNOW SUPER GIANTS',
  'Winning Team': 'Delhi Capitals won by 19 runs',
  'Venue': 'Arun Jaitley Stadium',
  'StartDate': '2024-05-14'},
 {'MatchDesc': '65th Match',
  'Team1': 'RAJASTHAN ROYALS',
  'Team2': 'PUNJAB KINGS',
  'Winning Team': 'Punjab Kings won by 5 wkts',
  'Venue': 'Barsapara Cricket Stadium',
  'StartDate': '2024-05-15'},
 {'MatchDesc': '66th Match',
  'Team1': 'SUNRISERS HYDERABAD',
  'Team2': 'GUJARAT TITANS',
  'Winning Team': 'Match abandoned without toss',
  'Venue': 'Rajiv Gandhi International Stadium',
  'StartDate': '2024-05-16'},
 {'MatchDesc': '67th Match',
  'Team1': 'MUMBAI INDIANS',
  'Team2': 'LUCKNOW SUPER GIANTS',
  'Winning Team': 'Lucknow Super Giants won by 18 runs',
  'Venue': 'Wankhede Stadium',
  'StartDate': '2024-05-17'},
 {'MatchDesc': '68th Match',
  'Team1': 'ROYAL CHALLENGERS BENGALURU',
  'Team2': 'CHENNAI SUPER KINGS',
  'Winning Team': 'Royal Challengers Bengaluru won by 27 runs',
  'Venue': 'M.Chinnaswamy Stadium',
  'StartDate': '2024-05-18'},
 {'MatchDesc': '69th Match',
  'Team1': 'SUNRISERS HYDERABAD',
  'Team2': 'PUNJAB KINGS',
  'Winning Team': 'Sunrisers Hyderabad won by 4 wkts',
  'Venue': 'Rajiv Gandhi International Stadium',
  'StartDate': '2024-05-19'},
 {'MatchDesc': '70th Match',
  'Team1': 'RAJASTHAN ROYALS',
  'Team2': 'KOLKATA KNIGHT RIDERS',
  'Winning Team': 'Match abandoned due to rain (with toss)',
  'Venue': 'Barsapara Cricket Stadium',
  'StartDate': '2024-05-19'},
 {'MatchDesc': 'Qualifier 1',
  'Team1': 'KOLKATA KNIGHT RIDERS',
  'Team2': 'SUNRISERS HYDERABAD',
  'Winning Team': 'Kolkata Knight Riders won by 8 wkts',
  'Venue': 'Narendra Modi Stadium',
  'StartDate': '2024-05-21'},
 {'MatchDesc': 'Eliminator',
  'Team1': 'RAJASTHAN ROYALS',
  'Team2': 'ROYAL CHALLENGERS BENGALURU',
  'Winning Team': 'Rajasthan Royals won by 4 wkts',
  'Venue': 'Narendra Modi Stadium',
  'StartDate': '2024-05-22'},
 {'MatchDesc': 'Qualifier 2',
  'Team1': 'SUNRISERS HYDERABAD',
  'Team2': 'RAJASTHAN ROYALS',
  'Winning Team': 'Sunrisers Hyderabad won by 36 runs',
  'Venue': 'MA Chidambaram Stadium',
  'StartDate': '2024-05-24'},
 {'MatchDesc': 'Final',
  'Team1': 'KOLKATA KNIGHT RIDERS',
  'Team2': 'SUNRISERS HYDERABAD',
  'Winning Team': 'Kolkata Knight Riders won by 8 wkts',
  'Venue': 'MA Chidambaram Stadium',
  'StartDate': '2024-05-26'}]

In [27]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

Last_20_Matches = pd.DataFrame(Match_Results)
table_name = "last_20_matches_table"  

engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


Last_20_Matches.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz last_20_matches_table

Q11.Compare each player's performance across different cricket formats. For players who have played at least 2 different formats, show their total runs in Test cricket, ODI cricket, and T20I cricket, along with their overall batting average across all formats.

In [5]:
indian_players_data = {'player': [{'name': 'BATSMEN', 'imageId': 174146},
  {'id': '11808',
   'name': 'Shubman Gill',
   'imageId': 616515,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '13940',
   'name': 'Yashasvi Jaiswal',
   'imageId': 591942,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '13866',
   'name': 'Sai Sudharsan',
   'imageId': 717782,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '576',
   'name': 'Rohit Sharma',
   'imageId': 616514,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '1413',
   'name': 'Virat Kohli',
   'imageId': 616517,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm medium'},
  {'id': '7915',
   'name': 'Suryakumar Yadav',
   'imageId': 352481,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '9428',
   'name': 'Shreyas Iyer',
   'imageId': 616518,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '10896',
   'name': 'Rinku Singh',
   'imageId': 279125,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '14504',
   'name': 'Tilak Varma',
   'imageId': 226525,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '11813',
   'name': 'Ruturaj Gaikwad',
   'imageId': 781069,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '10636',
   'name': 'Rajat Patidar',
   'imageId': 760758,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '9429',
   'name': 'Sarfaraz Khan',
   'imageId': 591955,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '9716',
   'name': 'Abhimanyu Easwaran',
   'imageId': 591956,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '8257',
   'name': 'Karun Nair',
   'imageId': 717781,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'name': 'ALL ROUNDER', 'imageId': 174146},
  {'id': '14701',
   'name': 'Nitish Kumar Reddy',
   'imageId': 591947,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '9647',
   'name': 'Hardik Pandya',
   'imageId': 616519,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '11195',
   'name': 'Shivam Dube',
   'imageId': 593805,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm medium'},
  {'id': '12086',
   'name': 'Abhishek Sharma',
   'imageId': 153963,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm orthodox'},
  {'id': '587',
   'name': 'Ravindra Jadeja',
   'imageId': 616520,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm orthodox'},
  {'id': '8683',
   'name': 'Shardul Thakur',
   'imageId': 352487,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '10945',
   'name': 'Washington Sundar',
   'imageId': 616522,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Right-arm offbreak'},
  {'id': '8808',
   'name': 'Axar Patel',
   'imageId': 616521,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm orthodox'},
  {'name': 'WICKET KEEPER', 'imageId': 174146},
  {'id': '10744',
   'name': 'Rishabh Pant',
   'imageId': 616524,
   'battingStyle': 'Left-hand bat'},
  {'id': '8733',
   'name': 'KL Rahul',
   'imageId': 616523,
   'battingStyle': 'Right-hand bat'},
  {'id': '14691',
   'name': 'Dhruv Jurel',
   'imageId': 591954,
   'battingStyle': 'Right-hand bat'},
  {'id': '8271',
   'name': 'Sanju Samson',
   'imageId': 226289,
   'battingStyle': 'Right-hand bat'},
  {'id': '10276',
   'name': 'Ishan Kishan',
   'imageId': 352492,
   'battingStyle': 'Left-hand bat'},
  {'name': 'BOWLER', 'imageId': 174146},
  {'id': '10808',
   'name': 'Mohammed Siraj',
   'imageId': 591952,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast'},
  {'id': '9311',
   'name': 'Jasprit Bumrah',
   'imageId': 591949,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast'},
  {'id': '10551',
   'name': 'Prasidh Krishna',
   'imageId': 591958,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast'},
  {'id': '14726',
   'name': 'Akash Deep',
   'imageId': 591951,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '8292',
   'name': 'Kuldeep Yadav',
   'imageId': 616525,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm wrist-spin'},
  {'id': '13217',
   'name': 'Arshdeep Singh',
   'imageId': 616527,
   'battingStyle': 'Left-hand bat',
   'bowlingStyle': 'Left-arm fast-medium'},
  {'id': '24729',
   'name': 'Harshit Rana',
   'imageId': 616529,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '14659',
   'name': 'Ravi Bishnoi',
   'imageId': 226280,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'},
  {'id': '10754',
   'name': 'Mukesh Kumar',
   'imageId': 333872,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm fast-medium'},
  {'id': '12926',
   'name': 'Varun Chakaravarthy',
   'imageId': 616528,
   'battingStyle': 'Right-hand bat',
   'bowlingStyle': 'Right-arm legbreak'}]}

In [6]:

indian_players_id_list = []


for item in indian_players_data['player']:

    
    if 'id' not in item: 
        continue

    player_details = {
        "playerId" : item.get('id'),
        "playerName": item.get('name')
    }
    indian_players_id_list.append(player_details)
    
indian_players_id_list

[{'playerId': '11808', 'playerName': 'Shubman Gill'},
 {'playerId': '13940', 'playerName': 'Yashasvi Jaiswal'},
 {'playerId': '13866', 'playerName': 'Sai Sudharsan'},
 {'playerId': '576', 'playerName': 'Rohit Sharma'},
 {'playerId': '1413', 'playerName': 'Virat Kohli'},
 {'playerId': '7915', 'playerName': 'Suryakumar Yadav'},
 {'playerId': '9428', 'playerName': 'Shreyas Iyer'},
 {'playerId': '10896', 'playerName': 'Rinku Singh'},
 {'playerId': '14504', 'playerName': 'Tilak Varma'},
 {'playerId': '11813', 'playerName': 'Ruturaj Gaikwad'},
 {'playerId': '10636', 'playerName': 'Rajat Patidar'},
 {'playerId': '9429', 'playerName': 'Sarfaraz Khan'},
 {'playerId': '9716', 'playerName': 'Abhimanyu Easwaran'},
 {'playerId': '8257', 'playerName': 'Karun Nair'},
 {'playerId': '14701', 'playerName': 'Nitish Kumar Reddy'},
 {'playerId': '9647', 'playerName': 'Hardik Pandya'},
 {'playerId': '11195', 'playerName': 'Shivam Dube'},
 {'playerId': '12086', 'playerName': 'Abhishek Sharma'},
 {'playerId': '587', 'playerName': 'Ravindra Jadeja'},
 {'playerId': '8683', 'playerName': 'Shardul Thakur'},
 {'playerId': '10945', 'playerName': 'Washington Sundar'},
 {'playerId': '8808', 'playerName': 'Axar Patel'},
 {'playerId': '10744', 'playerName': 'Rishabh Pant'},
 {'playerId': '8733', 'playerName': 'KL Rahul'},
 {'playerId': '14691', 'playerName': 'Dhruv Jurel'},
 {'playerId': '8271', 'playerName': 'Sanju Samson'},
 {'playerId': '10276', 'playerName': 'Ishan Kishan'},
 {'playerId': '10808', 'playerName': 'Mohammed Siraj'},
 {'playerId': '9311', 'playerName': 'Jasprit Bumrah'},
 {'playerId': '10551', 'playerName': 'Prasidh Krishna'},
 {'playerId': '14726', 'playerName': 'Akash Deep'},
 {'playerId': '8292', 'playerName': 'Kuldeep Yadav'},
 {'playerId': '13217', 'playerName': 'Arshdeep Singh'},
 {'playerId': '24729', 'playerName': 'Harshit Rana'},
 {'playerId': '14659', 'playerName': 'Ravi Bishnoi'},
 {'playerId': '10754', 'playerName': 'Mukesh Kumar'},
 {'playerId': '12926', 'playerName': 'Varun Chakaravarthy'}]

In [11]:
import requests
import pandas as pd
import time

batting_stats_data=[]
indian_players_id_list=[{'playerId': '11808', 'playerName': 'Shubman Gill'},
 {'playerId': '13940', 'playerName': 'Yashasvi Jaiswal'},
 {'playerId': '13866', 'playerName': 'Sai Sudharsan'},
 {'playerId': '576', 'playerName': 'Rohit Sharma'},
 {'playerId': '1413', 'playerName': 'Virat Kohli'},
 {'playerId': '7915', 'playerName': 'Suryakumar Yadav'},
 {'playerId': '9428', 'playerName': 'Shreyas Iyer'},
 {'playerId': '10896', 'playerName': 'Rinku Singh'},
 {'playerId': '14504', 'playerName': 'Tilak Varma'},
 {'playerId': '11813', 'playerName': 'Ruturaj Gaikwad'},
 {'playerId': '10636', 'playerName': 'Rajat Patidar'},
 {'playerId': '9429', 'playerName': 'Sarfaraz Khan'},
 {'playerId': '9716', 'playerName': 'Abhimanyu Easwaran'},
 {'playerId': '8257', 'playerName': 'Karun Nair'},
 {'playerId': '14701', 'playerName': 'Nitish Kumar Reddy'},
 {'playerId': '9647', 'playerName': 'Hardik Pandya'},
 {'playerId': '11195', 'playerName': 'Shivam Dube'},
 {'playerId': '12086', 'playerName': 'Abhishek Sharma'},
 {'playerId': '587', 'playerName': 'Ravindra Jadeja'},
 {'playerId': '8683', 'playerName': 'Shardul Thakur'},
 {'playerId': '10945', 'playerName': 'Washington Sundar'},
 {'playerId': '8808', 'playerName': 'Axar Patel'},
 {'playerId': '10744', 'playerName': 'Rishabh Pant'},
 {'playerId': '8733', 'playerName': 'KL Rahul'},
 {'playerId': '14691', 'playerName': 'Dhruv Jurel'},
 {'playerId': '8271', 'playerName': 'Sanju Samson'},
 {'playerId': '10276', 'playerName': 'Ishan Kishan'},
 {'playerId': '10808', 'playerName': 'Mohammed Siraj'},
 {'playerId': '9311', 'playerName': 'Jasprit Bumrah'},
 {'playerId': '10551', 'playerName': 'Prasidh Krishna'},
 {'playerId': '14726', 'playerName': 'Akash Deep'}]

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}



batting_stats_data = []
 
for player in indian_players_id_list:
	player_id = player['playerId']
	player_name = player['playerName']
 
	url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{player_id}/batting"
	response = requests.get(url, headers=headers)
 
	
	if response.status_code != 200 or not response.text.strip():
		print(f"Skipping {player_name}: HTTP {response.status_code} - {response.text[:100]}")
		time.sleep(1)
		continue
 
	data = response.json()
 
	row = {"playerId": player_id, "playerName": player_name}
	formats = data["headers"][1:]  # e.g. Test, ODI, T20, IPL
 
	for entry in data["values"]:
		stat_name = entry["values"][0]
		stat_values = entry["values"][1:]
		for fmt, val in zip(formats, stat_values):
			row[f"{stat_name}_{fmt}"] = val
 
	batting_stats_data.append(row)
	time.sleep(2)
 
df = pd.DataFrame(batting_stats_data)
df

Skipping Abhimanyu Easwaran: HTTP 204 -

,playerId,playerName,Matches_Test,Matches_ODI,Matches_T20,Matches_IPL,Innings_Test,Innings_ODI,Innings_T20,Innings_IPL,...,200s_T20,200s_IPL,300s_Test,300s_ODI,300s_T20,300s_IPL,400s_Test,400s_ODI,400s_T20,400s_IPL
0,11808,Shubman Gill,41,67,36,134,74,66,36,131,...,0,0,0,0,0,0,0,0,0,0
1,13940,Yashasvi Jaiswal,29,6,23,82,54,6,22,82,...,0,0,0,0,0,0,0,0,0,0
2,13866,Sai Sudharsan,7,3,1,57,12,3,0,57,...,0,0,0,0,0,0,0,0,0,0
3,576,Rohit Sharma,67,288,159,281,116,280,151,276,...,0,0,0,0,0,0,0,0,0,0
4,1413,Virat Kohli,123,314,125,283,210,302,117,275,...,0,0,0,0,0,0,0,0,0,0
5,7915,Suryakumar Yadav,1,37,113,179,1,35,107,164,...,0,0,0,0,0,0,0,0,0,0
6,9428,Shreyas Iyer,14,82,60,146,24,76,56,145,...,0,0,0,0,0,0,0,0,0,0
7,10896,Rinku Singh,0,2,47,72,0,2,34,62,...,0,0,0,0,0,0,0,0,0,0
8,14504,Tilak Varma,0,5,58,68,0,4,55,65,...,0,0,0,0,0,0,0,0,0,0
9,11813,Ruturaj Gaikwad,0,9,23,85,0,8,20,84,...,0,0,0,0,0,0,0,0,0,0
10,10636,Rajat Patidar,3,1,0,57,6,1,0,52,...,0,0,0,0,0,0,0,0,0,0
11,9429,Sarfaraz Khan,6,0,0,58,11,0,0,44,...,0,0,0,0,0,0,0,0,0,0
12,8257,Karun Nair,10,2,0,86,15,2,0,78,...,0,0,1,0,0,0,0,0,0,0
13,14701,Nitish Kumar Reddy,10,6,4,42,16,4,3,35,...,0,0,0,0,0,0,0,0,0,0
14,9647,Hardik Pandya,11,94,138,162,18,68,109,150,...,0,0,0,0,0,0,0,0,0,0
15,11195,Shivam Dube,0,6,73,92,0,5,56,87,...,0,0,0,0,0,0,0,0,0,0
16,12086,Abhishek Sharma,0,0,55,92,0,0,54,89,...,0,0,0,0,0,0,0,0,0,0
17,587,Ravindra Jadeja,89,210,74,268,133,142,41,209,...,0,0,0,0,0,0,0,0,0,0
18,8683,Shardul Thakur,13,47,25,114,21,25,6,45,...,0,0,0,0,0,0,0,0,0,0
19,10945,Washington Sundar,18,34,62,83,30,23,27,61,...,0,0,0,0,0,0,0,0,0,0
20,8808,Axar Patel,15,74,101,176,24,52,64,135,...,0,0,0,0,0,0,0,0,0,0
21,10744,Rishabh Pant,50,31,76,139,87,27,66,136,...,0,0,0,0,0,0,0,0,0,0
22,8733,KL Rahul,68,98,72,159,119,90,68,150,...,0,0,0,0,0,0,0,0,0,0
23,14691,Dhruv Jurel,10,0,4,57,16,0,3,51,...,0,0,0,0,0,0,0,0,0,0
24,8271,Sanju Samson,0,16,66,190,0,14,58,186,...,0,0,0,0,0,0,0,0,0,0
25,10276,Ishan Kishan,2,32,54,134,3,28,54,127,...,0,0,0,0,0,0,0,0,0,0
26,10808,Mohammed Siraj,46,50,17,125,62,21,5,28,...,0,0,0,0,0,0,0,0,0,0
27,9311,Jasprit Bumrah,52,91,95,158,78,27,12,33,...,0,0,0,0,0,0,0,0,0,0
28,10551,Prasidh Krishna,7,28,8,78,10,8,2,11,...,0,0,0,0,0,0,0,0,0,0
29,14726,Akash Deep,10,0,0,14,15,0,0,5,...,0,0,0,0,0,0,0,0,0,0

In [16]:
batt_stats = []

for i in batting_stats_data:
    player_data = {
        "Player ID": int(i['playerId']),
        "Player Name": i['playerName'],
        "Test Runs": int(i.get('Runs_Test', 0)),
        "ODI Runs": int(i.get('Runs_ODI', 0)),
        "T20 Runs": int(i.get('Runs_T20', 0)),
        "Total Batt Avg": (float(i.get('Average_Test', 0)) + float(i.get('Average_ODI', 0)) + float(i.get('Average_T20', 0))) / 3
    }

    zero_count = sum([
        player_data["Test Runs"] == 0,
        player_data["ODI Runs"] == 0,
        player_data["T20 Runs"] == 0,
    ])

    if zero_count < 2:
        batt_stats.append(player_data)

batt_stats

[{'Player ID': 11808,
  'Player Name': 'Shubman Gill',
  'Test Runs': 2969,
  'ODI Runs': 3379,
  'T20 Runs': 869,
  'Total Batt Avg': 43.656666666666666},
 {'Player ID': 13940,
  'Player Name': 'Yashasvi Jaiswal',
  'Test Runs': 2535,
  'ODI Runs': 285,
  'T20 Runs': 723,
  'Total Batt Avg': 52.050000000000004},
 {'Player ID': 13866,
  'Player Name': 'Sai Sudharsan',
  'Test Runs': 383,
  'ODI Runs': 127,
  'T20 Runs': 0,
  'Total Batt Avg': 31.80666666666667},
 {'Player ID': 576,
  'Player Name': 'Rohit Sharma',
  'Test Runs': 4301,
  'ODI Runs': 11895,
  'T20 Runs': 4231,
  'Total Batt Avg': 40.29},
 {'Player ID': 1413,
  'Player Name': 'Virat Kohli',
  'Test Runs': 9230,
  'ODI Runs': 14941,
  'T20 Runs': 4188,
  'Total Batt Avg': 51.379999999999995},
 {'Player ID': 7915,
  'Player Name': 'Suryakumar Yadav',
  'Test Runs': 8,
  'ODI Runs': 773,
  'T20 Runs': 3272,
  'Total Batt Avg': 23.376666666666665},
 {'Player ID': 9428,
  'Player Name': 'Shreyas Iyer',
  'Test Runs': 811,
  'ODI Runs': 3136,
  'T20 Runs': 1388,
  'Total Batt Avg': 38.196666666666665},
 {'Player ID': 10896,
  'Player Name': 'Rinku Singh',
  'Test Runs': 0,
  'ODI Runs': 55,
  'T20 Runs': 677,
  'Total Batt Avg': 21.703333333333333},
 {'Player ID': 14504,
  'Player Name': 'Tilak Varma',
  'Test Runs': 0,
  'ODI Runs': 68,
  'T20 Runs': 1633,
  'Total Batt Avg': 22.27},
 {'Player ID': 11813,
  'Player Name': 'Ruturaj Gaikwad',
  'Test Runs': 0,
  'ODI Runs': 228,
  'T20 Runs': 633,
  'Total Batt Avg': 22.686666666666667},
 {'Player ID': 10636,
  'Player Name': 'Rajat Patidar',
  'Test Runs': 63,
  'ODI Runs': 22,
  'T20 Runs': 0,
  'Total Batt Avg': 10.833333333333334},
 {'Player ID': 8257,
  'Player Name': 'Karun Nair',
  'Test Runs': 579,
  'ODI Runs': 46,
  'T20 Runs': 0,
  'Total Batt Avg': 21.453333333333333},
 {'Player ID': 14701,
  'Player Name': 'Nitish Kumar Reddy',
  'Test Runs': 396,
  'ODI Runs': 100,
  'T20 Runs': 90,
  'Total Batt Avg': 34.91},
 {'Player ID': 9647,
  'Player Name': 'Hardik Pandya',
  'Test Runs': 532,
  'ODI Runs': 1904,
  'T20 Runs': 2288,
  'Total Batt Avg': 30.790000000000003},
 {'Player ID': 11195,
  'Player Name': 'Shivam Dube',
  'Test Runs': 0,
  'ODI Runs': 43,
  'T20 Runs': 1127,
  'Total Batt Avg': 12.753333333333332},
 {'Player ID': 587,
  'Player Name': 'Ravindra Jadeja',
  'Test Runs': 4095,
  'ODI Runs': 2905,
  'T20 Runs': 515,
  'Total Batt Avg': 30.670000000000005},
 {'Player ID': 8683,
  'Player Name': 'Shardul Thakur',
  'Test Runs': 377,
  'ODI Runs': 329,
  'T20 Runs': 69,
  'Total Batt Avg': 19.723333333333333},
 {'Player ID': 10945,
  'Player Name': 'Washington Sundar',
  'Test Runs': 937,
  'ODI Runs': 445,
  'T20 Runs': 279,
  'Total Batt Avg': 27.456666666666667},
 {'Player ID': 8808,
  'Player Name': 'Axar Patel',
  'Test Runs': 688,
  'ODI Runs': 918,
  'T20 Runs': 750,
  'Total Batt Avg': 24.87},
 {'Player ID': 10744,
  'Player Name': 'Rishabh Pant',
  'Test Runs': 3557,
  'ODI Runs': 871,
  'T20 Runs': 1209,
  'Total Batt Avg': 33.376666666666665},
 {'Player ID': 8733,
  'Player Name': 'KL Rahul',
  'Test Runs': 4153,
  'ODI Runs': 3412,
  'T20 Runs': 2265,
  'Total Batt Avg': 41.21},
 {'Player ID': 14691,
  'Player Name': 'Dhruv Jurel',
  'Test Runs': 478,
  'ODI Runs': 0,
  'T20 Runs': 12,
  'Total Batt Avg': 12.713333333333333},
 {'Player ID': 8271,
  'Player Name': 'Sanju Samson',
  'Test Runs': 0,
  'ODI Runs': 510,
  'T20 Runs': 1432,
  'Total Batt Avg': 27.896666666666665},
 {'Player ID': 10276,
  'Player Name': 'Ishan Kishan',
  'Test Runs': 78,
  'ODI Runs': 1107,
  'T20 Runs': 1579,
  'Total Batt Avg': 50.123333333333335},
 {'Player ID': 10808,
  'Player Name': 'Mohammed Siraj',
  'Test Runs': 176,
  'ODI Runs': 57,
  'T20 Runs': 14,
  'Total Batt Avg': 6.34},
 {'Player ID': 9311,
  'Player Name': 'Jasprit Bumrah',
  'Test Runs': 348,
  'ODI Runs': 111,
  'T20 Runs': 12,
  'Total Batt Avg': 5.94},
 {'Player ID': 10551,
  'Player Name': 'Prasidh Krishna',
  'Test Runs': 10,
  'ODI Runs': 2,
  'T20 Runs': 2,
  'Total Batt Avg': 0.89}]

In [18]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

Last_20_Matches = pd.DataFrame(batt_stats)
table_name = "Batting Data"  

engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


Last_20_Matches.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz Batting Data

C:\Users\Dell\AppData\Local\Temp\ipykernel_16412\886394196.py:24: UserWarning: The provided table name 'Batting Data' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  Last_20_Matches.to_sql(table_name, con=engine, if_exists='replace', index=False)

Q12 

Analyze each international team's performance when playing at home versus playing away. Determine whether each team played at home or away based on whether the venue country matches the team's country. Count wins for each team in both home and away conditions.

In [20]:
team_details=[{'TeamId': 2, 'TeamName': 'India'},
 {'TeamId': 96, 'TeamName': 'Afghanistan'},
 {'TeamId': 27, 'TeamName': 'Ireland'},
 {'TeamId': 3, 'TeamName': 'Pakistan'},
 {'TeamId': 4, 'TeamName': 'Australia'},
 {'TeamId': 5, 'TeamName': 'Sri Lanka'},
 {'TeamId': 6, 'TeamName': 'Bangladesh'},
 {'TeamId': 9, 'TeamName': 'England'},
 {'TeamId': 10, 'TeamName': 'West Indies'},
 {'TeamId': 11, 'TeamName': 'South Africa'},
 {'TeamId': 12, 'TeamName': 'Zimbabwe'},
 {'TeamId': 13, 'TeamName': 'New Zealand'}]

In [21]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/9638"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
result1=response.json()

{'matchDetails': [{'matchDetailsMap': {'key': 'Fri, 14 Nov 2025 - Tue, 18 Nov 2025', 'match': [{'matchInfo': {'matchId': 117371, 'seriesId': 9638, 'seriesName': 'South Africa tour of India, 2025', 'matchDesc': '1st Test', 'matchFormat': 'TEST', 'startDate': '1763092800000', 'endDate': '1763438400000', 'state': 'complete', 'status': 'South Africa won by 30 runs', 'team1': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 11, 'teamName': 'SOUTH AFRICA', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'ground': 'Eden Gardens', 'city': 'Kolkata', 'timezone': '+05:30'}, 'currBatTeamId': 11, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 189, 'wickets': 10, 'overs': 62.2}, 'inngs2': {'inningsId': 4, 'runs': 93, 'wickets': 10, 'overs': 35.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 159, 'wickets': 10, 'overs': 55.0}, 'inngs2': {'inningsId': 3, 'runs': 153, 'wickets': 10, 'overs': 54.0}}}}], 'seriesId': 9638}}, {'adDetail': {'name': 'native_news_index_random_1', 'layout': 'native_large', 'position': 1}}, {'matchDetailsMap': {'key': 'Sat, 22 Nov 2025 - Wed, 26 Nov 2025', 'match': [{'matchInfo': {'matchId': 117380, 'seriesId': 9638, 'seriesName': 'South Africa tour of India, 2025', 'matchDesc': '2nd Test', 'matchFormat': 'TEST', 'startDate': '1763782200000', 'endDate': '1764127800000', 'state': 'complete', 'status': 'South Africa won by 408 runs', 'team1': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 11, 'teamName': 'SOUTH AFRICA', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'ground': 'Barsapara Cricket Stadium', 'city': 'Guwahati', 'timezone': '+05:30'}, 'currBatTeamId': 11, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 201, 'wickets': 10, 'overs': 83.5}, 'inngs2': {'inningsId': 4, 'runs': 140, 'wickets': 10, 'overs': 63.5}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 489, 'wickets': 10, 'overs': 151.1}, 'inngs2': {'inningsId': 3, 'runs': 260, 'wickets': 5, 'overs': 78.3, 'isDeclared': True}}}}], 'seriesId': 9638}}, {'matchDetailsMap': {'key': 'Sun, 30 Nov 2025', 'match': [{'matchInfo': {'matchId': 117389, 'seriesId': 9638, 'seriesName': 'South Africa tour of India, 2025', 'matchDesc': '1st ODI', 'matchFormat': 'ODI', 'startDate': '1764489600000', 'endDate': '1764489600000', 'state': 'complete', 'status': 'India won by 17 runs', 'team1': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 11, 'teamName': 'SOUTH AFRICA', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'ground': 'JSCA International Stadium Complex', 'city': 'Ranchi', 'timezone': '+05:30'}, 'currBatTeamId': 2, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 349, 'wickets': 8, 'overs': 50.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 332, 'wickets': 10, 'overs': 49.2}}}}], 'seriesId': 9638}}, {'matchDetailsMap': {'key': 'Wed, 03 Dec 2025', 'match': [{'matchInfo': {'matchId': 117398, 'seriesId': 9638, 'seriesName': 'South Africa tour of India, 2025', 'matchDesc': '2nd ODI', 'matchFormat': 'ODI', 'startDate': '1764748800000', 'endDate': '1764748800000', 'state': 'complete', 'status': 'South Africa won by 4 wkts', 'team1': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 11, 'teamName': 'SOUTH AFRICA', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'ground': 'Shaheed Veer Narayan Singh International Stadium', 'city': 'Raipur', 'timezone': '+05:30'}, 'currBatTeamId': 11, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 358, 'wickets': 5, 'overs': 50.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 362, 'wickets': 6, 'overs': 49.2}}}}], 'seriesId': 9638}}, {'matchDetailsMap': {'key': 'Sat, 06 Dec 2025', 'match': [{'matchInfo': {'matchId': 117404, 'seriesId': 9638, 'seriesName': 'South Africa tour of India, 2025', 'matchDesc': '3rd ODI', 'matchFormat': 'ODI', 'startDate': '1765008000000', 'endDate': '1765008000000', 'state': 'complete', 'status': 'India won by 9 wkts', 'team1': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 11, 'teamName': 'SOUTH AFRICA', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'ground': 'ACA-VDCA Cricket Stadium', 'city': 'Visakhapatnam', 'timezone': '+05:30'}, 'currBatTeamId': 2, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 271, 'wickets': 1, 'overs': 39.5}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 270, 'wickets': 10, 'overs': 47.5}}}}], 'seriesId': 9638}}, {'matchDetailsMap': {'key': 'Tue, 09 Dec 2025', 'match': [{'matchInfo': {'matchId': 117413, 'seriesId': 9638, 'seriesName': 'South Africa tour of India, 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1765287000000', 'endDate': '1765287000000', 'state': 'complete', 'status': 'India won by 101 runs', 'team1': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 11, 'teamName': 'SOUTH AFRICA', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'ground': 'Barabati Stadium', 'city': 'Cuttack', 'timezone': '+05:30'}, 'currBatTeamId': 2, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 175, 'wickets': 6, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 74, 'wickets': 10, 'overs': 12.3}}}}], 'seriesId': 9638}}, {'matchDetailsMap': {'key': 'Thu, 11 Dec 2025', 'match': [{'matchInfo': {'matchId': 117416, 'seriesId': 9638, 'seriesName': 'South Africa tour of India, 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1765459800000', 'endDate': '1765459800000', 'state': 'complete', 'status': 'South Africa won by 51 runs', 'team1': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 11, 'teamName': 'SOUTH AFRICA', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'ground': 'Maharaja Yadavindra Singh International Cricket Stadium, Mullanpur', 'city': 'New Chandigarh', 'timezone': '+05:30'}, 'currBatTeamId': 11, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 162, 'wickets': 10, 'overs': 19.1}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 213, 'wickets': 4, 'overs': 20.0}}}}], 'seriesId': 9638}}, {'matchDetailsMap': {'key': 'Sun, 14 Dec 2025', 'match': [{'matchInfo': {'matchId': 117425, 'seriesId': 9638, 'seriesName': 'South Africa tour of India, 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1765719000000', 'endDate': '1765719000000', 'state': 'complete', 'status': 'India won by 7 wkts', 'team1': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 11, 'teamName': 'SOUTH AFRICA', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'ground': 'Himachal Pradesh Cricket Association Stadium', 'city': 'Dharamsala', 'timezone': '+05:30'}, 'currBatTeamId': 2, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 120, 'wickets': 3, 'overs': 15.5}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 117, 'wickets': 10, 'overs': 20.0}}}}], 'seriesId': 9638}}, {'matchDetailsMap': {'key': 'Wed, 17 Dec 2025', 'match': [{'matchInfo': {'matchId': 117434, 'seriesId': 9638, 'seriesName': 'South Africa tour of India, 2025', 'matchDesc': '4th T20I', 'matchFormat': 'T20', 'startDate': '1765978200000', 'endDate': '1765978200000', 'state': 'complete', 'status': 'Match abandoned - due to excessive fog', 'team1': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 11, 'teamName': 'SOUTH AFRICA', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'ground': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium', 'city': 'Lucknow', 'timezone': '+05:30'}, 'isTimeAnnounced': True}}], 'seriesId': 9638}}, {'matchDetailsMap': {'key': 'Fri, 19 Dec 2025', 'match': [{'matchInfo': {'matchId': 117440, 'seriesId': 9638, 'seriesName': 'South Africa tour of India, 2025', 'matchDesc': '5th T20I', 'matchFormat': 'T20', 'startDate': '1766151000000', 'endDate': '1766151000000', 'state': 'complete', 'status': 'India won by 30 runs', 'team1': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'team2': {'teamId': 11, 'teamName': 'SOUTH AFRICA', 'teamSName': 'RSA', 'imageId': 776287}, 'venueInfo': {'ground': 'Narendra Modi Stadium', 'city': 'Ahmedabad', 'timezone': '+05:30'}, 'currBatTeamId': 2, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 231, 'wickets': 5, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 201, 'wickets': 8, 'overs': 20.0}}}}], 'seriesId': 9638}}], 'appIndex': {'seoTitle': 'South Africa tour of India, 2025 live scores, schedule and results - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [22]:

win=0
loose=0
for i in result1['matchDetails']:
    if not i.get('matchDetailsMap'):
        continue
    status=i['matchDetailsMap']['match'][0]['matchInfo']['status']
    if "won" in status.lower():
        if "india" in status.lower():
            win=win+1
        else:
            loose=loose+1
    res1=[
        {
            "Team" : "India",
            "Series" : "Home Series",
            "Wins" : win,
            "Lost" : loose
        },
        {
            "Team" : "SouthAfrica",
            "Series" : "Away Series",
            "Wins" : loose,
            "Lost" : win
        }]
print(res1)

[{'Team': 'India', 'Series': 'Home Series', 'Wins': 5, 'Lost': 4}, {'Team': 'SouthAfrica', 'Series': 'Away Series', 'Wins': 4, 'Lost': 5}]

In [23]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/8786"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
result2=response.json()

{'matchDetails': [{'matchDetailsMap': {'key': 'Fri, 20 Jun 2025 - Tue, 24 Jun 2025', 'match': [{'matchInfo': {'matchId': 105762, 'seriesId': 8786, 'seriesName': 'India tour of England, 2025', 'matchDesc': '1st Test', 'matchFormat': 'TEST', 'startDate': '1750413600000', 'endDate': '1750759200000', 'state': 'complete', 'status': 'England won by 5 wkts', 'team1': {'teamId': 9, 'teamName': 'ENGLAND', 'teamSName': 'ENG', 'imageId': 776237}, 'team2': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'venueInfo': {'ground': 'Headingley', 'city': 'Leeds', 'timezone': '+01:00'}, 'currBatTeamId': 9, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 465, 'wickets': 10, 'overs': 100.4}, 'inngs2': {'inningsId': 4, 'runs': 373, 'wickets': 5, 'overs': 82.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 471, 'wickets': 10, 'overs': 113.0}, 'inngs2': {'inningsId': 3, 'runs': 364, 'wickets': 10, 'overs': 96.0}}}}], 'seriesId': 8786}}, {'adDetail': {'name': 'native_news_index_random_1', 'layout': 'native_large', 'position': 1}}, {'matchDetailsMap': {'key': 'Wed, 02 Jul 2025 - Sun, 06 Jul 2025', 'match': [{'matchInfo': {'matchId': 105770, 'seriesId': 8786, 'seriesName': 'India tour of England, 2025', 'matchDesc': '2nd Test', 'matchFormat': 'TEST', 'startDate': '1751450400000', 'endDate': '1751796000000', 'state': 'complete', 'status': 'India won by 336 runs', 'team1': {'teamId': 9, 'teamName': 'ENGLAND', 'teamSName': 'ENG', 'imageId': 776237}, 'team2': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'venueInfo': {'ground': 'Edgbaston', 'city': 'Birmingham', 'timezone': '+01:00'}, 'currBatTeamId': 2, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 407, 'wickets': 10, 'overs': 89.3}, 'inngs2': {'inningsId': 4, 'runs': 271, 'wickets': 10, 'overs': 68.1}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 587, 'wickets': 10, 'overs': 151.0}, 'inngs2': {'inningsId': 3, 'runs': 427, 'wickets': 6, 'overs': 83.0, 'isDeclared': True}}}}], 'seriesId': 8786}}, {'matchDetailsMap': {'key': 'Thu, 10 Jul 2025 - Mon, 14 Jul 2025', 'match': [{'matchInfo': {'matchId': 105772, 'seriesId': 8786, 'seriesName': 'India tour of England, 2025', 'matchDesc': '3rd Test', 'matchFormat': 'TEST', 'startDate': '1752141600000', 'endDate': '1752487200000', 'state': 'complete', 'status': 'England won by 22 runs', 'team1': {'teamId': 9, 'teamName': 'ENGLAND', 'teamSName': 'ENG', 'imageId': 776237}, 'team2': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'venueInfo': {'ground': "Lord's", 'city': 'London', 'timezone': '+01:00'}, 'currBatTeamId': 9, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 387, 'wickets': 10, 'overs': 112.3}, 'inngs2': {'inningsId': 3, 'runs': 192, 'wickets': 10, 'overs': 62.1}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 387, 'wickets': 10, 'overs': 119.2}, 'inngs2': {'inningsId': 4, 'runs': 170, 'wickets': 10, 'overs': 74.5}}}}], 'seriesId': 8786}}, {'matchDetailsMap': {'key': 'Wed, 23 Jul 2025 - Sun, 27 Jul 2025', 'match': [{'matchInfo': {'matchId': 105778, 'seriesId': 8786, 'seriesName': 'India tour of England, 2025', 'matchDesc': '4th Test', 'matchFormat': 'TEST', 'startDate': '1753264800000', 'endDate': '1753610400000', 'state': 'complete', 'status': 'Match drawn', 'team1': {'teamId': 9, 'teamName': 'ENGLAND', 'teamSName': 'ENG', 'imageId': 776237}, 'team2': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'venueInfo': {'ground': 'Emirates Old Trafford', 'city': 'Manchester', 'timezone': '+01:00'}, 'currBatTeamId': 2, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 669, 'wickets': 10, 'overs': 157.1}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 358, 'wickets': 10, 'overs': 114.1}, 'inngs2': {'inningsId': 3, 'runs': 425, 'wickets': 4, 'overs': 143.0}}}}], 'seriesId': 8786}}, {'matchDetailsMap': {'key': 'Thu, 31 Jul 2025 - Mon, 04 Aug 2025', 'match': [{'matchInfo': {'matchId': 105780, 'seriesId': 8786, 'seriesName': 'India tour of England, 2025', 'matchDesc': '5th Test', 'matchFormat': 'TEST', 'startDate': '1753956000000', 'endDate': '1754301600000', 'state': 'complete', 'status': 'India won by 6 runs', 'team1': {'teamId': 9, 'teamName': 'ENGLAND', 'teamSName': 'ENG', 'imageId': 776237}, 'team2': {'teamId': 2, 'teamName': 'INDIA', 'teamSName': 'IND', 'imageId': 776162}, 'venueInfo': {'ground': 'Kennington Oval', 'city': 'London', 'timezone': '+01:00'}, 'currBatTeamId': 2, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 247, 'wickets': 10, 'overs': 51.2}, 'inngs2': {'inningsId': 4, 'runs': 367, 'wickets': 10, 'overs': 85.1}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 224, 'wickets': 10, 'overs': 69.4}, 'inngs2': {'inningsId': 3, 'runs': 396, 'wickets': 10, 'overs': 88.0}}}}], 'seriesId': 8786}}], 'appIndex': {'seoTitle': 'India tour of England, 2025 live scores, schedule and results - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [24]:

win=0
loose=0
for i in result2['matchDetails']:
    if not i.get('matchDetailsMap'):
        continue
    status=i['matchDetailsMap']['match'][0]['matchInfo']['status']
    if "won" in status.lower():
        if "india" in status.lower():
            win=win+1
        else:
            loose=loose+1
    res2= [{
            "Team" : "India",
            "Series" : "Away Series",
            "Wins" : win,
            "Lost" : loose
        },
        {
            "Team" : "England",
            "Series" : "Home Series",
            "Wins" : loose,
            "Lost" : win
        }]
print(res2)

[{'Team': 'India', 'Series': 'Away Series', 'Wins': 2, 'Lost': 2}, {'Team': 'England', 'Series': 'Home Series', 'Wins': 2, 'Lost': 2}]

In [25]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/8802"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
result3=response.json()

{'matchDetails': [{'matchDetailsMap': {'key': 'Wed, 17 Sep 2025', 'match': [{'matchInfo': {'matchId': 105844, 'seriesId': 8802, 'seriesName': 'England tour of Ireland, 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1758112200000', 'endDate': '1758112200000', 'state': 'complete', 'status': 'England won by 4 wkts', 'team1': {'teamId': 27, 'teamName': 'IRELAND', 'teamSName': 'IRE', 'imageId': 839366}, 'team2': {'teamId': 9, 'teamName': 'ENGLAND', 'teamSName': 'ENG', 'imageId': 776237}, 'venueInfo': {'ground': 'The Village', 'city': 'Dublin', 'timezone': '+01:00'}, 'currBatTeamId': 9, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 196, 'wickets': 3, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 197, 'wickets': 6, 'overs': 17.4}}}}], 'seriesId': 8802}}, {'adDetail': {'name': 'native_news_index_random_1', 'layout': 'native_large', 'position': 1}}, {'matchDetailsMap': {'key': 'Fri, 19 Sep 2025', 'match': [{'matchInfo': {'matchId': 105850, 'seriesId': 8802, 'seriesName': 'England tour of Ireland, 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1758285000000', 'endDate': '1758285000000', 'state': 'complete', 'team1': {'teamId': 27, 'teamName': 'IRELAND', 'teamSName': 'IRE', 'imageId': 839366}, 'team2': {'teamId': 9, 'teamName': 'ENGLAND', 'teamSName': 'ENG', 'imageId': 776237}, 'venueInfo': {'ground': 'The Village', 'city': 'Dublin', 'timezone': '+01:00'}, 'isTimeAnnounced': True}}], 'seriesId': 8802}}, {'matchDetailsMap': {'key': 'Sun, 21 Sep 2025', 'match': [{'matchInfo': {'matchId': 105858, 'seriesId': 8802, 'seriesName': 'England tour of Ireland, 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1758457800000', 'endDate': '1758457800000', 'state': 'complete', 'status': 'England won by 6 wkts', 'team1': {'teamId': 27, 'teamName': 'IRELAND', 'teamSName': 'IRE', 'imageId': 839366}, 'team2': {'teamId': 9, 'teamName': 'ENGLAND', 'teamSName': 'ENG', 'imageId': 776237}, 'venueInfo': {'ground': 'The Village', 'city': 'Dublin', 'timezone': '+01:00'}, 'currBatTeamId': 9, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 154, 'wickets': 8, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 155, 'wickets': 4, 'overs': 17.1}}}}], 'seriesId': 8802}}], 'appIndex': {'seoTitle': 'England tour of Ireland, 2025 live scores, schedule and results - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [26]:
win = 0
loose = 0

for i in result3['matchDetails']:
    if not i.get('matchDetailsMap'):
        continue

    match_info = i['matchDetailsMap']['match'][0]['matchInfo']
    status = match_info.get('status', "")

    if "abandoned" in status.lower() or "no result" in status.lower():
        continue

    if "won" in status:
        if "ireland" in status.lower():  
            win += 1
        else:                    
            loose += 1


res3 = [
    {
        "Team": "Ireland",
        "Series": "Home Series",
        "Wins": win,
        "Lost": loose
    },
    {
        "Team": "England",
        "Series": "Away Series",
        "Wins": loose,
        "Lost": win
    }
]

print(res3)

[{'Team': 'Ireland', 'Series': 'Home Series', 'Wins': 0, 'Lost': 2}, {'Team': 'England', 'Series': 'Away Series', 'Wins': 2, 'Lost': 0}]

In [27]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/10972"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
result4=response.json()

{'matchDetails': [{'matchDetailsMap': {'key': 'Tue, 11 Nov 2025 - Sat, 15 Nov 2025', 'match': [{'matchInfo': {'matchId': 135041, 'seriesId': 10972, 'seriesName': 'Ireland tour of Bangladesh, 2025', 'matchDesc': '1st Test', 'matchFormat': 'TEST', 'startDate': '1762831800000', 'endDate': '1763177400000', 'state': 'complete', 'status': 'Bangladesh won by an innings and 47 runs', 'team1': {'teamId': 6, 'teamName': 'BANGLADESH', 'teamSName': 'BAN', 'imageId': 776210}, 'team2': {'teamId': 27, 'teamName': 'IRELAND', 'teamSName': 'IRE', 'imageId': 839366}, 'venueInfo': {'ground': 'Sylhet International Cricket Stadium', 'city': 'Sylhet', 'timezone': '+06:00'}, 'currBatTeamId': 6, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 587, 'wickets': 8, 'overs': 141.0, 'isDeclared': True}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 286, 'wickets': 10, 'overs': 92.2}, 'inngs2': {'inningsId': 3, 'runs': 254, 'wickets': 10, 'overs': 70.2}}}}], 'seriesId': 10972}}, {'adDetail': {'name': 'native_news_index_random_1', 'layout': 'native_large', 'position': 1}}, {'matchDetailsMap': {'key': 'Wed, 19 Nov 2025 - Sun, 23 Nov 2025', 'match': [{'matchInfo': {'matchId': 135046, 'seriesId': 10972, 'seriesName': 'Ireland tour of Bangladesh, 2025', 'matchDesc': '2nd Test', 'matchFormat': 'TEST', 'startDate': '1763523000000', 'endDate': '1763868600000', 'state': 'complete', 'status': 'Bangladesh won by 217 runs', 'team1': {'teamId': 6, 'teamName': 'BANGLADESH', 'teamSName': 'BAN', 'imageId': 776210}, 'team2': {'teamId': 27, 'teamName': 'IRELAND', 'teamSName': 'IRE', 'imageId': 839366}, 'venueInfo': {'ground': 'Shere Bangla National Stadium', 'city': 'Dhaka', 'timezone': '+06:00'}, 'currBatTeamId': 6, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 476, 'wickets': 10, 'overs': 141.1}, 'inngs2': {'inningsId': 3, 'runs': 297, 'wickets': 4, 'overs': 69.0, 'isDeclared': True}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 265, 'wickets': 10, 'overs': 88.3}, 'inngs2': {'inningsId': 4, 'runs': 291, 'wickets': 10, 'overs': 113.3}}}}], 'seriesId': 10972}}, {'matchDetailsMap': {'key': 'Thu, 27 Nov 2025', 'match': [{'matchInfo': {'matchId': 135057, 'seriesId': 10972, 'seriesName': 'Ireland tour of Bangladesh, 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1764244800000', 'endDate': '1764244800000', 'state': 'complete', 'status': 'Ireland won by 39 runs', 'team1': {'teamId': 6, 'teamName': 'BANGLADESH', 'teamSName': 'BAN', 'imageId': 776210}, 'team2': {'teamId': 27, 'teamName': 'IRELAND', 'teamSName': 'IRE', 'imageId': 839366}, 'venueInfo': {'ground': 'Bir Sreshtho Flight Lieutenant Matiur Rahman Stadium', 'city': 'Chattogram', 'timezone': '+06:00'}, 'currBatTeamId': 27, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 142, 'wickets': 9, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 181, 'wickets': 4, 'overs': 20.0}}}}], 'seriesId': 10972}}, {'matchDetailsMap': {'key': 'Sat, 29 Nov 2025', 'match': [{'matchInfo': {'matchId': 135063, 'seriesId': 10972, 'seriesName': 'Ireland tour of Bangladesh, 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1764417600000', 'endDate': '1764417600000', 'state': 'complete', 'status': 'Bangladesh won by 4 wkts', 'team1': {'teamId': 6, 'teamName': 'BANGLADESH', 'teamSName': 'BAN', 'imageId': 776210}, 'team2': {'teamId': 27, 'teamName': 'IRELAND', 'teamSName': 'IRE', 'imageId': 839366}, 'venueInfo': {'ground': 'Bir Sreshtho Flight Lieutenant Matiur Rahman Stadium', 'city': 'Chattogram', 'timezone': '+06:00'}, 'currBatTeamId': 6, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 174, 'wickets': 6, 'overs': 19.4}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 170, 'wickets': 6, 'overs': 20.0}}}}], 'seriesId': 10972}}, {'matchDetailsMap': {'key': 'Tue, 02 Dec 2025', 'match': [{'matchInfo': {'matchId': 135068, 'seriesId': 10972, 'seriesName': 'Ireland tour of Bangladesh, 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1764662400000', 'endDate': '1764662400000', 'state': 'complete', 'status': 'Bangladesh won by 8 wkts', 'team1': {'teamId': 6, 'teamName': 'BANGLADESH', 'teamSName': 'BAN', 'imageId': 776210}, 'team2': {'teamId': 27, 'teamName': 'IRELAND', 'teamSName': 'IRE', 'imageId': 839366}, 'venueInfo': {'ground': 'Bir Sreshtho Flight Lieutenant Matiur Rahman Stadium', 'city': 'Chattogram', 'timezone': '+06:00'}, 'currBatTeamId': 6, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 119, 'wickets': 2, 'overs': 13.4}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 117, 'wickets': 10, 'overs': 19.5}}}}], 'seriesId': 10972}}], 'appIndex': {'seoTitle': 'Ireland tour of Bangladesh, 2025 live scores, schedule and results - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [28]:
win = 0
loose = 0

for i in result4['matchDetails']:
    if not i.get('matchDetailsMap'):
        continue

    match_info = i['matchDetailsMap']['match'][0]['matchInfo']
    status = match_info.get('status', "")

    if "abandoned" in status.lower() or "no result" in status.lower():
        continue

    if "won" in status:
        if "bangladesh" in status.lower():  
            win += 1
        else:                    
            loose += 1


res4 = [
    {
        "Team": "Bangladesh",
        "Series": "Home Series",
        "Wins": win,
        "Lost": loose
    },
    {
        "Team": "Ireland",
        "Series": "Away Series",
        "Wins": loose,
        "Lost": win
    }
]

print(res4)

[{'Team': 'Bangladesh', 'Series': 'Home Series', 'Wins': 4, 'Lost': 1}, {'Team': 'Ireland', 'Series': 'Away Series', 'Wins': 1, 'Lost': 4}]

In [29]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/10933"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
result5=response.json()

{'matchDetails': [{'matchDetailsMap': {'key': 'Tue, 11 Nov 2025', 'match': [{'matchInfo': {'matchId': 134744, 'seriesId': 10933, 'seriesName': 'Sri Lanka tour of Pakistan 2025', 'matchDesc': '1st ODI', 'matchFormat': 'ODI', 'startDate': '1762853400000', 'endDate': '1762853400000', 'state': 'complete', 'status': 'Pakistan won by 6 runs', 'team1': {'teamId': 3, 'teamName': 'PAKISTAN', 'teamSName': 'PAK', 'imageId': 776308}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Rawalpindi Cricket Stadium', 'city': 'Rawalpindi', 'timezone': '+05:00'}, 'currBatTeamId': 3, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 299, 'wickets': 5, 'overs': 50.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 293, 'wickets': 9, 'overs': 50.0}}}}], 'seriesId': 10933}}, {'adDetail': {'name': 'native_news_index_random_1', 'layout': 'native_large', 'position': 1}}, {'matchDetailsMap': {'key': 'Fri, 14 Nov 2025', 'match': [{'matchInfo': {'matchId': 134749, 'seriesId': 10933, 'seriesName': 'Sri Lanka tour of Pakistan 2025', 'matchDesc': '2nd ODI', 'matchFormat': 'ODI', 'startDate': '1763112600000', 'endDate': '1763112600000', 'state': 'complete', 'status': 'Pakistan won by 8 wkts', 'team1': {'teamId': 3, 'teamName': 'PAKISTAN', 'teamSName': 'PAK', 'imageId': 776308}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Rawalpindi Cricket Stadium', 'city': 'Rawalpindi', 'timezone': '+05:00'}, 'currBatTeamId': 3, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 289, 'wickets': 2, 'overs': 48.2}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 288, 'wickets': 8, 'overs': 50.0}}}}], 'seriesId': 10933}}, {'matchDetailsMap': {'key': 'Sun, 16 Nov 2025', 'match': [{'matchInfo': {'matchId': 134755, 'seriesId': 10933, 'seriesName': 'Sri Lanka tour of Pakistan 2025', 'matchDesc': '3rd ODI', 'matchFormat': 'ODI', 'startDate': '1763285400000', 'endDate': '1763285400000', 'state': 'complete', 'status': 'Pakistan won by 6 wkts', 'team1': {'teamId': 3, 'teamName': 'PAKISTAN', 'teamSName': 'PAK', 'imageId': 776308}, 'team2': {'teamId': 5, 'teamName': 'SRI LANKA', 'teamSName': 'SL', 'imageId': 776254}, 'venueInfo': {'ground': 'Rawalpindi Cricket Stadium', 'city': 'Rawalpindi', 'timezone': '+05:00'}, 'currBatTeamId': 3, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 215, 'wickets': 4, 'overs': 44.4}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 211, 'wickets': 10, 'overs': 45.2}}}}], 'seriesId': 10933}}], 'appIndex': {'seoTitle': 'Sri Lanka tour of Pakistan 2025 live scores, schedule and results - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [30]:
win = 0
loose = 0

for i in result5['matchDetails']:
    if not i.get('matchDetailsMap'):
        continue

    match_info = i['matchDetailsMap']['match'][0]['matchInfo']
    status = match_info.get('status', "")

    if "abandoned" in status.lower() or "no result" in status.lower():
        continue

    if "won" in status:
        if "pakistan" in status.lower():  
            win += 1
        else:                    
            loose += 1


res5 = [
    {
        "Team": "Pakistan",
        "Series": "Home Series",
        "Wins": win,
        "Lost": loose
    },
    {
        "Team": "SriLanka",
        "Series": "Away Series",
        "Wins": loose,
        "Lost": win
    }
]

print(res5)

[{'Team': 'Pakistan', 'Series': 'Home Series', 'Wins': 3, 'Lost': 0}, {'Team': 'SriLanka', 'Series': 'Away Series', 'Wins': 0, 'Lost': 3}]

In [33]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/9399"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
result6=response.json()

{'matchDetails': [{'matchDetailsMap': {'key': 'Fri, 01 Aug 2025', 'match': [{'matchInfo': {'matchId': 114636, 'seriesId': 9399, 'seriesName': 'Pakistan tour of West Indies, 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1754006400000', 'endDate': '1754006400000', 'state': 'complete', 'status': 'Pakistan won by 14 runs', 'team1': {'teamId': 10, 'teamName': 'WEST INDIES', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 3, 'teamName': 'PAKISTAN', 'teamSName': 'PAK', 'imageId': 776308}, 'venueInfo': {'ground': 'Central Broward Regional Park Stadium Turf Ground', 'city': 'Lauderhill, Florida', 'timezone': '-04:00'}, 'currBatTeamId': 3, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 164, 'wickets': 7, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 178, 'wickets': 6, 'overs': 20.0}}}}], 'seriesId': 9399}}, {'adDetail': {'name': 'native_news_index_random_1', 'layout': 'native_large', 'position': 1}}, {'matchDetailsMap': {'key': 'Sun, 03 Aug 2025', 'match': [{'matchInfo': {'matchId': 114643, 'seriesId': 9399, 'seriesName': 'Pakistan tour of West Indies, 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1754179200000', 'endDate': '1754179200000', 'state': 'complete', 'status': 'West Indies won by 2 wkts', 'team1': {'teamId': 10, 'teamName': 'WEST INDIES', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 3, 'teamName': 'PAKISTAN', 'teamSName': 'PAK', 'imageId': 776308}, 'venueInfo': {'ground': 'Central Broward Regional Park Stadium Turf Ground', 'city': 'Lauderhill, Florida', 'timezone': '-04:00'}, 'currBatTeamId': 10, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 135, 'wickets': 8, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 133, 'wickets': 9, 'overs': 20.0}}}}], 'seriesId': 9399}}, {'matchDetailsMap': {'key': 'Mon, 04 Aug 2025', 'match': [{'matchInfo': {'matchId': 114645, 'seriesId': 9399, 'seriesName': 'Pakistan tour of West Indies, 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1754265600000', 'endDate': '1754265600000', 'state': 'complete', 'status': 'Pakistan won by 13 runs', 'team1': {'teamId': 10, 'teamName': 'WEST INDIES', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 3, 'teamName': 'PAKISTAN', 'teamSName': 'PAK', 'imageId': 776308}, 'venueInfo': {'ground': 'Central Broward Regional Park Stadium Turf Ground', 'city': 'Lauderhill, Florida', 'timezone': '-04:00'}, 'currBatTeamId': 3, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 176, 'wickets': 6, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 189, 'wickets': 4, 'overs': 20.0}}}}], 'seriesId': 9399}}, {'matchDetailsMap': {'key': 'Fri, 08 Aug 2025', 'match': [{'matchInfo': {'matchId': 114661, 'seriesId': 9399, 'seriesName': 'Pakistan tour of West Indies, 2025', 'matchDesc': '1st ODI', 'matchFormat': 'ODI', 'startDate': '1754676000000', 'endDate': '1754676000000', 'state': 'complete', 'status': 'Pakistan won by 5 wkts', 'team1': {'teamId': 10, 'teamName': 'WEST INDIES', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 3, 'teamName': 'PAKISTAN', 'teamSName': 'PAK', 'imageId': 776308}, 'venueInfo': {'ground': 'Brian Lara Stadium', 'city': 'Tarouba, Trinidad', 'timezone': '-04:00'}, 'currBatTeamId': 3, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 280, 'wickets': 10, 'overs': 49.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 284, 'wickets': 5, 'overs': 48.5}}}}], 'seriesId': 9399}}, {'matchDetailsMap': {'key': 'Sun, 10 Aug 2025', 'match': [{'matchInfo': {'matchId': 114670, 'seriesId': 9399, 'seriesName': 'Pakistan tour of West Indies, 2025', 'matchDesc': '2nd ODI', 'matchFormat': 'ODI', 'startDate': '1754832600000', 'endDate': '1754832600000', 'state': 'complete', 'status': 'West Indies won by 5 wkts (DLS Method)', 'team1': {'teamId': 10, 'teamName': 'WEST INDIES', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 3, 'teamName': 'PAKISTAN', 'teamSName': 'PAK', 'imageId': 776308}, 'venueInfo': {'ground': 'Brian Lara Stadium', 'city': 'Tarouba, Trinidad', 'timezone': '-04:00'}, 'currBatTeamId': 10, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 2, 'runs': 184, 'wickets': 5, 'overs': 33.2}}, 'team2Score': {'inngs1': {'inningsId': 1, 'runs': 171, 'wickets': 7, 'overs': 37.0}}}}], 'seriesId': 9399}}, {'matchDetailsMap': {'key': 'Tue, 12 Aug 2025', 'match': [{'matchInfo': {'matchId': 114672, 'seriesId': 9399, 'seriesName': 'Pakistan tour of West Indies, 2025', 'matchDesc': '3rd ODI', 'matchFormat': 'ODI', 'startDate': '1755005400000', 'endDate': '1755005400000', 'state': 'complete', 'status': 'West Indies won by 202 runs', 'team1': {'teamId': 10, 'teamName': 'WEST INDIES', 'teamSName': 'WI', 'imageId': 776191}, 'team2': {'teamId': 3, 'teamName': 'PAKISTAN', 'teamSName': 'PAK', 'imageId': 776308}, 'venueInfo': {'ground': 'Brian Lara Stadium', 'city': 'Tarouba, Trinidad', 'timezone': '-04:00'}, 'currBatTeamId': 10, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 294, 'wickets': 6, 'overs': 50.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 92, 'wickets': 10, 'overs': 29.2}}}}], 'seriesId': 9399}}], 'appIndex': {'seoTitle': 'Pakistan tour of West Indies, 2025 live scores, schedule and results - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [34]:
win = 0
loose = 0

for i in result6['matchDetails']:
    if not i.get('matchDetailsMap'):
        continue

    match_info = i['matchDetailsMap']['match'][0]['matchInfo']
    status = match_info.get('status', "")

    if "abandoned" in status.lower() or "no result" in status.lower():
        continue

    if "won" in status:
        if "west indies" in status.lower():  
            win += 1
        else:                    
            loose += 1


res6 = [
    {
        "Team": "West Indies",
        "Series": "Home Series",
        "Wins": win,
        "Lost": loose
    },
    {
        "Team": "Pakistan",
        "Series": "Away Series",
        "Wins": loose,
        "Lost": win
    }
]

print(res6)

[{'Team': 'West Indies', 'Series': 'Home Series', 'Wins': 3, 'Lost': 3}, {'Team': 'Pakistan', 'Series': 'Away Series', 'Wins': 3, 'Lost': 3}]

In [35]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/series/v1/10201"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())
result7=response.json()

{'matchDetails': [{'matchDetailsMap': {'key': 'Wed, 01 Oct 2025', 'match': [{'matchInfo': {'matchId': 122517, 'seriesId': 10201, 'seriesName': 'Australia tour of New Zealand, 2025', 'matchDesc': '1st T20I', 'matchFormat': 'T20', 'startDate': '1759299300000', 'endDate': '1759299300000', 'state': 'complete', 'status': 'Australia won by 6 wkts', 'team1': {'teamId': 13, 'teamName': 'NEW ZEALAND', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 4, 'teamName': 'AUSTRALIA', 'teamSName': 'AUS', 'imageId': 776202}, 'venueInfo': {'ground': 'Bay Oval', 'city': 'Mount Maunganui', 'timezone': '+13:00'}, 'currBatTeamId': 4, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 181, 'wickets': 6, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 185, 'wickets': 4, 'overs': 16.3}}}}], 'seriesId': 10201}}, {'adDetail': {'name': 'native_news_index_random_1', 'layout': 'native_large', 'position': 1}}, {'matchDetailsMap': {'key': 'Fri, 03 Oct 2025', 'match': [{'matchInfo': {'matchId': 122522, 'seriesId': 10201, 'seriesName': 'Australia tour of New Zealand, 2025', 'matchDesc': '2nd T20I', 'matchFormat': 'T20', 'startDate': '1759472100000', 'endDate': '1759472100000', 'state': 'complete', 'status': 'No result due to rain', 'team1': {'teamId': 13, 'teamName': 'NEW ZEALAND', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 4, 'teamName': 'AUSTRALIA', 'teamSName': 'AUS', 'imageId': 776202}, 'venueInfo': {'ground': 'Bay Oval', 'city': 'Mount Maunganui', 'timezone': '+13:00'}, 'currBatTeamId': 4, 'isTimeAnnounced': True}, 'matchScore': {'team2Score': {'inngs1': {'inningsId': 1, 'runs': 16, 'wickets': 1, 'overs': 2.1}}}}], 'seriesId': 10201}}, {'matchDetailsMap': {'key': 'Sat, 04 Oct 2025', 'match': [{'matchInfo': {'matchId': 122528, 'seriesId': 10201, 'seriesName': 'Australia tour of New Zealand, 2025', 'matchDesc': '3rd T20I', 'matchFormat': 'T20', 'startDate': '1759558500000', 'endDate': '1759558500000', 'state': 'complete', 'status': 'Australia won by 3 wkts', 'team1': {'teamId': 13, 'teamName': 'NEW ZEALAND', 'teamSName': 'NZ', 'imageId': 776333}, 'team2': {'teamId': 4, 'teamName': 'AUSTRALIA', 'teamSName': 'AUS', 'imageId': 776202}, 'venueInfo': {'ground': 'Bay Oval', 'city': 'Mount Maunganui', 'timezone': '+13:00'}, 'currBatTeamId': 4, 'isTimeAnnounced': True}, 'matchScore': {'team1Score': {'inngs1': {'inningsId': 1, 'runs': 156, 'wickets': 9, 'overs': 20.0}}, 'team2Score': {'inngs1': {'inningsId': 2, 'runs': 160, 'wickets': 7, 'overs': 18.0}}}}], 'seriesId': 10201}}], 'appIndex': {'seoTitle': 'Australia tour of New Zealand, 2025 live scores, schedule and results - Cricbuzz | Cricbuzz.com', 'webURL': 'www.cricbuzz.com/cricket-series/'}}

In [36]:
win = 0
loose = 0

for i in result7['matchDetails']:
    if not i.get('matchDetailsMap'):
        continue

    match_info = i['matchDetailsMap']['match'][0]['matchInfo']
    status = match_info.get('status', "")

    if "abandoned" in status.lower() or "no result" in status.lower():
        continue

    if "won" in status:
        if "new zealand" in status.lower():  
            win += 1
        else:                    
            loose += 1


res7 = [
    {
        "Team": "New Zealand",
        "Series": "Home Series",
        "Wins": win,
        "Lost": loose
    },
    {
        "Team": "Australia",
        "Series": "Away Series",
        "Wins": loose,
        "Lost": win
    }
]

print(res7)

[{'Team': 'New Zealand', 'Series': 'Home Series', 'Wins': 0, 'Lost': 2}, {'Team': 'Australia', 'Series': 'Away Series', 'Wins': 2, 'Lost': 0}]

In [37]:
final=res1+res2+res3+res4+res5+res6+res7
final_results0 = pd.DataFrame(final)

print(final_results0)

           Team       Series  Wins  Lost
0         India  Home Series     5     4
1   SouthAfrica  Away Series     4     5
2         India  Away Series     2     2
3       England  Home Series     2     2
4       Ireland  Home Series     0     2
5       England  Away Series     2     0
6    Bangladesh  Home Series     4     1
7       Ireland  Away Series     1     4
8      Pakistan  Home Series     3     0
9      SriLanka  Away Series     0     3
10  West Indies  Home Series     3     3
11     Pakistan  Away Series     3     3
12  New Zealand  Home Series     0     2
13    Australia  Away Series     2     0

In [40]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

ITP = pd.DataFrame(final_results0)
table_name = "Team_Performance"  

engine = create_engine(
    f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


ITP.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz Team_Performance

C:\Users\Dell\AppData\Local\Temp\ipykernel_16412\1497268549.py:24: UserWarning: The provided table name 'Team_Performance' is not found exactly as such in the database after writing the table, possibly due to case sensitivity issues. Consider using lower case table names.
  ITP.to_sql(table_name, con=engine, if_exists='replace', index=False)

Q.13 

Identify batting partnerships where two consecutive batsmen (batting positions next to each other) scored a combined total of 100 or more runs in the same innings. Show both player names, their combined partnership runs, and which innings it occurred in.

In [41]:
import requests

url = "https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/135041/scard"

headers = {
	"x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
}

response = requests.get(url, headers=headers)

print(response.json())

{'scorecard': [{'inningsid': 1, 'batsman': [{'id': 6710, 'balls': 4, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Balbirnie', 'nickname': '', 'iscaptain': True, 'iskeeper': False, 'outdec': 'lbw b Hasan Mahmud', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 1114, 'balls': 76, 'runs': 60, 'fours': 9, 'sixes': 0, 'strkrate': '78.95', 'name': 'Stirling', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Shadman Islam b Nahid Rana', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 1451963, 'balls': 129, 'runs': 59, 'fours': 7, 'sixes': 0, 'strkrate': '45.74', 'name': 'Cade Carmichael', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Shanto b Mehidy Hasan Miraz', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11130, 'balls': 6, 'runs': 1, 'fours': 0, 'sixes': 0, 'strkrate': '16.67', 'name': 'Harry Tector', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'lbw b Mehidy Hasan Miraz', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 18143, 'balls': 94, 'runs': 44, 'fours': 4, 'sixes': 2, 'strkrate': '46.81', 'name': 'Curtis Campher', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Shanto b Hasan Murad', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11131, 'balls': 80, 'runs': 41, 'fours': 3, 'sixes': 2, 'strkrate': '51.25', 'name': 'Lorcan Tucker', 'nickname': '', 'iscaptain': False, 'iskeeper': True, 'outdec': 'st Litton Das b Hasan Murad', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 9667, 'balls': 35, 'runs': 5, 'fours': 1, 'sixes': 0, 'strkrate': '14.29', 'name': 'Andy McBrine', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'st Litton Das b Mehidy Hasan Miraz', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 54252, 'balls': 60, 'runs': 30, 'fours': 3, 'sixes': 1, 'strkrate': '50', 'name': 'Jordan Neill', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'lbw b Taijul Islam', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 10451, 'balls': 64, 'runs': 31, 'fours': 4, 'sixes': 0, 'strkrate': '48.44', 'name': 'Barry McCarthy', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'b Hasan Mahmud', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 23506, 'balls': 2, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Matthew Humphreys', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'lbw b Taijul Islam', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 6575, 'balls': 4, 'runs': 6, 'fours': 0, 'sixes': 1, 'strkrate': '150', 'name': 'Craig Young', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'bowler': [{'id': 13226, 'overs': '13.2', 'maidens': 4, 'wickets': 2, 'runs': 42, 'economy': '3.2', 'name': 'Hasan Mahmud', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 80, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 37581, 'overs': '14', 'maidens': 0, 'wickets': 1, 'runs': 65, 'economy': '4.6', 'name': 'Nahid Rana', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 84, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8253, 'overs': '22', 'maidens': 6, 'wickets': 2, 'runs': 78, 'economy': '3.5', 'name': 'Taijul Islam', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 132, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 15535, 'overs': '20', 'maidens': 5, 'wickets': 2, 'runs': 47, 'economy': '2.4', 'name': 'Hasan Murad', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 120, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11081, 'overs': '23', 'maidens': 6, 'wickets': 3, 'runs': 50, 'economy': '2.2', 'name': 'Mehidy Hasan Miraz', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 138, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'fow': {'fow': [{'batsmanid': 6710, 'batsmanname': 'Balbirnie', 'overnbr': 0.4, 'runs': 0, 'ballnbr': 4}, {'batsmanid': 1114, 'batsmanname': 'Stirling', 'overnbr': 26.3, 'runs': 96, 'ballnbr': 159}, {'batsmanid': 11130, 'batsmanname': 'Harry Tector', 'overnbr': 27.5, 'runs': 97, 'ballnbr': 167}, {'batsmanid': 1451963, 'batsmanname': 'Cade Carmichael', 'overnbr': 43.2, 'runs': 150, 'ballnbr': 260}, {'batsmanid': 18143, 'batsmanname': 'Curtis Campher', 'overnbr': 63.3, 'runs': 203, 'ballnbr': 381}, {'batsmanid': 11131, 'batsmanname': 'Lorcan Tucker', 'overnbr': 67.4, 'runs': 218, 'ballnbr': 406}, {'batsmanid': 9667, 'batsmanname': 'Andy McBrine', 'overnbr': 72.5, 'runs': 222, 'ballnbr': 437}, {'batsmanid': 54252, 'batsmanname': 'Jordan Neill', 'overnbr': 89.6, 'runs': 270, 'ballnbr': 540}, {'batsmanid': 23506, 'batsmanname': 'Matthew Humphreys', 'overnbr': 91.2, 'runs': 278, 'ballnbr': 548}, {'batsmanid': 10451, 'batsmanname': 'Barry McCarthy', 'overnbr': 92.2, 'runs': 286, 'ballnbr': 554}]}, 'extras': {'legbyes': 4, 'byes': 0, 'wides': 5, 'noballs': 0, 'penalty': 0, 'total': 9}, 'score': 286, 'wickets': 10, 'overs': 92.2, 'runrate': 3.1, 'batteamname': 'Ireland', 'batteamsname': 'IRE', 'isdeclared': False, 'isfollowon': False, 'ballnbr': 554, 'rpb': 0.52, 'partnership': {'partnership': [{'id': 0, 'bat1id': 6710, 'bat1name': 'Balbirnie', 'bat1runs': 0, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 1114, 'bat2name': 'Stirling', 'bat2runs': 0, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 0, 'totalballs': 4, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 1451963, 'bat1name': 'Cade Carmichael', 'bat1runs': 30, 'bat1fours': 3, 'bat1sixes': 0, 'bat2id': 1114, 'bat2name': 'Stirling', 'bat2runs': 60, 'bat2fours': 9, 'bat2sixes': 0, 'totalruns': 96, 'totalballs': 155, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 1451963, 'bat1name': 'Cade Carmichael', 'bat1runs': 0, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 11130, 'bat2name': 'Tector', 'bat2runs': 1, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 1, 'totalballs': 8, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 1451963, 'bat1name': 'Cade Carmichael', 'bat1runs': 29, 'bat1fours': 4, 'bat1sixes': 0, 'bat2id': 18143, 'bat2name': 'Curtis Campher', 'bat2runs': 23, 'bat2fours': 2, 'bat2sixes': 1, 'totalruns': 53, 'totalballs': 93, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Tucker', 'bat1runs': 30, 'bat1fours': 3, 'bat1sixes': 1, 'bat2id': 18143, 'bat2name': 'Curtis Campher', 'bat2runs': 21, 'bat2fours': 2, 'bat2sixes': 1, 'totalruns': 53, 'totalballs': 121, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 11131, 'bat1name': 'Tucker', 'bat1runs': 11, 'bat1fours': 0, 'bat1sixes': 1, 'bat2id': 9667, 'bat2name': 'Andy McBrine', 'bat2runs': 4, 'bat2fours': 1, 'bat2sixes': 0, 'totalruns': 15, 'totalballs': 25, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 54252, 'bat1name': 'Jordan Neill', 'bat1runs': 3, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 9667, 'bat2name': 'Andy McBrine', 'bat2runs': 1, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 4, 'totalballs': 31, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 54252, 'bat1name': 'Jordan Neill', 'bat1runs': 27, 'bat1fours': 3, 'bat1sixes': 1, 'bat2id': 10451, 'bat2name': 'McCarthy', 'bat2runs': 21, 'bat2fours': 2, 'bat2sixes': 0, 'totalruns': 48, 'totalballs': 103, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 10451, 'bat1name': 'McCarthy', 'bat1runs': 8, 'bat1fours': 2, 'bat1sixes': 0, 'bat2id': 23506, 'bat2name': 'Humphreys', 'bat2runs': 0, 'bat2fours': 0, 'bat2sixes': 0, 'totalruns': 8, 'totalballs': 8, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}, {'id': 0, 'bat1id': 10451, 'bat1name': 'McCarthy', 'bat1runs': 2, 'bat1fours': 0, 'bat1sixes': 0, 'bat2id': 6575, 'bat2name': 'Young', 'bat2runs': 6, 'bat2fours': 0, 'bat2sixes': 1, 'totalruns': 8, 'totalballs': 6, 'bat1balls': 0, 'bat2balls': 0, 'teamname': '', 'teamid': 0, 'bat1ones': 0, 'bat1twos': 0, 'bat1threes': 0, 'bat1fives': 0, 'bat1boundaries': 0, 'bat1sixers': 0, 'bat2ones': 0, 'bat2twos': 0, 'bat2threes': 0, 'bat2fives': 0, 'bat2boundaries': 0, 'bat2sixers': 0}]}}, {'inningsid': 2, 'batsman': [{'id': 14273, 'balls': 286, 'runs': 171, 'fours': 14, 'sixes': 4, 'strkrate': '59.79', 'name': 'Mahmudul Hasan Joy', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Lorcan Tucker b Barry McCarthy', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 9868, 'balls': 104, 'runs': 80, 'fours': 9, 'sixes': 1, 'strkrate': '76.92', 'name': 'Shadman Islam', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Lorcan Tucker b Matthew Humphreys', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8219, 'balls': 132, 'runs': 82, 'fours': 5, 'sixes': 2, 'strkrate': '62.12', 'name': 'Mominul', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Balbirnie b Barry McCarthy', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 9864, 'balls': 114, 'runs': 100, 'fours': 14, 'sixes': 0, 'strkrate': '87.72', 'name': 'Shanto', 'nickname': '', 'iscaptain': True, 'iskeeper': False, 'outdec': 'lbw b Andy McBrine', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 394, 'balls': 52, 'runs': 23, 'fours': 3, 'sixes': 0, 'strkrate': '44.23', 'name': 'Mushfiqur Rahim', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Balbirnie b Matthew Humphreys', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8540, 'balls': 66, 'runs': 60, 'fours': 8, 'sixes': 1, 'strkrate': '90.91', 'name': 'Litton Das', 'nickname': '', 'iscaptain': False, 'iskeeper': True, 'outdec': 'c Harry Tector b Matthew Humphreys', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11081, 'balls': 33, 'runs': 17, 'fours': 2, 'sixes': 0, 'strkrate': '51.52', 'name': 'Mehidy Hasan Miraz', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c and b Matthew Humphreys', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 15535, 'balls': 26, 'runs': 16, 'fours': 4, 'sixes': 0, 'strkrate': '61.54', 'name': 'Hasan Murad', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'c Curtis Campher b Matthew Humphreys', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 13226, 'balls': 28, 'runs': 13, 'fours': 2, 'sixes': 0, 'strkrate': '46.43', 'name': 'Hasan Mahmud', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 37581, 'balls': 6, 'runs': 4, 'fours': 1, 'sixes': 0, 'strkrate': '66.67', 'name': 'Nahid Rana', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': 'not out', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 8253, 'balls': 0, 'runs': 0, 'fours': 0, 'sixes': 0, 'strkrate': '0', 'name': 'Taijul Islam', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'outdec': '', 'videotype': '', 'videourl': '', 'videoid': 0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'iscbplusfree': False, 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'bowler': [{'id': 10451, 'overs': '17', 'maidens': 3, 'wickets': 2, 'runs': 72, 'economy': '4.2', 'name': 'Barry McCarthy', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 102, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 6575, 'overs': '12', 'maidens': 0, 'wickets': 0, 'runs': 54, 'economy': '4.5', 'name': 'Craig Young', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 72, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 9667, 'overs': '39', 'maidens': 6, 'wickets': 1, 'runs': 141, 'economy': '3.6', 'name': 'Andy McBrine', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 234, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 54252, 'overs': '11', 'maidens': 0, 'wickets': 0, 'runs': 60, 'economy': '5.5', 'name': 'Jordan Neill', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 66, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 23506, 'overs': '43', 'maidens': 1, 'wickets': 5, 'runs': 170, 'economy': '4', 'name': 'Matthew Humphreys', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 258, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 18143, 'overs': '10', 'maidens': 0, 'wickets': 0, 'runs': 45, 'economy': '4.5', 'name': 'Curtis Campher', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 60, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}, {'id': 11130, 'overs': '9', 'maidens': 1, 'wickets': 0, 'runs': 31, 'economy': '3.4', 'name': 'Harry Tector', 'nickname': '', 'iscaptain': False, 'iskeeper': False, 'videotype': '', 'videourl': '', 'videoid': 0, 'dots': 0, 'balls': 54, 'rpb': 0.0, 'planid': 0, 'imageid': 0, 'premiumvideourl': '', 'ispremiumfree': False, 'inmatchchange': '', 'isoverseas': False, 'playingxichange': ''}], 'fow': {'fow': [{'batsmanid': 9868, 

In [42]:
scorecard = response.json()
scorecard['appindex']['seotitle']

'Cricket scorecard - BAN vs IRE 1st Test,Ireland tour of Bangladesh, 2025 | Cricbuzz.com'

In [43]:
partnerships_100 = []

for innings in scorecard['scorecard']:
    innings_no = innings['inningsid']
    
    for p in innings['partnership']['partnership']:
        total_runs = p['totalruns']

        if total_runs >= 100:
            batsman1 = p['bat1name']
            batsman2 = p['bat2name']

            partnerships_100.append({
                "match_details" : "BAN vs IRE 1st Test,Ireland tour of Bangladesh, 2025",
                "innings_id": innings_no,
                "batsman_1": batsman1,
                "batsman_2": batsman2,
                "total_runs": total_runs
            })
partnerships_100

[{'match_details': 'BAN vs IRE 1st Test,Ireland tour of Bangladesh, 2025',
  'innings_id': 2,
  'batsman_1': 'Mahmudul Hasan Joy',
  'batsman_2': 'Shadman Islam',
  'total_runs': 168},
 {'match_details': 'BAN vs IRE 1st Test,Ireland tour of Bangladesh, 2025',
  'innings_id': 2,
  'batsman_1': 'Mahmudul Hasan Joy',
  'batsman_2': 'Mominul',
  'total_runs': 173}]

In [44]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

Partnership = pd.DataFrame(partnerships_100)
table_name = "partnership"

engine = create_engine(
f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


Partnership.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz partnership

In [ ]:
Q.14 

Examine bowling performance at different venues. For bowlers who have played at least 3 matches at the same venue, calculate their average economy rate, total wickets taken, and number of matches played at each venue. Focus on bowlers who bowled at least 4 overs in each match.

In [45]:
match_ids=[89665, 89721, 89745, 89779, 91420, 91443, 91479, 91528, 91564, 91596, 91618, 91658, 91677, 91726, 91736, 91740]
import requests
data=[]
for i in match_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{i}"
    headers = {
	    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
    	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }

    response = requests.get(url, headers=headers)
    try:
        json_data = response.json()
        data.append(json_data)
    except:
        continue
data

[{'matchid': 89665,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '3rd Match',
  'matchformat': 'T20',
  'startdate': 1711202400000,
  'enddate': 1711216417335,
  'state': 'Complete',
  'status': 'Sunrisers Hyderabad opt to bowl',
  'team1': {'teamid': 63,
   'teamname': 'Kolkata Knight Riders',
   'teamsname': 'KKR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 255,
   'teamname': 'Sunrisers Hyderabad',
   'teamsname': 'SRH',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8867, 'name': 'Rohan Pandit', 'country': 'IND'},
  'umpire2': {'id': 10279, 'name': 'Yeshwant Barde', 'country': 'IND'},
  'umpire3': {'id': 6841, 'name': 'Bruce Oxenford', 'country': 'AUS'},
  'referee': {'id': 7596, 'name': 'Manu Nayyar', 'country': 'IND'},
  'venueinfo': {'id': 31,
   'ground': 'Eden Gardens',
   'city': 'Kolkata',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1864,
   'capacity': '63000',
   'knownas': '',
   'ends': 'High Court End, Pavilion End',
   'hometeam': 'Bengal, Kolkata Knight Riders',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts KKR vs SRH 3rd Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/89665/kkr-vs-srh-3rd-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Sunrisers Hyderabad opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'KKR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 387017,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 89745,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '16th Match',
  'matchformat': 'T20',
  'startdate': 1712152800000,
  'enddate': 1712166555184,
  'state': 'Complete',
  'status': 'Kolkata Knight Riders opt to bat',
  'team1': {'teamid': 61,
   'teamname': 'Delhi Capitals',
   'teamsname': 'DC',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 63,
   'teamname': 'Kolkata Knight Riders',
   'teamsname': 'KKR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 7500, 'name': 'Ulhas Gandhe', 'country': 'IND'},
  'umpire2': {'id': 14178, 'name': 'Akshay Totre', 'country': 'IND'},
  'umpire3': {'id': 3576, 'name': 'Kumar Dharmasena', 'country': 'SL'},
  'referee': {'id': 9225, 'name': 'Prakash Bhatt', 'country': 'IND'},
  'venueinfo': {'id': 154,
   'ground': 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
   'city': 'Visakhapatnam',
   'country': 'India',
   'timezone': '+05:30',
   'established': 2003,
   'capacity': '28,000',
   'knownas': '',
   'ends': 'Vizzy End, DV Subba Rao End',
   'hometeam': 'Andhra',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts DC vs KKR 16th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/89745/dc-vs-kkr-16th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Kolkata Knight Riders opt to bat',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'KKR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402052,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91420,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '28th Match',
  'matchformat': 'T20',
  'startdate': 1713088800000,
  'enddate': 1713101385030,
  'state': 'Complete',
  'status': 'Kolkata Knight Riders opt to bowl',
  'team1': {'teamid': 63,
   'teamname': 'Kolkata Knight Riders',
   'teamsname': 'KKR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 966,
   'teamname': 'Lucknow Super Giants',
   'teamsname': 'LSG',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 14178, 'name': 'Akshay Totre', 'country': 'IND'},
  'umpire2': {'id': 13663, 'name': 'Vinod Seshan', 'country': 'IND'},
  'umpire3': {'id': 8871, 'name': 'KN Anantha Padmanabhan', 'country': 'IND'},
  'referee': {'id': 8864, 'name': 'Amit Sharma', 'country': 'IND'},
  'venueinfo': {'id': 31,
   'ground': 'Eden Gardens',
   'city': 'Kolkata',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1864,
   'capacity': '63000',
   'knownas': '',
   'ends': 'High Court End, Pavilion End',
   'hometeam': 'Bengal, Kolkata Knight Riders',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts KKR vs LSG 28th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/91420/kkr-vs-lsg-28th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Kolkata Knight Riders opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'KKR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402133,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91443,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '31st Match',
  'matchformat': 'T20',
  'startdate': 1713276000000,
  'enddate': 1713290927739,
  'state': 'Complete',
  'status': 'Rajasthan Royals opt to bowl',
  'team1': {'teamid': 63,
   'teamname': 'Kolkata Knight Riders',
   'teamsname': 'KKR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 64,
   'teamname': 'Rajasthan Royals',
   'teamsname': 'RR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8034, 'name': 'Michael Gough', 'country': 'ENG'},
  'umpire2': {'id': 7500, 'name': 'Ulhas Gandhe', 'country': 'IND'},
  'umpire3': {'id': 8871, 'name': 'KN Anantha Padmanabhan', 'country': 'IND'},
  'referee': {'id': 8864, 'name': 'Amit Sharma', 'country': 'IND'},
  'venueinfo': {'id': 31,
   'ground': 'Eden Gardens',
   'city': 'Kolkata',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1864,
   'capacity': '63000',
   'knownas': '',
   'ends': 'High Court End, Pavilion End',
   'hometeam': 'Bengal, Kolkata Knight Riders',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts KKR vs RR 31st Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/91443/kkr-vs-rr-31st-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Rajasthan Royals opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'RR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 430855,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91479,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '36th Match',
  'matchformat': 'T20',
  'startdate': 1713693600000,
  'enddate': 1713708578980,
  'state': 'Complete',
  'status': 'Royal Challengers Bengaluru opt to bowl',
  'team1': {'teamid': 63,
   'teamname': 'Kolkata Knight Riders',
   'teamsname': 'KKR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 59,
   'teamname': 'Royal Challengers Bengaluru',
   'teamsname': 'RCB',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 14178, 'name': 'Akshay Totre', 'country': 'IND'},
  'umpire2': {'id': 13663, 'name': 'Vinod Seshan', 'country': 'IND'},
  'umpire3': {'id': 8034, 'name': 'Michael Gough', 'country': 'ENG'},
  'referee': {'id': 8864, 'name': 'Amit Sharma', 'country': 'IND'},
  'venueinfo': {'id': 31,
   'ground': 'Eden Gardens',
   'city': 'Kolkata',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1864,
   'capacity': '63000',
   'knownas': '',
   'ends': 'High Court End, Pavilion End',
   'hometeam': 'Bengal, Kolkata Knight Riders',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts KKR vs RCB 36th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/91479/kkr-vs-rcb-36th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Royal Challengers Bengaluru opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'KKR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402193,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91528,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '42nd Match',
  'matchformat': 'T20',
  'startdate': 1714140000000,
  'enddate': 1714153636570,
  'state': 'Complete',
  'status': 'Punjab Kings opt to bowl',
  'team1': {'teamid': 63,
   'teamname': 'Kolkata Knight Riders',
   'teamsname': 'KKR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 65,
   'teamname': 'Punjab Kings',
   'teamsname': 'PBKS',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8294, 'name': 'Anil Chaudhary', 'country': 'IND'},
  'umpire2': {'id': 10279, 'name': 'Yeshwant Barde', 'country': 'IND'},
  'umpire3': {'id': 8867, 'name': 'Rohan Pandit', 'country': 'IND'},
  'referee': {'id': 8912, 'name': 'Sanjay Verma', 'country': 'IND'},
  'venueinfo': {'id': 31,
   'ground': 'Eden Gardens',
   'city': 'Kolkata',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1864,
   'capacity': '63000',
   'knownas': '',
   'ends': 'High Court End, Pavilion End',
   'hometeam': 'Bengal, Kolkata Knight Riders',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts KKR vs PBKS 42nd Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/91528/kkr-vs-pbks-42nd-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Punjab Kings opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'PBKS won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402220,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91564,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '47th Match',
  'matchformat': 'T20',
  'startdate': 1714399200000,
  'enddate': 1714411764283,
  'state': 'Complete',
  'status': 'Delhi Capitals opt to bat',
  'team1': {'teamid': 63,
   'teamname': 'Kolkata Knight Riders',
   'teamsname': 'KKR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 61,
   'teamname': 'Delhi Capitals',
   'teamsname': 'DC',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 9678, 'name': 'Navdeep Singh', 'country': 'IND'},
  'umpire2': {'id': 9608, 'name': 'Tapan Sharma', 'country': 'IND'},
  'umpire3': {'id': 8870, 'name': 'Nikhil Patwardhan', 'country': 'IND'},
  'referee': {'id': 8968,
   'name': 'Vengalil Narayanan Kutty',
   'country': 'IND'},
  'venueinfo': {'id': 31,
   'ground': 'Eden Gardens',
   'city': 'Kolkata',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1864,
   'capacity': '63000',
   'knownas': '',
   'ends': 'High Court End, Pavilion End',
   'hometeam': 'Bengal, Kolkata Knight Riders',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts KKR vs DC 47th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/91564/kkr-vs-dc-47th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Delhi Capitals opt to bat',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'KKR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402248,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91596,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '51st Match',
  'matchformat': 'T20',
  'startdate': 1714744800000,
  'enddate': 1714758342415,
  'state': 'Complete',
  'status': 'Mumbai Indians opt to bowl',
  'team1': {'teamid': 62,
   'teamname': 'Mumbai Indians',
   'teamsname': 'MI',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 63,
   'teamname': 'Kolkata Knight Riders',
   'teamsname': 'KKR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8905, 'name': 'Jayaraman Madanagopal', 'country': 'IND'},
  'umpire2': {'id': 9608, 'name': 'Tapan Sharma', 'country': 'IND'},
  'umpire3': {'id': 8034, 'name': 'Michael Gough', 'country': 'ENG'},
  'referee': {'id': 1820, 'name': 'Pankaj Dharmani', 'country': 'IND'},
  'venueinfo': {'id': 81,
   'ground': 'Wankhede Stadium',
   'city': 'Mumbai',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1974,

In [46]:
match_venue_details=[]
for data1 in data:
    match_id = data1.get("matchid")
    venue = data1.get("venueinfo", {})
    venue_id = venue.get("id")
    venue_ground = venue.get("ground")
    #venue_city = venue.get("city")
    #venue_country = venue.get("country")

    result = {
        "Match ID": match_id,
        "Venue ID": venue_id,
        "Ground": venue_ground,
        #"City": venue_city,
        #"Country": venue_country
    }
    match_venue_details.append(result)
match_venue_details

[{'Match ID': 89665, 'Venue ID': 31, 'Ground': 'Eden Gardens'},
 {'Match ID': 89745,
  'Venue ID': 154,
  'Ground': 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'},
 {'Match ID': 91420, 'Venue ID': 31, 'Ground': 'Eden Gardens'},
 {'Match ID': 91443, 'Venue ID': 31, 'Ground': 'Eden Gardens'},
 {'Match ID': 91479, 'Venue ID': 31, 'Ground': 'Eden Gardens'},
 {'Match ID': 91528, 'Venue ID': 31, 'Ground': 'Eden Gardens'},
 {'Match ID': 91564, 'Venue ID': 31, 'Ground': 'Eden Gardens'},
 {'Match ID': 91596, 'Venue ID': 81, 'Ground': 'Wankhede Stadium'},
 {'Match ID': 91618,
  'Venue ID': 485,
  'Ground': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium'},
 {'Match ID': 91677, 'Venue ID': 50, 'Ground': 'Narendra Modi Stadium'},
 {'Match ID': 91740, 'Venue ID': 11, 'Ground': 'MA Chidambaram Stadium'}]

In [47]:
match_ids=[89665, 89721, 89745, 89779, 91420, 91443, 91479, 91528, 91564, 91596, 91618, 91658, 91677, 91726, 91736, 91740]
score_card=[]
for i in match_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{i}/scard"

    headers = {
	    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }

    response = requests.get(url, headers=headers)
    try:
        json_data = response.json()
        score_card.append(json_data)
    except:
        continue

score_card

[{'scorecard': [{'inningsid': 1,
    'batsman': [{'id': 10479,
      'balls': 40,
      'runs': 54,
      'fours': 3,
      'sixes': 3,
      'strkrate': '135',
      'name': 'Salt',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': True,
      'outdec': 'c Marco Jansen b Markande',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 2276,
      'balls': 4,
      'runs': 2,
      'fours': 0,
      'sixes': 0,
      'strkrate': '50',
      'name': 'Narine',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'run out (Shahbaz Ahmed)',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 10917,
      'balls': 5,
      'runs': 7,
      'fours': 1,
      'sixes': 0,
      'strkrate': '140',
      'name': 'Venkatesh Iyer',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Marco Jansen b T Natarajan',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9428,
      'balls': 2,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Shreyas Iyer',
      'nickname': '',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'c Cummins b T Natarajan',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9204,
      'balls': 11,
      'runs': 9,
      'fours': 1,
      'sixes': 0,
      'strkrate': '81.82',
      'name': 'Nitish Rana',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Tripathi b Markande',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 12337,
      'balls': 17,
      'runs': 35,
      'fours': 1,
      'sixes': 4,
      'strkrate': '205.88',
      'name': 'Ramandeep Singh',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Markande b Cummins',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': 'MOUT',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 10896,
      'balls': 15,
      'runs': 23,
      'fours': 3,
      'sixes': 0,
      'strkrate': '153.33',
      'name': 'Rinku Singh',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Markram b T Natarajan',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 7736,
      'balls': 25,
      'runs': 64,
      'fours': 3,
      'sixes': 7,
      'strkrate': '256',
      'name': 'Russell',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 7710,
      'balls': 3,
      'runs': 6,
      'fours': 1,
      'sixes': 0,
      'strkrate': '200',
      'name': 'Starc',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 24729,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Harshit Rana',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 12926,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Chakaravarthy',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 36487,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Suyash Sharma',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': 'MIN',
      'isoverseas': False,
      'playingxichange': ''}],
    'bowler': [{'id': 1726,
      'overs': '4',
      'maidens': 0,
      'wickets': 0,
      'runs': 51,
      'economy': '12.8',
      'name': 'Bhuvneshwar',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 14565,
      'overs': '3',
      'maidens': 0,
      'wickets': 0,
      'runs': 40,
      'economy': '13.3',
      'name': 'Marco Jansen',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 18,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 10225,
      'overs': '4',
      'maidens': 0,
      'wickets': 3,
      'runs': 32,
      'economy': '8',
      'name': 'T Natarajan',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': 'MOUT',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8095,
      'overs': '4',
      'maidens': 0,
      'wickets': 1,
      'runs': 32,
      'economy': '8',
      'name': 'Cummins',
      'nickname': '',
      'iscaptain': True,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 12627,
      'overs': '4',
      'maidens': 0,
      'wickets': 2,
      'runs': 39,
      'economy': '9.8',
      'name': 'Markande',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 14606,
      'overs': '1',
      'maidens': 0,
      'wickets': 0,
      'runs': 14,
      'economy': '14',
      'name': 'Shahbaz Ahmed',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 6,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''}],
    'fow': {'fow': [{'batsmanid': 2276,
       'batsmanname': 'Narine',
       'overnbr': 2.0,
       'runs': 23,
       'ballnbr': 12},
      {'batsmanid': 10917,
       'batsmanname': 'Venkatesh Iyer',
       'overnbr': 3.3,
       'runs': 32,
       'ballnbr': 21},
      {'batsmanid': 9428,
       'batsmanname': 'Shreyas Iyer',
       'overnbr': 3.5,
       'runs': 32,
       'ballnbr': 23},
      {'batsmanid': 9204,
       'batsmanname': 'Nitish Rana',
       'overnbr': 7.3,
       'runs': 51,
       'ballnbr': 45},
      {'batsmanid': 12337,
       'batsmanname': 'Ramandeep Singh ',
       'overnbr': 12.1,
       'runs': 105,
       'ballnbr': 73},
      {'batsmanid': 10479,
       'batsmanname': 'Salt',
       'overnbr': 13.5,
       'runs': 119,
       'ballnbr': 83},
      {'batsmanid': 10896,
       'batsmanname': 'Rinku Singh',
       'overnbr': 19.1,
       'runs': 200,
       'ballnbr': 115}]},
    'extras': {'legbyes': 0,
     'byes': 0,
     'wides': 6,
     'noballs': 2,
     'penalty': 0,
     'total': 8},
    'pp': {'powerplay': [{'id': 1,
       'ovrfrom': 0.1,
       'ovrto': 6.0,
       'pptype': 'Mandatory',
       'run': 43,
       'wickets': 0}]},
    'score': 208,
    'wickets': 7,
    'overs': 20.0,
    'runrate': 10.4,
    'batteamname': 'Kolkata Knight Riders',
    'batteamsname': 'KKR',
    'isdeclared': False,
    'isfollowon': False,
    'ballnbr': 120,
    'rpb': 1.73,
    'partnership': {'partnership': [{'id': 0,
       'bat1id': 10479,
       'bat1name': 'Philip Salt',
       'bat1runs': 19,
       'bat1fours': 0,
       'bat1sixes': 3,
       'bat2id': 2276,
       'bat2name': 'Narine',
       'bat2runs': 2,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 23,
       'totalballs': 12,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 10479,
       'bat1name': 'Philip Salt',
       'bat1runs': 2,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 10917,
       'bat2name': 'Venkatesh Iyer',
       'bat2runs': 7,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 9,
       'totalballs': 9,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 10479,
       'bat1name': 'Philip Salt',
       'bat1runs': 0,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 9428,
       'bat2name': 'Shreyas Iyer',
       'bat2runs': 0,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 0,
       'totalballs': 2,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 10479,
       'bat1name': 'Philip Salt',
       'bat1runs': 9,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 9204,
       'bat2name': 'Nitish Rana',
       'bat2runs': 9,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 19,
       'totalballs': 22,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 10479,
       'bat1name': 'Philip Salt',
       'bat1runs': 18,
       'bat1fours': 2,
       'bat1sixes': 0,
       'bat2id': 12337,
       'bat2name': 'Ramandeep Singh ',
       'bat2runs': 35,
       'bat2fours': 1,
       'bat2sixes': 4,
       'totalruns': 54,
       'totalballs': 29,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 10479,
       'bat1name': 'Philip Salt',
       'bat1runs': 6,
       'bat1fours': 1,
       'bat1sixes': 0,
       'bat2id': 10896,
       'bat2name': 'Rinku Singh',
       'bat2runs': 8,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 14,
       'totalballs': 10,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 7736,
       'bat1name': 'Russell',
       'bat1runs': 62,
       'bat1fours': 3,
       'bat1sixes': 7,
       'bat2id': 10896,
       'bat2name': 'Rinku Singh',
       'bat2runs': 15,
       'bat2fours': 2,
       'bat2sixes': 0,
       'totalruns': 81,
       'totalballs': 33,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 7736,
       'bat1name': 'Russell',
       'bat1runs': 2,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 7710,
       'bat2name': 'Starc',
       'bat2runs': 6,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 8,
       'totalballs': 5,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0}]}},
   {'inningsid': 2,
    'batsman': [{'id': 2195,
      'balls': 21,
      'runs': 32,
      'fours': 4,
      'sixes': 1,
      'strkrate': '152.38',
      'name': 'Mayank Agarwal',
      'nickname': 'Mayank Agarwal',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Rinku Singh b Harshit Rana',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 12086,
      'balls': 19,
      'runs': 32,
      'fours': 4,
      'sixes': 2,
      'strkrate': '168.42',
      'name': 'Abhishek Sharma',
      'nickname': 'Abhishek Sharma',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Chakaravarthy b Russell',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': 'MIN',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9012,
      'balls': 20,
      'runs': 20,
      'fours': 0,
      'sixes': 1,
      'strkrate': '100',
      'name': 'Rahul Tripathi',
      'nickname': 'Tripathi',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Harshit Rana b Narine',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9582,
      'balls': 13,
      'runs': 18,
      'fours': 2,
      'sixes': 0,
      'strkrate': '138.46',
      'name': 'Aiden Markram',
      'nickname': 'Markram',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Rinku Singh b Chakaravarthy',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 10209,
      'balls': 29,
      'runs': 63,
      'fours': 0,
      'sixes': 8,
      'strkrate': '217.24',
      'name': 'Heinrich Klaasen',
      'nickname': 'Klaasen',
      'iscaptain': False,
      'iskeeper': True,
      'outdec': 'c Suyash Sharma b Harshit Rana',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 14628,
      'balls': 11,
      'runs': 15,
      'fours': 1,
      'sixes': 1,
      'strkrate': '136.36',
      'name': 'Abdul Samad',
      'nickname': 'Abdul Samad',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Venkatesh Iyer b Russell',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 14606,
      'balls': 5,
      'runs': 16,
      'fours': 1,
      'sixes': 2,
      'strkrate': '320',

In [48]:

starc_stats = []

for match in score_card:
    scorecard_list = match.get("scorecard", [])
    
    for innings in scorecard_list:
        bowlers = innings.get("bowler", [])
        
        for bowler in bowlers:
            if bowler.get("name", "").lower() in ["starc", "mitchell starc"]:
                starc_stats.append({
                    "match_id": match.get("appindex", {}).get("weburl", "").split("/")[4],
                    #"innings_id": innings.get("inningsid"),
                    "name": bowler.get("name"),
                    "wickets": bowler.get("wickets"),
                    "economy": bowler.get("economy")
                })

starc_stats

[{'match_id': '89665',
  'name': 'Mitchell Starc',
  'wickets': 0,
  'economy': '13.2'},
 {'match_id': '89745',
  'name': 'Mitchell Starc',
  'wickets': 2,
  'economy': '8.3'},
 {'match_id': '91420', 'name': 'Starc', 'wickets': 3, 'economy': '7'},
 {'match_id': '91443',
  'name': 'Mitchell Starc',
  'wickets': 0,
  'economy': '12.5'},
 {'match_id': '91479',
  'name': 'Mitchell Starc',
  'wickets': 1,
  'economy': '18.3'},
 {'match_id': '91564', 'name': 'Starc', 'wickets': 1, 'economy': '14.3'},
 {'match_id': '91596',
  'name': 'Mitchell Starc',
  'wickets': 4,
  'economy': '8.6'},
 {'match_id': '91618',
  'name': 'Mitchell Starc',
  'wickets': 1,
  'economy': '11'},
 {'match_id': '91740', 'name': 'Starc', 'wickets': 2, 'economy': '4.7'}]

In [49]:
for item in starc_stats:
    mid = int(item['match_id'])    

    for m in match_venue_details:
        if m['Match ID'] == mid:
            item['ground'] = m['Ground']
            break

print(starc_stats)

[{'match_id': '89665', 'name': 'Mitchell Starc', 'wickets': 0, 'economy': '13.2', 'ground': 'Eden Gardens'}, {'match_id': '89745', 'name': 'Mitchell Starc', 'wickets': 2, 'economy': '8.3', 'ground': 'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium'}, {'match_id': '91420', 'name': 'Starc', 'wickets': 3, 'economy': '7', 'ground': 'Eden Gardens'}, {'match_id': '91443', 'name': 'Mitchell Starc', 'wickets': 0, 'economy': '12.5', 'ground': 'Eden Gardens'}, {'match_id': '91479', 'name': 'Mitchell Starc', 'wickets': 1, 'economy': '18.3', 'ground': 'Eden Gardens'}, {'match_id': '91564', 'name': 'Starc', 'wickets': 1, 'economy': '14.3', 'ground': 'Eden Gardens'}, {'match_id': '91596', 'name': 'Mitchell Starc', 'wickets': 4, 'economy': '8.6', 'ground': 'Wankhede Stadium'}, {'match_id': '91618', 'name': 'Mitchell Starc', 'wickets': 1, 'economy': '11', 'ground': 'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium'}, {'match_id': '91740', 'name': 'Starc', 'wickets': 2, 'economy': '4.7', 'ground': 'MA Chidambaram Stadium'}]

In [50]:
import pandas as pd
starc_table=pd.DataFrame(starc_stats)
starc_table

,match_id,name,wickets,economy,ground
0,89665,Mitchell Starc,0,13.2,Eden Gardens
1,89745,Mitchell Starc,2,8.3,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...
2,91420,Starc,3,7,Eden Gardens
3,91443,Mitchell Starc,0,12.5,Eden Gardens
4,91479,Mitchell Starc,1,18.3,Eden Gardens
5,91564,Starc,1,14.3,Eden Gardens
6,91596,Mitchell Starc,4,8.6,Wankhede Stadium
7,91618,Mitchell Starc,1,11,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...
8,91740,Starc,2,4.7,MA Chidambaram Stadium

In [51]:
match_ids=[89675, 89704, 89731, 89763, 91398, 91425, 91456, 91489, 91533, 91563, 91596, 91623, 91658, 91699]
import requests
bumrah_data=[]
for i in match_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{i}"
    headers = {
	    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
    	"x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }

    response = requests.get(url, headers=headers)
    try:
        json_data = response.json()
        bumrah_data.append(json_data)
    except:
        continue
bumrah_data

[{'matchid': 89675,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '5th Match',
  'matchformat': 'T20',
  'startdate': 1711288800000,
  'enddate': 1711302619411,
  'state': 'Complete',
  'status': 'Mumbai Indians opt to bowl',
  'team1': {'teamid': 971,
   'teamname': 'Gujarat Titans',
   'teamsname': 'GT',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 62,
   'teamname': 'Mumbai Indians',
   'teamsname': 'MI',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8111, 'name': 'Vineet Kulkarni', 'country': 'IND'},
  'umpire2': {'id': 8909, 'name': 'Virender Sharma', 'country': 'IND'},
  'umpire3': {'id': 8862, 'name': 'Nitin Menon', 'country': 'IND'},
  'referee': {'id': 3894, 'name': 'Javagal Srinath', 'country': 'IND'},
  'venueinfo': {'id': 50,
   'ground': 'Narendra Modi Stadium',
   'city': 'Ahmedabad',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1982,
   'capacity': '132,000',
   'knownas': '',
   'ends': 'Adani Pavilion End, GMDC End',
   'hometeam': 'Gujarat, Gujarat Titans',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts GT vs MI 5th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/89675/gt-vs-mi-5th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Mumbai Indians opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'GT won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 387732,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 89731,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '14th Match',
  'matchformat': 'T20',
  'startdate': 1711980000000,
  'enddate': 1711992473703,
  'state': 'Complete',
  'status': 'Rajasthan Royals opt to bowl',
  'team1': {'teamid': 62,
   'teamname': 'Mumbai Indians',
   'teamsname': 'MI',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 64,
   'teamname': 'Rajasthan Royals',
   'teamsname': 'RR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 10593, 'name': 'Sai Darshan Kumar', 'country': 'IND'},
  'umpire2': {'id': 10279, 'name': 'Yeshwant Barde', 'country': 'IND'},
  'umpire3': {'id': 6841, 'name': 'Bruce Oxenford', 'country': 'AUS'},
  'referee': {'id': 7596, 'name': 'Manu Nayar', 'country': 'IND'},
  'venueinfo': {'id': 81,
   'ground': 'Wankhede Stadium',
   'city': 'Mumbai',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1974,
   'capacity': '33,000',
   'knownas': '',
   'ends': 'Garware Pavilion End, Tata End',
   'hometeam': 'Mumbai, Mumbai Indians',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts MI vs RR 14th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/89731/mi-vs-rr-14th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Rajasthan Royals opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': True,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'RR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402043,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 89763,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '20th Match',
  'matchformat': 'T20',
  'startdate': 1712484000000,
  'enddate': 1712497480376,
  'state': 'Complete',
  'status': 'Delhi Capitals opt to bowl',
  'team1': {'teamid': 62,
   'teamname': 'Mumbai Indians',
   'teamsname': 'MI',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 61,
   'teamname': 'Delhi Capitals',
   'teamsname': 'DC',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 3576, 'name': 'Kumar Dharmasena', 'country': 'SL'},
  'umpire2': {'id': 7500, 'name': 'Ulhas Gandhe', 'country': 'IND'},
  'umpire3': {'id': 8871, 'name': 'KN Anantha Padmanabhan', 'country': 'IND'},
  'referee': {'id': 9225, 'name': 'Prakash Bhatt', 'country': 'IND'},
  'venueinfo': {'id': 81,
   'ground': 'Wankhede Stadium',
   'city': 'Mumbai',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1974,
   'capacity': '33,000',
   'knownas': '',
   'ends': 'Garware Pavilion End, Tata End',
   'hometeam': 'Mumbai, Mumbai Indians',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts MI vs DC 20th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/89763/mi-vs-dc-20th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Delhi Capitals opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'MI won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402064,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91398,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '25th Match',
  'matchformat': 'T20',
  'startdate': 1712844000000,
  'enddate': 1712857397451,
  'state': 'Complete',
  'status': 'Mumbai Indians opt to bowl',
  'team1': {'teamid': 62,
   'teamname': 'Mumbai Indians',
   'teamsname': 'MI',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 59,
   'teamname': 'Royal Challengers Bengaluru',
   'teamsname': 'RCB',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8862, 'name': 'Nitin Menon', 'country': 'IND'},
  'umpire2': {'id': 8111, 'name': 'Vineet Kulkarni', 'country': 'IND'},
  'umpire3': {'id': 8909, 'name': 'Virender Sharma', 'country': 'IND'},
  'referee': {'id': 3894, 'name': 'Javagal Srinath', 'country': 'IND'},
  'venueinfo': {'id': 81,
   'ground': 'Wankhede Stadium',
   'city': 'Mumbai',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1974,
   'capacity': '33,000',
   'knownas': '',
   'ends': 'Garware Pavilion End, Tata End',
   'hometeam': 'Mumbai, Mumbai Indians',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts MI vs RCB 25th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/91398/mi-vs-rcb-25th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Mumbai Indians opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'MI won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 421755,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91425,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '29th Match',
  'matchformat': 'T20',
  'startdate': 1713103200000,
  'enddate': 1713117205865,
  'state': 'Complete',
  'status': 'Mumbai Indians opt to bowl',
  'team1': {'teamid': 62,
   'teamname': 'Mumbai Indians',
   'teamsname': 'MI',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 58,
   'teamname': 'Chennai Super Kings',
   'teamsname': 'CSK',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8862, 'name': 'Nitin Menon', 'country': 'IND'},
  'umpire2': {'id': 9680, 'name': 'Saiyed Khalid', 'country': 'IND'},
  'umpire3': {'id': 8909, 'name': 'Virender Sharma', 'country': 'IND'},
  'referee': {'id': 3894, 'name': 'Javagal Srinath', 'country': 'IND'},
  'venueinfo': {'id': 81,
   'ground': 'Wankhede Stadium',
   'city': 'Mumbai',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1974,
   'capacity': '33,000',
   'knownas': '',
   'ends': 'Garware Pavilion End, Tata End',
   'hometeam': 'Mumbai, Mumbai Indians',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts MI vs CSK 29th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/91425/mi-vs-csk-29th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Mumbai Indians opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'CSK won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402136,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91533,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '43rd Match',
  'matchformat': 'T20',
  'startdate': 1714212000000,
  'enddate': 1714227047896,
  'state': 'Complete',
  'status': 'Mumbai Indians opt to bowl',
  'team1': {'teamid': 61,
   'teamname': 'Delhi Capitals',
   'teamsname': 'DC',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 62,
   'teamname': 'Mumbai Indians',
   'teamsname': 'MI',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 9678, 'name': 'Navdeep Singh', 'country': 'IND'},
  'umpire2': {'id': 8870, 'name': 'Nikhil Patwardhan', 'country': 'IND'},
  'umpire3': {'id': 8905, 'name': 'Jayaraman Madanagopal', 'country': 'IND'},
  'referee': {'id': 8968,
   'name': 'Vengalil Narayanan Kutty',
   'country': 'IND'},
  'venueinfo': {'id': 51,
   'ground': 'Arun Jaitley Stadium',
   'city': 'Delhi',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1883,
   'capacity': '48000',
   'knownas': '',
   'ends': 'Stadium End, Pavilion End',
   'hometeam': 'Delhi, Delhi Capitals',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts DC vs MI 43rd Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/91533/dc-vs-mi-43rd-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Mumbai Indians opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'DC won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402221,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91596,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '51st Match',
  'matchformat': 'T20',
  'startdate': 1714744800000,
  'enddate': 1714758342415,
  'state': 'Complete',
  'status': 'Mumbai Indians opt to bowl',
  'team1': {'teamid': 62,
   'teamname': 'Mumbai Indians',
   'teamsname': 'MI',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 63,
   'teamname': 'Kolkata Knight Riders',
   'teamsname': 'KKR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8905, 'name': 'Jayaraman Madanagopal', 'country': 'IND'},
  'umpire2': {'id': 9608, 'name': 'Tapan Sharma', 'country': 'IND'},
  'umpire3': {'id': 8034, 'name': 'Michael Gough', 'country': 'ENG'},
  'referee': {'id': 1820, 'name': 'Pankaj Dharmani', 'country': 'IND'},
  'venueinfo': {'id': 81,
   'ground': 'Wankhede Stadium',
   'city': 'Mumbai',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1974,
   'capacity': '33,000',
   'knownas': '',
   'ends': 'Garware Pavilion End, Tata End',
   'hometeam': 'Mumbai, Mumbai Indians',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts MI vs KKR 51st Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/91596/mi-vs-kkr-51st-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Mumbai Indians opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'KKR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402272,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91623,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '55th Match',
  'matchformat': 'T20',
  'startdate': 1715004000000,
  'enddate': 1715017345711,
  'state': 'Complete',
  'status': 'Mumbai Indians opt to bowl',
  'team1': {'teamid': 62,
   'teamname': 'Mumbai Indians',
   'teamsname': 'MI',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 255,
   'teamname': 'Sunrisers Hyderabad',
   'teamsname': 'SRH',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 9678, 'name': 'Navdeep Singh', 'country': 'IND'},
  'umpire2': {'id': 9608, 'name': 'Tapan Sharma', 'country': 'IND'},
  'umpire3': {'id': 8905, 'name': 'Jayaraman Madanagopal', 'country': 'IND'},
  'referee': {'id': 1820, 'name': 'Pankaj Dharmani', 'country': 'IND'},
  'venueinfo': {'id': 81,
   'ground': 'Wankhede Stadium',
   'city': 'Mumbai',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1974,
   'capacity': '33,000',
   'knownas': '',
   'ends': 'Garware Pavilion End, Tata End',
   'hometeam': 'Mumbai, Mumbai Indians',

In [52]:
match_venue_details1=[]
for data1 in bumrah_data:
    match_id = data1.get("matchid")
    venue = data1.get("venueinfo", {})
    venue_id = venue.get("id")
    venue_ground = venue.get("ground")
    #venue_city = venue.get("city")
    #venue_country = venue.get("country")

    result = {
        "Match ID": match_id,
        "Venue ID": venue_id,
        "Ground": venue_ground,
        #"City": venue_city,
        #"Country": venue_country
    }
    match_venue_details1.append(result)
match_venue_details1

[{'Match ID': 89675, 'Venue ID': 50, 'Ground': 'Narendra Modi Stadium'},
 {'Match ID': 89731, 'Venue ID': 81, 'Ground': 'Wankhede Stadium'},
 {'Match ID': 89763, 'Venue ID': 81, 'Ground': 'Wankhede Stadium'},
 {'Match ID': 91398, 'Venue ID': 81, 'Ground': 'Wankhede Stadium'},
 {'Match ID': 91425, 'Venue ID': 81, 'Ground': 'Wankhede Stadium'},
 {'Match ID': 91533, 'Venue ID': 51, 'Ground': 'Arun Jaitley Stadium'},
 {'Match ID': 91596, 'Venue ID': 81, 'Ground': 'Wankhede Stadium'},
 {'Match ID': 91623, 'Venue ID': 81, 'Ground': 'Wankhede Stadium'},
 {'Match ID': 91699, 'Venue ID': 81, 'Ground': 'Wankhede Stadium'}]

In [53]:
match_ids=[89675, 89704, 89731, 89763, 91398, 91425, 91456, 91489, 91533, 91563, 91596, 91623, 91658, 91699]
bum_score_card=[]
for i in match_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{i}/scard"

    headers = {
	    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }

    response = requests.get(url, headers=headers)
    try:
        json_data = response.json()
        bum_score_card.append(json_data)
    except:
        continue

bum_score_card

[{'scorecard': [{'inningsid': 1,
    'batsman': [{'id': 1465,
      'balls': 15,
      'runs': 19,
      'fours': 4,
      'sixes': 0,
      'strkrate': '126.67',
      'name': 'W Saha',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': True,
      'outdec': 'b Bumrah',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 11808,
      'balls': 22,
      'runs': 31,
      'fours': 3,
      'sixes': 1,
      'strkrate': '140.91',
      'name': 'Shubman Gill',
      'nickname': '',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'c Rohit b Chawla',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 13866,
      'balls': 39,
      'runs': 45,
      'fours': 3,
      'sixes': 1,
      'strkrate': '115.38',
      'name': 'Sai Sudharsan',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Tilak Varma b Bumrah',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': 'MOUT',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 13214,
      'balls': 11,
      'runs': 17,
      'fours': 1,
      'sixes': 1,
      'strkrate': '154.55',
      'name': 'Azmatullah',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Tilak Varma b Gerald Coetzee',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 6349,
      'balls': 11,
      'runs': 12,
      'fours': 1,
      'sixes': 0,
      'strkrate': '109.09',
      'name': 'David Miller',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Hardik Pandya b Bumrah',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 8204,
      'balls': 5,
      'runs': 6,
      'fours': 0,
      'sixes': 0,
      'strkrate': '120',
      'name': 'Vijay Shankar',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9693,
      'balls': 15,
      'runs': 22,
      'fours': 2,
      'sixes': 1,
      'strkrate': '146.67',
      'name': 'Rahul Tewatia',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Naman Dhir b Gerald Coetzee',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 10738,
      'balls': 3,
      'runs': 4,
      'fours': 0,
      'sixes': 0,
      'strkrate': '133.33',
      'name': 'Rashid Khan',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 1858,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Umesh',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 11595,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Sai Kishore',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 13143,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Spencer Johnson',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 8181,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Mohit Sharma',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': 'MIN',
      'isoverseas': False,
      'playingxichange': ''}],
    'bowler': [{'id': 9647,
      'overs': '3',
      'maidens': 0,
      'wickets': 0,
      'runs': 30,
      'economy': '10',
      'name': 'Hardik Pandya',
      'nickname': '',
      'iscaptain': True,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 18,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9821,
      'overs': '2',
      'maidens': 0,
      'wickets': 0,
      'runs': 25,
      'economy': '12.5',
      'name': 'Luke Wood',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 12,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': 'MOUT',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 9311,
      'overs': '4',
      'maidens': 0,
      'wickets': 3,
      'runs': 14,
      'economy': '3.5',
      'name': 'Bumrah',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 13496,
      'overs': '3',
      'maidens': 0,
      'wickets': 0,
      'runs': 24,
      'economy': '8',
      'name': 'Shams Mulani',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 18,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 466,
      'overs': '3',
      'maidens': 0,
      'wickets': 1,
      'runs': 31,
      'economy': '10.3',
      'name': 'Chawla',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 18,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 36139,
      'overs': '1',
      'maidens': 0,
      'wickets': 0,
      'runs': 13,
      'economy': '13',
      'name': 'Naman Dhir',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 6,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 13320,
      'overs': '4',
      'maidens': 0,
      'wickets': 2,
      'runs': 27,
      'economy': '6.8',
      'name': 'Gerald Coetzee',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''}],
    'fow': {'fow': [{'batsmanid': 1465,
       'batsmanname': 'W Saha',
       'overnbr': 3.6,
       'runs': 31,
       'ballnbr': 24},
      {'batsmanid': 11808,
       'batsmanname': 'Shubman Gill',
       'overnbr': 7.4,
       'runs': 64,
       'ballnbr': 46},
      {'batsmanid': 13214,
       'batsmanname': 'Azmatullah',
       'overnbr': 11.6,
       'runs': 104,
       'ballnbr': 72},
      {'batsmanid': 6349,
       'batsmanname': 'David Miller',
       'overnbr': 16.1,
       'runs': 133,
       'ballnbr': 97},
      {'batsmanid': 13866,
       'batsmanname': 'Sai Sudharsan',
       'overnbr': 16.3,
       'runs': 134,
       'ballnbr': 99},
      {'batsmanid': 9693,
       'batsmanname': 'Rahul Tewatia',
       'overnbr': 19.1,
       'runs': 161,
       'ballnbr': 115}]},
    'extras': {'legbyes': 4,
     'byes': 0,
     'wides': 7,
     'noballs': 1,
     'penalty': 0,
     'total': 12},
    'pp': {'powerplay': [{'id': 4,
       'ovrfrom': 0.1,
       'ovrto': 6.0,
       'pptype': 'Mandatory',
       'run': 47,
       'wickets': 0}]},
    'score': 168,
    'wickets': 6,
    'overs': 20.0,
    'runrate': 8.4,
    'batteamname': 'Gujarat Titans',
    'batteamsname': 'GT',
    'isdeclared': False,
    'isfollowon': False,
    'ballnbr': 120,
    'rpb': 1.4,
    'partnership': {'partnership': [{'id': 0,
       'bat1id': 1465,
       'bat1name': 'Saha',
       'bat1runs': 19,
       'bat1fours': 4,
       'bat1sixes': 0,
       'bat2id': 11808,
       'bat2name': 'Shubman Gill',
       'bat2runs': 11,
       'bat2fours': 2,
       'bat2sixes': 0,
       'totalruns': 31,
       'totalballs': 24,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 13866,
       'bat1name': 'Sai Sudharsan',
       'bat1runs': 7,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 11808,
       'bat2name': 'Shubman Gill',
       'bat2runs': 20,
       'bat2fours': 1,
       'bat2sixes': 1,
       'totalruns': 33,
       'totalballs': 22,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 13866,
       'bat1name': 'Sai Sudharsan',
       'bat1runs': 22,
       'bat1fours': 1,
       'bat1sixes': 1,
       'bat2id': 13214,
       'bat2name': 'Azmatullah',
       'bat2runs': 17,
       'bat2fours': 1,
       'bat2sixes': 1,
       'totalruns': 40,
       'totalballs': 26,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 13866,
       'bat1name': 'Sai Sudharsan',
       'bat1runs': 16,
       'bat1fours': 2,
       'bat1sixes': 0,
       'bat2id': 6349,
       'bat2name': 'Miller',
       'bat2runs': 12,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 29,
       'totalballs': 25,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 13866,
       'bat1name': 'Sai Sudharsan',
       'bat1runs': 0,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 8204,
       'bat2name': 'Shankar',
       'bat2runs': 1,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 1,
       'totalballs': 2,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 9693,
       'bat1name': 'Rahul Tewatia',
       'bat1runs': 22,
       'bat1fours': 2,
       'bat1sixes': 1,
       'bat2id': 8204,
       'bat2name': 'Shankar',
       'bat2runs': 2,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 27,
       'totalballs': 17,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 10738,
       'bat1name': 'Rashid Khan',
       'bat1runs': 4,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 8204,
       'bat2name': 'Shankar',
       'bat2runs': 3,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 7,
       'totalballs': 5,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0}]}},
   {'inningsid': 2,
    'batsman': [{'id': 10276,
      'balls': 4,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Ishan Kishan',
      'nickname': 'Ishan Kishan',
      'iscaptain': False,
      'iskeeper': True,
      'outdec': 'c W Saha b Azmatullah',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 576,
      'balls': 29,
      'runs': 43,
      'fours': 7,
      'sixes': 1,
      'strkrate': '148.28',
      'name': 'Rohit Sharma',
      'nickname': 'Rohit',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'lbw b Sai Kishore',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 36139,
      'balls': 10,
      'runs': 20,
      'fours': 3,
      'sixes': 1,
      'strkrate': '200',
      'name': 'Naman Dhir',
      'nickname': 'Naman Dhir',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'lbw b Azmatullah',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 20538,
      'balls': 38,
      'runs': 46,
      'fours': 2,
      'sixes': 3,
      'strkrate': '121.05',
      'name': 'Dewald Brevis',
      'nickname': 'Dewald Brevis',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c and b Mohit Sharma',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': 'MIN',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 14504,
      'balls': 19,
      'runs': 25,
      'fours': 1,
      'sixes': 1,
      'strkrate': '131.58',
      'name': 'Tilak Varma',
      'nickname': 'Tilak Varma',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c (sub)Abhinav Manohar b Spencer Johnson',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 13169,
      'balls': 10,
      'runs': 11,
      'fours': 1,
      'sixes': 0,
      'strkrate': '110',
      'name': 'Tim David',
      'nickname': 'Tim David',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c David Miller b Mohit Sharma',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': True,
      'playingxichange': ''},
     {'id': 9647,
      'balls': 4,
      'runs': 11,
      'fours': 1,
      'sixes': 1,
      'strkrate': '275',
      'name': 'Hardik Pandya',
      'nickname': 'Hardik Pandya',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'c Rahul Tewatia b Umesh',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,

In [54]:

bumrah_stats = []

for match in bum_score_card:
    scorecard_list = match.get("scorecard", [])
    
    for innings in scorecard_list:
        bowlers = innings.get("bowler", [])
        
        for bowler in bowlers:
            if bowler.get("name", "").lower() in ["bumrah", "jasprit bumrah"]:
                bumrah_stats.append({
                    "match_id": match.get("appindex", {}).get("weburl", "").split("/")[4],
                    #"innings_id": innings.get("inningsid"),
                    "name": bowler.get("name"),
                    "wickets": bowler.get("wickets"),
                    "economy": bowler.get("economy")
                })

bumrah_stats

[{'match_id': '89675', 'name': 'Bumrah', 'wickets': 3, 'economy': '3.5'},
 {'match_id': '89731',
  'name': 'Jasprit Bumrah',
  'wickets': 0,
  'economy': '6.5'},
 {'match_id': '89763',
  'name': 'Jasprit Bumrah',
  'wickets': 2,
  'economy': '5.5'},
 {'match_id': '91398', 'name': 'Bumrah', 'wickets': 5, 'economy': '5.2'},
 {'match_id': '91425', 'name': 'Bumrah', 'wickets': 0, 'economy': '6.8'},
 {'match_id': '91533', 'name': 'Bumrah', 'wickets': 1, 'economy': '8.8'},
 {'match_id': '91596', 'name': 'Bumrah', 'wickets': 3, 'economy': '4.7'},
 {'match_id': '91623', 'name': 'Bumrah', 'wickets': 1, 'economy': '5.8'}]

In [55]:
for item in bumrah_stats:
    mid = int(item['match_id'])    

    for m in match_venue_details1:
        if m['Match ID'] == mid:
            item['ground'] = m['Ground']
            break

print(bumrah_stats)

[{'match_id': '89675', 'name': 'Bumrah', 'wickets': 3, 'economy': '3.5', 'ground': 'Narendra Modi Stadium'}, {'match_id': '89731', 'name': 'Jasprit Bumrah', 'wickets': 0, 'economy': '6.5', 'ground': 'Wankhede Stadium'}, {'match_id': '89763', 'name': 'Jasprit Bumrah', 'wickets': 2, 'economy': '5.5', 'ground': 'Wankhede Stadium'}, {'match_id': '91398', 'name': 'Bumrah', 'wickets': 5, 'economy': '5.2', 'ground': 'Wankhede Stadium'}, {'match_id': '91425', 'name': 'Bumrah', 'wickets': 0, 'economy': '6.8', 'ground': 'Wankhede Stadium'}, {'match_id': '91533', 'name': 'Bumrah', 'wickets': 1, 'economy': '8.8', 'ground': 'Arun Jaitley Stadium'}, {'match_id': '91596', 'name': 'Bumrah', 'wickets': 3, 'economy': '4.7', 'ground': 'Wankhede Stadium'}, {'match_id': '91623', 'name': 'Bumrah', 'wickets': 1, 'economy': '5.8', 'ground': 'Wankhede Stadium'}]

In [56]:
import pandas as pd
bumrah_table=pd.DataFrame(bumrah_stats)
bumrah_table

  match_id            name  wickets economy                 ground
0    89675          Bumrah        3     3.5  Narendra Modi Stadium
1    89731  Jasprit Bumrah        0     6.5       Wankhede Stadium
2    89763  Jasprit Bumrah        2     5.5       Wankhede Stadium
3    91398          Bumrah        5     5.2       Wankhede Stadium
4    91425          Bumrah        0     6.8       Wankhede Stadium
5    91533          Bumrah        1     8.8   Arun Jaitley Stadium
6    91596          Bumrah        3     4.7       Wankhede Stadium
7    91623          Bumrah        1     5.8       Wankhede Stadium

In [60]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

table_name = "starc_data"

engine = create_engine(
f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


starc_table.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz starc_data

In [61]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

table_name = "bumrah_data"

engine = create_engine(
f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


bumrah_table.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz bumrah_data

In [ ]:
Q.15 

Identify players who perform exceptionally well in close matches. A close match is defined as one decided by less than 50 runs OR less than 5 wickets. For these close matches, calculate each player's average runs scored, total close matches played, and how many of those close matches their team won when they batted.

In [62]:
close_matches_id=[101590, 101626, 101635, 101680, 101694, 101703, 101748, 101757, 101766, 101820, 101829, 101833, 101571, 101613, 101617, 101653, 101716, 101725, 101734, 101784, 101788, 101806, 101842]

In [63]:
import requests
result_card=[]

for each_match in close_matches_id:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{each_match}/scard"

    headers = {
	    "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
	    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    try:
        response = requests.get(url, headers=headers)
        result_card.append(response.json())
    except:
        continue

result_card

[{'scorecard': [{'inningsid': 1,
    'batsman': [{'id': 9456,
      'balls': 9,
      'runs': 11,
      'fours': 0,
      'sixes': 1,
      'strkrate': '122.22',
      'name': 'Matthew Short',
      'nickname': '',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'b Milne',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 11375,
      'balls': 10,
      'runs': 11,
      'fours': 1,
      'sixes': 0,
      'strkrate': '110',
      'name': 'Weatherald',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Cartwright b Maxwell',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 11050,
      'balls': 42,
      'runs': 60,
      'fours': 8,
      'sixes': 2,
      'strkrate': '142.86',
      'name': 'D Arcy Short',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Duckett b Siddle',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': 'IN'},
     {'id': 11691,
      'balls': 10,
      'runs': 8,
      'fours': 1,
      'sixes': 0,
      'strkrate': '80',
      'name': 'Ollie Pope',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': True,
      'outdec': 'c Sam Harper b Siddle',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': 'IN'},
     {'id': 8647,
      'balls': 26,
      'runs': 35,
      'fours': 1,
      'sixes': 3,
      'strkrate': '134.62',
      'name': 'Ross',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'b Milne',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9813,
      'balls': 13,
      'runs': 16,
      'fours': 2,
      'sixes': 0,
      'strkrate': '123.08',
      'name': 'Bazley',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'b Doug Warren',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8512,
      'balls': 6,
      'runs': 6,
      'fours': 1,
      'sixes': 0,
      'strkrate': '100',
      'name': 'Jamie Overton',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 15143,
      'balls': 5,
      'runs': 8,
      'fours': 1,
      'sixes': 0,
      'strkrate': '160',
      'name': 'Liam Scott',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': 'IN'},
     {'id': 12219,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Thornton',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8125,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Boyce',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 12227,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Lloyd Pope',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''}],
    'bowler': [{'id': 7625,
      'overs': '4',
      'maidens': 0,
      'wickets': 2,
      'runs': 32,
      'economy': '8',
      'name': 'Milne',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 1444,
      'overs': '4',
      'maidens': 0,
      'wickets': 2,
      'runs': 21,
      'economy': '5.2',
      'name': 'Siddle',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': 'IN'},
     {'id': 7662,
      'overs': '2',
      'maidens': 0,
      'wickets': 1,
      'runs': 12,
      'economy': '6',
      'name': 'Maxwell',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 12,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': 'IN'},
     {'id': 9522,
      'overs': '4',
      'maidens': 0,
      'wickets': 0,
      'runs': 46,
      'economy': '11.5',
      'name': 'Tom Curran',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 51921,
      'overs': '4',
      'maidens': 0,
      'wickets': 1,
      'runs': 39,
      'economy': '9.8',
      'name': 'Doug Warren',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': 'IN'},
     {'id': 8989,
      'overs': '2',
      'maidens': 0,
      'wickets': 0,
      'runs': 11,
      'economy': '5.5',
      'name': 'Stoinis',
      'nickname': '',
      'iscaptain': True,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 12,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''}],
    'fow': {'fow': [{'batsmanid': 9456,
       'batsmanname': 'Matthew Short',
       'overnbr': 2.1,
       'runs': 17,
       'ballnbr': 13},
      {'batsmanid': 11375,
       'batsmanname': 'Weatherald ',
       'overnbr': 5.6,
       'runs': 56,
       'ballnbr': 36},
      {'batsmanid': 11691,
       'batsmanname': 'Ollie Pope',
       'overnbr': 10.1,
       'runs': 85,
       'ballnbr': 61},
      {'batsmanid': 11050,
       'batsmanname': 'D Arcy Short',
       'overnbr': 14.4,
       'runs': 115,
       'ballnbr': 88},
      {'batsmanid': 9813,
       'batsmanname': 'Bazley',
       'overnbr': 17.5,
       'runs': 151,
       'ballnbr': 107},
      {'batsmanid': 8647,
       'batsmanname': 'Ross',
       'overnbr': 18.2,
       'runs': 151,
       'ballnbr': 110}]},
    'extras': {'legbyes': 3,
     'byes': 1,
     'wides': 5,
     'noballs': 1,
     'penalty': 0,
     'total': 10},
    'pp': {'powerplay': [{'id': 1,
       'ovrfrom': 0.1,
       'ovrto': 4.0,
       'pptype': 'Mandatory',
       'run': 37,
       'wickets': 0},
      {'id': 2,
       'ovrfrom': 13.1,
       'ovrto': 15.0,
       'pptype': 'Batting',
       'run': 22,
       'wickets': 0}]},
    'score': 165,
    'wickets': 6,
    'overs': 20.0,
    'runrate': 8.25,
    'batteamname': 'Adelaide Strikers',
    'batteamsname': 'ADS',
    'isdeclared': False,
    'isfollowon': False,
    'ballnbr': 120,
    'rpb': 1.38,
    'partnership': {'partnership': [{'id': 0,
       'bat1id': 9456,
       'bat1name': 'Matthew Short',
       'bat1runs': 11,
       'bat1fours': 0,
       'bat1sixes': 1,
       'bat2id': 11375,
       'bat2name': 'Weatherald ',
       'bat2runs': 3,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 17,
       'totalballs': 13,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 11050,
       'bat1name': 'D Arcy Short',
       'bat1runs': 29,
       'bat1fours': 5,
       'bat1sixes': 1,
       'bat2id': 11375,
       'bat2name': 'Weatherald ',
       'bat2runs': 8,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 39,
       'totalballs': 23,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 11050,
       'bat1name': 'D Arcy Short',
       'bat1runs': 20,
       'bat1fours': 3,
       'bat1sixes': 0,
       'bat2id': 11691,
       'bat2name': 'Pope',
       'bat2runs': 8,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 29,
       'totalballs': 25,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 11050,
       'bat1name': 'D Arcy Short',
       'bat1runs': 11,
       'bat1fours': 0,
       'bat1sixes': 1,
       'bat2id': 8647,
       'bat2name': 'Ross',
       'bat2runs': 16,
       'bat2fours': 0,
       'bat2sixes': 1,
       'totalruns': 30,
       'totalballs': 27,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 9813,
       'bat1name': 'Bazley',
       'bat1runs': 16,
       'bat1fours': 2,
       'bat1sixes': 0,
       'bat2id': 8647,
       'bat2name': 'Ross',
       'bat2runs': 19,
       'bat2fours': 1,
       'bat2sixes': 2,
       'totalruns': 36,
       'totalballs': 20,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 8512,
       'bat1name': 'Jamie Overton',
       'bat1runs': 0,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 8647,
       'bat2name': 'Ross',
       'bat2runs': 0,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 0,
       'totalballs': 3,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 8512,
       'bat1name': 'Jamie Overton',
       'bat1runs': 6,
       'bat1fours': 1,
       'bat1sixes': 0,
       'bat2id': 15143,
       'bat2name': 'Liam Scott',
       'bat2runs': 8,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 14,
       'totalballs': 10,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0}]}},
   {'inningsid': 2,
    'batsman': [{'id': 10979,
      'balls': 44,
      'runs': 48,
      'fours': 5,
      'sixes': 1,
      'strkrate': '109.09',
      'name': 'Sam Harper',
      'nickname': 'Sam Harper',
      'iscaptain': False,
      'iskeeper': True,
      'outdec': 'b Lloyd Pope',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8502,
      'balls': 1,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Ben Duckett',
      'nickname': 'Duckett',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'lbw b Matthew Short',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': 'IN'},
     {'id': 8989,
      'balls': 19,
      'runs': 27,
      'fours': 4,
      'sixes': 1,
      'strkrate': '142.11',
      'name': 'Marcus Stoinis',
      'nickname': 'Stoinis',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'b Boyce',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 7662,
      'balls': 5,
      'runs': 15,
      'fours': 0,
      'sixes': 2,
      'strkrate': '300',
      'name': 'Glenn Maxwell',
      'nickname': 'Maxwell',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'lbw b Thornton',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': 'IN'},
     {'id': 23186,
      'balls': 3,
      'runs': 2,
      'fours': 0,
      'sixes': 0,
      'strkrate': '66.67',
      'name': 'Thomas Fraser Rogers',
      'nickname': 'Thomas Rogers',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'b Matthew Short',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8876,
      'balls': 9,
      'runs': 4,
      'fours': 0,
      'sixes': 0,
      'strkrate': '44.44',
      'name': 'Hilton Cartwright',
      'nickname': 'Cartwright',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'b Lloyd Pope',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8646,
      'balls': 5,
      'runs': 3,
      'fours': 0,
      'sixes': 0,
      'strkrate': '60',
      'name': 'Beau Webster',
      'nickname': 'Webster',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Ollie Pope b Jamie Overton',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9522,
      'balls': 22,
      'runs': 25,
      'fours': 4,
      'sixes': 0,
      'strkrate': '113.64',
      'name': 'Tom Curran',
      'nickname': 'Tom Curran',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Ross b Jamie Overton',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 7625,
      'balls': 4,
      'runs': 3,
      'fours': 0,
      'sixes': 0,
      'strkrate': '75',
      'name': 'Adam Milne',
      'nickname': 'Milne',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Jamie Overton b Lloyd Pope',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,

In [64]:
player_stats = []

for match in result_card:
    winner = match["status"].split(" won")[0].strip()

    for inng in match["scorecard"]:
        batteam = inng["batteamname"]
        team_won = (batteam == winner)

        for player in inng["batsman"]:
            player_stats.append({
                "name": player["name"],
                "total_runs":player["runs"],
                "innings": 1,
                "matches_won": 1 if team_won else 0,
                "matches_when_batted": 1 if (team_won and player["balls"] > 0) else 0
            })

player_stats

[{'name': 'Matthew Short',
  'total_runs': 11,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Weatherald',
  'total_runs': 11,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'D Arcy Short',
  'total_runs': 60,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Ollie Pope',
  'total_runs': 8,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Ross',
  'total_runs': 35,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Bazley',
  'total_runs': 16,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Jamie Overton',
  'total_runs': 6,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Liam Scott',
  'total_runs': 8,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Thornton',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Boyce',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Lloyd Pope',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Sam Harper',
  'total_runs': 48,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Ben Duckett',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Marcus Stoinis',
  'total_runs': 27,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Glenn Maxwell',
  'total_runs': 15,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Thomas Fraser Rogers',
  'total_runs': 2,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Hilton Cartwright',
  'total_runs': 4,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Beau Webster',
  'total_runs': 3,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Tom Curran',
  'total_runs': 25,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Adam Milne',
  'total_runs': 3,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Doug Warren',
  'total_runs': 3,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Peter Siddle',
  'total_runs': 12,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Duckett',
  'total_runs': 68,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Thomas Rogers',
  'total_runs': 12,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Sam Harper',
  'total_runs': 12,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Maxwell',
  'total_runs': 32,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Stoinis',
  'total_runs': 20,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Cartwright',
  'total_runs': 15,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Tom Curran',
  'total_runs': 15,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jonathan Merlo',
  'total_runs': 8,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Usama Mir',
  'total_runs': 2,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Doug Warren',
  'total_runs': 3,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Siddle',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Josh Philippe',
  'total_runs': 42,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'James Vince',
  'total_runs': 101,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Moises Henriques',
  'total_runs': 11,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Jordan Silk',
  'total_runs': 34,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Jack Edwards',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Lachlan Shaw',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Hayden Kerr',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Ben Dwarshuis',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Akeal Hosein',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Todd Murphy',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Jackson Bird',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Finn Allen',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Matthew Hurst',
  'total_runs': 28,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Cooper Connolly',
  'total_runs': 37,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Aaron Hardie',
  'total_runs': 24,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Turner',
  'total_runs': 22,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Nick Hobson',
  'total_runs': 47,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Agar',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Matthew Kelly',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Andrew Tye',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Behrendorff',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Lance Morris',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Tom Banton',
  'total_runs': 7,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jimmy Peirson',
  'total_runs': 1,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Colin Munro',
  'total_runs': 6,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Nathan McSweeney',
  'total_runs': 8,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Matt Renshaw',
  'total_runs': 36,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Max Bryant',
  'total_runs': 35,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Paul Walter',
  'total_runs': 5,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Xavier Bartlett',
  'total_runs': 3,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Mitchell Swepson',
  'total_runs': 2,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Spencer Johnson',
  'total_runs': 6,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Matthew Kuhnemann',
  'total_runs': 8,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Wade',
  'total_runs': 15,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Mitchell Owen',
  'total_runs': 33,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Shai Hope',
  'total_runs': 4,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Ben McDermott',
  'total_runs': 34,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Nikhil Chaudhary',
  'total_runs': 42,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Tim David',
  'total_runs': 4,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Chris Jordan',
  'total_runs': 16,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Peter Hatzoglou',
  'total_runs': 2,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Riley Meredith',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Stanlake',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Waqar Salamkheil',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Josh Philippe',
  'total_runs': 6,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'James Vince',
  'total_runs': 11,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Kurtis Patterson',
  'total_runs': 9,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Moises Henriques',
  'total_runs': 22,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jordan Silk',
  'total_runs': 20,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jack Edwards',
  'total_runs': 1,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Hayden Kerr',
  'total_runs': 2,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Ben Dwarshuis',
  'total_runs': 9,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Akeal Hosein',
  'total_runs': 10,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Todd Murphy',
  'total_runs': 14,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jackson Bird',
  'total_runs': 3,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Josh Brown',
  'total_runs': 66,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jake Fraser-McGurk',
  'total_runs': 1,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Seifert',
  'total_runs': 4,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jacob Bethell',
  'total_runs': 21,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Mackenzie Harvey',
  'total_runs': 6,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Laurie Evans',
  'total_runs': 6,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Sutherland',
  'total_runs': 18,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Fergus O Neill',
  'total_runs': 3,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Tom Rogers',
  'total_runs': 8,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Zampa',
  'total_runs': 3,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Kane Richardson',
  'total_runs': 1,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Chris Lynn',
  'total_runs': 88,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'D Arcy Short',
  'total_runs': 27,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'James Bazley',
  'total_runs': 1,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Jake Weatherald',
  'total_runs': 3,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Ollie Pope',
  'total_runs': 12,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Alex Ross',
  'total_runs': 6,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Jamie Overton',
  'total_runs': 2,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Henry Thornton',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Brendan Doggett',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Cameron Boyce',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Lloyd Pope',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Matthew Hurst',
  'total_runs': 23,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Finn Allen',
  'total_runs': 68,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Aaron Hardie',
  'total_runs': 10,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Cooper Connolly',
  'total_runs': 43,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Turner',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Nick Hobson',
  'total_runs': 21,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Matthew Spoors',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Matthew Kelly',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Andrew Tye',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Behrendorff',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Lance Morris',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Blake Nikitaras',
  'total_runs': 1,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'David Warner',
  'total_runs': 49,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Matthew Gilkes',
  'total_runs': 43,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Oliver Davies',
  'total_runs': 3,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Sam Billings',
  'total_runs': 13,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Sherfane Rutherford',
  'total_runs': 39,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Chris Green',
  'total_runs': 11,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Hugh Weibgen',
  'total_runs': 9,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Tom Andrews',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Lockie Ferguson',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Wes Agar',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Cameron Bancroft',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Daniel Sams',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Duckett',
  'total_runs': 20,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Sam Harper',
  'total_runs': 4,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Webster',
  'total_runs': 48,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Dan Lawrence',
  'total_runs': 14,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Stoinis',
  'total_runs': 4,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Maxwell',
  'total_runs': 58,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Cartwright',
  'total_runs': 2,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Usama Mir',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Joel Paris',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Steketee',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Siddle',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Josh Philippe',
  'total_runs': 8,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'James Vince',
  'total_runs': 53,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Kurtis Patterson',
  'total_runs': 18,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Moises Henriques',
  'total_runs': 13,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jordan Silk',
  'total_runs': 1,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jack Edwards',
  'total_runs': 9,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Hayden Kerr',
  'total_runs': 21,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Ben Dwarshuis',
  'total_runs': 4,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Sean Abbott',
  'total_runs': 5,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Akeal Hosein',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Todd Murphy',
  'total_runs': 1,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Philippe',
  'total_runs': 9,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Steven Smith',
  'total_runs': 121,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Kurtis Patterson',
  'total_runs': 12,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Henriques',
  'total_runs': 46,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Dwarshuis',
  'total_runs': 23,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Silk',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Jack Edwards',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Joel Davies',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Hayden Kerr',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Abbott',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'T Murphy',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 0},
 {'name': 'Sam Fanning',
  'total_runs': 41,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Finn Allen',
  'total_runs': 15,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Aaron Hardie',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Cooper Connolly',
  'total_runs': 33,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Ashton Turner',
  'total_runs': 66,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Nick Hobson',
  'total_runs': 12,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Ashton Agar',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Matthew Spoors',
  'total_runs': 28,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jhye Richardson',
  'total_runs': 1,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Andrew Tye',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Jason Behrendorff',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 0,
  'matches_when_batted': 0},
 {'name': 'Sam Harper',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Duckett',
  'total_runs': 21,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Webster',
  'total_runs': 15,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},
 {'name': 'Thomas Rogers',
  'total_runs': 0,
  'innings': 1,
  'matches_won': 1,
  'matches_when_batted': 1},

In [65]:
close_match_stats=pd.DataFrame(player_stats)

In [66]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

table_name = "close_match_data"

engine = create_engine(
f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


close_match_stats.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz close_match_data

Q.16

In [67]:
rr_match_ids=[30342, 30369, 30380, 30390, 30414, 30420, 30430, 30445, 30454, 30468, 30489, 30495, 30515, 30529]

import requests 

rr_scorecards = []

for each in rr_match_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{each}/scard"

    headers = {
        "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    try:
        response = requests.get(url, headers=headers)
        rr_scorecards.append(response.json())
    except Exception as e:
        print(f"Error fetching {each}: {e}")

Error fetching 30342: Expecting value: line 1 column 1 (char 0)
Error fetching 30468: Expecting value: line 1 column 1 (char 0)

In [68]:
rr_stats_2020 = []
for match in rr_scorecards:
    inn_list = match["scorecard"] 
    for innings in inn_list:
        if innings["batteamname"] == "Rajasthan Royals":    # only RR batting innings
            for b in innings["batsman"]:
                player_data1 = {
                    "pid": b["id"],
                    "name": b["name"],
                    "runs": b["runs"],
                    "sr": float(b["strkrate"])
                }           
                rr_stats_2020.append(player_data1)
rr_stats_2020

[{'pid': 2258, 'name': 'Jos Buttler', 'runs': 4, 'sr': 57.14},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 50, 'sr': 185.19},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 85, 'sr': 202.38},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 53, 'sr': 170.97},
 {'pid': 527, 'name': 'Robin Uthappa', 'runs': 9, 'sr': 225.0},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 13, 'sr': 433.33},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 0, 'sr': 0.0},
 {'pid': 9522, 'name': 'Tom Curran', 'runs': 4, 'sr': 400.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 0, 'sr': 0.0},
 {'pid': 8924, 'name': 'Ankit Rajpoot', 'runs': 0, 'sr': 0.0},
 {'pid': 6327, 'name': 'Jaydev Unadkat', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 21, 'sr': 131.25},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 3, 'sr': 42.86},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 8, 'sr': 88.89},
 {'pid': 527, 'name': 'Robin Uthappa', 'runs': 2, 'sr': 28.57},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 1, 'sr': 16.67},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 14, 'sr': 140.0},
 {'pid': 9522, 'name': 'Tom Curran', 'runs': 54, 'sr': 150.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 5, 'sr': 71.43},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 6, 'sr': 150.0},
 {'pid': 6327, 'name': 'Jaydev Unadkat', 'runs': 9, 'sr': 69.23},
 {'pid': 8924, 'name': 'Ankit Rajpoot', 'runs': 7, 'sr': 140.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 22, 'sr': 183.33},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 5, 'sr': 100.0},
 {'pid': 8271, 'name': 'Samson', 'runs': 4, 'sr': 133.33},
 {'pid': 527, 'name': 'Uthappa', 'runs': 17, 'sr': 77.27},
 {'pid': 10954, 'name': 'Lomror', 'runs': 47, 'sr': 120.51},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 16, 'sr': 88.89},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 24, 'sr': 200.0},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 16, 'sr': 160.0},
 {'pid': 9522, 'name': 'Tom Curran', 'runs': 0, 'sr': 0.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 0, 'sr': 0.0},
 {'pid': 6327, 'name': 'Unadkat', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 70, 'sr': 159.09},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 6, 'sr': 85.71},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 0, 'sr': 0.0},
 {'pid': 10954, 'name': 'Mahipal Lomror', 'runs': 11, 'sr': 84.62},
 {'pid': 9522, 'name': 'Tom Curran', 'runs': 15, 'sr': 93.75},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 5, 'sr': 83.33},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 24, 'sr': 218.18},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 1, 'sr': 50.0},
 {'pid': 8924, 'name': 'Ankit Rajpoot', 'runs': 2, 'sr': 40.0},
 {'pid': 13136, 'name': 'Kartik Tyagi', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 34, 'sr': 94.44},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 13, 'sr': 162.5},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 24, 'sr': 141.18},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 5, 'sr': 55.56},
 {'pid': 10954, 'name': 'Mahipal Lomror', 'runs': 1, 'sr': 50.0},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 38, 'sr': 131.03},
 {'pid': 9617, 'name': 'Andrew Tye', 'runs': 6, 'sr': 100.0},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 2, 'sr': 50.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 2, 'sr': 66.67},
 {'pid': 13136, 'name': 'Kartik Tyagi', 'runs': 2, 'sr': 66.67},
 {'pid': 6293, 'name': 'Varun Aaron', 'runs': 1, 'sr': 50.0},
 {'pid': 6557, 'name': 'Ben Stokes', 'runs': 5, 'sr': 83.33},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 16, 'sr': 123.08},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 5, 'sr': 83.33},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 26, 'sr': 104.0},
 {'pid': 527, 'name': 'Robin Uthappa', 'runs': 18, 'sr': 120.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 42, 'sr': 161.54},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 45, 'sr': 160.71},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 0, 'sr': 0.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 0, 'sr': 0.0},
 {'pid': 6327, 'name': 'Jaydev Unadkat', 'runs': 0, 'sr': 0.0},
 {'pid': 13136, 'name': 'Kartik Tyagi', 'runs': 0, 'sr': 0.0},
 {'pid': 6557, 'name': 'Ben Stokes', 'runs': 41, 'sr': 117.14},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 22, 'sr': 244.44},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 1, 'sr': 25.0},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 25, 'sr': 138.89},
 {'pid': 527, 'name': 'Robin Uthappa', 'runs': 32, 'sr': 118.52},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 1, 'sr': 50.0},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 14, 'sr': 77.78},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 1, 'sr': 25.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 6, 'sr': 150.0},
 {'pid': 6327, 'name': 'Jaydev Unadkat', 'runs': 0, 'sr': 0.0},
 {'pid': 13136, 'name': 'Kartik Tyagi', 'runs': 0, 'sr': 0.0},
 {'pid': 527, 'name': 'Uthappa', 'runs': 41, 'sr': 186.36},
 {'pid': 6557, 'name': 'Stokes', 'runs': 15, 'sr': 78.95},
 {'pid': 8271, 'name': 'Samson', 'runs': 9, 'sr': 150.0},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 57, 'sr': 158.33},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 24, 'sr': 96.0},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 19, 'sr': 172.73},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 2, 'sr': 66.67},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 0, 'sr': 0.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 0, 'sr': 0.0},
 {'pid': 6327, 'name': 'Unadkat', 'runs': 0, 'sr': 0.0},
 {'pid': 13136, 'name': 'Kartik Tyagi', 'runs': 0, 'sr': 0.0},
 {'pid': 527, 'name': 'Robin Uthappa', 'runs': 13, 'sr': 118.18},
 {'pid': 6557, 'name': 'Ben Stokes', 'runs': 107, 'sr': 178.33},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 11, 'sr': 137.5},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 54, 'sr': 174.19},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 0, 'sr': 0.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 0, 'sr': 0.0},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 0, 'sr': 0.0},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 0, 'sr': 0.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 0, 'sr': 0.0},
 {'pid': 8924, 'name': 'Ankit Rajpoot', 'runs': 0, 'sr': 0.0},
 {'pid': 13136, 'name': 'Kartik Tyagi', 'runs': 0, 'sr': 0.0},
 {'pid': 527, 'name': 'Robin Uthappa', 'runs': 30, 'sr': 130.43},
 {'pid': 6557, 'name': 'Ben Stokes', 'runs': 50, 'sr': 192.31},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 48, 'sr': 192.0},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 31, 'sr': 155.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 22, 'sr': 200.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 0, 'sr': 0.0},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 0, 'sr': 0.0},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 0, 'sr': 0.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 0, 'sr': 0.0},
 {'pid': 6293, 'name': 'Varun Aaron', 'runs': 0, 'sr': 0.0},
 {'pid': 13136, 'name': 'Kartik Tyagi', 'runs': 0, 'sr': 0.0},
 {'pid': 527, 'name': 'Robin Uthappa', 'runs': 6, 'sr': 300.0},
 {'pid': 6557, 'name': 'Ben Stokes', 'runs': 18, 'sr': 163.64},
 {'pid': 2250, 'name': 'Steven Smith', 'runs': 4, 'sr': 100.0},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 1, 'sr': 25.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 35, 'sr': 159.09},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 0, 'sr': 0.0},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 31, 'sr': 114.81},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 23, 'sr': 100.0},
 {'pid': 11540, 'name': 'Jofra Archer', 'runs': 6, 'sr': 66.67},
 {'pid': 13136, 'name': 'Kartik Tyagi', 'runs': 2, 'sr': 66.67},
 {'pid': 6293, 'name': 'Varun Aaron', 'runs': 0, 'sr': 0.0}]

In [69]:
rr_statspd_2020=pd.DataFrame(rr_stats_2020)
rr_2020 = rr_statspd_2020.groupby("pid").agg(
    name=("name", "first"),
    total_runs=("runs", "sum"),
    avg_sr=("sr", "mean"),
    matches=("pid", "count")
).reset_index()


rr_2020["avg_runs_per_match"] = rr_2020["total_runs"] / rr_2020["matches"]
rr_2020["year"] = 2020

rr_2020 = rr_2020[[
    "pid",
    "name",
    "year",
    "total_runs",
    "avg_runs_per_match",
    "avg_sr",
    "matches"
]]


rr_2020 = rr_2020[rr_2020["matches"] >= 5]


rr_2020

,pid,name,year,total_runs,avg_runs_per_match,avg_sr,matches
0,527,Robin Uthappa,2020,168,18.666667,144.925556,9
1,2250,Steven Smith,2020,197,17.909091,110.372727,11
2,2258,Jos Buttler,2020,249,22.636364,137.810909,11
4,6327,Jaydev Unadkat,2020,9,1.500000,11.538333,6
5,6557,Ben Stokes,2020,236,39.333333,135.616667,6
6,8271,Sanju Samson,2020,265,24.090909,114.930909,11
10,9693,Rahul Tewatia,2020,243,22.090909,113.760000,11
11,9746,Shreyas Gopal,2020,37,3.363636,39.827273,11
13,11540,Jofra Archer,2020,70,6.363636,106.350000,11
14,12305,Riyan Parag,2020,60,6.666667,35.233333,9
15,13136,Kartik Tyagi,2020,4,0.500000,16.667500,8

In [70]:
rr_match_ids_2021=[35622, 35632, 35648, 35671, 35673, 35695, 35713, 37562, 37583, 37604, 37620, 37626, 37637, 37648]

import requests 

rr_scorecards_2021 = []

for each in rr_match_ids_2021:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{each}/scard"

    headers = {
        "x-rapidapi-key": "f28eedda78mshf250801249f0213p108557jsn01ea9788bf50",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    try:
        response = requests.get(url, headers=headers)
        rr_scorecards_2021.append(response.json())
    except Exception as e:
        print(f"Error fetching {each}: {e}")

Error fetching 35671: Expecting value: line 1 column 1 (char 0)
Error fetching 35695: Expecting value: line 1 column 1 (char 0)
Error fetching 37583: Expecting value: line 1 column 1 (char 0)
Error fetching 37604: Expecting value: line 1 column 1 (char 0)
Error fetching 37620: Expecting value: line 1 column 1 (char 0)
Error fetching 37648: Expecting value: line 1 column 1 (char 0)

In [71]:
rr_stats_2021 = []
for match in rr_scorecards_2021:
    inn_list = match["scorecard"] 
    for innings in inn_list:
        if innings["batteamname"] == "Rajasthan Royals":    # only RR batting innings
            for b in innings["batsman"]:
                player_data2 = {
                    "pid": b["id"],
                    "name": b["name"],
                    "runs": b["runs"],
                    "sr": float(b["strkrate"])
                }           
                rr_stats_2021.append(player_data2)
rr_stats_2021

[{'pid': 6557, 'name': 'Ben Stokes', 'runs': 0, 'sr': 0.0},
 {'pid': 8358, 'name': 'Manan Vohra', 'runs': 12, 'sr': 150.0},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 119, 'sr': 188.89},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 25, 'sr': 192.31},
 {'pid': 11195, 'name': 'Shivam Dube', 'runs': 23, 'sr': 153.33},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 25, 'sr': 227.27},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 2, 'sr': 50.0},
 {'pid': 8333, 'name': 'Chris Morris', 'runs': 2, 'sr': 50.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 0, 'sr': 0.0},
 {'pid': 13494, 'name': 'Chetan Sakariya', 'runs': 0, 'sr': 0.0},
 {'pid': 9863, 'name': 'Mustafizur Rahman', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 2, 'sr': 28.57},
 {'pid': 8358, 'name': 'Manan Vohra', 'runs': 9, 'sr': 81.82},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 4, 'sr': 133.33},
 {'pid': 11195, 'name': 'Shivam Dube', 'runs': 2, 'sr': 28.57},
 {'pid': 6349, 'name': 'David Miller', 'runs': 62, 'sr': 144.19},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 2, 'sr': 40.0},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 19, 'sr': 111.76},
 {'pid': 8333, 'name': 'Chris Morris', 'runs': 36, 'sr': 200.0},
 {'pid': 6327, 'name': 'Jaydev Unadkat', 'runs': 11, 'sr': 157.14},
 {'pid': 13494, 'name': 'Chetan Sakariya', 'runs': 0, 'sr': 0.0},
 {'pid': 9863, 'name': 'Mustafizur Rahman', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 49, 'sr': 140.0},
 {'pid': 8358, 'name': 'Manan Vohra', 'runs': 14, 'sr': 127.27},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 1, 'sr': 20.0},
 {'pid': 11195, 'name': 'Shivam Dube', 'runs': 17, 'sr': 85.0},
 {'pid': 6349, 'name': 'David Miller', 'runs': 2, 'sr': 40.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 3, 'sr': 42.86},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 20, 'sr': 133.33},
 {'pid': 8333, 'name': 'Chris Morris', 'runs': 0, 'sr': 0.0},
 {'pid': 6327, 'name': 'Jaydev Unadkat', 'runs': 24, 'sr': 141.18},
 {'pid': 13494, 'name': 'Chetan Sakariya', 'runs': 0, 'sr': 0.0},
 {'pid': 9863, 'name': 'Mustafizur Rahman', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 5, 'sr': 71.43},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 22, 'sr': 129.41},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 42, 'sr': 102.44},
 {'pid': 11195, 'name': 'Shivam Dube', 'runs': 22, 'sr': 122.22},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 5, 'sr': 62.5},
 {'pid': 6349, 'name': 'David Miller', 'runs': 24, 'sr': 104.35},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 0, 'sr': 0.0},
 {'pid': 8333, 'name': 'Chris Morris', 'runs': 0, 'sr': 0.0},
 {'pid': 6327, 'name': 'Jaydev Unadkat', 'runs': 0, 'sr': 0.0},
 {'pid': 13494, 'name': 'Chetan Sakariya', 'runs': 0, 'sr': 0.0},
 {'pid': 9863, 'name': 'Mustafizur Rahman', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 124, 'sr': 193.75},
 {'pid': 13940, 'name': 'Jaiswal', 'runs': 12, 'sr': 92.31},
 {'pid': 8271, 'name': 'Samson', 'runs': 48, 'sr': 145.45},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 15, 'sr': 187.5},
 {'pid': 6349, 'name': 'Miller', 'runs': 7, 'sr': 233.33},
 {'pid': 13135, 'name': 'Anuj Rawat', 'runs': 0, 'sr': 0.0},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 0, 'sr': 0.0},
 {'pid': 8333, 'name': 'Chris Morris', 'runs': 0, 'sr': 0.0},
 {'pid': 13136, 'name': 'Kartik Tyagi', 'runs': 0, 'sr': 0.0},
 {'pid': 13494, 'name': 'Chetan Sakariya', 'runs': 0, 'sr': 0.0},
 {'pid': 9863, 'name': 'Mustafizur', 'runs': 0, 'sr': 0.0},
 {'pid': 8579, 'name': 'Lewis', 'runs': 36, 'sr': 171.43},
 {'pid': 13940, 'name': 'Jaiswal', 'runs': 49, 'sr': 136.11},
 {'pid': 8271, 'name': 'Samson', 'runs': 4, 'sr': 80.0},
 {'pid': 10045, 'name': 'Livingstone', 'runs': 25, 'sr': 147.06},
 {'pid': 10954, 'name': 'Lomror', 'runs': 43, 'sr': 252.94},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 4, 'sr': 80.0},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 2, 'sr': 40.0},
 {'pid': 8333, 'name': 'Chris Morris', 'runs': 5, 'sr': 100.0},
 {'pid': 13494, 'name': 'Chetan Sakariya', 'runs': 7, 'sr': 116.67},
 {'pid': 13136, 'name': 'Kartik Tyagi', 'runs': 1, 'sr': 33.33},
 {'pid': 9863, 'name': 'Mustafizur', 'runs': 0, 'sr': 0.0},
 {'pid': 8579, 'name': 'Evin Lewis', 'runs': 27, 'sr': 225.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 50, 'sr': 238.1},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 28, 'sr': 116.67},
 {'pid': 11195, 'name': 'Shivam Dube', 'runs': 64, 'sr': 152.38},
 {'pid': 10693, 'name': 'Glenn Phillips', 'runs': 14, 'sr': 175.0},
 {'pid': 6349, 'name': 'David Miller', 'runs': 0, 'sr': 0.0},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 0, 'sr': 0.0},
 {'pid': 14696, 'name': 'Akash Singh', 'runs': 0, 'sr': 0.0},
 {'pid': 12627, 'name': 'Mayank Markande', 'runs': 0, 'sr': 0.0},
 {'pid': 13494, 'name': 'Chetan Sakariya', 'runs': 0, 'sr': 0.0},
 {'pid': 9863, 'name': 'Mustafizur Rahman', 'runs': 0, 'sr': 0.0},
 {'pid': 8579, 'name': 'Lewis', 'runs': 24, 'sr': 126.32},
 {'pid': 13940, 'name': 'Jaiswal', 'runs': 12, 'sr': 133.33},
 {'pid': 8271, 'name': 'Samson', 'runs': 3, 'sr': 50.0},
 {'pid': 11195, 'name': 'Shivam Dube', 'runs': 3, 'sr': 37.5},
 {'pid': 10693, 'name': 'Glenn Phillips', 'runs': 4, 'sr': 30.77},
 {'pid': 6349, 'name': 'Miller', 'runs': 15, 'sr': 65.22},
 {'pid': 9693, 'name': 'Rahul Tewatia', 'runs': 12, 'sr': 60.0},
 {'pid': 9746, 'name': 'Shreyas Gopal', 'runs': 0, 'sr': 0.0},
 {'pid': 13494, 'name': 'Chetan Sakariya', 'runs': 6, 'sr': 54.55},
 {'pid': 13537, 'name': 'Kuldip Yadav', 'runs': 0, 'sr': 0.0},
 {'pid': 9863, 'name': 'Mustafizur', 'runs': 8, 'sr': 114.29}]

In [72]:
rr_statspd_2021=pd.DataFrame(rr_stats_2021)
rr_2021 = rr_statspd_2021.groupby("pid").agg(
    name=("name", "first"),
    total_runs=("runs", "sum"),
    avg_sr=("sr", "mean"),
    matches=("pid", "count")
).reset_index()


rr_2021["avg_runs_per_match"] = rr_2021["total_runs"] / rr_2021["matches"]
rr_2021["year"] = 2021



rr_2021 = rr_2021[[
    "pid",
    "name",
    "year",
    "total_runs",
    "avg_runs_per_match",
    "avg_sr",
    "matches"
]]


rr_2021 = rr_2021[rr_2021["matches"] >= 5]


rr_2021

,pid,name,year,total_runs,avg_runs_per_match,avg_sr,matches
0,2258,Jos Buttler,2021,205,41.000000,125.212000,5
2,6349,David Miller,2021,110,18.333333,97.848333,6
4,8271,Sanju Samson,2021,249,31.125000,104.597500,8
5,8333,Chris Morris,2021,43,7.166667,58.333333,6
8,9693,Rahul Tewatia,2021,60,7.500000,57.198750,8
10,9863,Mustafizur Rahman,2021,8,1.000000,14.286250,8
14,11195,Shivam Dube,2021,131,21.833333,96.500000,6
15,12305,Riyan Parag,2021,49,8.166667,96.271667,6
19,13494,Chetan Sakariya,2021,13,1.625000,21.402500,8
21,13940,Yashasvi Jaiswal,2021,145,29.000000,145.852000,5

In [75]:
rr_match_ids_2022=[45906, 45934, 45946, 45981, 46001, 46031, 46051, 46076, 46101, 46132, 46152, 46171, 46187, 46205, 47584, 47598, 47605]

import requests 

rr_scorecards_2022 = []

for each in rr_match_ids_2022:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{each}/scard"

    headers = {
        "x-rapidapi-key": "fc7f30fb9cmsh8725b330cc40e86p18a9aejsnb2a96a85740a",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    try:
        response = requests.get(url, headers=headers)
        rr_scorecards_2022.append(response.json())
    except Exception as e:
        print(f"Error fetching {each}: {e}")

Error fetching 45934: Expecting value: line 1 column 1 (char 0)
Error fetching 46132: Expecting value: line 1 column 1 (char 0)
Error fetching 46152: Expecting value: line 1 column 1 (char 0)
Error fetching 46187: Expecting value: line 1 column 1 (char 0)
Error fetching 46205: Expecting value: line 1 column 1 (char 0)

In [76]:
rr_stats_2022 = []
for match in rr_scorecards_2022:
    inn_list = match["scorecard"] 
    for innings in inn_list:
        if innings["batteamname"] == "Rajasthan Royals":    # only RR batting innings
            for b in innings["batsman"]:
                player_data3 = {
                    "pid": b["id"],
                    "name": b["name"],
                    "runs": b["runs"],
                    "sr": float(b["strkrate"])
                }           
                rr_stats_2022.append(player_data3)
rr_stats_2022

[{'pid': 2258, 'name': 'Jos Buttler', 'runs': 35, 'sr': 125.0},
 {'pid': 13940, 'name': 'Jaiswal', 'runs': 20, 'sr': 125.0},
 {'pid': 8271, 'name': 'Samson', 'runs': 55, 'sr': 203.7},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 41, 'sr': 141.38},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 32, 'sr': 246.15},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 12, 'sr': 133.33},
 {'pid': 7774, 'name': 'Coulter-Nile', 'runs': 1, 'sr': 50.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 10551, 'name': 'Prasidh', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 70, 'sr': 148.94},
 {'pid': 13940, 'name': 'Jaiswal', 'runs': 4, 'sr': 66.67},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 37, 'sr': 127.59},
 {'pid': 8271, 'name': 'Samson', 'runs': 8, 'sr': 100.0},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 42, 'sr': 135.48},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 9715, 'name': 'Navdeep Saini', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 10551, 'name': 'Prasidh', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 13, 'sr': 118.18},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 29, 'sr': 100.0},
 {'pid': 8271, 'name': 'Samson', 'runs': 13, 'sr': 108.33},
 {'pid': 9554, 'name': 'van der Dussen', 'runs': 4, 'sr': 100.0},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 59, 'sr': 163.89},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 28, 'sr': 121.74},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 8, 'sr': 200.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 2, 'sr': 200.0},
 {'pid': 14336, 'name': 'Kuldeep Sen', 'runs': 0, 'sr': 0.0},
 {'pid': 10551, 'name': 'Prasidh', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 54, 'sr': 225.0},
 {'pid': 13088, 'name': 'Devdutt Padikkal', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 8, 'sr': 100.0},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 11, 'sr': 100.0},
 {'pid': 9554, 'name': 'Rassie van der Dussen', 'runs': 6, 'sr': 60.0},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 29, 'sr': 170.59},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 18, 'sr': 112.5},
 {'pid': 8983, 'name': 'James Neesham', 'runs': 17, 'sr': 113.33},
 {'pid': 10551, 'name': 'Prasidh Krishna', 'runs': 4, 'sr': 57.14},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 5, 'sr': 62.5},
 {'pid': 14336, 'name': 'Kuldeep Sen', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 103, 'sr': 168.85},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 24, 'sr': 133.33},
 {'pid': 8271, 'name': 'Samson', 'runs': 38, 'sr': 200.0},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 26, 'sr': 200.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 5, 'sr': 166.67},
 {'pid': 8257, 'name': 'Karun Nair', 'runs': 3, 'sr': 60.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 2, 'sr': 100.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 10551, 'name': 'Prasidh', 'runs': 0, 'sr': 0.0},
 {'pid': 11221, 'name': 'Obed McCoy', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 116, 'sr': 178.46},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 54, 'sr': 154.29},
 {'pid': 8271, 'name': 'Samson', 'runs': 46, 'sr': 242.11},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 1, 'sr': 100.0},
 {'pid': 8257, 'name': 'Karun Nair', 'runs': 0, 'sr': 0.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 10551, 'name': 'Prasidh', 'runs': 0, 'sr': 0.0},
 {'pid': 11221, 'name': 'Obed McCoy', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 8, 'sr': 88.89},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 7, 'sr': 100.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 17, 'sr': 188.89},
 {'pid': 8271, 'name': 'Samson', 'runs': 27, 'sr': 128.57},
 {'pid': 10713, 'name': 'Daryl Mitchell', 'runs': 16, 'sr': 66.67},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 56, 'sr': 180.65},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 3, 'sr': 42.86},
 {'pid': 8117, 'name': 'Boult', 'runs': 5, 'sr': 71.43},
 {'pid': 10551, 'name': 'Prasidh', 'runs': 2, 'sr': 40.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 14336, 'name': 'Kuldeep Sen', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 67, 'sr': 128.85},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 15, 'sr': 100.0},
 {'pid': 8271, 'name': 'Samson', 'runs': 16, 'sr': 228.57},
 {'pid': 10713, 'name': 'Daryl Mitchell', 'runs': 17, 'sr': 85.0},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 6, 'sr': 42.86},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 3, 'sr': 100.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 21, 'sr': 233.33},
 {'pid': 8117, 'name': 'Boult', 'runs': 1, 'sr': 100.0},
 {'pid': 10551, 'name': 'Prasidh', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 14336, 'name': 'Kuldeep Sen', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Jaiswal', 'runs': 19, 'sr': 100.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 7, 'sr': 63.64},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 50, 'sr': 131.58},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 48, 'sr': 160.0},
 {'pid': 8271, 'name': 'Samson', 'runs': 6, 'sr': 150.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 9, 'sr': 180.0},
 {'pid': 9554, 'name': 'van der Dussen', 'runs': 12, 'sr': 120.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 3, 'sr': 100.0},
 {'pid': 10551, 'name': 'Prasidh', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 14336, 'name': 'Kuldeep Sen', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Jaiswal', 'runs': 3, 'sr': 37.5},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 89, 'sr': 158.93},
 {'pid': 8271, 'name': 'Samson', 'runs': 47, 'sr': 180.77},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 28, 'sr': 140.0},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 4, 'sr': 57.14},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 4, 'sr': 133.33},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 2, 'sr': 200.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 10551, 'name': 'Prasidh', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 11221, 'name': 'Obed McCoy', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 21, 'sr': 161.54},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 106, 'sr': 176.67},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 23, 'sr': 109.52},
 {'pid': 13088, 'name': 'Devdutt Padikkal', 'runs': 9, 'sr': 75.0},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 2, 'sr': 66.67},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 10551, 'name': 'Prasidh Krishna', 'runs': 0, 'sr': 0.0},
 {'pid': 11221, 'name': 'Obed McCoy', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Jaiswal', 'runs': 22, 'sr': 137.5},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 39, 'sr': 111.43},
 {'pid': 8271, 'name': 'Samson', 'runs': 14, 'sr': 127.27},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 2, 'sr': 20.0},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 11, 'sr': 91.67},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 6, 'sr': 66.67},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 15, 'sr': 100.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 11, 'sr': 157.14},
 {'pid': 11221, 'name': 'Obed McCoy', 'runs': 8, 'sr': 160.0},
 {'pid': 10551, 'name': 'Prasidh', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0}]

In [77]:
rr_statspd_2022=pd.DataFrame(rr_stats_2022)
rr_2022 = rr_statspd_2022.groupby("pid").agg(
    name=("name", "first"),
    total_runs=("runs", "sum"),
    avg_sr=("sr", "mean"),
    matches=("pid", "count")
).reset_index()


rr_2022["avg_runs_per_match"] = rr_2022["total_runs"] / rr_2022["matches"]
rr_2022["year"] = 2022



rr_2022 = rr_2022[[
    "pid",
    "name",
    "year",
    "total_runs",
    "avg_runs_per_match",
    "avg_sr",
    "matches"
]]


rr_2022 = rr_2022[rr_2022["matches"] >= 5]


rr_2022

,pid,name,year,total_runs,avg_runs_per_match,avg_sr,matches
0,1593,Ashwin,2022,134,11.166667,95.184167,12
1,2258,Jos Buttler,2022,707,58.916667,141.070000,12
3,7910,Chahal,2022,5,0.416667,5.208333,12
4,8117,Boult,2022,22,2.000000,57.142727,11
6,8271,Samson,2022,304,25.333333,156.570000,12
10,9789,Hetmyer,2022,215,19.545455,119.755455,11
11,10551,Prasidh,2022,6,0.500000,8.095000,12
13,11221,Obed McCoy,2022,8,1.600000,32.000000,5
14,12305,Riyan Parag,2022,130,10.833333,108.873333,12
15,13088,Padikkal,2022,294,24.500000,104.299167,12
16,13940,Jaiswal,2022,89,14.833333,104.701667,6
17,14336,Kuldeep Sen,2022,0,0.000000,0.000000,5

In [78]:
rr_match_ids_2023=[66186, 66208, 66218, 66250, 66274, 66292, 66421, 66324, 66299, 66348, 66376, 66397, 66432, 66455]

import requests 

rr_scorecards_2023 = []

for each in rr_match_ids_2023:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{each}/scard"

    headers = {
        "x-rapidapi-key": "fc7f30fb9cmsh8725b330cc40e86p18a9aejsnb2a96a85740a",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    try:
        response = requests.get(url, headers=headers)
        rr_scorecards_2023.append(response.json())
    except Exception as e:
        print(f"Error fetching {each}: {e}")

Error fetching 66186: Expecting value: line 1 column 1 (char 0)
Error fetching 66324: Expecting value: line 1 column 1 (char 0)
Error fetching 66455: Expecting value: line 1 column 1 (char 0)

In [79]:
rr_stats_2023 = []
for match in rr_scorecards_2023:
    inn_list = match["scorecard"] 
    for innings in inn_list:
        if innings["batteamname"] == "Rajasthan Royals":    
            for b in innings["batsman"]:
                player_data4 = {
                    "pid": b["id"],
                    "name": b["name"],
                    "runs": b["runs"],
                    "sr": float(b["strkrate"])
                }           
                rr_stats_2023.append(player_data4)
rr_stats_2023

[{'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 11, 'sr': 137.5},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 19, 'sr': 172.73},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 42, 'sr': 168.0},
 {'pid': 13088, 'name': 'Devdutt Padikkal', 'runs': 21, 'sr': 80.77},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 20, 'sr': 166.67},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 36, 'sr': 200.0},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 32, 'sr': 213.33},
 {'pid': 8313, 'name': 'Jason Holder', 'runs': 1, 'sr': 100.0},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 13483, 'name': 'KM Asif', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 60, 'sr': 193.55},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 79, 'sr': 154.9},
 {'pid': 8271, 'name': 'Samson', 'runs': 0, 'sr': 0.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 7, 'sr': 63.64},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 39, 'sr': 185.71},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 8, 'sr': 266.67},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8313, 'name': 'Holder', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 8796, 'name': 'M Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 10, 'sr': 125.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 52, 'sr': 144.44},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 38, 'sr': 146.15},
 {'pid': 8271, 'name': 'Samson', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 30, 'sr': 136.36},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 30, 'sr': 166.67},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 4, 'sr': 66.67},
 {'pid': 8313, 'name': 'Holder', 'runs': 0, 'sr': 0.0},
 {'pid': 8642, 'name': 'Zampa', 'runs': 1, 'sr': 100.0},
 {'pid': 14336, 'name': 'Kuldeep Sen', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 1, 'sr': 14.29},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 0, 'sr': 0.0},
 {'pid': 13088, 'name': 'Devdutt Padikkal', 'runs': 26, 'sr': 104.0},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 60, 'sr': 187.5},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 5, 'sr': 71.43},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 56, 'sr': 215.38},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 18, 'sr': 180.0},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 10, 'sr': 333.33},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 8642, 'name': 'Adam Zampa', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 44, 'sr': 125.71},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 40, 'sr': 97.56},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 2, 'sr': 50.0},
 {'pid': 13088, 'name': 'Devdutt Padikkal', 'runs': 26, 'sr': 123.81},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 2, 'sr': 40.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 15, 'sr': 125.0},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 3, 'sr': 150.0},
 {'pid': 8313, 'name': 'Jason Holder', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 47, 'sr': 127.03},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 0, 'sr': 0.0},
 {'pid': 13088, 'name': 'Devdutt Padikkal', 'runs': 52, 'sr': 152.94},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 22, 'sr': 146.67},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 3, 'sr': 33.33},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 34, 'sr': 212.5},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 12, 'sr': 200.0},
 {'pid': 22466, 'name': 'Abdul Basith', 'runs': 1, 'sr': 100.0},
 {'pid': 8313, 'name': 'Jason Holder', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 124, 'sr': 200.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 18, 'sr': 94.74},
 {'pid': 8271, 'name': 'Samson', 'runs': 14, 'sr': 140.0},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 2, 'sr': 50.0},
 {'pid': 8313, 'name': 'Holder', 'runs': 11, 'sr': 122.22},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 8, 'sr': 88.89},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 2, 'sr': 66.67},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 8, 'sr': 160.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 14336, 'name': 'Kuldeep Sen', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 14, 'sr': 127.27},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 8, 'sr': 133.33},
 {'pid': 8271, 'name': 'Samson', 'runs': 30, 'sr': 150.0},
 {'pid': 13088, 'name': 'Padikkal', 'runs': 12, 'sr': 100.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 2, 'sr': 33.33},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 4, 'sr': 66.67},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 7, 'sr': 53.85},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 9, 'sr': 112.5},
 {'pid': 8117, 'name': 'Boult', 'runs': 15, 'sr': 136.36},
 {'pid': 8642, 'name': 'Zampa', 'runs': 7, 'sr': 77.78},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 2, 'sr': 40.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 35, 'sr': 194.44},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 95, 'sr': 161.02},
 {'pid': 8271, 'name': 'Samson', 'runs': 66, 'sr': 173.68},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 7, 'sr': 140.0},
 {'pid': 8019, 'name': 'Root', 'runs': 0, 'sr': 0.0},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8796, 'name': 'M Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 13537, 'name': 'Kuldip Yadav', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 11221, 'name': 'Obed McCoy', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 98, 'sr': 208.51},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 0, 'sr': 0.0},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 48, 'sr': 165.52},
 {'pid': 8019, 'name': 'Joe Root', 'runs': 0, 'sr': 0.0},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 0, 'sr': 0.0},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 13483, 'name': 'KM Asif', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 0, 'sr': 0.0},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 4, 'sr': 80.0},
 {'pid': 8019, 'name': 'Joe Root', 'runs': 10, 'sr': 66.67},
 {'pid': 13088, 'name': 'Devdutt Padikkal', 'runs': 4, 'sr': 100.0},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 35, 'sr': 184.21},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 1, 'sr': 14.29},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8642, 'name': 'Adam Zampa', 'runs': 2, 'sr': 33.33},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 13483, 'name': 'KM Asif', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0}]

In [80]:
rr_statspd_2023=pd.DataFrame(rr_stats_2023)
rr_2023 = rr_statspd_2023.groupby("pid").agg(
    name=("name", "first"),
    total_runs=("runs", "sum"),
    avg_sr=("sr", "mean"),
    matches=("pid", "count")
).reset_index()


rr_2023["avg_runs_per_match"] = rr_2023["total_runs"] / rr_2023["matches"]
rr_2023["year"] = 2023



rr_2023 = rr_2023[[
    "pid",
    "name",
    "year",
    "total_runs",
    "avg_runs_per_match",
    "avg_sr",
    "matches"
]]


rr_2023 = rr_2023[rr_2023["matches"] >= 5]


rr_2023

,pid,name,year,total_runs,avg_runs_per_match,avg_sr,matches
0,1593,Ravichandran Ashwin,2023,65,5.909091,92.092727,11
1,2258,Jos Buttler,2023,311,28.272727,87.156364,11
2,7910,Yuzvendra Chahal,2023,0,0.000000,0.000000,11
4,8117,Trent Boult,2023,15,1.875000,17.045000,8
5,8271,Sanju Samson,2023,288,26.181818,114.670000,11
6,8313,Jason Holder,2023,12,2.000000,37.036667,6
7,8356,Sandeep Sharma,2023,2,0.200000,4.000000,10
10,9789,Shimron Hetmyer,2023,223,20.272727,118.912727,11
12,12305,Riyan Parag,2023,51,10.200000,98.682000,5
13,13088,Devdutt Padikkal,2023,181,22.625000,107.208750,8
16,13940,Yashasvi Jaiswal,2023,444,40.363636,132.118182,11
18,14691,Dhruv Jurel,2023,108,9.818182,102.966364,11

In [81]:


rr_match_ids_2024=[89668, 89700, 89736, 89756, 91393, 89785, 89809, 91497, 91542, 91587, 91632, 91663, 91686, 91717, 91731, 91746]

import requests 

rr_scorecards_2024 = []

for each in rr_match_ids_2024:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{each}/scard"

    headers = {
        "x-rapidapi-key": "fc7f30fb9cmsh8725b330cc40e86p18a9aejsnb2a96a85740a",
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    try:
        response = requests.get(url, headers=headers)
        rr_scorecards_2024.append(response.json())
    except Exception as e:
        print(f"Error fetching {each}: {e}")

Error fetching 89736: Expecting value: line 1 column 1 (char 0)
Error fetching 89785: Expecting value: line 1 column 1 (char 0)
Error fetching 89809: Expecting value: line 1 column 1 (char 0)
Error fetching 91746: Expecting value: line 1 column 1 (char 0)

In [82]:
rr_stats_2024 = []
for match in rr_scorecards_2024:
    inn_list = match["scorecard"] 
    for innings in inn_list:
        if innings["batteamname"] == "Rajasthan Royals":    # only RR batting innings
            for b in innings["batsman"]:
                player_data5 = {
                    "pid": b["id"],
                    "name": b["name"],
                    "runs": b["runs"],
                    "sr": float(b["strkrate"])
                }           
                rr_stats_2024.append(player_data5)
rr_stats_2024

[{'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 24, 'sr': 200.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 11, 'sr': 122.22},
 {'pid': 8271, 'name': 'Samson', 'runs': 82, 'sr': 157.69},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 43, 'sr': 148.28},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 5, 'sr': 71.43},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 20, 'sr': 166.67},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13630, 'name': 'Nandre Burger', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 5, 'sr': 71.43},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 11, 'sr': 68.75},
 {'pid': 8271, 'name': 'Samson', 'runs': 15, 'sr': 107.14},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 84, 'sr': 186.67},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 29, 'sr': 152.63},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 20, 'sr': 166.67},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 14, 'sr': 200.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 0, 'sr': 0.0},
 {'pid': 13630, 'name': 'Nandre Burger', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 0, 'sr': 0.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 100, 'sr': 172.41},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 69, 'sr': 164.29},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 4, 'sr': 100.0},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 2, 'sr': 66.67},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 11, 'sr': 183.33},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 0, 'sr': 0.0},
 {'pid': 13630, 'name': 'Nandre Burger', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 19328, 'name': 'Shubham Dubey', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 24, 'sr': 126.32},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 8, 'sr': 80.0},
 {'pid': 8271, 'name': 'Samson', 'runs': 68, 'sr': 178.95},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 76, 'sr': 158.33},
 {'pid': 9789, 'name': 'Hetmyer', 'runs': 13, 'sr': 260.0},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 0, 'sr': 0.0},
 {'pid': 14336, 'name': 'Kuldeep Sen', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 9720, 'name': 'Maharaj', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 104, 'sr': 173.33},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 35, 'sr': 140.0},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 38, 'sr': 135.71},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 0, 'sr': 0.0},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 0, 'sr': 0.0},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 0, 'sr': 0.0},
 {'pid': 11445, 'name': 'Rovman Powell', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 24, 'sr': 133.33},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 34, 'sr': 188.89},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 71, 'sr': 215.15},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 14, 'sr': 127.27},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 52, 'sr': 152.94},
 {'pid': 11445, 'name': 'Rovman Powell', 'runs': 0, 'sr': 0.0},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 67, 'sr': 167.5},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 0, 'sr': 0.0},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 0, 'sr': 0.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 77, 'sr': 157.14},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 13, 'sr': 144.44},
 {'pid': 11445, 'name': 'Rovman Powell', 'runs': 27, 'sr': 180.0},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 1, 'sr': 33.33},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 2, 'sr': 100.0},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 4, 'sr': 200.0},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 19, 'sr': 111.76},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 86, 'sr': 186.96},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 27, 'sr': 122.73},
 {'pid': 19328, 'name': 'Shubham Dubey', 'runs': 25, 'sr': 208.33},
 {'pid': 11445, 'name': 'Rovman Powell', 'runs': 13, 'sr': 130.0},
 {'pid': 14798, 'name': 'Donovan Ferreira', 'runs': 1, 'sr': 33.33},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 2, 'sr': 66.67},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 2, 'sr': 66.67},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 7, 'sr': 233.33},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 24, 'sr': 114.29},
 {'pid': 2258, 'name': 'Jos Buttler', 'runs': 21, 'sr': 84.0},
 {'pid': 8271, 'name': 'Samson', 'runs': 15, 'sr': 78.95},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 47, 'sr': 134.29},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 28, 'sr': 155.56},
 {'pid': 19328, 'name': 'Shubham Dubey', 'runs': 0, 'sr': 0.0},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 1, 'sr': 100.0},
 {'pid': 8117, 'name': 'Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13630, 'name': 'Nandre Burger', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 4, 'sr': 100.0},
 {'pid': 10033, 'name': 'Kohler-Cadmore', 'runs': 18, 'sr': 78.26},
 {'pid': 8271, 'name': 'Samson', 'runs': 18, 'sr': 120.0},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 48, 'sr': 141.18},
 {'pid': 1593, 'name': 'Ashwin', 'runs': 28, 'sr': 147.37},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 0, 'sr': 0.0},
 {'pid': 11445, 'name': 'Rovman Powell', 'runs': 4, 'sr': 80.0},
 {'pid': 14798, 'name': 'Donovan Ferreira', 'runs': 7, 'sr': 87.5},
 {'pid': 8117, 'name': 'Boult', 'runs': 12, 'sr': 133.33},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 3, 'sr': 150.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Chahal', 'runs': 0, 'sr': 0.0},
 {'pid': 13940, 'name': 'Yashasvi Jaiswal', 'runs': 45, 'sr': 150.0},
 {'pid': 10033, 'name': 'Tom Kohler-Cadmore', 'runs': 20, 'sr': 133.33},
 {'pid': 8271, 'name': 'Sanju Samson', 'runs': 17, 'sr': 130.77},
 {'pid': 12305, 'name': 'Riyan Parag', 'runs': 36, 'sr': 138.46},
 {'pid': 14691, 'name': 'Dhruv Jurel', 'runs': 8, 'sr': 100.0},
 {'pid': 9789, 'name': 'Shimron Hetmyer', 'runs': 26, 'sr': 185.71},
 {'pid': 11445, 'name': 'Rovman Powell', 'runs': 16, 'sr': 200.0},
 {'pid': 1593, 'name': 'Ravichandran Ashwin', 'runs': 0, 'sr': 0.0},
 {'pid': 8117, 'name': 'Trent Boult', 'runs': 0, 'sr': 0.0},
 {'pid': 9781, 'name': 'Avesh Khan', 'runs': 0, 'sr': 0.0},
 {'pid': 8356, 'name': 'Sandeep Sharma', 'runs': 0, 'sr': 0.0},
 {'pid': 7910, 'name': 'Yuzvendra Chahal', 'runs': 0, 'sr': 0.0}]

In [83]:
rr_statspd_2024=pd.DataFrame(rr_stats_2024)
rr_2024 = rr_statspd_2024.groupby("pid").agg(
    name=("name", "first"),
    total_runs=("runs", "sum"),
    avg_sr=("sr", "mean"),
    matches=("pid", "count")
).reset_index()


rr_2024["avg_runs_per_match"] = rr_2024["total_runs"] / rr_2024["matches"]
rr_2024["year"] = 2024



rr_2024 = rr_2024[[
    "pid",
    "name",
    "year",
    "total_runs",
    "avg_runs_per_match",
    "avg_sr",
    "matches"
]]


rr_2024 = rr_2024[rr_2024["matches"] >= 5]


rr_2024

,pid,name,year,total_runs,avg_runs_per_match,avg_sr,matches
0,1593,Ashwin,2024,62,5.636364,51.515455,11
1,2258,Jos Buttler,2024,239,26.555556,107.558889,9
2,7910,Chahal,2024,0,0.000000,0.000000,11
3,8117,Boult,2024,14,1.272727,18.181818,11
4,8271,Samson,2024,479,43.545455,134.146364,11
5,8356,Sandeep Sharma,2024,0,0.000000,0.000000,9
7,9781,Avesh Khan,2024,10,0.909091,34.848182,11
8,9789,Hetmyer,2024,82,10.250000,130.613750,8
10,11445,Rovman Powell,2024,60,10.000000,98.333333,6
11,12305,Riyan Parag,2024,456,41.454545,128.577273,11
13,13940,Yashasvi Jaiswal,2024,325,29.545455,130.563636,11
15,14691,Dhruv Jurel,2024,131,13.100000,84.184000,10

In [84]:
import pandas as pd

rr_all = pd.concat([rr_2024, rr_2023, rr_2022, rr_2021, rr_2020])
rr_all

rr_all=rr_all.round({'avg_runs_per_match': 2, 'avg_sr': 2})

In [85]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

table_name = "rr_batt_stats" 

engine = create_engine(
f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


rr_all.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz rr_batt_stats

Q.17
Investigate whether winning the toss gives teams an advantage in winning matches. Calculate what percentage of matches are won by the team that wins the toss, broken down by their toss decision (choosing to bat first or bowl first).

In [86]:
rr_match_ids_2024

[89668,
 89700,
 89736,
 89756,
 91393,
 89785,
 89809,
 91497,
 91542,
 91587,
 91632,
 91663,
 91686,
 91717,
 91731,
 91746]

In [87]:
import requests
rr_match_ids_2024=[89668,89700,89736,66186, 66208, 66218, 66250, 66274,89756,91393, 89785, 89809, 91497, 91542, 91587, 91632, 91663, 91686, 91717, 91731, 91746]
matchdata=[]
for i in rr_match_ids_2024:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{i}"
    headers = {
	    "x-rapidapi-key": "fc7f30fb9cmsh8725b330cc40e86p18a9aejsnb2a96a85740a",
	    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    try:
        response = requests.get(url, headers=headers)
        matchdata.append(response.json())
    except:
        continue

matchdata

[{'matchid': 89668,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '4th Match',
  'matchformat': 'T20',
  'startdate': 1711274400000,
  'enddate': 1711288497383,
  'state': 'Complete',
  'status': 'Rajasthan Royals opt to bat',
  'team1': {'teamid': 64,
   'teamname': 'Rajasthan Royals',
   'teamsname': 'RR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 966,
   'teamname': 'Lucknow Super Giants',
   'teamsname': 'LSG',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 14178, 'name': 'Akshay Totre', 'country': 'IND'},
  'umpire2': {'id': 3576, 'name': 'Kumar Dharmasena', 'country': 'SL'},
  'umpire3': {'id': 8871, 'name': 'KN Anantha Padmanabhan', 'country': 'IND'},
  'referee': {'id': 9225, 'name': 'Prakash Bhatt', 'country': 'IND'},
  'venueinfo': {'id': 76,
   'ground': 'Sawai Mansingh Stadium',
   'city': 'Jaipur',
   'country': 'India',
   'timezone': '+05:30',
   'established': 0,
   'capacity': '30000',
   'knownas': '',
   'ends': '',
   'hometeam': 'Rajasthan, Rajasthan Royals',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts RR vs LSG 4th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/89668/rr-vs-lsg-4th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Rajasthan Royals opt to bat',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'RR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 387729,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 89700,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '9th Match',
  'matchformat': 'T20',
  'startdate': 1711634400000,
  'enddate': 1711648537923,
  'state': 'Complete',
  'status': 'Delhi Capitals opt to bowl',
  'team1': {'teamid': 64,
   'teamname': 'Rajasthan Royals',
   'teamsname': 'RR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 61,
   'teamname': 'Delhi Capitals',
   'teamsname': 'DC',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8862, 'name': 'Nitin Menon', 'country': 'IND'},
  'umpire2': {'id': 8874, 'name': 'Nand Kishore', 'country': 'IND'},
  'umpire3': {'id': 8909, 'name': 'Virender Sharma', 'country': 'IND'},
  'referee': {'id': 3894, 'name': 'Javagal Srinath', 'country': 'IND'},
  'venueinfo': {'id': 76,
   'ground': 'Sawai Mansingh Stadium',
   'city': 'Jaipur',
   'country': 'India',
   'timezone': '+05:30',
   'established': 0,
   'capacity': '30000',
   'knownas': '',
   'ends': '',
   'hometeam': 'Rajasthan, Rajasthan Royals',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts RR vs DC 9th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/89700/rr-vs-dc-9th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Delhi Capitals opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'RR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 387746,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 66208,
  'seriesid': 5945,
  'seriesname': 'Indian Premier League 2023',
  'matchdesc': '8th Match',
  'matchformat': 'T20',
  'startdate': 1680703200000,
  'enddate': 1680718460976,
  'state': 'Complete',
  'status': 'Rajasthan Royals opt to bowl',
  'team1': {'teamid': 64,
   'teamname': 'Rajasthan Royals',
   'teamsname': 'RR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 65,
   'teamname': 'Punjab Kings',
   'teamsname': 'PBKS',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8871, 'name': 'KN Anantha Padmanabhan', 'country': 'IND'},
  'umpire2': {'id': 10593, 'name': 'Sai Darshan Kumar', 'country': 'IND'},
  'umpire3': {'id': 8867, 'name': 'Rohan Pandit', 'country': 'IND'},
  'referee': {'id': 8968, 'name': 'Vengalil Narayan Kutty', 'country': 'IND'},
  'venueinfo': {'id': 380,
   'ground': 'Barsapara Cricket Stadium',
   'city': 'Guwahati',
   'country': 'India',
   'timezone': '+05:30',
   'established': 2012,
   'capacity': '40000',
   'knownas': '',
   'ends': 'Media End, Pavilion End',
   'hometeam': 'Assam',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts RR vs PBKS 8th Match,Indian Premier League 2023 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/66208/rr-vs-pbks-8th-match-indian-premier-league-2023'},
  'istournament': True,
  'tossstatus': 'Rajasthan Royals opt to bowl',
  'seriesstartdt': 1680134400000,
  'seriesenddt': 1685318400000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'PBKS won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 876143,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 66218,
  'seriesid': 5945,
  'seriesname': 'Indian Premier League 2023',
  'matchdesc': '11th Match',
  'matchformat': 'T20',
  'startdate': 1680948000000,
  'enddate': 1680961853072,
  'state': 'Complete',
  'status': 'Delhi Capitals opt to bowl',
  'team1': {'teamid': 64,
   'teamname': 'Rajasthan Royals',
   'teamsname': 'RR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 61,
   'teamname': 'Delhi Capitals',
   'teamsname': 'DC',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 9678, 'name': 'Navdeep Singh', 'country': 'IND'},
  'umpire2': {'id': 18923, 'name': 'Saidharshan Kumar', 'country': 'IND'},
  'umpire3': {'id': 8871, 'name': 'KN Anantha Padmanabhan', 'country': 'IND'},
  'referee': {'id': 8968,
   'name': 'Vengalil Narayanan Kutty',
   'country': 'IND'},
  'venueinfo': {'id': 380,
   'ground': 'Barsapara Cricket Stadium',
   'city': 'Guwahati',
   'country': 'India',
   'timezone': '+05:30',
   'established': 2012,
   'capacity': '40000',
   'knownas': '',
   'ends': 'Media End, Pavilion End',
   'hometeam': 'Assam',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts RR vs DC 11th Match,Indian Premier League 2023 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/66218/rr-vs-dc-11th-match-indian-premier-league-2023'},
  'istournament': True,
  'tossstatus': 'Delhi Capitals opt to bowl',
  'seriesstartdt': 1680134400000,
  'seriesenddt': 1685318400000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'RR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 876143,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 66250,
  'seriesid': 5945,
  'seriesname': 'Indian Premier League 2023',
  'matchdesc': '17th Match',
  'matchformat': 'T20',
  'startdate': 1681308000000,
  'enddate': 1681321969415,
  'state': 'Complete',
  'status': 'Chennai Super Kings opt to bowl',
  'team1': {'teamid': 58,
   'teamname': 'Chennai Super Kings',
   'teamsname': 'CSK',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 64,
   'teamname': 'Rajasthan Royals',
   'teamsname': 'RR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 13663, 'name': 'Vinod Seshan', 'country': 'IND'},
  'umpire2': {'id': 8909, 'name': 'Virender Sharma', 'country': 'IND'},
  'umpire3': {'id': 8862, 'name': 'Nitin Menon', 'country': 'IND'},
  'referee': {'id': 3894, 'name': 'Javagal Srinath', 'country': 'IND'},
  'venueinfo': {'id': 11,
   'ground': 'MA Chidambaram Stadium',
   'city': 'Chennai',
   'country': 'India',
   'timezone': '+05:30',
   'established': 0,
   'capacity': '50000',
   'knownas': '',
   'ends': 'Anna Pavilion End, V Pattabhiraman Gate End',
   'hometeam': 'Tamil Nadu, Chennai Super Kings',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts CSK vs RR 17th Match,Indian Premier League 2023 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/66250/csk-vs-rr-17th-match-indian-premier-league-2023'},
  'istournament': True,
  'tossstatus': 'Chennai Super Kings opt to bowl',
  'seriesstartdt': 1680134400000,
  'seriesenddt': 1685318400000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': True,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'RR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 876143,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 66274,
  'seriesid': 5945,
  'seriesname': 'Indian Premier League 2023',
  'matchdesc': '23rd Match',
  'matchformat': 'T20',
  'startdate': 1681653600000,
  'enddate': 1681666715414,
  'state': 'Complete',
  'status': 'Rajasthan Royals opt to bowl',
  'team1': {'teamid': 971,
   'teamname': 'Gujarat Titans',
   'teamsname': 'GT',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 64,
   'teamname': 'Rajasthan Royals',
   'teamsname': 'RR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8297, 'name': 'Anil Kumar Chaudhary', 'country': 'IND'},
  'umpire2': {'id': 6864, 'name': 'Chris Gaffaney', 'country': 'NZ'},
  'umpire3': {'id': 38169, 'name': 'A Nanda Kishore', 'country': 'IND'},
  'referee': {'id': 9225, 'name': 'Prakash Bhatt', 'country': 'IND'},
  'venueinfo': {'id': 50,
   'ground': 'Narendra Modi Stadium',
   'city': 'Ahmedabad',
   'country': 'India',
   'timezone': '+05:30',
   'established': 1982,
   'capacity': '132,000',
   'knownas': '',
   'ends': 'Adani Pavilion End, GMDC End',
   'hometeam': 'Gujarat, Gujarat Titans',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts GT vs RR 23rd Match,Indian Premier League 2023 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/66274/gt-vs-rr-23rd-match-indian-premier-league-2023'},
  'istournament': True,
  'tossstatus': 'Rajasthan Royals opt to bowl',
  'seriesstartdt': 1680134400000,
  'seriesenddt': 1685318400000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'RR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 876143,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 89756,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '19th Match',
  'matchformat': 'T20',
  'startdate': 1712412000000,
  'enddate': 1712424990055,
  'state': 'Complete',
  'status': 'Rajasthan Royals opt to bowl',
  'team1': {'teamid': 64,
   'teamname': 'Rajasthan Royals',
   'teamsname': 'RR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 59,
   'teamname': 'Royal Challengers Bengaluru',
   'teamsname': 'RCB',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 8905, 'name': 'Jayaraman Madanagopal', 'country': 'IND'},
  'umpire2': {'id': 9608, 'name': 'Tapan Sharma', 'country': 'IND'},
  'umpire3': {'id': 5475, 'name': 'Alex Wharf', 'country': 'ENG'},
  'referee': {'id': 8968,
   'name': 'Vengalil Narayanan Kutty',
   'country': 'IND'},
  'venueinfo': {'id': 76,
   'ground': 'Sawai Mansingh Stadium',
   'city': 'Jaipur',
   'country': 'India',
   'timezone': '+05:30',
   'established': 0,
   'capacity': '30000',
   'knownas': '',
   'ends': '',
   'hometeam': 'Rajasthan, Rajasthan Royals',
   'floodlights': False,
   'curator': '',
   'profile': '',
   'imageurl': '',
   'groundlength': 0.0,
   'groundwidth': 0.0,
   'othersports': '',
   'imageid': 0,
   'latitude': '',
   'longitude': ''},
  'currbatteamid': 0,
  'ismatchnotcovered': False,
  'appindex': {'seotitle': 'Cricket match facts RR vs RCB 19th Match,Indian Premier League 2024 | Cricbuzz.com',
   'weburl': 'http://www.cricbuzz.com/cricket-match-facts/89756/rr-vs-rcb-19th-match-indian-premier-league-2024'},
  'istournament': True,
  'tossstatus': 'Rajasthan Royals opt to bowl',
  'seriesstartdt': 1710979200000,
  'seriesenddt': 1716768000000,
  'istimeannounced': False,
  'statetitle': '',
  'replacematchid': 0,
  'livestreamenabled': False,
  'isfantasyenabled': True,
  'broadcastinfo': [],
  'daynight': False,
  'matchtype': 'league',
  'seriestype': 'IPL',
  'shortstatus': 'RR won',
  'boundarytrackervalues': {'boundarytrackervalue': []},
  'matchimageid': 402062,
  'islivestreamenabled': False,
  'isfantasyhandbookenabled': False,
  'isforecastenabled': False,
  'ispollenabled': False},
 {'matchid': 91393,
  'seriesid': 7607,
  'seriesname': 'Indian Premier League 2024',
  'matchdesc': '24th Match',
  'matchformat': 'T20',
  'startdate': 1712757600000,
  'enddate': 1712773123113,
  'state': 'Complete',
  'status': 'Gujarat Titans opt to bowl',
  'team1': {'teamid': 64,
   'teamname': 'Rajasthan Royals',
   'teamsname': 'RR',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'team2': {'teamid': 971,
   'teamname': 'Gujarat Titans',
   'teamsname': 'GT',
   'isfullmember': False,
   'isassociated': False,
   'isleagueteam': False,
   'iswomenteam': False,
   'isheader': False,
   'isactive': False,
   'teampriority': '',
   'isvideopresent': False,
   'imageid': 0,
   'countryname': '',
   'belongsto': '',
   'teamcolor': ''},
  'umpire1': {'id': 3576, 'name': 'Kumar Dharmasena', 'country': 'SL'},
  'umpire2': {'id': 13663, 'name': 'Vinod Seshan', 'country': 'IND'},
  'umpire3': {'id': 8871, 'name': 'KN Anantha Padmanabhan', 'country': 'IND'},
  'referee': {'id': 9225, 'name': 'Prakash Bhatt', 'country': 'IND'},
  'venueinfo': {'id': 76,
   'ground': 'Sawai Mansingh Stadium',
   'city': 'Jaipur',
   'country': 'India',
   'timezone': '+05:30',
   'established': 0,
   'capacity': '30000',
   'knownas': '',
   'ends': '',
   'hometeam': 'Rajasthan, Rajasthan Royals',
   'floodlights': False,

In [88]:
matches_toss_data = []

for match in matchdata:
    toss_status = match['tossstatus'].lower()
    toss_winner = match['tossstatus'].split(' opt')[0].strip()
    match_winner = match['shortstatus'].replace(' won','').strip()
    toss_decision = 'bat' if 'bat' in toss_status else 'bowl'
    
    matches_toss_data.append({
        'matchid': match['matchid'],
        'toss_winner': toss_winner,
        'toss_status': "won" if toss_winner == "Rajasthan Royals" else "lost",
        'toss_decision': toss_decision if toss_winner == "Rajasthan Royals" else "Null",
        'match_winner': match_winner
    })

matches_toss_data

[{'matchid': 89668,
  'toss_winner': 'Rajasthan Royals',
  'toss_status': 'won',
  'toss_decision': 'bat',
  'match_winner': 'RR'},
 {'matchid': 89700,
  'toss_winner': 'Delhi Capitals',
  'toss_status': 'lost',
  'toss_decision': 'Null',
  'match_winner': 'RR'},
 {'matchid': 66208,
  'toss_winner': 'Rajasthan Royals',
  'toss_status': 'won',
  'toss_decision': 'bowl',
  'match_winner': 'PBKS'},
 {'matchid': 66218,
  'toss_winner': 'Delhi Capitals',
  'toss_status': 'lost',
  'toss_decision': 'Null',
  'match_winner': 'RR'},
 {'matchid': 66250,
  'toss_winner': 'Chennai Super Kings',
  'toss_status': 'lost',
  'toss_decision': 'Null',
  'match_winner': 'RR'},
 {'matchid': 66274,
  'toss_winner': 'Rajasthan Royals',
  'toss_status': 'won',
  'toss_decision': 'bowl',
  'match_winner': 'RR'},
 {'matchid': 89756,
  'toss_winner': 'Rajasthan Royals',
  'toss_status': 'won',
  'toss_decision': 'bowl',
  'match_winner': 'RR'},
 {'matchid': 91393,
  'toss_winner': 'Gujarat Titans',
  'toss_status': 'lost',
  'toss_decision': 'Null',
  'match_winner': 'GT'},
 {'matchid': 91497,
  'toss_winner': 'Mumbai Indians',
  'toss_status': 'lost',
  'toss_decision': 'Null',
  'match_winner': 'RR'},
 {'matchid': 91542,
  'toss_winner': 'Rajasthan Royals',
  'toss_status': 'won',
  'toss_decision': 'bowl',
  'match_winner': 'RR'},
 {'matchid': 91587,
  'toss_winner': 'Sunrisers Hyderabad',
  'toss_status': 'lost',
  'toss_decision': 'Null',
  'match_winner': 'SRH'},
 {'matchid': 91632,
  'toss_winner': 'Rajasthan Royals',
  'toss_status': 'won',
  'toss_decision': 'bowl',
  'match_winner': 'DC'},
 {'matchid': 91663,
  'toss_winner': 'Rajasthan Royals',
  'toss_status': 'won',
  'toss_decision': 'bat',
  'match_winner': 'CSK'},
 {'matchid': 91686,
  'toss_winner': 'Rajasthan Royals',
  'toss_status': 'won',
  'toss_decision': 'bat',
  'match_winner': 'PBKS'},
 {'matchid': 91717,
  'toss_winner': 'Kolkata Knight Riders',
  'toss_status': 'lost',
  'toss_decision': 'Null',
  'match_winner': 'Abandon'},
 {'matchid': 91731,
  'toss_winner': 'Rajasthan Royals',
  'toss_status': 'won',
  'toss_decision': 'bowl',
  'match_winner': 'RR'}]

In [89]:
data = [
    {'matchid': 89668, 'toss_winner': 'Rajasthan Royals', 'toss_status': 'won',  'toss_decision': 'bat',  'match_winner': 'RR'},
    {'matchid': 89700, 'toss_winner': 'Delhi Capitals',   'toss_status': 'lost', 'toss_decision': 'Null', 'match_winner': 'RR'},
    {'matchid': 66208, 'toss_winner': 'Rajasthan Royals', 'toss_status': 'won',  'toss_decision': 'bowl', 'match_winner': 'PBKS'},
    {'matchid': 66218, 'toss_winner': 'Delhi Capitals',   'toss_status': 'lost', 'toss_decision': 'Null', 'match_winner': 'RR'},
    {'matchid': 66250, 'toss_winner': 'Chennai Super Kings', 'toss_status': 'lost', 'toss_decision': 'Null', 'match_winner': 'RR'},
    {'matchid': 66274, 'toss_winner': 'Rajasthan Royals', 'toss_status': 'won',  'toss_decision': 'bowl', 'match_winner': 'RR'},
    {'matchid': 89756, 'toss_winner': 'Rajasthan Royals', 'toss_status': 'won',  'toss_decision': 'bowl', 'match_winner': 'RR'},
    {'matchid': 91393, 'toss_winner': 'Gujarat Titans',   'toss_status': 'lost', 'toss_decision': 'Null', 'match_winner': 'GT'},
    {'matchid': 91497, 'toss_winner': 'Mumbai Indians',   'toss_status': 'lost', 'toss_decision': 'Null', 'match_winner': 'RR'},
    {'matchid': 91542, 'toss_winner': 'Rajasthan Royals', 'toss_status': 'won',  'toss_decision': 'bowl', 'match_winner': 'RR'},
    {'matchid': 91587, 'toss_winner': 'Sunrisers Hyderabad', 'toss_status': 'lost', 'toss_decision': 'Null', 'match_winner': 'SRH'},
    {'matchid': 91632, 'toss_winner': 'Rajasthan Royals', 'toss_status': 'won',  'toss_decision': 'bowl', 'match_winner': 'DC'},
    {'matchid': 91663, 'toss_winner': 'Rajasthan Royals', 'toss_status': 'won',  'toss_decision': 'bat',  'match_winner': 'CSK'},
    {'matchid': 91686, 'toss_winner': 'Rajasthan Royals', 'toss_status': 'won',  'toss_decision': 'bat',  'match_winner': 'PBKS'},
    {'matchid': 91717, 'toss_winner': 'Kolkata Knight Riders', 'toss_status': 'lost', 'toss_decision': 'Null', 'match_winner': 'Abandon'},
    {'matchid': 91731, 'toss_winner': 'Rajasthan Royals', 'toss_status': 'won',  'toss_decision': 'bowl', 'match_winner': 'RR'}
]

win_toss_bat = {'wins': 0, 'total': 0}
win_toss_bowl = {'wins': 0, 'total': 0}
lost_toss = {'wins': 0, 'total': 0}

for m in data:
    is_rr_winner = (m['match_winner'] == 'RR')
    rr_won_toss = (m['toss_winner'] == 'Rajasthan Royals')
    
    if rr_won_toss:
        if m['toss_decision'] == 'bat':
            win_toss_bat['total'] += 1
            if is_rr_winner:
                win_toss_bat['wins'] += 1
        
        elif m['toss_decision'] == 'bowl':
            win_toss_bowl['total'] += 1
            if is_rr_winner:
                win_toss_bowl['wins'] += 1
    
    else:
        lost_toss['total'] += 1
        if is_rr_winner:
            lost_toss['wins'] += 1


def percent(x):
    return round((x['wins'] / x['total']) * 100, 2) if x['total'] > 0 else 0

print("RR win % when they win toss & bat :", percent(win_toss_bat), "%")
print("RR win % when they win toss & bowl:", percent(win_toss_bowl), "%")
print("RR win % when they lose the toss  :", percent(lost_toss), "%")

RR win % when they win toss & bat : 33.33 %
RR win % when they win toss & bowl: 66.67 %
RR win % when they lose the toss  : 57.14 %

In [90]:
rr_toss_data=pd.DataFrame(matches_toss_data)

rr_toss_data["win_percent"] = None

# 1) RR won toss & chose bat
rr_toss_data.loc[
    (rr_toss_data["toss_winner"] == "Rajasthan Royals") &
    (rr_toss_data["toss_decision"] == "bat"),
    "win_percent"
] = 33.33

# 2) RR won toss & chose bowl
rr_toss_data.loc[
    (rr_toss_data["toss_winner"] == "Rajasthan Royals") &
    (rr_toss_data["toss_decision"] == "bowl"),
    "win_percent"
] = 66.67

# 3) RR lost the toss
rr_toss_data.loc[
    (rr_toss_data["toss_winner"] != "Rajasthan Royals"),
    "win_percent"
] = 57.14

In [91]:
rr_toss_data

,matchid,toss_winner,toss_status,toss_decision,match_winner,win_percent
0,89668,Rajasthan Royals,won,bat,RR,33.33
1,89700,Delhi Capitals,lost,Null,RR,57.14
2,66208,Rajasthan Royals,won,bowl,PBKS,66.67
3,66218,Delhi Capitals,lost,Null,RR,57.14
4,66250,Chennai Super Kings,lost,Null,RR,57.14
5,66274,Rajasthan Royals,won,bowl,RR,66.67
6,89756,Rajasthan Royals,won,bowl,RR,66.67
7,91393,Gujarat Titans,lost,Null,GT,57.14
8,91497,Mumbai Indians,lost,Null,RR,57.14
9,91542,Rajasthan Royals,won,bowl,RR,66.67
10,91587,Sunrisers Hyderabad,lost,Null,SRH,57.14
11,91632,Rajasthan Royals,won,bowl,DC,66.67
12,91663,Rajasthan Royals,won,bat,CSK,33.33
13,91686,Rajasthan Royals,won,bat,PBKS,33.33
14,91717,Kolkata Knight Riders,lost,Null,Abandon,57.14
15,91731,Rajasthan Royals,won,bowl,RR,66.67

In [92]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

table_name = "rr_toss_data" 

engine = create_engine(
f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


rr_toss_data.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz rr_toss_data

In [ ]:
Q.18
Find the most economical bowlers in limited-overs cricket (ODI and T20 formats). Calculate each bowler's overall economy rate and total wickets taken. Only consider bowlers who have bowled in at least 10 matches and bowled at least 2 overs per match on average.

In [93]:
aus_match_ids=[75437, 75465, 75481, 75505, 75549, 75569, 75593, 75609, 75629, 75641, 75651]

In [94]:
import requests
aus_scorecards=[]
for match_id1 in aus_match_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{match_id1}/scard"

    headers = {
	    "x-rapidapi-key": "fc7f30fb9cmsh8725b330cc40e86p18a9aejsnb2a96a85740a",
	    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    try:
        response = requests.get(url, headers=headers)
        aus_scorecards.append(response.json())
    except:
        continue
aus_scorecards

[{'scorecard': [{'inningsid': 1,
    'batsman': [{'id': 1739,
      'balls': 52,
      'runs': 41,
      'fours': 6,
      'sixes': 0,
      'strkrate': '78.85',
      'name': 'Warner',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c and b Kuldeep Yadav',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 6250,
      'balls': 6,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Mitchell Marsh',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Kohli b Bumrah',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 2250,
      'balls': 71,
      'runs': 46,
      'fours': 5,
      'sixes': 0,
      'strkrate': '64.79',
      'name': 'Steven Smith',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'b Ravindra Jadeja',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 10182,
      'balls': 41,
      'runs': 27,
      'fours': 1,
      'sixes': 0,
      'strkrate': '65.85',
      'name': 'Labuschagne',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Rahul b Ravindra Jadeja',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 7662,
      'balls': 25,
      'runs': 15,
      'fours': 1,
      'sixes': 0,
      'strkrate': '60',
      'name': 'Maxwell',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'b Kuldeep Yadav',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9200,
      'balls': 2,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Alex Carey',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': True,
      'outdec': 'lbw b Ravindra Jadeja',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 12225,
      'balls': 20,
      'runs': 8,
      'fours': 0,
      'sixes': 0,
      'strkrate': '40',
      'name': 'Green',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Hardik Pandya b Ashwin',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8095,
      'balls': 24,
      'runs': 15,
      'fours': 1,
      'sixes': 1,
      'strkrate': '62.5',
      'name': 'Cummins',
      'nickname': '',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'c Shreyas Iyer b Bumrah',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 7710,
      'balls': 35,
      'runs': 28,
      'fours': 2,
      'sixes': 1,
      'strkrate': '80',
      'name': 'Starc',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Shreyas Iyer b Siraj',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8642,
      'balls': 20,
      'runs': 6,
      'fours': 0,
      'sixes': 0,
      'strkrate': '30',
      'name': 'Zampa',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Kohli b Hardik Pandya',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 6258,
      'balls': 1,
      'runs': 1,
      'fours': 0,
      'sixes': 0,
      'strkrate': '100',
      'name': 'Hazlewood',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''}],
    'bowler': [{'id': 9311,
      'overs': '10',
      'maidens': 0,
      'wickets': 2,
      'runs': 35,
      'economy': '3.5',
      'name': 'Bumrah',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 60,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 10808,
      'overs': '6.3',
      'maidens': 1,
      'wickets': 1,
      'runs': 26,
      'economy': '4',
      'name': 'Siraj',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 39,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9647,
      'overs': '3',
      'maidens': 0,
      'wickets': 1,
      'runs': 28,
      'economy': '9.3',
      'name': 'Hardik Pandya',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 18,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 1593,
      'overs': '10',
      'maidens': 1,
      'wickets': 1,
      'runs': 34,
      'economy': '3.4',
      'name': 'Ashwin',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 60,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8292,
      'overs': '10',
      'maidens': 0,
      'wickets': 2,
      'runs': 42,
      'economy': '4.2',
      'name': 'Kuldeep Yadav',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 60,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 587,
      'overs': '10',
      'maidens': 2,
      'wickets': 3,
      'runs': 28,
      'economy': '2.8',
      'name': 'Ravindra Jadeja',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 60,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''}],
    'fow': {'fow': [{'batsmanid': 6250,
       'batsmanname': 'Mitchell Marsh',
       'overnbr': 2.2,
       'runs': 5,
       'ballnbr': 14},
      {'batsmanid': 1739,
       'batsmanname': 'Warner',
       'overnbr': 16.3,
       'runs': 74,
       'ballnbr': 99},
      {'batsmanid': 2250,
       'batsmanname': 'Steven Smith',
       'overnbr': 27.1,
       'runs': 110,
       'ballnbr': 163},
      {'batsmanid': 10182,
       'batsmanname': 'Labuschagne',
       'overnbr': 29.2,
       'runs': 119,
       'ballnbr': 176},
      {'batsmanid': 9200,
       'batsmanname': 'Alex Carey',
       'overnbr': 29.4,
       'runs': 119,
       'ballnbr': 178},
      {'batsmanid': 7662,
       'batsmanname': 'Maxwell',
       'overnbr': 35.5,
       'runs': 140,
       'ballnbr': 215},
      {'batsmanid': 12225,
       'batsmanname': 'Green',
       'overnbr': 36.2,
       'runs': 140,
       'ballnbr': 218},
      {'batsmanid': 8095,
       'batsmanname': 'Cummins',
       'overnbr': 42.2,
       'runs': 165,
       'ballnbr': 254},
      {'batsmanid': 8642,
       'batsmanname': 'Zampa',
       'overnbr': 48.2,
       'runs': 189,
       'ballnbr': 290},
      {'batsmanid': 7710,
       'batsmanname': 'Starc',
       'overnbr': 49.3,
       'runs': 199,
       'ballnbr': 297}]},
    'extras': {'legbyes': 6,
     'byes': 0,
     'wides': 6,
     'noballs': 0,
     'penalty': 0,
     'total': 12},
    'pp': {'powerplay': [{'id': 4,
       'ovrfrom': 0.1,
       'ovrto': 10.0,
       'pptype': 'Mandatory',
       'run': 43,
       'wickets': 0}]},
    'score': 199,
    'wickets': 10,
    'overs': 49.3,
    'runrate': 4.02,
    'batteamname': 'Australia',
    'batteamsname': 'AUS',
    'isdeclared': False,
    'isfollowon': False,
    'ballnbr': 297,
    'rpb': 0.67,
    'partnership': {'partnership': [{'id': 0,
       'bat1id': 1739,
       'bat1name': 'Warner',
       'bat1runs': 5,
       'bat1fours': 1,
       'bat1sixes': 0,
       'bat2id': 6250,
       'bat2name': 'Mitchell Marsh',
       'bat2runs': 0,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 5,
       'totalballs': 14,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 1739,
       'bat1name': 'Warner',
       'bat1runs': 35,
       'bat1fours': 5,
       'bat1sixes': 0,
       'bat2id': 2250,
       'bat2name': 'Smith',
       'bat2runs': 33,
       'bat2fours': 5,
       'bat2sixes': 0,
       'totalruns': 69,
       'totalballs': 85,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 10182,
       'bat1name': 'Labuschagne',
       'bat1runs': 22,
       'bat1fours': 1,
       'bat1sixes': 0,
       'bat2id': 2250,
       'bat2name': 'Smith',
       'bat2runs': 13,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 36,
       'totalballs': 64,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 10182,
       'bat1name': 'Labuschagne',
       'bat1runs': 5,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 7662,
       'bat2name': 'Maxwell',
       'bat2runs': 4,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 9,
       'totalballs': 13,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 9200,
       'bat1name': 'Carey',
       'bat1runs': 0,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 7662,
       'bat2name': 'Maxwell',
       'bat2runs': 0,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 0,
       'totalballs': 2,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 12225,
       'bat1name': 'Green',
       'bat1runs': 8,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 7662,
       'bat2name': 'Maxwell',
       'bat2runs': 11,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 21,
       'totalballs': 37,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 12225,
       'bat1name': 'Green',
       'bat1runs': 0,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 8095,
       'bat2name': 'Cummins',
       'bat2runs': 0,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 0,
       'totalballs': 3,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 7710,
       'bat1name': 'Starc',
       'bat1runs': 6,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 8095,
       'bat2name': 'Cummins',
       'bat2runs': 15,
       'bat2fours': 1,
       'bat2sixes': 1,
       'totalruns': 25,
       'totalballs': 36,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 7710,
       'bat1name': 'Starc',
       'bat1runs': 14,
       'bat1fours': 0,
       'bat1sixes': 1,
       'bat2id': 8642,
       'bat2name': 'Zampa',
       'bat2runs': 6,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 24,
       'totalballs': 36,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 7710,
       'bat1name': 'Starc',
       'bat1runs': 9,
       'bat1fours': 2,
       'bat1sixes': 0,
       'bat2id': 6258,
       'bat2name': 'Hazlewood',
       'bat2runs': 1,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 10,
       'totalballs': 7,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0}]}},
   {'inningsid': 2,
    'batsman': [{'id': 576,
      'balls': 6,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Rohit Sharma',
      'nickname': 'Rohit',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'lbw b Hazlewood',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 10276,
      'balls': 1,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Ishan Kishan',
      'nickname': 'Ishan Kishan',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Green b Starc',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 1413,
      'balls': 116,
      'runs': 85,
      'fours': 6,
      'sixes': 0,
      'strkrate': '73.28',
      'name': 'Virat Kohli',
      'nickname': 'Kohli',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Labuschagne b Hazlewood',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9428,
      'balls': 3,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Shreyas Iyer',
      'nickname': 'Shreyas Iyer',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Warner b Hazlewood',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8733,
      'balls': 115,
      'runs': 97,
      'fours': 8,
      'sixes': 2,
      'strkrate': '84.35',

In [95]:
aus_scorecards

[{'scorecard': [{'inningsid': 1,
    'batsman': [{'id': 1739,
      'balls': 52,
      'runs': 41,
      'fours': 6,
      'sixes': 0,
      'strkrate': '78.85',
      'name': 'Warner',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c and b Kuldeep Yadav',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 6250,
      'balls': 6,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Mitchell Marsh',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Kohli b Bumrah',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 2250,
      'balls': 71,
      'runs': 46,
      'fours': 5,
      'sixes': 0,
      'strkrate': '64.79',
      'name': 'Steven Smith',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'b Ravindra Jadeja',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 10182,
      'balls': 41,
      'runs': 27,
      'fours': 1,
      'sixes': 0,
      'strkrate': '65.85',
      'name': 'Labuschagne',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Rahul b Ravindra Jadeja',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 7662,
      'balls': 25,
      'runs': 15,
      'fours': 1,
      'sixes': 0,
      'strkrate': '60',
      'name': 'Maxwell',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'b Kuldeep Yadav',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9200,
      'balls': 2,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Alex Carey',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': True,
      'outdec': 'lbw b Ravindra Jadeja',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 12225,
      'balls': 20,
      'runs': 8,
      'fours': 0,
      'sixes': 0,
      'strkrate': '40',
      'name': 'Green',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Hardik Pandya b Ashwin',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8095,
      'balls': 24,
      'runs': 15,
      'fours': 1,
      'sixes': 1,
      'strkrate': '62.5',
      'name': 'Cummins',
      'nickname': '',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'c Shreyas Iyer b Bumrah',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 7710,
      'balls': 35,
      'runs': 28,
      'fours': 2,
      'sixes': 1,
      'strkrate': '80',
      'name': 'Starc',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Shreyas Iyer b Siraj',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8642,
      'balls': 20,
      'runs': 6,
      'fours': 0,
      'sixes': 0,
      'strkrate': '30',
      'name': 'Zampa',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Kohli b Hardik Pandya',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 6258,
      'balls': 1,
      'runs': 1,
      'fours': 0,
      'sixes': 0,
      'strkrate': '100',
      'name': 'Hazlewood',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''}],
    'bowler': [{'id': 9311,
      'overs': '10',
      'maidens': 0,
      'wickets': 2,
      'runs': 35,
      'economy': '3.5',
      'name': 'Bumrah',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 60,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 10808,
      'overs': '6.3',
      'maidens': 1,
      'wickets': 1,
      'runs': 26,
      'economy': '4',
      'name': 'Siraj',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 39,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9647,
      'overs': '3',
      'maidens': 0,
      'wickets': 1,
      'runs': 28,
      'economy': '9.3',
      'name': 'Hardik Pandya',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 18,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 1593,
      'overs': '10',
      'maidens': 1,
      'wickets': 1,
      'runs': 34,
      'economy': '3.4',
      'name': 'Ashwin',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 60,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8292,
      'overs': '10',
      'maidens': 0,
      'wickets': 2,
      'runs': 42,
      'economy': '4.2',
      'name': 'Kuldeep Yadav',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 60,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 587,
      'overs': '10',
      'maidens': 2,
      'wickets': 3,
      'runs': 28,
      'economy': '2.8',
      'name': 'Ravindra Jadeja',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 60,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''}],
    'fow': {'fow': [{'batsmanid': 6250,
       'batsmanname': 'Mitchell Marsh',
       'overnbr': 2.2,
       'runs': 5,
       'ballnbr': 14},
      {'batsmanid': 1739,
       'batsmanname': 'Warner',
       'overnbr': 16.3,
       'runs': 74,
       'ballnbr': 99},
      {'batsmanid': 2250,
       'batsmanname': 'Steven Smith',
       'overnbr': 27.1,
       'runs': 110,
       'ballnbr': 163},
      {'batsmanid': 10182,
       'batsmanname': 'Labuschagne',
       'overnbr': 29.2,
       'runs': 119,
       'ballnbr': 176},
      {'batsmanid': 9200,
       'batsmanname': 'Alex Carey',
       'overnbr': 29.4,
       'runs': 119,
       'ballnbr': 178},
      {'batsmanid': 7662,
       'batsmanname': 'Maxwell',
       'overnbr': 35.5,
       'runs': 140,
       'ballnbr': 215},
      {'batsmanid': 12225,
       'batsmanname': 'Green',
       'overnbr': 36.2,
       'runs': 140,
       'ballnbr': 218},
      {'batsmanid': 8095,
       'batsmanname': 'Cummins',
       'overnbr': 42.2,
       'runs': 165,
       'ballnbr': 254},
      {'batsmanid': 8642,
       'batsmanname': 'Zampa',
       'overnbr': 48.2,
       'runs': 189,
       'ballnbr': 290},
      {'batsmanid': 7710,
       'batsmanname': 'Starc',
       'overnbr': 49.3,
       'runs': 199,
       'ballnbr': 297}]},
    'extras': {'legbyes': 6,
     'byes': 0,
     'wides': 6,
     'noballs': 0,
     'penalty': 0,
     'total': 12},
    'pp': {'powerplay': [{'id': 4,
       'ovrfrom': 0.1,
       'ovrto': 10.0,
       'pptype': 'Mandatory',
       'run': 43,
       'wickets': 0}]},
    'score': 199,
    'wickets': 10,
    'overs': 49.3,
    'runrate': 4.02,
    'batteamname': 'Australia',
    'batteamsname': 'AUS',
    'isdeclared': False,
    'isfollowon': False,
    'ballnbr': 297,
    'rpb': 0.67,
    'partnership': {'partnership': [{'id': 0,
       'bat1id': 1739,
       'bat1name': 'Warner',
       'bat1runs': 5,
       'bat1fours': 1,
       'bat1sixes': 0,
       'bat2id': 6250,
       'bat2name': 'Mitchell Marsh',
       'bat2runs': 0,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 5,
       'totalballs': 14,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 1739,
       'bat1name': 'Warner',
       'bat1runs': 35,
       'bat1fours': 5,
       'bat1sixes': 0,
       'bat2id': 2250,
       'bat2name': 'Smith',
       'bat2runs': 33,
       'bat2fours': 5,
       'bat2sixes': 0,
       'totalruns': 69,
       'totalballs': 85,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 10182,
       'bat1name': 'Labuschagne',
       'bat1runs': 22,
       'bat1fours': 1,
       'bat1sixes': 0,
       'bat2id': 2250,
       'bat2name': 'Smith',
       'bat2runs': 13,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 36,
       'totalballs': 64,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 10182,
       'bat1name': 'Labuschagne',
       'bat1runs': 5,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 7662,
       'bat2name': 'Maxwell',
       'bat2runs': 4,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 9,
       'totalballs': 13,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 9200,
       'bat1name': 'Carey',
       'bat1runs': 0,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 7662,
       'bat2name': 'Maxwell',
       'bat2runs': 0,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 0,
       'totalballs': 2,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 12225,
       'bat1name': 'Green',
       'bat1runs': 8,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 7662,
       'bat2name': 'Maxwell',
       'bat2runs': 11,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 21,
       'totalballs': 37,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 12225,
       'bat1name': 'Green',
       'bat1runs': 0,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 8095,
       'bat2name': 'Cummins',
       'bat2runs': 0,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 0,
       'totalballs': 3,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 7710,
       'bat1name': 'Starc',
       'bat1runs': 6,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 8095,
       'bat2name': 'Cummins',
       'bat2runs': 15,
       'bat2fours': 1,
       'bat2sixes': 1,
       'totalruns': 25,
       'totalballs': 36,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 7710,
       'bat1name': 'Starc',
       'bat1runs': 14,
       'bat1fours': 0,
       'bat1sixes': 1,
       'bat2id': 8642,
       'bat2name': 'Zampa',
       'bat2runs': 6,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 24,
       'totalballs': 36,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 7710,
       'bat1name': 'Starc',
       'bat1runs': 9,
       'bat1fours': 2,
       'bat1sixes': 0,
       'bat2id': 6258,
       'bat2name': 'Hazlewood',
       'bat2runs': 1,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 10,
       'totalballs': 7,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0}]}},
   {'inningsid': 2,
    'batsman': [{'id': 576,
      'balls': 6,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Rohit Sharma',
      'nickname': 'Rohit',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'lbw b Hazlewood',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 10276,
      'balls': 1,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Ishan Kishan',
      'nickname': 'Ishan Kishan',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Green b Starc',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 1413,
      'balls': 116,
      'runs': 85,
      'fours': 6,
      'sixes': 0,
      'strkrate': '73.28',
      'name': 'Virat Kohli',
      'nickname': 'Kohli',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Labuschagne b Hazlewood',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9428,
      'balls': 3,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Shreyas Iyer',
      'nickname': 'Shreyas Iyer',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Warner b Hazlewood',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8733,
      'balls': 115,
      'runs': 97,
      'fours': 8,
      'sixes': 2,
      'strkrate': '84.35',

In [96]:
australian_bowlers = []

for match in aus_scorecards:
    first_innings = match["scorecard"][0]
    teamA = first_innings["batteamsname"]
    second_innings = match["scorecard"][1]
    teamB = second_innings["batteamsname"]

    if "AUS" not in [teamA, teamB]:
        continue

    for innings in match["scorecard"]:

        if innings["batteamsname"] == "AUS":
            continue

        for bowler in innings["bowler"]:
            aus_bowls = {
                "name": bowler["name"],
                "player_id": bowler["id"],
                "runs": bowler["runs"],
                "balls": bowler["balls"],
                "wickets": bowler["wickets"],
                "game_format": "ODI"
            }
            australian_bowlers.append(aus_bowls)

In [97]:
australian_bowlers

[{'name': 'Mitchell Starc',
  'player_id': 7710,
  'runs': 31,
  'balls': 48,
  'wickets': 1,
  'game_format': 'ODI'},
 {'name': 'Josh Hazlewood',
  'player_id': 6258,
  'runs': 38,
  'balls': 54,
  'wickets': 3,
  'game_format': 'ODI'},
 {'name': 'Pat Cummins',
  'player_id': 8095,
  'runs': 33,
  'balls': 38,
  'wickets': 0,
  'game_format': 'ODI'},
 {'name': 'Glenn Maxwell',
  'player_id': 7662,
  'runs': 33,
  'balls': 48,
  'wickets': 0,
  'game_format': 'ODI'},
 {'name': 'Cameron Green',
  'player_id': 12225,
  'runs': 11,
  'balls': 12,
  'wickets': 0,
  'game_format': 'ODI'},
 {'name': 'Adam Zampa',
  'player_id': 8642,
  'runs': 53,
  'balls': 48,
  'wickets': 0,
  'game_format': 'ODI'},
 {'name': 'Starc',
  'player_id': 7710,
  'runs': 53,
  'balls': 54,
  'wickets': 2,
  'game_format': 'ODI'},
 {'name': 'Hazlewood',
  'player_id': 6258,
  'runs': 60,
  'balls': 54,
  'wickets': 1,
  'game_format': 'ODI'},
 {'name': 'Maxwell',
  'player_id': 7662,
  'runs': 34,
  'balls': 60,
  'wickets': 2,
  'game_format': 'ODI'},
 {'name': 'Cummins',
  'player_id': 8095,
  'runs': 71,
  'balls': 54,
  'wickets': 1,
  'game_format': 'ODI'},
 {'name': 'Zampa',
  'player_id': 8642,
  'runs': 70,
  'balls': 60,
  'wickets': 1,
  'game_format': 'ODI'},
 {'name': 'Mitchell Marsh',
  'player_id': 6250,
  'runs': 6,
  'balls': 6,
  'wickets': 0,
  'game_format': 'ODI'},
 {'name': 'Stoinis',
  'player_id': 8989,
  'runs': 11,
  'balls': 12,
  'wickets': 0,
  'game_format': 'ODI'},
 {'name': 'Starc',
  'player_id': 7710,
  'runs': 70,
  'balls': 54,
  'wickets': 1,
  'game_format': 'ODI'},
 {'name': 'Hazlewood',
  'player_id': 6258,
  'runs': 39,
  'balls': 54,
  'wickets': 2,
  'game_format': 'ODI'},
 {'name': 'Maxwell',
  'player_id': 7662,
  'runs': 55,
  'balls': 60,
  'wickets': 1,
  'game_format': 'ODI'},
 {'name': 'Cummins',
  'player_id': 8095,
  'runs': 47,
  'balls': 48,
  'wickets': 0,
  'game_format': 'ODI'},
 {'name': 'Zampa',
  'player_id': 8642,
  'runs': 58,
  'balls': 60,
  'wickets': 1,
  'game_format': 'ODI'},
 {'name': 'Head',
  'player_id': 8497,
  'runs': 15,
  'balls': 18,
  'wickets': 0,
  'game_format': 'ODI'},
 {'name': 'Stoinis',
  'player_id': 8989,
  'runs': 2,
  'balls': 6,
  'wickets': 0,
  'game_format': 'ODI'},
 {'name': 'Starc',
  'player_id': 7710,
  'runs': 55,
  'balls': 60,
  'wickets': 3,
  'game_format': 'ODI'},
 {'name': 'Hazlewood',
  'player_id': 6258,
  'runs': 60,
  'balls': 60,
  'wickets': 2,
  'game_format': 'ODI'},
 {'name': 'Maxwell',
  'player_id': 7662,
  'runs': 35,
  'balls': 36,
  'wickets': 1,
  'game_format': 'ODI'},
 {'name': 'Cummins',
  'player_id': 8095,
  'runs': 34,
  'balls': 60,
  'wickets': 2,
  'game_format': 'ODI'},
 {'name': 'Zampa',
  'player_id': 8642,
  'runs': 44,
  'balls': 60,
  'wickets': 1,
  'game_format': 'ODI'},
 {'name': 'Mitchell Marsh',
  'player_id': 6250,
  'runs': 5,
  'balls': 12,
  'wickets': 0,
  'game_format': 'ODI'},
 {'name': 'Head',
  'player_id': 8497,
  'runs': 4,
  'balls': 12,
  'wickets': 0,
  'game_format': 'ODI'}]

In [98]:
aus_bowl_data=pd.DataFrame(australian_bowlers)
aus_bowl_data

              name  player_id  runs  balls  wickets game_format
0   Mitchell Starc       7710    31     48        1         ODI
1   Josh Hazlewood       6258    38     54        3         ODI
2      Pat Cummins       8095    33     38        0         ODI
3    Glenn Maxwell       7662    33     48        0         ODI
4    Cameron Green      12225    11     12        0         ODI
5       Adam Zampa       8642    53     48        0         ODI
6            Starc       7710    53     54        2         ODI
7        Hazlewood       6258    60     54        1         ODI
8          Maxwell       7662    34     60        2         ODI
9          Cummins       8095    71     54        1         ODI
10           Zampa       8642    70     60        1         ODI
11  Mitchell Marsh       6250     6      6        0         ODI
12         Stoinis       8989    11     12        0         ODI
13           Starc       7710    70     54        1         ODI
14       Hazlewood       6258    39     54        2         ODI
15         Maxwell       7662    55     60        1         ODI
16         Cummins       8095    47     48        0         ODI
17           Zampa       8642    58     60        1         ODI
18            Head       8497    15     18        0         ODI
19         Stoinis       8989     2      6        0         ODI
20           Starc       7710    55     60        3         ODI
21       Hazlewood       6258    60     60        2         ODI
22         Maxwell       7662    35     36        1         ODI
23         Cummins       8095    34     60        2         ODI
24           Zampa       8642    44     60        1         ODI
25  Mitchell Marsh       6250     5     12        0         ODI
26            Head       8497     4     12        0         ODI

In [99]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

table_name = "aus_bowl_stats" 

engine = create_engine(
f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


aus_bowl_data.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz aus_bowl_stats

In [100]:
indian_match_ids=[87652, 87663, 87668, 87676, 87834, 87844, 87850, 87871, 87878]

import requests
ind_scorecards=[]
for match_id2 in indian_match_ids:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/mcenter/v1/{match_id2}/scard"

    headers = {
	   "x-rapidapi-key": "fc7f30fb9cmsh8725b330cc40e86p18a9aejsnb2a96a85740a",
	    "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    try:
        response = requests.get(url, headers=headers)
        ind_scorecards.append(response.json())
    except:
        continue
ind_scorecards

[{'scorecard': [{'inningsid': 1,
    'batsman': [{'id': 18155,
      'balls': 1,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Shayan Jahangir',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'lbw b Arshdeep Singh',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': 'IN'},
     {'id': 8670,
      'balls': 30,
      'runs': 24,
      'fours': 0,
      'sixes': 2,
      'strkrate': '80',
      'name': 'Steven Taylor',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'b Axar',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 11959,
      'balls': 5,
      'runs': 2,
      'fours': 0,
      'sixes': 0,
      'strkrate': '40',
      'name': 'Andries Gous',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': True,
      'outdec': 'c Hardik Pandya b Arshdeep Singh',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 14730,
      'balls': 22,
      'runs': 11,
      'fours': 0,
      'sixes': 1,
      'strkrate': '50',
      'name': 'Aaron Jones',
      'nickname': '',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'c Siraj b Hardik Pandya',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 6474,
      'balls': 23,
      'runs': 27,
      'fours': 2,
      'sixes': 1,
      'strkrate': '117.39',
      'name': 'NR Kumar',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Siraj b Arshdeep Singh',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8982,
      'balls': 12,
      'runs': 15,
      'fours': 1,
      'sixes': 1,
      'strkrate': '125',
      'name': 'CJ Anderson',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Pant b Hardik Pandya',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8426,
      'balls': 10,
      'runs': 10,
      'fours': 0,
      'sixes': 1,
      'strkrate': '100',
      'name': 'Harmeet Singh',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Pant b Arshdeep Singh',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 2245,
      'balls': 10,
      'runs': 11,
      'fours': 1,
      'sixes': 0,
      'strkrate': '110',
      'name': 'van Schalkwyk',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': 'IN'},
     {'id': 14734,
      'balls': 7,
      'runs': 2,
      'fours': 0,
      'sixes': 0,
      'strkrate': '28.57',
      'name': 'Jasdeep Singh',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'run out (Pant/Siraj)',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9748,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Netravalkar',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 11450,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Ali Khan',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''}],
    'bowler': [{'id': 13217,
      'overs': '4',
      'maidens': 0,
      'wickets': 4,
      'runs': 9,
      'economy': '2.2',
      'name': 'Arshdeep Singh',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 10808,
      'overs': '4',
      'maidens': 0,
      'wickets': 0,
      'runs': 25,
      'economy': '6.2',
      'name': 'Siraj',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9311,
      'overs': '4',
      'maidens': 0,
      'wickets': 0,
      'runs': 25,
      'economy': '6.2',
      'name': 'Bumrah',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9647,
      'overs': '4',
      'maidens': 1,
      'wickets': 2,
      'runs': 14,
      'economy': '3.5',
      'name': 'Hardik Pandya',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 24,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 11195,
      'overs': '1',
      'maidens': 0,
      'wickets': 0,
      'runs': 11,
      'economy': '11',
      'name': 'Shivam Dube',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 6,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8808,
      'overs': '3',
      'maidens': 0,
      'wickets': 1,
      'runs': 25,
      'economy': '8.3',
      'name': 'Axar',
      'nickname': '',
      'iscaptain': False,
      'iskeeper': False,
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'dots': 0,
      'balls': 18,
      'rpb': 0.0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''}],
    'fow': {'fow': [{'batsmanid': 18155,
       'batsmanname': 'Shayan Jahangir',
       'overnbr': 0.1,
       'runs': 0,
       'ballnbr': 1},
      {'batsmanid': 11959,
       'batsmanname': 'Andries Gous',
       'overnbr': 0.6,
       'runs': 3,
       'ballnbr': 6},
      {'batsmanid': 14730,
       'batsmanname': 'Aaron Jones',
       'overnbr': 7.2,
       'runs': 25,
       'ballnbr': 44},
      {'batsmanid': 8670,
       'batsmanname': 'Steven Taylor',
       'overnbr': 11.4,
       'runs': 56,
       'ballnbr': 70},
      {'batsmanid': 6474,
       'batsmanname': 'NR Kumar',
       'overnbr': 14.4,
       'runs': 81,
       'ballnbr': 88},
      {'batsmanid': 8982,
       'batsmanname': 'CJ Anderson',
       'overnbr': 16.5,
       'runs': 96,
       'ballnbr': 101},
      {'batsmanid': 8426,
       'batsmanname': 'Harmeet Singh',
       'overnbr': 17.3,
       'runs': 98,
       'ballnbr': 105},
      {'batsmanid': 14734,
       'batsmanname': 'Jasdeep Singh',
       'overnbr': 20.0,
       'runs': 110,
       'ballnbr': 120}]},
    'extras': {'legbyes': 1,
     'byes': 0,
     'wides': 7,
     'noballs': 0,
     'penalty': 0,
     'total': 8},
    'pp': {'powerplay': [{'id': 1,
       'ovrfrom': 0.1,
       'ovrto': 6.0,
       'pptype': 'Mandatory',
       'run': 18,
       'wickets': 0}]},
    'score': 110,
    'wickets': 8,
    'overs': 20.0,
    'runrate': 5.5,
    'batteamname': 'United States',
    'batteamsname': 'USA',
    'isdeclared': False,
    'isfollowon': False,
    'ballnbr': 120,
    'rpb': 0.92,
    'partnership': {'partnership': [{'id': 0,
       'bat1id': 18155,
       'bat1name': 'S Jahangir',
       'bat1runs': 0,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 8670,
       'bat2name': 'Steven Taylor',
       'bat2runs': 0,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 0,
       'totalballs': 1,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 11959,
       'bat1name': 'Gous',
       'bat1runs': 2,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 8670,
       'bat2name': 'Steven Taylor',
       'bat2runs': 0,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 3,
       'totalballs': 5,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 14730,
       'bat1name': 'Aaron Jones',
       'bat1runs': 11,
       'bat1fours': 0,
       'bat1sixes': 1,
       'bat2id': 8670,
       'bat2name': 'Steven Taylor',
       'bat2runs': 6,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 22,
       'totalballs': 38,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 6474,
       'bat1name': 'Nitish Kumar',
       'bat1runs': 13,
       'bat1fours': 1,
       'bat1sixes': 0,
       'bat2id': 8670,
       'bat2name': 'Steven Taylor',
       'bat2runs': 18,
       'bat2fours': 0,
       'bat2sixes': 2,
       'totalruns': 31,
       'totalballs': 26,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 6474,
       'bat1name': 'Nitish Kumar',
       'bat1runs': 14,
       'bat1fours': 1,
       'bat1sixes': 1,
       'bat2id': 8982,
       'bat2name': 'Corey Anderson',
       'bat2runs': 9,
       'bat2fours': 0,
       'bat2sixes': 1,
       'totalruns': 25,
       'totalballs': 18,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 8426,
       'bat1name': 'Harmeet Singh',
       'bat1runs': 9,
       'bat1fours': 0,
       'bat1sixes': 1,
       'bat2id': 8982,
       'bat2name': 'Corey Anderson',
       'bat2runs': 5,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 15,
       'totalballs': 13,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 8426,
       'bat1name': 'Harmeet Singh',
       'bat1runs': 1,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 2245,
       'bat2name': 'van Schalkwyk',
       'bat2runs': 1,
       'bat2fours': 0,
       'bat2sixes': 0,
       'totalruns': 2,
       'totalballs': 4,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0},
      {'id': 0,
       'bat1id': 14734,
       'bat1name': 'Jessy Singh',
       'bat1runs': 2,
       'bat1fours': 0,
       'bat1sixes': 0,
       'bat2id': 2245,
       'bat2name': 'van Schalkwyk',
       'bat2runs': 10,
       'bat2fours': 1,
       'bat2sixes': 0,
       'totalruns': 12,
       'totalballs': 15,
       'bat1balls': 0,
       'bat2balls': 0,
       'teamname': '',
       'teamid': 0,
       'bat1ones': 0,
       'bat1twos': 0,
       'bat1threes': 0,
       'bat1fives': 0,
       'bat1boundaries': 0,
       'bat1sixers': 0,
       'bat2ones': 0,
       'bat2twos': 0,
       'bat2threes': 0,
       'bat2fives': 0,
       'bat2boundaries': 0,
       'bat2sixers': 0}]}},
   {'inningsid': 2,
    'batsman': [{'id': 576,
      'balls': 6,
      'runs': 3,
      'fours': 0,
      'sixes': 0,
      'strkrate': '50',
      'name': 'Rohit Sharma',
      'nickname': 'Rohit',
      'iscaptain': True,
      'iskeeper': False,
      'outdec': 'c Harmeet Singh b Netravalkar',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 1413,
      'balls': 1,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Virat Kohli',
      'nickname': 'Kohli',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'c Andries Gous b Netravalkar',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 10744,
      'balls': 20,
      'runs': 18,
      'fours': 1,
      'sixes': 1,
      'strkrate': '90',
      'name': 'Rishabh Pant',
      'nickname': 'Pant',
      'iscaptain': False,
      'iskeeper': True,
      'outdec': 'b Ali Khan',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 7915,
      'balls': 49,
      'runs': 50,
      'fours': 2,
      'sixes': 2,
      'strkrate': '102.04',
      'name': 'Suryakumar Yadav',
      'nickname': 'Suryakumar Yadav',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 11195,
      'balls': 35,
      'runs': 31,
      'fours': 1,
      'sixes': 1,
      'strkrate': '88.57',
      'name': 'Shivam Dube',
      'nickname': 'Shivam Dube',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': 'not out',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 9647,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Hardik Pandya',
      'nickname': 'Hardik Pandya',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 587,
      'balls': 0,
      'runs': 0,
      'fours': 0,
      'sixes': 0,
      'strkrate': '0',
      'name': 'Ravindra Jadeja',
      'nickname': 'Ravindra Jadeja',
      'iscaptain': False,
      'iskeeper': False,
      'outdec': '',
      'videotype': '',
      'videourl': '',
      'videoid': 0,
      'planid': 0,
      'imageid': 0,
      'premiumvideourl': '',
      'iscbplusfree': False,
      'ispremiumfree': False,
      'inmatchchange': '',
      'isoverseas': False,
      'playingxichange': ''},
     {'id': 8808,
      'balls': 0,
      'runs': 0,
      'fours': 0,

In [101]:
indian_bowlers = []

for match in ind_scorecards:
    first_innings = match["scorecard"][0]
    teamA = first_innings["batteamsname"]
    second_innings = match["scorecard"][1]
    teamB = second_innings["batteamsname"]

    if "IND" not in [teamA, teamB]:
        continue

    for innings in match["scorecard"]:

        if innings["batteamsname"] == "IND":
            continue

        for bowler in innings["bowler"]:
            ind_bowls = {
                "name": bowler["name"],
                "player_id": bowler["id"],
                "runs": bowler["runs"],
                "balls": bowler["balls"],
                "wickets": bowler["wickets"],
                "game_format": "t20"
            }
            indian_bowlers.append(ind_bowls)

In [102]:
indian_bowlers

[{'name': 'Arshdeep Singh',
  'player_id': 13217,
  'runs': 9,
  'balls': 24,
  'wickets': 4,
  'game_format': 't20'},
 {'name': 'Siraj',
  'player_id': 10808,
  'runs': 25,
  'balls': 24,
  'wickets': 0,
  'game_format': 't20'},
 {'name': 'Bumrah',
  'player_id': 9311,
  'runs': 25,
  'balls': 24,
  'wickets': 0,
  'game_format': 't20'},
 {'name': 'Hardik Pandya',
  'player_id': 9647,
  'runs': 14,
  'balls': 24,
  'wickets': 2,
  'game_format': 't20'},
 {'name': 'Shivam Dube',
  'player_id': 11195,
  'runs': 11,
  'balls': 6,
  'wickets': 0,
  'game_format': 't20'},
 {'name': 'Axar',
  'player_id': 8808,
  'runs': 25,
  'balls': 18,
  'wickets': 1,
  'game_format': 't20'},
 {'name': 'Arshdeep Singh',
  'player_id': 13217,
  'runs': 37,
  'balls': 24,
  'wickets': 3,
  'game_format': 't20'},
 {'name': 'Jasprit Bumrah',
  'player_id': 9311,
  'runs': 29,
  'balls': 24,
  'wickets': 1,
  'game_format': 't20'},
 {'name': 'Axar Patel',
  'player_id': 8808,
  'runs': 21,
  'balls': 18,
  'wickets': 1,
  'game_format': 't20'},
 {'name': 'Hardik Pandya',
  'player_id': 9647,
  'runs': 47,
  'balls': 24,
  'wickets': 0,
  'game_format': 't20'},
 {'name': 'Kuldeep Yadav',
  'player_id': 8292,
  'runs': 24,
  'balls': 24,
  'wickets': 2,
  'game_format': 't20'},
 {'name': 'Ravindra Jadeja',
  'player_id': 587,
  'runs': 17,
  'balls': 6,
  'wickets': 0,
  'game_format': 't20'},
 {'name': 'Arshdeep Singh',
  'player_id': 13217,
  'runs': 17,
  'balls': 12,
  'wickets': 0,
  'game_format': 't20'},
 {'name': 'Jasprit Bumrah',
  'player_id': 9311,
  'runs': 12,
  'balls': 16,
  'wickets': 2,
  'game_format': 't20'},
 {'name': 'Axar Patel',
  'player_id': 8808,
  'runs': 23,
  'balls': 24,
  'wickets': 3,
  'game_format': 't20'},
 {'name': 'Kuldeep Yadav',
  'player_id': 8292,
  'runs': 19,
  'balls': 24,
  'wickets': 3,
  'game_format': 't20'},
 {'name': 'Ravindra Jadeja',
  'player_id': 587,
  'runs': 16,
  'balls': 18,
  'wickets': 0,
  'game_format': 't20'},
 {'name': 'Hardik Pandya',
  'player_id': 9647,
  'runs': 14,
  'balls': 6,
  'wickets': 0,
  'game_format': 't20'},
 {'name': 'Arshdeep Singh',
  'player_id': 13217,
  'runs': 20,
  'balls': 24,
  'wickets': 2,
  'game_format': 't20'},
 {'name': 'Jasprit Bumrah',
  'player_id': 9311,
  'runs': 18,
  'balls': 24,
  'wickets': 2,
  'game_format': 't20'},
 {'name': 'Axar Patel',
  'player_id': 8808,
  'runs': 49,
  'balls': 24,
  'wickets': 1,
  'game_format': 't20'},
 {'name': 'Kuldeep Yadav',
  'player_id': 8292,
  'runs': 45,
  'balls': 24,
  'wickets': 0,
  'game_format': 't20'},
 {'name': 'Hardik Pandya',
  'player_id': 9647,
  'runs': 20,
  'balls': 18,
  'wickets': 3,
  'game_format': 't20'},
 {'name': 'Ravindra Jadeja',
  'player_id': 587,
  'runs': 12,
  'balls': 6,
  'wickets': 0,
  'game_format': 't20'}]

In [103]:
ind_bowl_data=pd.DataFrame(indian_bowlers)
ind_bowl_data

               name  player_id  runs  balls  wickets game_format
0    Arshdeep Singh      13217     9     24        4         t20
1             Siraj      10808    25     24        0         t20
2            Bumrah       9311    25     24        0         t20
3     Hardik Pandya       9647    14     24        2         t20
4       Shivam Dube      11195    11      6        0         t20
5              Axar       8808    25     18        1         t20
6    Arshdeep Singh      13217    37     24        3         t20
7    Jasprit Bumrah       9311    29     24        1         t20
8        Axar Patel       8808    21     18        1         t20
9     Hardik Pandya       9647    47     24        0         t20
10    Kuldeep Yadav       8292    24     24        2         t20
11  Ravindra Jadeja        587    17      6        0         t20
12   Arshdeep Singh      13217    17     12        0         t20
13   Jasprit Bumrah       9311    12     16        2         t20
14       Axar Patel       8808    23     24        3         t20
15    Kuldeep Yadav       8292    19     24        3         t20
16  Ravindra Jadeja        587    16     18        0         t20
17    Hardik Pandya       9647    14      6        0         t20
18   Arshdeep Singh      13217    20     24        2         t20
19   Jasprit Bumrah       9311    18     24        2         t20
20       Axar Patel       8808    49     24        1         t20
21    Kuldeep Yadav       8292    45     24        0         t20
22    Hardik Pandya       9647    20     18        3         t20
23  Ravindra Jadeja        587    12      6        0         t20

In [104]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

table_name = "ind_bowl_stats" 

engine = create_engine(
f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


ind_bowl_data.to_sql(table_name, con=engine, if_exists='replace', index=False)

print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz ind_bowl_stats

Q.19
Determine which batsmen are most consistent in their scoring. Calculate the average runs scored and the standard deviation of runs for each player. Only include players who have faced at least 10 balls per innings and played since 2022. A lower standard deviation indicates more consistent performance.

In [105]:
#data taken fro previous qn
aus_scorecards[2]

{'scorecard': [{'inningsid': 1,
   'batsman': [{'id': 13682,
     'balls': 60,
     'runs': 46,
     'fours': 5,
     'sixes': 0,
     'strkrate': '76.67',
     'name': 'Pathum Nissanka',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Gurbaz b Azmatullah',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 7952,
     'balls': 21,
     'runs': 15,
     'fours': 1,
     'sixes': 0,
     'strkrate': '71.43',
     'name': 'Karunaratne',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'lbw b Fazalhaq Farooqi',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': 'IN'},
    {'id': 9494,
     'balls': 50,
     'runs': 39,
     'fours': 3,
     'sixes': 0,
     'strkrate': '78',
     'name': 'Kusal Mendis',
     'nickname': '',
     'iscaptain': True,
     'iskeeper': True,
     'outdec': 'c (sub)Najibullah b Mujeeb',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 9495,
     'balls': 40,
     'runs': 36,
     'fours': 3,
     'sixes': 0,
     'strkrate': '90',
     'name': 'Samarawickrama',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'lbw b Mujeeb',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10934,
     'balls': 28,
     'runs': 22,
     'fours': 2,
     'sixes': 0,
     'strkrate': '78.57',
     'name': 'Asalanka',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Rashid Khan b Fazalhaq Farooqi',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 7872,
     'balls': 26,
     'runs': 14,
     'fours': 1,
     'sixes': 0,
     'strkrate': '53.85',
     'name': 'Dhananjaya de Silva',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'b Rashid Khan',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 1629,
     'balls': 26,
     'runs': 23,
     'fours': 1,
     'sixes': 1,
     'strkrate': '88.46',
     'name': 'Mathews',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Nabi b Fazalhaq Farooqi',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8393,
     'balls': 4,
     'runs': 1,
     'fours': 0,
     'sixes': 0,
     'strkrate': '25',
     'name': 'Chameera',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'run out (Ibrahim Zadran)',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': 'IN'},
    {'id': 18504,
     'balls': 31,
     'runs': 29,
     'fours': 3,
     'sixes': 1,
     'strkrate': '93.55',
     'name': 'M Theekshana',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'b Fazalhaq Farooqi',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10472,
     'balls': 7,
     'runs': 5,
     'fours': 0,
     'sixes': 0,
     'strkrate': '71.43',
     'name': 'Rajitha',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'run out (Gurbaz)',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 15067,
     'balls': 4,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Dilshan Madushanka',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'bowler': [{'id': 12071,
     'overs': '10',
     'maidens': 0,
     'wickets': 2,
     'runs': 38,
     'economy': '3.8',
     'name': 'Mujeeb',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 60,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 14282,
     'overs': '10',
     'maidens': 1,
     'wickets': 4,
     'runs': 34,
     'economy': '3.4',
     'name': 'Fazalhaq Farooqi',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 60,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': 'IN'},
    {'id': 11289,
     'overs': '6.3',
     'maidens': 0,
     'wickets': 0,
     'runs': 47,
     'economy': '7.2',
     'name': 'Naveen-ul-Haq',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 39,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 13214,
     'overs': '7',
     'maidens': 0,
     'wickets': 1,
     'runs': 37,
     'economy': '5.3',
     'name': 'Azmatullah',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 42,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 10738,
     'overs': '10',
     'maidens': 0,
     'wickets': 1,
     'runs': 50,
     'economy': '5',
     'name': 'Rashid Khan',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 60,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 3007,
     'overs': '6',
     'maidens': 0,
     'wickets': 0,
     'runs': 33,
     'economy': '5.5',
     'name': 'Nabi',
     'nickname': '',
     'iscaptain': False,
     'iskeeper': False,
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'dots': 0,
     'balls': 36,
     'rpb': 0.0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''}],
   'fow': {'fow': [{'batsmanid': 7952,
      'batsmanname': 'Karunaratne',
      'overnbr': 5.2,
      'runs': 22,
      'ballnbr': 32},
     {'batsmanid': 13682,
      'batsmanname': 'Pathum Nissanka',
      'overnbr': 18.1,
      'runs': 84,
      'ballnbr': 109},
     {'batsmanid': 9494,
      'batsmanname': 'Kusal Mendis',
      'overnbr': 27.4,
      'runs': 134,
      'ballnbr': 166},
     {'batsmanid': 9495,
      'batsmanname': 'Samarawickrama',
      'overnbr': 29.1,
      'runs': 139,
      'ballnbr': 175},
     {'batsmanid': 7872,
      'batsmanname': 'Dhananjaya de Silva',
      'overnbr': 35.6,
      'runs': 167,
      'ballnbr': 216},
     {'batsmanid': 10934,
      'batsmanname': 'Asalanka',
      'overnbr': 38.5,
      'runs': 180,
      'ballnbr': 233},
     {'batsmanid': 8393,
      'batsmanname': 'Chameera',
      'overnbr': 40.0,
      'runs': 185,
      'ballnbr': 240},
     {'batsmanid': 18504,
      'batsmanname': 'M Theekshana',
      'overnbr': 46.6,
      'runs': 230,
      'ballnbr': 282},
     {'batsmanid': 1629,
      'batsmanname': 'Mathews',
      'overnbr': 48.3,
      'runs': 239,
      'ballnbr': 291},
     {'batsmanid': 10472,
      'batsmanname': 'Rajitha',
      'overnbr': 49.3,
      'runs': 241,
      'ballnbr': 297}]},
   'extras': {'legbyes': 2,
    'byes': 0,
    'wides': 9,
    'noballs': 0,
    'penalty': 0,
    'total': 11},
   'pp': {'powerplay': [{'id': 3,
      'ovrfrom': 0.1,
      'ovrto': 10.0,
      'pptype': 'Mandatory',
      'run': 41,
      'wickets': 0}]},
   'score': 241,
   'wickets': 10,
   'overs': 49.3,
   'runrate': 4.87,
   'batteamname': 'Sri Lanka',
   'batteamsname': 'SL',
   'isdeclared': False,
   'isfollowon': False,
   'ballnbr': 298,
   'rpb': 0.81,
   'partnership': {'partnership': [{'id': 0,
      'bat1id': 13682,
      'bat1name': 'Nissanka',
      'bat1runs': 7,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 7952,
      'bat2name': 'Karunaratne',
      'bat2runs': 15,
      'bat2fours': 1,
      'bat2sixes': 0,
      'totalruns': 22,
      'totalballs': 32,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 13682,
      'bat1name': 'Nissanka',
      'bat1runs': 39,
      'bat1fours': 5,
      'bat1sixes': 0,
      'bat2id': 9494,
      'bat2name': 'Kusal Mendis',
      'bat2runs': 21,
      'bat2fours': 2,
      'bat2sixes': 0,
      'totalruns': 62,
      'totalballs': 77,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 9495,
      'bat1name': 'Samarawickrama',
      'bat1runs': 32,
      'bat1fours': 3,
      'bat1sixes': 0,
      'bat2id': 9494,
      'bat2name': 'Kusal Mendis',
      'bat2runs': 18,
      'bat2fours': 1,
      'bat2sixes': 0,
      'totalruns': 50,
      'totalballs': 57,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 9495,
      'bat1name': 'Samarawickrama',
      'bat1runs': 4,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 10934,
      'bat2name': 'Asalanka',
      'bat2runs': 1,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 5,
      'totalballs': 9,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 7872,
      'bat1name': 'Dhananjaya',
      'bat1runs': 14,
      'bat1fours': 1,
      'bat1sixes': 0,
      'bat2id': 10934,
      'bat2name': 'Asalanka',
      'bat2runs': 14,
      'bat2fours': 1,
      'bat2sixes': 0,
      'totalruns': 28,
      'totalballs': 41,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 1629,
      'bat1name': 'Mathews',
      'bat1runs': 1,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 10934,
      'bat2name': 'Asalanka',
      'bat2runs': 7,
      'bat2fours': 1,
      'bat2sixes': 0,
      'totalruns': 13,
      'totalballs': 17,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 1629,
      'bat1name': 'Mathews',
      'bat1runs': 3,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 8393,
      'bat2name': 'Chameera',
      'bat2runs': 1,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 5,
      'totalballs': 7,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 1629,
      'bat1name': 'Mathews',
      'bat1runs': 15,
      'bat1fours': 0,
      'bat1sixes': 1,
      'bat2id': 18504,
      'bat2name': 'Theekshana',
      'bat2runs': 29,
      'bat2fours': 3,
      'bat2sixes': 1,
      'totalruns': 45,
      'totalballs': 42,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 1629,
      'bat1name': 'Mathews',
      'bat1runs': 5,
      'bat1fours': 1,
      'bat1sixes': 0,
      'bat2id': 10472,
      'bat2name': 'Rajitha',
      'bat2runs': 4,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 9,
      'totalballs': 9,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0},
     {'id': 0,
      'bat1id': 15067,
      'bat1name': 'Madushanka',
      'bat1runs': 0,
      'bat1fours': 0,
      'bat1sixes': 0,
      'bat2id': 10472,
      'bat2name': 'Rajitha',
      'bat2runs': 1,
      'bat2fours': 0,
      'bat2sixes': 0,
      'totalruns': 2,
      'totalballs': 7,
      'bat1balls': 0,
      'bat2balls': 0,
      'teamname': '',
      'teamid': 0,
      'bat1ones': 0,
      'bat1twos': 0,
      'bat1threes': 0,
      'bat1fives': 0,
      'bat1boundaries': 0,
      'bat1sixers': 0,
      'bat2ones': 0,
      'bat2twos': 0,
      'bat2threes': 0,
      'bat2fives': 0,
      'bat2boundaries': 0,
      'bat2sixers': 0}]}},
  {'inningsid': 2,
   'batsman': [{'id': 13213,
     'balls': 4,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Rahmanullah Gurbaz',
     'nickname': 'Gurbaz',
     'iscaptain': False,
     'iskeeper': True,
     'outdec': 'b Dilshan Madushanka',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 12173,
     'balls': 57,
     'runs': 39,
     'fours': 4,
     'sixes': 1,
     'strkrate': '68.42',
     'name': 'Ibrahim Zadran',
     'nickname': 'Ibrahim Zadran',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Karunaratne b Dilshan Madushanka',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8571,
     'balls': 74,
     'runs': 62,
     'fours': 7,
     'sixes': 0,
     'strkrate': '83.78',
     'name': 'Rahmat Shah',
     'nickname': 'Rahmat',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'c Karunaratne b Rajitha',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 8277,
     'balls': 74,
     'runs': 58,
     'fours': 2,
     'sixes': 1,
     'strkrate': '78.38',
     'name': 'Hashmatullah Shahidi',
     'nickname': 'Shahidi',
     'iscaptain': True,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 13214,
     'balls': 63,
     'runs': 73,
     'fours': 6,
     'sixes': 3,
     'strkrate': '115.87',
     'name': 'Azmatullah Omarzai',
     'nickname': 'Azmatullah',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': 'not out',
     'videotype': '',
     'videourl': '',
     'videoid': 0,
     'planid': 0,
     'imageid': 0,
     'premiumvideourl': '',
     'iscbplusfree': False,
     'ispremiumfree': False,
     'inmatchchange': '',
     'isoverseas': False,
     'playingxichange': ''},
    {'id': 11071,
     'balls': 0,
     'runs': 0,
     'fours': 0,
     'sixes': 0,
     'strkrate': '0',
     'name': 'Ikram Alikhil',
     'nickname': 'Ikram Alikhil',
     'iscaptain': False,
     'iskeeper': False,
     'outdec': '',
     'videotype': '',

In [106]:
australian_batsmen = []

for match in aus_scorecards:      
    for innings in match["scorecard"]:
        if innings["batteamsname"] != "AUS":
            continue
        for bat in innings["batsman"]:
            aus_bat = {
                "player_id": bat["id"],
                "name": bat["name"],
                "runs": bat["runs"],
                "balls" : bat["balls"]   
            }
            australian_batsmen.append(aus_bat)

In [107]:
australian_batsmen

[{'player_id': 1739, 'name': 'Warner', 'runs': 41, 'balls': 52},
 {'player_id': 6250, 'name': 'Mitchell Marsh', 'runs': 0, 'balls': 6},
 {'player_id': 2250, 'name': 'Steven Smith', 'runs': 46, 'balls': 71},
 {'player_id': 10182, 'name': 'Labuschagne', 'runs': 27, 'balls': 41},
 {'player_id': 7662, 'name': 'Maxwell', 'runs': 15, 'balls': 25},
 {'player_id': 9200, 'name': 'Alex Carey', 'runs': 0, 'balls': 2},
 {'player_id': 12225, 'name': 'Green', 'runs': 8, 'balls': 20},
 {'player_id': 8095, 'name': 'Cummins', 'runs': 15, 'balls': 24},
 {'player_id': 7710, 'name': 'Starc', 'runs': 28, 'balls': 35},
 {'player_id': 8642, 'name': 'Zampa', 'runs': 6, 'balls': 20},
 {'player_id': 6258, 'name': 'Hazlewood', 'runs': 1, 'balls': 1},
 {'player_id': 6250, 'name': 'Mitchell Marsh', 'runs': 7, 'balls': 15},
 {'player_id': 1739, 'name': 'David Warner', 'runs': 13, 'balls': 27},
 {'player_id': 2250, 'name': 'Steven Smith', 'runs': 19, 'balls': 16},
 {'player_id': 10182, 'name': 'Marnus Labuschagne', 'runs': 46, 'balls': 74},
 {'player_id': 10637, 'name': 'Josh Inglis', 'runs': 5, 'balls': 4},
 {'player_id': 7662, 'name': 'Glenn Maxwell', 'runs': 3, 'balls': 17},
 {'player_id': 8989, 'name': 'Marcus Stoinis', 'runs': 5, 'balls': 4},
 {'player_id': 7710, 'name': 'Mitchell Starc', 'runs': 27, 'balls': 51},
 {'player_id': 8095, 'name': 'Pat Cummins', 'runs': 22, 'balls': 21},
 {'player_id': 8642, 'name': 'Adam Zampa', 'runs': 11, 'balls': 16},
 {'player_id': 6258, 'name': 'Josh Hazlewood', 'runs': 2, 'balls': 2},
 {'player_id': 1739, 'name': 'David Warner', 'runs': 18, 'balls': 29},
 {'player_id': 8497, 'name': 'Travis Head', 'runs': 0, 'balls': 2},
 {'player_id': 6250, 'name': 'Mitchell Marsh', 'runs': 24, 'balls': 11},
 {'player_id': 10182, 'name': 'Marnus Labuschagne', 'runs': 14, 'balls': 28},
 {'player_id': 10637, 'name': 'Josh Inglis', 'runs': 0, 'balls': 1},
 {'player_id': 7662, 'name': 'Glenn Maxwell', 'runs': 201, 'balls': 128},
 {'player_id': 8989, 'name': 'Marcus Stoinis', 'runs': 6, 'balls': 7},
 {'player_id': 7710, 'name': 'Mitchell Starc', 'runs': 3, 'balls': 7},
 {'player_id': 8095, 'name': 'Pat Cummins', 'runs': 12, 'balls': 68},
 {'player_id': 8642, 'name': 'Adam Zampa', 'runs': 0, 'balls': 0},
 {'player_id': 6258, 'name': 'Josh Hazlewood', 'runs': 0, 'balls': 0},
 {'player_id': 1739, 'name': 'David Warner', 'runs': 7, 'balls': 3},
 {'player_id': 8497, 'name': 'Travis Head', 'runs': 137, 'balls': 120},
 {'player_id': 6250, 'name': 'Mitchell Marsh', 'runs': 15, 'balls': 15},
 {'player_id': 2250, 'name': 'Steven Smith', 'runs': 4, 'balls': 9},
 {'player_id': 10182, 'name': 'Marnus Labuschagne', 'runs': 58, 'balls': 110},
 {'player_id': 7662, 'name': 'Glenn Maxwell', 'runs': 2, 'balls': 1},
 {'player_id': 10637, 'name': 'Josh Inglis', 'runs': 0, 'balls': 0},
 {'player_id': 7710, 'name': 'Mitchell Starc', 'runs': 0, 'balls': 0},
 {'player_id': 8095, 'name': 'Pat Cummins', 'runs': 0, 'balls': 0},
 {'player_id': 8642, 'name': 'Adam Zampa', 'runs': 0, 'balls': 0},
 {'player_id': 6258, 'name': 'Josh Hazlewood', 'runs': 0, 'balls': 0}]

In [108]:
aus_player_stats = {}

for entry in australian_batsmen:
    pid = entry["player_id"]
    name = entry["name"]
    runs = entry["runs"]
    balls = entry["balls"]

    if pid not in aus_player_stats:
        aus_player_stats[pid] = {
            "player_id": pid,
            "name": name,
            "runs": [],
            "balls": []
        }

    if balls > 10:
        aus_player_stats[pid]["runs"].append(runs)
        aus_player_stats[pid]["balls"].append(balls)

final_list = list(aus_player_stats.values())

In [109]:
for p in final_list:
    runs = p["runs"]
    n = len(runs)

    if n == 0:
        p["std_deviation"] = None
        continue

    mean = sum(runs) / n
    variance = sum((x - mean) ** 2 for x in runs) / n
    std_dev = variance ** 0.5

    p["std_deviation"] = round(std_dev, 2)

In [110]:
final_list

[{'player_id': 1739,
  'name': 'Warner',
  'runs': [41, 13, 18],
  'balls': [52, 27, 29],
  'std_deviation': 12.19},
 {'player_id': 6250,
  'name': 'Mitchell Marsh',
  'runs': [7, 24, 15],
  'balls': [15, 11, 15],
  'std_deviation': 6.94},
 {'player_id': 2250,
  'name': 'Steven Smith',
  'runs': [46, 19],
  'balls': [71, 16],
  'std_deviation': 13.5},
 {'player_id': 10182,
  'name': 'Labuschagne',
  'runs': [27, 46, 14, 58],
  'balls': [41, 74, 28, 110],
  'std_deviation': 16.95},
 {'player_id': 7662,
  'name': 'Maxwell',
  'runs': [15, 3, 201],
  'balls': [25, 17, 128],
  'std_deviation': 90.64},
 {'player_id': 9200,
  'name': 'Alex Carey',
  'runs': [],
  'balls': [],
  'std_deviation': None},
 {'player_id': 12225,
  'name': 'Green',
  'runs': [8],
  'balls': [20],
  'std_deviation': 0.0},
 {'player_id': 8095,
  'name': 'Cummins',
  'runs': [15, 22, 12],
  'balls': [24, 21, 68],
  'std_deviation': 4.19},
 {'player_id': 7710,
  'name': 'Starc',
  'runs': [28, 27],
  'balls': [35, 51],
  'std_deviation': 0.5},
 {'player_id': 8642,
  'name': 'Zampa',
  'runs': [6, 11],
  'balls': [20, 16],
  'std_deviation': 2.5},
 {'player_id': 6258,
  'name': 'Hazlewood',
  'runs': [],
  'balls': [],
  'std_deviation': None},
 {'player_id': 10637,
  'name': 'Josh Inglis',
  'runs': [],
  'balls': [],
  'std_deviation': None},
 {'player_id': 8989,
  'name': 'Marcus Stoinis',
  'runs': [],
  'balls': [],
  'std_deviation': None},
 {'player_id': 8497,
  'name': 'Travis Head',
  'runs': [137],
  'balls': [120],
  'std_deviation': 0.0}]

In [111]:
df=pd.DataFrame(final_list)
df

df["runs"] = df["runs"].apply(lambda x: str(x))
df["balls"] = df["balls"].apply(lambda x: str(x))

df

,player_id,name,runs,balls,std_deviation
0,1739,Warner,"[41, 13, 18]","[52, 27, 29]",12.19
1,6250,Mitchell Marsh,"[7, 24, 15]","[15, 11, 15]",6.94
2,2250,Steven Smith,"[46, 19]","[71, 16]",13.50
3,10182,Labuschagne,"[27, 46, 14, 58]","[41, 74, 28, 110]",16.95
4,7662,Maxwell,"[15, 3, 201]","[25, 17, 128]",90.64
5,9200,Alex Carey,[],[],NaN
6,12225,Green,[8],[20],0.00
7,8095,Cummins,"[15, 22, 12]","[24, 21, 68]",4.19
8,7710,Starc,"[28, 27]","[35, 51]",0.50
9,8642,Zampa,"[6, 11]","[20, 16]",2.50
10,6258,Hazlewood,[],[],NaN
11,10637,Josh Inglis,[],[],NaN
12,8989,Marcus Stoinis,[],[],NaN
13,8497,Travis Head,[137],[120],0.00

In [112]:
import os
from dotenv import load_dotenv
import pandas as pd
from pathlib import Path
from sqlalchemy import create_engine

# Load local .env.cricbuzz for local development
load_dotenv(dotenv_path=Path("../.env.cricbuzz"), override=True)

# Get MySQL credentials from environment
user = os.getenv("MYSQL_USER")
password = os.getenv("MYSQL_PWD")
host = os.getenv("MYSQL_HOST")
port = os.getenv("MYSQL_PORT")
database = os.getenv("MYSQL_DB")

table_name = "aus_std_deviation" 

engine = create_engine(
f"mysql+mysqlconnector://{user}:{password}@{host}:{port}/{database}")


df.to_sql(table_name, con=engine, if_exists='replace', index=False)
print("Data pushed successfully to MySQL table:", database, table_name)

Data pushed successfully to MySQL table: CricBuzz aus_std_deviation

Q.20

Analyze how many matches each player has played in different cricket formats and their batting average in each format. Show the count of Test matches, ODI matches, and T20 matches for each player, along with their respective batting averages. Only include players who have played at least 20 total matches across all formats.

In [1]:
players_id=[1413, 576, 445, 587, 1726, 7909, 7910, 8271, 8292, 8733, 8808, 9428, 9647, 10276, 10744, 10808, 10945, 11808, 11813, 13940, 9311, 7745, 418, 494, 562, 1115, 7748, 8412, 4118, 11956]

In [ ]:
import requests
players_batt_data = []

for each in players_id:
    url = f"https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/{each}/batting"

    headers = {
        "x-rapidapi-key": "fc7f30fb9cmsh8725b330cc40e86p18a9aejsnb2a96a85740a",,
        "x-rapidapi-host": "cricbuzz-cricket.p.rapidapi.com"
    }
    try:
        response = requests.get(url, headers=headers)
        players_batt_data.append(response.json())
    except:
        continue

players_batt_data[29]